async function Vips(moduleArg={}){var moduleRtn;var h=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,p=ba&&"em-pthread"==globalThis.name;h.dynamicLibraries=h.dynamicLibraries||["vips-jxl.wasm","vips-heif.wasm"];var ca=[],da="./this.program",ea=import.meta.url,fa="";function ha(a){return h.locateFile?h.locateFile(a,fa):fa+a}var ia,ja;
if(aa||ba){try{fa=(new URL(".",ea)).href}catch{}ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ia=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var ka=console.log.bind(console),t=console.error.bind(console),la=[],ma,na,oa=!1,pa;function w(){qa.buffer!=y.buffer&&ra()}var sa,ta,ua={},va;
if(p){var xa=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.V;if("load"===d){let e=[];self.onmessage=f=>e.push(f);va=()=>{postMessage({V:"loaded"});for(let f of e)a(f);self.onmessage=a};la=c.Eb;ua=c.oc;for(const f of c.Rb)if(!h[f]||h[f].proxy)h[f]=(...g)=>{postMessage({V:"callHandler",Qb:f,yb:g})},"print"==f&&(ka=h[f]),"printErr"==f&&(t=h[f]);qa=c.uc;ra();na=c.vc;ya();za()}else if("run"===d){Aa(c.X);Ba(c.X,0,0,1,0,0);Ca();Da(c.X);xa||(Ea(),xa=!0);try{Fa(c.rc,
c.Da)}catch(e){if("unwind"!=e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?xa&&Ga():d&&(t(`worker: received unknown command ${d}`),t(c)))}catch(e){throw Ha(),e;}}self.onmessage=a}var Ja=!1,Ka=!1;function ra(){var a=qa.buffer;y=new Int8Array(a);z=new Int16Array(a);A=new Uint8Array(a);F=new Uint16Array(a);G=new Int32Array(a);H=new Uint32Array(a);La=new Float32Array(a);Ma=new Float64Array(a);I=new BigInt64Array(a);Na=new BigUint64Array(a)}var Oa=[];
function Pa(){Ja=!0;p?va():(Qa(Oa),h.noFSInit||FS.Ha||FS.init(),Ra.__wasm_call_ctors(),Qa(Sa),FS.eb=!1)}function J(a){h.onAbort?.(a);a=`Aborted(${a})`;t(a);oa=!0;a+=". Build with -sASSERTIONS for more info.";Ja&&Ta();a=new WebAssembly.RuntimeError(a);ta?.(a);throw a;}var Ua;async function Va(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==Ua&&ma)a=new Uint8Array(ma);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Wa(a,b){try{var c=await Va(a);return await WebAssembly.instantiate(c,b)}catch(d){t(`failed to asynchronously prepare wasm: ${d}`),J(d)}}async function Xa(a){var b=Ua;if(!ma)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){t(`wasm streaming compile failed: ${d}`),t("falling back to ArrayBuffer instantiation")}return Wa(b,a)}
function Ya(){K={__assert_fail:Za,__call_sighandler:ab,__lsan_ignore_object:bb,__pthread_create_js:cb,__syscall_dup:db,__syscall_faccessat:eb,__syscall_fcntl64:fb,__syscall_fstat64:gb,__syscall_ftruncate64:hb,__syscall_getcwd:ib,__syscall_ioctl:jb,__syscall_lstat64:kb,__syscall_newfstatat:lb,__syscall_openat:mb,__syscall_rmdir:nb,__syscall_stat64:ob,__syscall_unlinkat:pb,__throw_exception_with_stack_trace:qb,_abort_js:rb,_dlopen_js:sb,_dlsym_catchup_js:tb,_dlsym_js:ub,_embind_finalize_value_object:vb,
_embind_register_arithmetic_vector:wb,_embind_register_bigint:xb,_embind_register_bool:Ab,_embind_register_class:Bb,_embind_register_class_class_function:Cb,_embind_register_class_constructor:Db,_embind_register_class_function:Eb,_embind_register_class_property:Fb,_embind_register_emval:Gb,_embind_register_enum:Hb,_embind_register_enum_value:Ib,_embind_register_float:Jb,_embind_register_function:Kb,_embind_register_integer:Lb,_embind_register_iterable:Mb,_embind_register_memory_view:Nb,_embind_register_optional:Ob,
_embind_register_std_string:Pb,_embind_register_std_wstring:Qb,_embind_register_value_object:Rb,_embind_register_value_object_field:Sb,_embind_register_void:Tb,_emscripten_dlopen_js:Ub,_emscripten_dlsync_threads:Vb,_emscripten_get_dynamic_libraries_js:Wb,_emscripten_init_main_thread_js:Xb,_emscripten_notify_mailbox_postmessage:Yb,_emscripten_receive_on_main_thread_js:Zb,_emscripten_runtime_keepalive_clear:$b,_emscripten_thread_cleanup:ac,_emscripten_thread_exit_joinable:bc,_emscripten_thread_mailbox_await:Da,
_emscripten_thread_set_strongref:cc,_emval_array_to_memory_view:dc,_emval_create_invoker:ec,_emval_decref:fc,_emval_get_global:gc,_emval_get_module_property:hc,_emval_get_property:ic,_emval_incref:jc,_emval_instanceof:kc,_emval_invoke:lc,_emval_is_number:mc,_emval_is_string:nc,_emval_new_cstring:oc,_emval_run_destructors:pc,_emval_set_property:qc,_emval_typeof:rc,_gmtime_js:sc,_localtime_js:tc,_mmap_js:uc,_munmap_js:vc,_tzset_js:wc,clock_time_get:xc,emscripten_check_blocking_allowed:yc,emscripten_date_now:zc,
emscripten_err:Ac,emscripten_exit_with_live_runtime:Bc,emscripten_get_heap_max:Cc,emscripten_get_now:Dc,emscripten_num_logical_cores:Ec,emscripten_promise_destroy:Fc,emscripten_promise_resolve:Gc,emscripten_resize_heap:Hc,environ_get:Ic,environ_sizes_get:Jc,exit:Kc,fd_close:Lc,fd_fdstat_get:Mc,fd_read:Nc,fd_seek:Oc,fd_write:Pc,ffi_call_js:Qc,memory:qa,proc_exit:Rc,random_get:Sc};var a=new Proxy(new Set(["__lsan_ignore_object"]),Tc);return{env:K,wasi_snapshot_preview1:K,"GOT.mem":a,"GOT.func":a}}
async function ya(){function a(d,e){var f=Ra=d.exports;Uc(Ra);var g=Vc(e);Wc(Ra._emscripten_tls_init,d.exports,g);d=Ra;Xc=d.pthread_self;Yc=d.malloc;h._main=d.main;L=d.free;Zc=d.fflush;$c=d.calloc;h.__ZnamSt11align_val_t=d._ZnamSt11align_val_t;ad=d.__getTypeName;Ea=d._embind_initialize_bindings;h._emscripten_builtin_free=d.emscripten_builtin_free;bd=d.emscripten_builtin_memalign;h._emscripten_builtin_malloc=d.emscripten_builtin_malloc;cd=d.__funcs_on_exit;h.___libc_calloc=d.__libc_calloc;h.___libc_free=
d.__libc_free;h.___libc_malloc=d.__libc_malloc;dd=d.__dl_seterr;ed=d._emscripten_dlsync_self_async;fd=d._emscripten_dlsync_self;gd=d._emscripten_proxy_dlsync_async;hd=d._emscripten_proxy_dlsync;jd=d._emscripten_find_dylib;Ba=d._emscripten_thread_init;kd=d.__set_thread_state;Ha=d._emscripten_thread_crashed;ld=d._emscripten_run_js_on_main_thread_done;md=d._emscripten_run_js_on_main_thread;nd=d._emscripten_thread_free_data;od=d._emscripten_thread_exit;h._strndup=d.strndup;pd=d._emscripten_check_mailbox;
h.__ZdaPvm=d._ZdaPvm;h.___libc_realloc=d.__libc_realloc;h._emscripten_builtin_calloc=d.emscripten_builtin_calloc;h._emscripten_builtin_realloc=d.emscripten_builtin_realloc;h._malloc_size=d.malloc_size;h._malloc_usable_size=d.malloc_usable_size;h._reallocf=d.reallocf;qd=d.emscripten_get_sbrk_ptr;Ta=d.__trap;rd=d.emscripten_stack_set_limits;sd=d._emscripten_stack_restore;td=d._emscripten_stack_alloc;ud=d.emscripten_stack_get_current;vd=d.__thrown_object_from_unwind_exception;wd=d.__get_exception_message;
M=d.__indirect_function_table;xd=d.__heap_base.value;yd=d.__cpp_exception;zd(f);Ad("__main__",0,K);Bd();na=e;return Ra}var b=Ya();if(h.instantiateWasm)return new Promise(d=>{h.instantiateWasm(b,(e,f)=>{d(a(e,f))})});if(p){var c=new WebAssembly.Instance(na,Ya());return a(c,na)}Ua??=h.locateFile?ha("vips.wasm"):(new URL("vips.wasm",import.meta.url)).href;return function(d){return a(d.instance,d.module)}(await Xa(b))}var Dd=a=>{if(!(a instanceof Cd||"unwind"==a))throw a;};
class Cd{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var N=0,Ed=a=>{a.terminate();a.onmessage=()=>{}},Kd=a=>{var b=Fd[a];Gd.delete(a);a in Hd&&Hd[a].resolve();a=b.X;delete Fd[a];Id.push(b);Jd.splice(Jd.indexOf(b),1);b.X=0;nd(a)},Qa=a=>{for(;0<a.length;)a.shift()(h)},Ld=[],Md=a=>{Gd.add(a);a in Hd&&Hd[a].resolve()},Nd=0,Od=null,Pd=()=>{Nd--;h.monitorRunDependencies?.(Nd);if(0==Nd&&Od){var a=Od;Od=null;a()}},Qd=()=>{Nd++;h.monitorRunDependencies?.(Nd)},Td=a=>{0==Id.length&&(Rd(),Sd(Id[0]));var b=Id.pop();if(!b)return 6;Jd.push(b);Fd[a.X]=b;b.X=a.X;b.postMessage({V:"run",
rc:a.qc,Da:a.Da,X:a.X},a.rb);return 0},Ud=!Atomics.waitAsync||globalThis.navigator?.userAgent&&91>Number((navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./)||[])[2]),Id=[],Jd=[],Vd=[],Fd={};function Wd(){for(var a=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;a--;)Rd();Ld.push(async()=>{var b=Xd();Qd("loading-workers");await b;Pd("loading-workers")});Hd={};Gd=new Set}var Yd=()=>{for(var a of Jd)Ed(a);for(a of Id)Ed(a);Id=[];Jd=[];Fd={}};function Ca(){Vd.forEach(a=>a())}
var Sd=a=>new Promise(b=>{a.onmessage=f=>{var g=f.data;f=g.V;if(g.Ca&&g.Ca!=Xc()){var k=Fd[g.Ca];k?k.postMessage(g,g.rb):t(`worker sent message (${f}) to pthread (${g.Ca}) that no longer exists`)}else if("checkMailbox"===f)Ga();else if("spawnThread"===f)Td(g);else if("cleanupThread"===f)Zd(()=>Kd(g.Ua));else if("markAsFinished"===f)Md(g.Ua);else if("loaded"===f)a.loaded=!0,b(a);else if("setimmediate"===g.target)a.postMessage(g);else if("callHandler"===f)h[g.Qb](...g.yb);else f&&t(`worker sent an unknown command ${f}`)};
a.onerror=f=>{t(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)h.propertyIsEnumerable(e)&&c.push(e);a.postMessage({V:"load",Rb:c,uc:qa,vc:na,Eb:la,oc:ua})});async function Xd(){if(!p)return Promise.all(Id.map(Sd))}
function Rd(){if(h.mainScriptUrlOrBlob){var a=h.mainScriptUrlOrBlob;"string"!=typeof a&&(a=URL.createObjectURL(a));a=new Worker(a,{type:"module",name:"em-pthread"})}else a=new Worker(new URL("vips-es6.js",import.meta.url),{type:"module",name:"em-pthread"});Id.push(a)}var Gd,Hd,$d,O=(a,b,...c)=>{var d=16*c.length,e=ud(),f=td(d),g=f>>3,k;for(k of c)"bigint"==typeof k?((w(),I)[g++]=1n,(w(),I)[g++]=k):((w(),I)[g++]=0n,(w(),Ma)[g++]=k);a=md(a,0,d,f,b);sd(e);return a};
function Rc(a){if(p)return O(0,1,a);pa=a;ae||0<N||(Yd(),h.onExit?.(a),oa=!0);throw new Cd(a);}Rc.g="vi";function be(a){if(p)return O(1,0,a);Kc(a)}var Kc=a=>{pa=a;if(p)throw be(a),"unwind";if(!(ae||0<N||p)){cd();FS.Ha=!1;Zc(0);for(var b of FS.streams)b&&FS.close(b);Yd();b=Xc();kd(0,0,0,1);Ud||Atomics.notify((w(),G),b>>2);Ka=!0}Rc(a)};Kc.g="vi";
var Zd=a=>{if(!Ka&&!oa)try{a()}catch(b){Dd(b)}finally{if(!(Ka||ae||0<N))try{p?Xc()&&od(pa):Kc(pa)}catch(b){Dd(b)}}},ce=a=>{N+=1;setTimeout(()=>{--N;Zd(a)},1E4)},de=[],ee={},fe=!1;
function ge(){function a(){fe=document.pointerLockElement===h.canvas}if(!he){he=!0;de.push({canHandle:c=>!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c),handle:async(c,d)=>{var e=new Blob([c],{type:ie(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:ie(d)}));var f=URL.createObjectURL(e);return new Promise((g,k)=>{var l=new Image;l.onload=()=>{var m=document.createElement("canvas");m.width=l.width;m.height=l.height;m.getContext("2d").drawImage(l,0,0);URL.revokeObjectURL(f);
g(c)};l.onerror=()=>{t(`Image ${f} could not be decoded`);k()};l.src=f})}});de.push({canHandle:c=>!h.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(c,d)=>new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,k=URL.createObjectURL(new Blob([c],{type:ie(d)})),l=new Audio;l.addEventListener("canplaythrough",()=>f(l),!1);l.onerror=()=>{if(!g){t(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);for(var m="",n=0,q=0,u=0;u<c.length;u++)for(n=n<<
8|c[u],q+=8;6<=q;){var r=n>>q-6&63;q-=6;m+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[r]}2==q?(m+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(n&3)<<4],m+="=="):4==q&&(m+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(n&15)<<2],m+="=");l.src="data:audio/x-"+d.slice(-3)+";base64,"+m;f(l)}};l.src=k;ce(()=>{f(l)})})});var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!fe&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}function ie(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}var je={},he,ke={},Tc={get(a,b){var c=ke[b];c||=ke[b]=new WebAssembly.Global({value:"i32",mutable:!0},-1);a.has(b)||(c.required=!0);return c}},z,G,I,y,La,Ma,F,H,Na,A,le=[];
function Aa(a){var b=(w(),H)[a+48>>2];a=(w(),H)[a+52>>2];rd(b,b-a);sd(b)}
var me=new TextDecoder,ne=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},oe=(a,b=0,c)=>{c=ne(a,b,c);return me.decode(a.buffer?a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c):new Uint8Array(a.slice(b,c)))},Vc=a=>{function b(){for(var q=0,u=1;;){var r=a[f++];q+=(r&127)*u;u*=128;if(!(r&128))break}return q}function c(){var q=b();f+=q;return oe(a,f-q,q)}function d(){for(var q=b(),u=[];q--;)u.push(c());return u}function e(q,u){if(q)throw Error(u);}var f=0,g=0;if(a instanceof
WebAssembly.Module)g=WebAssembly.Module.customSections(a,"dylink.0"),e(0===g.length,"need dylink section"),a=new Uint8Array(g[0]),g=a.length;else{g=1836278016==(new Uint32Array((new Uint8Array(a.subarray(0,24))).buffer))[0];e(!g,"need to see wasm magic number");e(0!==a[8],"need the dylink section to be first");f=9;g=b();g=f+g;var k=c();e("dylink.0"!==k)}for(k={Na:[],qb:new Set,tb:new Set,nb:[]};f<g;){var l=a[f++],m=b();if(1===l)k.Ma=b(),k.Zb=b(),k.ta=b(),k.Pc=b();else if(2===l)k.Na=d();else if(3===
l)for(l=b();l--;){m=c();var n=b();n&256&&k.qb.add(m)}else if(4===l)for(l=b();l--;)c(),m=c(),n=b(),1==(n&3)&&k.tb.add(m);else 5===l?k.nb=d():f+=m}return k},Fa=(a,b)=>{ae=N=0;fd();a=M.get(a)(b);ae||0<N?pa=a:od(a)},Ad=(a,b,c)=>{c={Aa:Infinity,name:a,exports:c,global:!0};pe[a]=c;void 0!=b&&(qe[b]=c);return c},pe={},qe={},re=(a,b)=>Math.ceil(a/b)*b,se=a=>{if(Ja)return $c(a,1);var b=xd;xd=a=b+16*Math.ceil(a/16);if(!p){var c=qd();(w(),H)[c>>2]=a}return b},ue=(a,b)=>{if(te)for(var c=a;c<a+b;c++){var d=M.get(c);
d&&te.set(d,c)}},te,ve=a=>{te||(te=new WeakMap,ue(0,M.length));return te.get(a)||0},we=[],xe=a=>{const b=a.length;return[b%128|128,b>>7,...a]},ye={i:127,p:127,j:126,f:125,d:124,e:111},ze=a=>xe(Array.from(a,b=>ye[b])),Ae=(a,b)=>{var c=ve(a);if(c)return c;c=we.length?we.pop():M.grow(1);try{M.set(c,a)}catch(d){if(!(d instanceof TypeError))throw d;b=Uint8Array.of(0,97,115,109,1,0,0,0,1,...xe([1,96,...ze(b.slice(1)),...ze("v"===b[0]?"":b[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(b);
b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f;M.set(c,b)}te.set(a,c);return c},zd=(a,b)=>{for(var c in a){var d=c;if(!"memory __memory_base __table_base __stack_pointer __indirect_function_table __cpp_exception __c_longjmp __wasm_apply_data_relocs __dso_handle __tls_size __tls_align __set_stack_limits _emscripten_tls_init __wasm_init_tls __wasm_call_ctors __start_em_asm __stop_em_asm __start_em_js __stop_em_js".split(" ").includes(d)&&!d.startsWith("__em_js__")){d=a[c];var e=ke[c]&&-1!=ke[c].value;
if(b||!e){if("function"==typeof d)d=Ae(d);else if("number"!=typeof d.value)continue;let f;ke[f=c]??(ke[f]=new WebAssembly.Global({value:"i32",mutable:!0}));ke[c].value=d}}}},Be=(a,b=0)=>{var c={},d;for(d in a){var e=d;var f=a[d];a:{if(f instanceof WebAssembly.Global)try{f.value=f.value}catch{var g=!0;break a}g=!1}f=g?new WebAssembly.Global({value:"i32"},f.value+b):f;c[e]=f}return c},Ce=a=>{a=K[a];return!a||a.Sa?!1:!0},De=(a,b)=>Object.defineProperty(b,"name",{value:a}),Ee=a=>{var b;Ce(a)&&(b=K[a]);
return{Ta:b,name:a}},Sa=[],P=(a,b,c)=>{if(!a)return"";b=ne((w(),A),a,b,c);return me.decode((w(),A).slice(a,b))},Je=(a,b,c,d,e)=>{function f(){function l(D,B){function E(wa,Z){wa=[];for(var yb=0;;yb++){var $a="$"+yb;if(!Z.includes($a))break;wa.push($a)}wa=wa.join(",");Fe[C]=eval(`(${wa}) => { ${Z} };`)}function R(wa,Z,yb){var $a=[];Z=Z.slice(1,-1);if("void"!=Z){Z=Z.split(",");for(var yg of Z)Z=yg.split(" ").pop(),$a.push(Z.replaceAll("*",""))}r[wa]=eval(`(${$a}) => ${yb};`)}!p&&c&&(ua[c]=D);ue(u,g.ta);
r=Be(B.exports,q);zd(r);b.xb||Ge();if("__start_em_asm"in r){var C=r.__start_em_asm.value;for(D=r.__stop_em_asm.value;C<D;){var Ia=P(C);E(C,Ia);C=(w(),A).indexOf(0,C)+1}}for(var zb in r)if(zb.startsWith("__em_js__")){C=r[zb].value;Ia=P(C);var [zg,Ag]=Ia.split("<::>");R(zb.replace("__em_js__",""),zg,Ag);delete r[zb]}Wc(r._emscripten_tls_init,B.exports,g);m&&((B=r.__wasm_apply_data_relocs)&&(Ja?B():Oa.push(B)),(B=r.__wasm_call_ctors)&&(Ja?B():Sa.push(B)));return r}var m=!e||!(w(),y)[e+8];if(m){var n=
Math.pow(2,g.Zb),q=g.Ma?re(se(g.Ma+n),n):0,u=g.ta?M.length:0;e&&((w(),y)[e+8]=1,(w(),H)[e+12>>2]=q,(w(),G)[e+16>>2]=g.Ma,(w(),H)[e+20>>2]=u,(w(),G)[e+24>>2]=g.ta)}else q=(w(),H)[e+12>>2],u=(w(),H)[e+20>>2];g.ta&&M.grow(g.ta);var r;n=new Proxy({},{get(D,B){switch(B){case "__memory_base":return q;case "__table_base":return u}if(B in K&&!K[B].Sa)return K[B];if(!(B in D)){var E;D[B]=(...R)=>{if(!E){var C=Ee(B).Ta;!C&&d&&(C=d[B]);C||=r[B];E=C}return E(...R)}}return D[B]}});var v=new Proxy(g.tb,Tc),x={"GOT.mem":v,
"GOT.func":v,env:n,wasi_snapshot_preview1:n};if(b.I)return(async()=>{var D;a instanceof WebAssembly.Module?D=new WebAssembly.Instance(a,x):{module:a,instance:D}=await WebAssembly.instantiate(a,x);return l(a,D)})();n=a instanceof WebAssembly.Module?a:new WebAssembly.Module(a);v=new WebAssembly.Instance(n,x);return l(n,v)}var g=Vc(a);b={...b,Ra:{dc:c,hc:g.nb}};if(b.I)return g.Na.reduce((l,m)=>l.then(()=>{m=He(m,b.Ra)??m;return Ie(m,b,d)}),Promise.resolve()).then(f);for(var k of g.Na)k=He(k,b.Ra)??k,
Ie(k,b,d);return f()},Uc=a=>{var b,c;for([b,c]of Object.entries(a))Ce(b)||(K[b]=c)},Ke=async a=>{a=await ia(a);return new Uint8Array(a)},Le=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Me=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Le(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ne=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Oe=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Pe=(a,b)=>Me(a+"/"+b),Qe=a=>{var b=ud();a=a();sd(b);return a},Re=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Se=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=
g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Te=(a,b,c)=>Se(a,(w(),A),b,c),Ue=a=>{var b=Re(a)+1,c=td(b);Te(a,c,b);return c},Ve=()=>a=>(a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),0),We=a=>(We=Ve())(a),Xe=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:FS.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");
if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Le(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ye=(a,b)=>{function c(g){for(var k=0;k<g.length&&""===g[k];k++);for(var l=g.length-1;0<=l&&""===g[l];l--);return k>l?[]:g.slice(k,l-k+1)}a=Xe(a).slice(1);b=Xe(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Ze=[],$e=a=>{var b=
Array(Re(a)+1);a=Se(a,b,0,b.length);b.length=a;return b},af=[];function bf(a,b){af[a]={input:[],output:[],ea:b};FS.registerDevice(a,cf)}
var cf={open(a){var b=af[a.node.ra];if(!b)throw new FS.h(43);a.C=b;a.seekable=!1},close(a){a.C.ea.xa(a.C)},xa(a){a.C.ea.xa(a.C)},read(a,b,c,d){if(!a.C||!a.C.ea.cb)throw new FS.h(60);for(var e=0,f=0;f<d;f++){try{var g=a.C.ea.cb(a.C)}catch(k){throw new FS.h(29);}if(void 0===g&&0===e)throw new FS.h(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.$=Date.now());return e},write(a,b,c,d){if(!a.C||!a.C.ea.Pa)throw new FS.h(60);try{for(var e=0;e<d;e++)a.C.ea.Pa(a.C,b[c+e])}catch(f){throw new FS.h(29);
}d&&(a.node.O=a.node.N=Date.now());return e}},df={cb(){a:{if(!Ze.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ze=$e(a)}a=Ze.shift()}return a},Pa(a,b){null===b||10===b?(ka(oe(a.output)),a.output=[]):0!=b&&a.output.push(b)},xa(a){0<a.output?.length&&(ka(oe(a.output)),a.output=[])},Ub(){return{Bc:25856,Dc:5,Ac:191,Cc:35387,zc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Vb(){return 0},Wb(){return[24,
80]}},ef={Pa(a,b){null===b||10===b?(t(oe(a.output)),a.output=[]):0!=b&&a.output.push(b)},xa(a){0<a.output?.length&&(t(oe(a.output)),a.output=[])}},ff=a=>{a=65536*Math.ceil(a/65536);var b=bd(65536,a);b&&(w(),A).fill(0,b,b+a);return b},Q={W:null,mount(){return Q.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=FS.isBlkdev(c))||(e=4096===(c&61440));if(e)throw new FS.h(63);Q.W||(Q.W={dir:{node:{S:Q.m.S,U:Q.m.U,ia:Q.m.ia,ca:Q.m.ca,rename:Q.m.rename,unlink:Q.m.unlink,rmdir:Q.m.rmdir,sa:Q.m.sa,
symlink:Q.m.symlink},stream:{llseek:Q.o.llseek}},file:{node:{S:Q.m.S,U:Q.m.U},stream:{llseek:Q.o.llseek,read:Q.o.read,write:Q.o.write,ja:Q.o.ja,la:Q.o.la}},link:{node:{S:Q.m.S,U:Q.m.U,readlink:Q.m.readlink},stream:{}},Wa:{node:{S:Q.m.S,U:Q.m.U},stream:FS.Ab}});c=FS.createNode(a,b,c,d);FS.isDir(c.mode)?(c.m=Q.W.dir.node,c.o=Q.W.dir.stream,c.u={}):FS.isFile(c.mode)?(c.m=Q.W.file.node,c.o=Q.W.file.stream,c.L=0,c.u=Q.Fb??(Q.Fb=new Uint8Array(0))):FS.isLink(c.mode)?(c.m=Q.W.link.node,c.o=Q.W.link.stream):
FS.isChrdev(c.mode)&&(c.m=Q.W.Wa.node,c.o=Q.W.Wa.stream);c.$=c.O=c.N=Date.now();a&&(a.u[b]=c,a.$=a.O=a.N=c.$);return c},m:{S(a){var b={};b.Cb=FS.isChrdev(a.mode)?a.id:1;b.Tb=a.id;b.mode=a.mode;b.$b=1;b.uid=0;b.Pb=0;b.ra=a.ra;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.L:FS.isLink(a.mode)?b.size=a.link.length:b.size=0;b.$=new Date(a.$);b.O=new Date(a.O);b.N=new Date(a.N);b.zb=4096;b.Va=Math.ceil(b.size/b.zb);return b},U(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=
b[c]);void 0!==b.size&&(b=b.size,a.L!=b&&(c=a.u,a.u=new Uint8Array(b),a.u.set(c.subarray(0,Math.min(b,a.L))),a.L=b))},ia(){Q.Ea||(Q.Ea=new FS.h(44),Q.Ea.stack="<generic error, no stack>");throw Q.Ea;},ca(a,b,c,d){return Q.createNode(a,b,c,d)},rename(a,b,c){try{var d=gf(b,c)}catch(f){}if(d){if(FS.isDir(a.mode))for(var e in d.u)throw new FS.h(55);hf(d)}delete a.parent.u[a.name];b.u[c]=a;a.name=c;b.N=b.O=a.parent.N=a.parent.O=Date.now()},unlink(a,b){delete a.u[b];a.N=a.O=Date.now()},rmdir(a,b){var c=
gf(a,b),d;for(d in c.u)throw new FS.h(55);delete a.u[b];a.N=a.O=Date.now()},sa(a){return[".","..",...Object.keys(a.u)]},symlink(a,b,c){a=Q.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(!FS.isLink(a.mode))throw new FS.h(28);return a.link}},o:{read(a,b,c,d,e){if(e>=a.node.L)return 0;d=Math.min(a.node.L-e,d);b.set(a.node.u.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===(w(),y).buffer&&(f=!1);if(!d)return 0;a=a.node;a.O=a.N=Date.now();if(f)a.u=b.subarray(c,c+d),a.L=d;else if(0===
a.L&&0===e)a.u=b.slice(c,c+d),a.L=d;else{f=e+d;var g=a.u.length;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.u.subarray(0,a.L),a.u=new Uint8Array(f),a.u.set(g));a.u.set(b.subarray(c,c+d),e);a.L=Math.max(a.L,e+d)}return d},llseek(a,b,c){1===c?b+=a.position:2===c&&FS.isFile(a.node.mode)&&(b+=a.node.L);if(0>b)throw new FS.h(28);return b},ja(a,b,c,d,e){if(!FS.isFile(a.node.mode))throw new FS.h(43);a=a.node.u;if(e&2||a.buffer!==(w(),y).buffer){d=!0;e=ff(b);if(!e)throw new FS.h(48);
if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);(w(),y).set(a,e)}}else d=!1,e=a.byteOffset;return{A:e,fa:d}},la(a,b,c,d){Q.o.write(a,b,0,d,c,!1);return 0}}},jf=a=>{"string"==typeof a&&(a=$e(a));a.subarray||(a=new Uint8Array(a));return a},kf=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},lf=async(a,b)=>{"undefined"!=typeof je&&ge();for(var c of de)if(c.canHandle(b))return c.handle(a,b);return a},mf=async(a,b,c,d,e,f,g,k)=>{var l=b?Xe(Me(a+"/"+b)):
a,m=`cp ${l}`;Qd(m);try{var n=c;"string"==typeof c&&(n=await Ke(c));n=await lf(n,l);k?.();f||FS.createDataFile(a,b,n,d,e,g)}finally{Pd(m)}};function gf(a,b){var c=FS.isDir(a.mode)?(c=nf(a,"x"))?c:a.m.ia?0:2:54;if(c)throw new FS.h(c);for(c=FS.da[of(a.id,b)];c;c=c.ka){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return FS.ia(a,b)}function hf(a){var b=of(a.parent.id,a.name);if(FS.da[b]===a)FS.da[b]=a.ka;else for(b=FS.da[b];b;){if(b.ka===a){b.ka=a.ka;break}b=b.ka}}
function of(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%FS.da.length}function pf(a){var b=of(a.parent.id,a.name);a.ka=FS.da[b];FS.da[b]=a}function nf(a,b){return FS.eb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function qf(a,b){if(!FS.isDir(a.mode))return 54;try{return gf(a,b),20}catch(c){}return nf(a,"wx")}
function rf(a,b,c){try{var d=gf(a,b)}catch(e){return e.B}if(a=nf(a,"wx"))return a;if(c){if(!FS.isDir(d.mode))return 54;if(FS.na(d)||FS.getPath(d)===FS.cwd())return 10}else if(FS.isDir(d.mode))return 31;return 0}function sf(a,b){if(!a)throw new FS.h(b);return a}function S(a){a=FS.Mb(a);if(!a)throw new FS.h(8);return a}function tf(a,b=-1){a=Object.assign(new FS.vb,a);if(-1==b)a:{for(b=0;b<=FS.wb;b++)if(!FS.streams[b])break a;throw new FS.h(33);}a.aa=b;return FS.streams[b]=a}
function uf(a,b=-1){a=tf(a,b);a.o?.Fc?.(a);return a}function vf(a,b,c){var d=a?.o.U;a=d?a:b;d??=b.m.U;sf(d,63);try{d(a,c)}catch(e){if(e instanceof RangeError)throw new FS.h(22);throw e;}}function wf(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.oa)}return b}function xf(a){var b={yc:4096,Ic:4096,Va:1E6,xc:5E5,wc:5E5,files:FS.Oa,Gc:FS.Oa-1,Jc:42,flags:2,Mc:255};a.m.pb&&Object.assign(b,a.m.pb(a.mount.bc.root));return b}
function yf(a,b,c,d){vf(a,b,{mode:c&4095|b.mode&-4096,N:Date.now(),$a:d})}function zf(a,b,c){if(FS.isDir(b.mode))throw new FS.h(31);if(!FS.isFile(b.mode))throw new FS.h(28);var d=nf(b,"w");if(d)throw new FS.h(d);vf(a,b,{size:c,timestamp:Date.now()})}function Af(a,b,c,d){a="string"==typeof a?a:FS.getPath(a);b=Me(a+"/"+b);return FS.create(b,kf(c,d))}
function Bf(a){if(!(a.Xb||a.Yb||a.link||a.u))if(globalThis.XMLHttpRequest)J("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.u=ja(a.url)}catch(b){throw new FS.h(29);}}
var FS={root:null,oa:[],Za:{},streams:[],Oa:1,da:null,Xa:"/",Ha:!1,eb:!0,Ib:null,Ba:0,h:class{name="ErrnoError";constructor(a){this.B=a}},vb:class{P={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.P.flags}set flags(a){this.P.flags=a}get position(){return this.P.position}set position(a){this.P.position=a}},ub:class{m={};o={};T=null;constructor(a,b,c,d){a||=this;this.parent=a;this.mount=a.mount;this.id=FS.Oa++;this.name=b;this.mode=c;this.ra=d;this.$=this.O=
this.N=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Yb(){return FS.isDir(this.mode)}get Xb(){return FS.isChrdev(this.mode)}},lookupPath(a,b={}){if(!a)throw new FS.h(44);b.wa??(b.wa=!0);"/"===a.charAt(0)||(a=FS.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=FS.root,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;
if("."!==a[f])if(".."===a[f])if(e=Ne(e),FS.na(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Me(e+"/"+a[f]);try{d=gf(d,a[f])}catch(k){if(44===k?.B&&g&&b.ac)return{path:e};throw k;}!d.T||g&&!b.wa||(d=d.T.root);if(FS.isLink(d.mode)&&(!g||b.follow)){if(!d.m.readlink)throw new FS.h(52);d=d.m.readlink(d);"/"===d.charAt(0)||(d=Ne(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new FS.h(32);},getPath(a){for(var b;;){if(FS.na(a))return a=a.mount.ib,
b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},createNode(a,b,c,d){a=new FS.ub(a,b,c,d);pf(a);return a},na(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isDir(a){return 16384===(a&61440)},isLink(a){return 40960===(a&61440)},isChrdev(a){return 8192===(a&61440)},isBlkdev(a){return 24576===(a&61440)},isSocket(a){return 49152===(a&49152)},wb:4096,Mb:a=>FS.streams[a],Ab:{open(a){a.o=FS.Kb(a.node.ra).o;a.o.open?.(a)},llseek(){throw new FS.h(70);}},La:a=>a>>
8,Kc:a=>a&255,makedev:(a,b)=>a<<8|b,registerDevice(a,b){FS.Za[a]={o:b}},Kb:a=>FS.Za[a],syncfs(a,b){function c(k){FS.Ba--;return b(k)}function d(k){if(k){if(!d.Gb)return d.Gb=!0,c(k)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);FS.Ba++;1<FS.Ba&&t(`warning: ${FS.Ba} FS.syncfs operations in flight at once, probably just doing extra work`);var e=wf(FS.root.mount),f=0,g;for(g of e)g.type.syncfs?g.type.syncfs(g,a,d):d(null)},mount(a,b,c){var d="/"===c;if(d&&FS.root)throw new FS.h(10);if(!d&&
c){var e=FS.lookupPath(c,{wa:!1});c=e.path;e=e.node;if(e.T)throw new FS.h(10);if(!FS.isDir(e.mode))throw new FS.h(54);}b={type:a,bc:b,ib:c,oa:[]};a=a.mount(b);a.mount=b;b.root=a;d?FS.root=a:e&&(e.T=b,e.mount&&e.mount.oa.push(b));return a},unmount(a){a=FS.lookupPath(a,{wa:!1});if(!a.node.T)throw new FS.h(28);a=a.node;var b=a.T,c=wf(b);for([,e]of Object.entries(FS.da))for(;e;){var d=e.ka;c.includes(e.mount)&&hf(e);var e=d}a.T=null;a.mount.oa.splice(a.mount.oa.indexOf(b),1)},ia(a,b){return a.m.ia(a,
b)},ca(a,b,c){var d=FS.lookupPath(a,{parent:!0}).node;a=Oe(a);if(!a)throw new FS.h(28);if("."===a||".."===a)throw new FS.h(20);var e=qf(d,a);if(e)throw new FS.h(e);if(!d.m.ca)throw new FS.h(63);return d.m.ca(d,a,b,c)},pb(a){return xf(FS.lookupPath(a,{follow:!0}).node)},Oc(a){return xf(a.node)},create(a,b=438){return FS.ca(a,b&4095|32768,0)},mkdir(a,b=511){return FS.ca(a,b&1023|16384,0)},Lc(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{FS.mkdir(d,b)}catch(f){if(20!=
f.B)throw f;}}},mkdev(a,b,c){"undefined"==typeof c&&(c=b,b=438);return FS.ca(a,b|8192,c)},symlink(a,b){if(!Xe(a))throw new FS.h(44);var c=FS.lookupPath(b,{parent:!0}).node;if(!c)throw new FS.h(44);b=Oe(b);var d=qf(c,b);if(d)throw new FS.h(d);if(!c.m.symlink)throw new FS.h(63);return c.m.symlink(c,b,a)},rename(a,b){var c=Ne(a),d=Ne(b),e=Oe(a),f=Oe(b);var g=FS.lookupPath(a,{parent:!0});var k=g.node;g=FS.lookupPath(b,{parent:!0});g=g.node;if(!k||!g)throw new FS.h(44);if(k.mount!==g.mount)throw new FS.h(75);
var l=gf(k,e);a=Ye(a,d);if("."!==a.charAt(0))throw new FS.h(28);a=Ye(b,c);if("."!==a.charAt(0))throw new FS.h(55);try{var m=gf(g,f)}catch(n){}if(l!==m){b=FS.isDir(l.mode);if(e=rf(k,e,b))throw new FS.h(e);if(e=m?rf(g,f,b):qf(g,f))throw new FS.h(e);if(!k.m.rename)throw new FS.h(63);if(l.T||m&&m.T)throw new FS.h(10);if(g!==k&&(e=nf(k,"w")))throw new FS.h(e);hf(l);try{k.m.rename(l,g,f),l.parent=g}catch(n){throw n;}finally{pf(l)}}},rmdir(a){var b=FS.lookupPath(a,{parent:!0}).node;a=Oe(a);var c=gf(b,a),
d=rf(b,a,!0);if(d)throw new FS.h(d);if(!b.m.rmdir)throw new FS.h(63);if(c.T)throw new FS.h(10);b.m.rmdir(b,a);hf(c)},sa(a){a=FS.lookupPath(a,{follow:!0}).node;return sf(a.m.sa,54)(a)},unlink(a){var b=FS.lookupPath(a,{parent:!0}).node;if(!b)throw new FS.h(44);a=Oe(a);var c=gf(b,a),d=rf(b,a,!1);if(d)throw new FS.h(d);if(!b.m.unlink)throw new FS.h(63);if(c.T)throw new FS.h(10);b.m.unlink(b,a);hf(c)},readlink(a){a=FS.lookupPath(a).node;if(!a)throw new FS.h(44);if(!a.m.readlink)throw new FS.h(28);return a.m.readlink(a)},
stat(a,b){a=FS.lookupPath(a,{follow:!b}).node;return sf(a.m.S,63)(a)},lstat(a){return FS.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?FS.lookupPath(a,{follow:!c}).node:a;yf(null,a,b,c)},lchmod(a,b){FS.chmod(a,b,!0)},fchmod(a,b){a=S(a);yf(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?FS.lookupPath(a,{follow:!d}).node:a;vf(null,a,{timestamp:Date.now(),$a:d})},lchown(a,b,c){FS.chown(a,b,c,!0)},fchown(a){a=S(a);vf(a,a.node,{timestamp:Date.now(),$a:!1})},truncate(a,b){if(0>b)throw new FS.h(28);
a="string"==typeof a?FS.lookupPath(a,{follow:!0}).node:a;zf(null,a,b)},ftruncate(a,b){a=S(a);if(0>b||0===(a.flags&2097155))throw new FS.h(28);zf(a,a.node,b)},utime(a,b,c){a=FS.lookupPath(a,{follow:!0}).node;sf(a.m.U,63)(a,{$:b,O:c})},open(a,b,c=438){if(""===a)throw new FS.h(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");
var f=FS.lookupPath(a,{follow:!(b&131072),ac:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new FS.h(20);}else{if(e)throw new FS.h(31);d=FS.ca(a,c|511,0);f=!0}if(!d)throw new FS.h(44);FS.isChrdev(d.mode)&&(b&=-513);if(b&65536&&!FS.isDir(d.mode))throw new FS.h(54);if(!f){e=d;a=b;if(e)if(FS.isLink(e.mode))e=32;else{var g=["r","w","rw"][a&3];a&512&&(g+="w");e=FS.isDir(e.mode)&&("r"!==g||a&576)?31:nf(e,g)}else e=44;if(e)throw new FS.h(e);}b&512&&!f&&FS.truncate(d,0);b&=-131713;b=tf({node:d,
path:FS.getPath(d),flags:b,seekable:!0,position:0,o:d.o,tc:[],error:!1});b.o.open&&b.o.open(b);f&&FS.chmod(d,c&511);return b},close(a){if(null===a.aa)throw new FS.h(8);a.Fa&&(a.Fa=null);try{a.o.close&&a.o.close(a)}catch(b){throw b;}finally{FS.streams[a.aa]=null}a.aa=null},llseek(a,b,c){if(null===a.aa)throw new FS.h(8);if(!a.seekable||!a.o.llseek)throw new FS.h(70);if(0!=c&&1!=c&&2!=c)throw new FS.h(28);a.position=a.o.llseek(a,b,c);a.tc=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new FS.h(28);
if(null===a.aa)throw new FS.h(8);if(1===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.read)throw new FS.h(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new FS.h(28);if(null===a.aa)throw new FS.h(8);if(0===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.write)throw new FS.h(28);a.seekable&&
a.flags&1024&&FS.llseek(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.write(a,b,c,d,e,f);g||(a.position+=b);return b},ja(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new FS.h(2);if(1===(a.flags&2097155))throw new FS.h(2);if(!a.o.ja)throw new FS.h(43);if(!b)throw new FS.h(28);return a.o.ja(a,b,c,d,e)},la(a,b,c,d,e){return a.o.la?a.o.la(a,b,c,d,e):0},Ia(a,b,c){if(!a.o.Ia)throw new FS.h(59);return a.o.Ia(a,b,c)},readFile(a,b={}){b.flags=
b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&J(`Invalid encoding type "${b.encoding}"`);var c=FS.open(a,b.flags);a=FS.stat(a).size;var d=new Uint8Array(a);FS.read(c,d,0,a,0);"utf8"===b.encoding&&(d=oe(d));FS.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=FS.open(a,c.flags,c.mode);b=jf(b);FS.write(a,b,0,b.byteLength,void 0,c.Ec);FS.close(a)},cwd:()=>FS.Xa,chdir(a){a=FS.lookupPath(a,{follow:!0});if(null===a.node)throw new FS.h(44);if(!FS.isDir(a.node.mode))throw new FS.h(54);
var b=nf(a.node,"x");if(b)throw new FS.h(b);FS.Xa=a.path},init(a,b,c){FS.Ha=!0;a??=h.stdin;b??=h.stdout;c??=h.stderr;a?FS.createDevice("/dev","stdin",a):FS.symlink("/dev/tty","/dev/stdin");b?FS.createDevice("/dev","stdout",null,b):FS.symlink("/dev/tty","/dev/stdout");c?FS.createDevice("/dev","stderr",null,c):FS.symlink("/dev/tty1","/dev/stderr");FS.open("/dev/stdin",0);FS.open("/dev/stdout",1);FS.open("/dev/stderr",1)},Hc(a,b){a=FS.analyzePath(a,b);return a.ab?a.object:null},analyzePath(a,b){try{var c=
FS.lookupPath(a,{follow:!b});a=c.path}catch(e){}var d={na:!1,ab:!1,error:0,name:null,path:null,object:null,cc:!1,fc:null,ec:null};try{c=FS.lookupPath(a,{parent:!0}),d.cc=!0,d.fc=c.path,d.ec=c.node,d.name=Oe(a),c=FS.lookupPath(a,{follow:!b}),d.ab=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.na="/"===c.path}catch(e){d.error=e.B}return d},createPath(a,b){a="string"==typeof a?a:FS.getPath(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Me(a+"/"+c);try{FS.mkdir(d)}catch(e){if(20!=
e.B)throw e;}a=d}}return d},createDataFile(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:FS.getPath(a),g=b?Me(a+"/"+b):a);a=kf(d,e);g=FS.create(g,a);c&&(c=jf(c),FS.chmod(g,a|146),b=FS.open(g,577),FS.write(b,c,0,c.length,0,f),FS.close(b),FS.chmod(g,a))},createDevice(a,b,c,d){a=Pe("string"==typeof a?a:FS.getPath(a),b);b=kf(!!c,!!d);var e;(e=FS.createDevice).La??(e.La=64);e=FS.makedev(FS.createDevice.La++,0);FS.registerDevice(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,k,l){for(var m=
0,n=0;n<l;n++){try{var q=c()}catch(u){throw new FS.h(29);}if(void 0===q&&0===m)throw new FS.h(6);if(null===q||void 0===q)break;m++;g[k+n]=q}m&&(f.node.$=Date.now());return m},write(f,g,k,l){for(var m=0;m<l;m++)try{d(g[k+m])}catch(n){throw new FS.h(29);}l&&(f.node.O=f.node.N=Date.now());return m}});return FS.mkdev(a,b,e)},createLazyFile(a,b,c,d,e){function f(n,q,u,r,v){n=n.node.u;if(v>=n.length)return 0;r=Math.min(n.length-v,r);if(n.slice)for(var x=0;x<r;x++)q[u+x]=n[v+x];else for(x=0;x<r;x++)q[u+
x]=n.get(v+x);return r}class g{Ga=!1;P=[];ma=void 0;hb=0;gb=0;get(n){if(!(n>this.length-1||0>n)){var q=n%this.ob;return this.ma(n/this.ob|0)[q]}}sc(n){this.ma=n}jb(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);200<=n.status&&300>n.status||304===n.status||J("Couldn't load "+c+". Status: "+n.status);var q=Number(n.getResponseHeader("Content-length")),u,r=(u=n.getResponseHeader("Accept-Ranges"))&&"bytes"===u;n=(u=n.getResponseHeader("Content-Encoding"))&&"gzip"===u;var v=1048576;r||(v=
q);var x=this;x.sc(D=>{var B=D*v,E=(D+1)*v-1;E=Math.min(E,q-1);if("undefined"==typeof x.P[D]){var R=x.P;B>E&&J("invalid range ("+B+", "+E+") or no bytes requested!");E>q-1&&J("only "+q+" bytes available! programmer error!");var C=new XMLHttpRequest;C.open("GET",c,!1);q!==v&&C.setRequestHeader("Range","bytes="+B+"-"+E);C.responseType="arraybuffer";C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");C.send(null);200<=C.status&&300>C.status||304===C.status||J("Couldn't load "+
c+". Status: "+C.status);B=void 0!==C.response?new Uint8Array(C.response||[]):$e(C.responseText||"");R[D]=B}"undefined"==typeof x.P[D]&&J("doXHR failed!");return x.P[D]});if(n||!q)v=q=1,v=q=this.ma(0).length,ka("LazyFiles on gzip forces download of the whole file when length is accessed");this.hb=q;this.gb=v;this.Ga=!0}get length(){this.Ga||this.jb();return this.hb}get ob(){this.Ga||this.jb();return this.gb}}if(globalThis.XMLHttpRequest){ba||J("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var k=new g;var l=void 0}else l=c,k=void 0;var m=Af(a,b,d,e);k?m.u=k:l&&(m.u=null,m.url=l);Object.defineProperties(m,{L:{get:function(){return this.u.length}}});a={};for(const [n,q]of Object.entries(m.o))a[n]=(...u)=>{Bf(m);return q(...u)};a.read=(n,q,u,r,v)=>{Bf(m);return f(n,q,u,r,v)};a.ja=(n,q,u)=>{Bf(m);var r=ff(q);if(!r)throw new FS.h(48);f(n,(w(),y),r,q,u);return{A:r,fa:!0}};m.o=a;return m}},He=(a,b)=>{if(Ja){if("/"===a.charAt(0))try{return FS.lookupPath(a),a}catch(d){return}var c=(b?.hc||[]).map(d=>
{var e=b?.dc;return d.startsWith("$ORIGIN")?d.replace("$ORIGIN",Ne(e)):d});return Qe(()=>{var d=td(512),e=Ue(c.join(":")),f=Ue(a);return(d=jd(d,e,f,512))?P(d):void 0})}};
function Ie(a,b={global:!0,pa:!0},c,d){function e(){var l=ua[a];if(l)return b.I?Promise.resolve(l):l;if(d){l=(w(),H)[d+28>>2];var m=(w(),H)[d+32>>2];if(l&&m)return l=(w(),y).slice(l,l+m),b.I?Promise.resolve(l):l}if(l=He(a,b.Ra))return l=FS.readFile(l,{encoding:"binary"}),b.I?Promise.resolve(l):l;l=ha(a);if(b.I)return Ke(l);if(!ja)throw Error(`${l}: file not found, and synchronous loading of external files is not available`);return ja(l)}function f(){var l=ee[a];return l?b.I?Promise.resolve(l):l:b.I?
e().then(m=>Je(m,b,a,c,d)):Je(e(),b,a,c,d)}function g(l){k.global?Uc(l):c&&Object.assign(c,l);k.exports=l}var k=pe[a];if(k)return b.global?k.global||(k.global=!0,Uc(k.exports)):c&&Object.assign(c,k.exports),b.pa&&Infinity!==k.Aa&&(k.Aa=Infinity),k.Aa++,d&&(qe[d]=k),b.I?Promise.resolve(!0):!0;k=Ad(a,d,"loading");k.Aa=b.pa?Infinity:1;k.global=b.global;if(b.I)return f().then(l=>{g(l);return!0});g(f());return!0}
var Ge=()=>{var a,b;for([a,b]of Object.entries(ke))if(-1==b.value){var c=Ee(a).Ta;if(c||b.required)if("function"==typeof c)b.value=Ae(c,c.g);else if("number"==typeof c)b.value=c;else if("number"==typeof c.value)b.value=c;else throw Error(`bad export type for '${a}': ${typeof c} (${c})`);else b.value=0}},Bd=async()=>{if(la.length){Qd("loadDylibs");for(var a of la)await Ie(a,{I:!0,global:!0,pa:!0,xb:!0});Ge();Pd("loadDylibs")}else Ge()},ae=!1,Wc=(a,b,c)=>{function d(){var e=a();if(e){var f={};c.qb.forEach(g=>
f[g]=b[g]);zd(Be(f,e),!0)}}Vd.push(d);Ja&&d()},qa,Za=(a,b,c,d)=>J(`Assertion failed: ${P(a)}, at: `+[b?P(b):"unknown filename",c,d?P(d):"unknown function"]);Za.g="vppip";var ab=(a,b)=>M.get(a)(b);ab.g="vpi";function bb(...a){return K.__lsan_ignore_object(...a)}bb.Sa=!0;function Cf(a,b,c,d){return p?O(2,1,a,b,c,d):cb(a,b,c,d)}
var cb=(a,b,c,d)=>{if(!globalThis.SharedArrayBuffer)return 6;var e=[];if(p&&0===e.length)return Cf(a,b,c,d);a={qc:c,X:a,Da:d,rb:e};return p?(a.V="spawnThread",postMessage(a,e),0):Td(a)};cb.g="ipppp";var Df=18;function Ef(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?FS.cwd():S(a).path;if(0==b.length){if(!c)throw new FS.h(44);return a}return a+"/"+b}
function Ff(a,b){(w(),H)[a>>2]=b.Cb;(w(),H)[a+4>>2]=b.mode;(w(),H)[a+8>>2]=b.$b;(w(),H)[a+12>>2]=b.uid;(w(),H)[a+16>>2]=b.Pb;(w(),H)[a+20>>2]=b.ra;(w(),I)[a+24>>3]=BigInt(b.size);(w(),G)[a+32>>2]=4096;(w(),G)[a+36>>2]=b.Va;var c=b.$.getTime(),d=b.O.getTime(),e=b.N.getTime();(w(),I)[a+40>>3]=BigInt(Math.floor(c/1E3));(w(),H)[a+48>>2]=c%1E3*1E6;(w(),I)[a+56>>3]=BigInt(Math.floor(d/1E3));(w(),H)[a+64>>2]=d%1E3*1E6;(w(),I)[a+72>>3]=BigInt(Math.floor(e/1E3));(w(),H)[a+80>>2]=e%1E3*1E6;(w(),I)[a+88>>3]=
BigInt(b.Tb);return 0}var Gf=void 0;function db(a){if(p)return O(3,1,a);try{var b=S(a);return uf(b).aa}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}db.g="ii";function eb(a,b,c,d){if(p)return O(4,1,a,b,c,d);try{b=P(b);b=Ef(a,b);if(c&-8)return-28;var e=FS.lookupPath(b,{follow:!0}).node;if(!e)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&nf(e,a)?-2:0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}eb.g="iipii";
var Hf=()=>{var a=(w(),G)[+Gf>>2];Gf+=4;return a};function fb(a,b,c){if(p)return O(5,1,a,b,c);Gf=c;try{var d=S(a);switch(b){case 0:var e=Hf();if(0>e)break;for(;FS.streams[e];)e++;return uf(d,e).aa;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Hf(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=Hf(),(w(),z)[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}fb.g="iiip";
function gb(a,b){if(p)return O(6,1,a,b);try{var c=S(a),d=c.node,e=c.o.S;a=e?c:d;e??=d.m.S;sf(e,63);var f=e(a);return Ff(b,f)}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.B}}gb.g="iip";function hb(a,b){if(p)return O(7,1,a,b);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return-22;FS.ftruncate(a,b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}hb.g="iij";
function ib(a,b){if(p)return O(8,1,a,b);try{if(0===b)return-28;var c=FS.cwd(),d=Re(c)+1;if(b<d)return-68;Te(c,a,b);return d}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.B}}ib.g="ipp";
function jb(a,b,c){if(p)return O(9,1,a,b,c);Gf=c;try{var d=S(a);switch(b){case 21509:return d.C?0:-59;case 21505:if(!d.C)return-59;if(d.C.ea.Ub){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Hf();(w(),G)[e>>2]=25856;(w(),G)[e+4>>2]=5;(w(),G)[e+8>>2]=191;(w(),G)[e+12>>2]=35387;for(var f=0;32>f;f++)(w(),y)[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.C?0:-59;case 21506:case 21507:case 21508:if(!d.C)return-59;if(d.C.ea.Vb)for(e=Hf(),w(),w(),
w(),w(),a=[],f=0;32>f;f++)a.push((w(),y)[e+f+17]);return 0;case 21519:if(!d.C)return-59;e=Hf();return(w(),G)[e>>2]=0;case 21520:return d.C?-28:-59;case 21537:case 21531:return e=Hf(),FS.Ia(d,b,e);case 21523:if(!d.C)return-59;d.C.ea.Wb&&(f=[24,80],e=Hf(),(w(),z)[e>>1]=f[0],(w(),z)[e+2>>1]=f[1]);return 0;case 21524:return d.C?0:-59;case 21515:return d.C?0:-59;default:return-28}}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.B}}jb.g="iiip";
function kb(a,b){if(p)return O(10,1,a,b);try{return a=P(a),Ff(b,FS.lstat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}kb.g="ipp";function lb(a,b,c,d){if(p)return O(11,1,a,b,c,d);try{b=P(b);var e=d&256;b=Ef(a,b,d&4096);return Ff(c,e?FS.lstat(b):FS.stat(b))}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}lb.g="iippi";
function mb(a,b,c,d){if(p)return O(12,1,a,b,c,d);Gf=d;try{b=P(b);b=Ef(a,b);var e=d?Hf():0;c&64&&(e&=~Df);return FS.open(b,c,e).aa}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}mb.g="iipip";function nb(a){if(p)return O(13,1,a);try{return a=P(a),FS.rmdir(a),0}catch(b){if("undefined"==typeof FS||"ErrnoError"!==b.name)throw b;return-b.B}}nb.g="ip";
function ob(a,b){if(p)return O(14,1,a,b);try{return a=P(a),Ff(b,FS.stat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}ob.g="ipp";function pb(a,b,c){if(p)return O(15,1,a,b,c);try{b=P(b);b=Ef(a,b);if(c)if(512===c)FS.rmdir(b);else return-28;else FS.unlink(b);return 0}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.B}}pb.g="iipi";
var qb=a=>{a=new WebAssembly.Exception(yd,[a],{traceStack:!0});var b=a.getArg(yd,0);var c=vd(b);b=ud();var d=td(4),e=td(4);wd(c,d,e);c=(w(),H)[d>>2];e=(w(),H)[e>>2];d=P(c);L(c);if(e){var f=P(e);L(e)}sd(b);a.message=[d,f];throw a;},rb=()=>J("");rb.g="v";
var If=a=>{var b=ud();a=Ue(a);dd(a,0);sd(b)},Jf=(a,b)=>{var c=P(a+36),d=(w(),G)[a+4>>2];c=Me(c);var e=!!(d&256),f=e?null:{};d={global:e,pa:!!(d&4096),I:b.I};if(b.I)return Ie(c,d,f,a);try{return Ie(c,d,f,a)}catch(g){return If(`could not load dynamic lib: ${c}\n${g}`),0}},sb=a=>Jf(a,{I:!1});sb.g="pp";var tb=(a,b)=>{a=qe[a].exports;b=Object.keys(a)[b];b=a[b];return Ae(b,b.g)};tb.g="ppi";
var ub=(a,b,c)=>{b=P(b);var d=qe[a];a=Object.keys(d.exports).indexOf(b);if(-1==a||d.exports[b].Sa)return If(`Tried to lookup unknown symbol "${b}" in dynamic lib: ${d.name}`),0;b=d.exports[b];"function"==typeof b&&((d=ve(b))?b=d:(b=Ae(b,b.g),(w(),H)[c>>2]=a));return b};ub.g="pppp";var Kf={},Lf=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Mf(a){return this.v((w(),H)[a>>2])}
var Nf={},Of={},Pf={},Qf=class extends Error{constructor(a){super(a);this.name="InternalError"}},U=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new Qf("Mismatched type converter count");for(var l=0;l<a.length;++l)T(a[l],k[l])}a.forEach(k=>Pf[k]=b);var e=Array(b.length),f=[],g=0;for(let [k,l]of b.entries())Of.hasOwnProperty(l)?e[k]=Of[l]:(f.push(l),Nf.hasOwnProperty(l)||(Nf[l]=[]),Nf[l].push(()=>{e[k]=Of[l];++g;g===f.length&&d(e)}));0===f.length&&d(e)},vb=a=>{var b=Kf[a];delete Kf[a];
var c=b.Qa,d=b.Y,e=b.bb,f=e.map(g=>g.Ob).concat(e.map(g=>g.mc));U([a],f,g=>{var k={},l,m;for([l,m]of e.entries()){const n=g[l],q=m.ma,u=m.Nb,r=g[l+e.length],v=m.lc,x=m.nc;k[m.Hb]={read:D=>n.v(q(u,D)),write:(D,B)=>{var E=[];v(x,D,r.F(E,B));Lf(E)},optional:n.optional}}return[{name:b.name,v:n=>{var q={},u;for(u in k)q[u]=k[u].read(n);d(n);return q},F:(n,q)=>{for(var u in k)if(!(u in q||k[u].optional))throw new TypeError(`Missing field: "${u}"`);var r=c();for(u in k)k[u].write(r,q[u]);null!==n&&n.push(d,
r);return r},K:Mf,H:d}]})};vb.g="vp";var V=a=>{for(var b="";;){var c=(w(),A)[a++];if(!c)return b;b+=String.fromCharCode(c)}},W=class extends Error{constructor(a){super(a);this.name="BindingError"}},Rf=a=>{throw new W(a);};
function Sf(a,b,c={}){var d=b.name;if(!a)throw new W(`type "${d}" must have a positive integer typeid pointer`);if(Of.hasOwnProperty(a)){if(c.Sb)return;throw new W(`Cannot register type '${d}' twice`);}Of[a]=b;delete Pf[a];Nf.hasOwnProperty(a)&&(b=Nf[a],delete Nf[a],b.forEach(e=>e()))}function T(a,b,c={}){return Sf(a,b,c)}
var Tf=(a,b)=>{switch(b){case 4:return w(),La;case 8:return w(),Ma;default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Uf=(a,b,c)=>{switch(b){case 1:return c?(w(),y):(w(),A);case 2:return c?(w(),z):(w(),F);case 4:return c?(w(),G):(w(),H);case 8:return c?(w(),I):(w(),Na);default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},wb=(a,b,c,d,e)=>{b=V(b);var f=d?Tf(b,c):Uf(b,c,e),g=Math.log2(c);T(a,{name:b,v:k=>{var l=(w(),H)[k>>2],m=k+Math.max(4,c)>>g;l=Array.from(f.subarray(m,
m+l));L(k);return l},F:(k,l)=>{"number"==typeof l&&(l=[l]);if(!Array.isArray(l))throw new W(`Cannot pass non-array to C++ vector type ${b}`);l=Array.prototype.concat.apply([],l);var m=l.length,n=Math.max(4,c),q=Yc(n+m*c);n=q+n>>g;(w(),H)[q>>2]=m;f.set(l,n);null!==k&&k.push(L,q);return q},K:Mf,H(k){L(k)}})};wb.g="vpppii";
var Vf=(a,b,c)=>{switch(b){case 1:return c?d=>(w(),y)[d]:d=>(w(),A)[d];case 2:return c?d=>(w(),z)[d>>1]:d=>(w(),F)[d>>1];case 4:return c?d=>(w(),G)[d>>2]:d=>(w(),H)[d>>2];case 8:return c?d=>(w(),I)[d>>3]:d=>(w(),Na)[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},xb=(a,b,c,d,e)=>{b=V(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=k=>BigInt.asUintN(g,k);e=f(e)}T(a,{name:b,v:f,F:(g,k)=>{"number"==typeof k&&(k=BigInt(k));return k},K:Vf(b,c,!d),H:null})};xb.g="vpppjj";
var Ab=(a,b,c,d)=>{b=V(b);T(a,{name:b,v:function(e){return!!e},F:function(e,f){return f?c:d},K:function(e){return this.v((w(),A)[e])},H:null})};Ab.g="vppii";
var Wf=a=>{throw new W(a.l.D.s.name+" instance already deleted");},Xf=!1,Yf=!1,Zf=()=>{},$f=a=>{if(Xf)return $f=b=>b.deleteLater(),$f(a);if(!globalThis.FinalizationRegistry)return $f=b=>b,a;Yf=new FinalizationRegistry(b=>{b=b.l;--b.count.value;0===b.count.value&&(b.J?b.R.Y(b.J):b.D.s.Y(b.A))});$f=b=>{var c=b.l;c.J&&Yf.register(b,{l:c},b);return b};Zf=b=>{Yf.unregister(b)};return $f(a)},ag=[],bg=()=>{for(;ag.length;){var a=ag.pop();a.l.ha=!1;a["delete"]()}},cg;function dg(){}
var eg={},fg=(a,b,c)=>{if(void 0===a[b].G){var d=a[b];a[b]=function(...e){if(!a[b].G.hasOwnProperty(e.length))throw new W(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].G})!`);return a[b].G[e.length].apply(this,e)};a[b].G=[];a[b].G[d.Z]=d}},gg=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].G&&void 0!==h[a].G[c])throw new W(`Cannot register public name '${a}' twice`);fg(h,a,a);if(h[a].G.hasOwnProperty(c))throw new W(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].G[c]=b}else h[a]=b,h[a].Z=c},hg=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function ig(a,b,c,d,e,f,g,k){this.name=a;this.constructor=b;this.ba=c;this.Y=d;this.M=e;this.Jb=f;this.ua=g;this.Db=k;this.jc=[]}
var jg=(a,b,c)=>{for(;b!==c;){if(!b.ua)throw new W(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ua(a);b=b.M}return a},kg=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function lg(a,b){if(null===b){if(this.Ja)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new W(`Cannot pass "${kg(b)}" as a ${this.name}`);if(!b.l.A)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);return jg(b.l.A,b.l.D.s,this.s)}
function mg(a,b){if(null===b){if(this.Ja)throw new W(`null is not a valid ${this.name}`);if(this.za){var c=this.Qa();null!==a&&a.push(this.Y,c);return c}return 0}if(!b||!b.l)throw new W(`Cannot pass "${kg(b)}" as a ${this.name}`);if(!b.l.A)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ya&&b.l.D.ya)throw new W(`Cannot convert argument of type ${b.l.R?b.l.R.name:b.l.D.name} to parameter type ${this.name}`);c=jg(b.l.A,b.l.D.s,this.s);if(this.za){if(void 0===b.l.J)throw new W("Passing raw pointer to smart pointer is illegal");
switch(this.pc){case 0:if(b.l.R===this)c=b.l.J;else throw new W(`Cannot convert argument of type ${b.l.R?b.l.R.name:b.l.D.name} to parameter type ${this.name}`);break;case 1:c=b.l.J;break;case 2:if(b.l.R===this)c=b.l.J;else{var d=b.clone();c=this.kc(c,ng(()=>d["delete"]()));null!==a&&a.push(this.Y,c)}break;default:throw new W("Unsupported sharing policy");}}return c}
function og(a,b){if(null===b){if(this.Ja)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new W(`Cannot pass "${kg(b)}" as a ${this.name}`);if(!b.l.A)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.l.D.ya)throw new W(`Cannot convert argument of type ${b.l.D.name} to parameter type ${this.name}`);return jg(b.l.A,b.l.D.s,this.s)}
var pg=(a,b,c)=>{if(b===c)return a;if(void 0===c.M)return null;a=pg(a,b,c.M);return null===a?null:c.Db(a)},qg={},rg=(a,b)=>{if(void 0===b)throw new W("ptr should not be undefined");for(;a.M;)b=a.ua(b),a=a.M;return qg[b]},sg=(a,b)=>{if(!b.D||!b.A)throw new Qf("makeClassHandle requires ptr and ptrType");if(!!b.R!==!!b.J)throw new Qf("Both smartPtrType and smartPtr must be specified");b.count={value:1};return $f(Object.create(a,{l:{value:b,writable:!0}}))};
function tg(a,b,c,d,e,f,g,k,l,m,n){this.name=a;this.s=b;this.Ja=c;this.ya=d;this.za=e;this.ic=f;this.pc=g;this.lb=k;this.Qa=l;this.kc=m;this.Y=n;e||void 0!==b.M?this.F=mg:(this.F=d?lg:og,this.H=null)}var ug=(a,b,c)=>{if(!h.hasOwnProperty(a))throw new Qf("Replacing nonexistent public symbol");void 0!==h[a].G&&void 0!==c?h[a].G[c]=b:(h[a]=b,h[a].Z=c)},X=(a,b)=>{a=V(a);var c=M.get(b);if("function"!=typeof c)throw new W(`unknown function pointer with signature ${a}: ${b}`);return c};
class vg extends Error{}
var wg=a=>{a=ad(a);var b=V(a);L(a);return b},xg=(a,b)=>{function c(f){e[f]||Of[f]||(Pf[f]?Pf[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new vg(`${a}: `+d.map(wg).join([", "]));},Bb=(a,b,c,d,e,f,g,k,l,m,n,q,u)=>{n=V(n);f=X(e,f);k&&=X(g,k);m&&=X(l,m);u=X(q,u);var r=hg(n);gg(r,function(){xg(`Cannot construct ${n} due to unbound types`,[d])});U([a,b,c],d?[d]:[],v=>{v=v[0];if(d){var x=v.s;var D=x.ba}else D=dg.prototype;v=De(n,function(...C){if(Object.getPrototypeOf(this)!==B)throw new W(`Use 'new' to construct ${n}`);
if(void 0===E.ga)throw new W(`${n} has no accessible constructor`);var Ia=E.ga[C.length];if(void 0===Ia)throw new W(`Tried to invoke ctor of ${n} with invalid number of parameters (${C.length}) - expected (${Object.keys(E.ga).toString()}) parameters instead!`);return Ia.apply(this,C)});var B=Object.create(D,{constructor:{value:v}});v.prototype=B;var E=new ig(n,v,B,u,x,f,k,m);if(E.M){var R;(R=E.M).va??(R.va=[]);E.M.va.push(E)}x=new tg(n,E,!0,!1,!1);R=new tg(n+"*",E,!1,!1,!1);D=new tg(n+" const*",E,
!1,!0,!1);eg[a]={pointerType:R,Bb:D};ug(r,v);return[x,R,D]})};Bb.g="vppppppppppppp";function Bg(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].H)return!0;return!1}
function Cg(a,b,c,d,e,f){var g=b.length;if(2>g)throw new W("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,l=Bg(b);c=!b[0].fb;var m=b[0],n=b[1];d=[a,Rf,d,e,Lf,m.v.bind(m),n?.F.bind(n)];for(e=2;e<g;++e)m=b[e],d.push(m.F.bind(m));if(!l)for(e=k?1:2;e<b.length;++e)null!==b[e].H&&d.push(b[e].H);l=Bg(b);e=b.length-2;n=[];m=["fn"];k&&m.push("thisWired");for(g=0;g<e;++g)n.push(`arg${g}`),m.push(`arg${g}Wired`);n=n.join(",");m=m.join(",");n=`return function (${n}) {\n`;
l&&(n+="var destructors = [];\n");var q=l?"destructors":"null",u="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");k&&(n+=`var thisWired = toClassParamWire(${q}, this);\n`);for(g=0;g<e;++g){var r=`toArg${g}Wire`;n+=`var arg${g}Wired = ${r}(${q}, arg${g});\n`;u.push(r)}n+=(c||f?"var rv = ":"")+`invoker(${m});\n`;if(l)n+="runDestructors(destructors);\n";else for(g=k?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].H&&(n+=`${f}_dtor(${f});\n`,
u.push(`${f}_dtor`));c&&(n+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(u,n+"}\n"))(...d);return De(a,b)}
var Dg=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push((w(),H)[b+4*d>>2]);return c},Eg=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Cb=(a,b,c,d,e,f,g,k)=>{var l=Dg(c,d);b=V(b);b=Eg(b);f=X(e,f);U([],[a],m=>{function n(){xg(`Cannot call ${q} due to unbound types`,l)}m=m[0];var q=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var u=m.s.constructor;void 0===u[b]?(n.Z=c-1,u[b]=n):(fg(u,b,q),u[b].G[c-1]=n);U([],l,r=>{r=Cg(q,[r[0],null].concat(r.slice(1)),null,f,g,k);void 0===
u[b].G?(r.Z=c-1,u[b]=r):u[b].G[c-1]=r;if(m.s.va)for(const v of m.s.va)v.constructor.hasOwnProperty(b)||(v.constructor[b]=r);return[]});return[]})};Cb.g="vppippppii";
var Db=(a,b,c,d,e,f)=>{var g=Dg(b,c);e=X(d,e);U([],[a],k=>{k=k[0];var l=`constructor ${k.name}`;void 0===k.s.ga&&(k.s.ga=[]);if(void 0!==k.s.ga[b-1])throw new W(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);k.s.ga[b-1]=()=>{xg(`Cannot construct ${k.name} due to unbound types`,g)};U([],g,m=>{m.splice(1,0,null);k.s.ga[b-1]=Cg(l,m,null,e,f);return[]});
return[]})};Db.g="vpipppp";var Eb=(a,b,c,d,e,f,g,k,l)=>{var m=Dg(c,d);b=V(b);b=Eg(b);f=X(e,f);U([],[a],n=>{function q(){xg(`Cannot call ${u} due to unbound types`,m)}n=n[0];var u=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&n.s.jc.push(b);var r=n.s.ba,v=r[b];void 0===v||void 0===v.G&&v.className!==n.name&&v.Z===c-2?(q.Z=c-2,q.className=n.name,r[b]=q):(fg(r,b,u),r[b].G[c-2]=q);U([],m,x=>{x=Cg(u,x,n,f,g,l);void 0===r[b].G?(x.Z=c-2,r[b]=x):r[b].G[c-2]=x;return[]});return[]})};
Eb.g="vppippppiii";
var Fg=(a,b,c)=>{if(!(a instanceof Object))throw new W(`${c} with invalid "this": ${a}`);if(!(a instanceof b.s.constructor))throw new W(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.l.A)throw new W(`cannot call emscripten binding method ${c} on deleted object`);return jg(a.l.A,a.l.D.s,b.s)},Fb=(a,b,c,d,e,f,g,k,l,m)=>{b=V(b);e=X(d,e);U([],[a],n=>{n=n[0];var q=`${n.name}.${b}`,u={get(){xg(`Cannot access ${q} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};u.set=l?
()=>xg(`Cannot access ${q} due to unbound types`,[c,g]):()=>{throw new W(q+" is a read-only property");};Object.defineProperty(n.s.ba,b,u);U([],l?[c,g]:[c],r=>{var v=r[0],x={get(){var B=Fg(this,n,q+" getter");return v.v(e(f,B))},enumerable:!0};if(l){l=X(k,l);var D=r[1];x.set=function(B){var E=Fg(this,n,q+" setter"),R=[];l(m,E,D.F(R,B));Lf(R)}}Object.defineProperty(n.s.ba,b,x);return[]});return[]})};Fb.g="vpppppppppp";
var Gg=[],Hg=[0,1,,1,null,1,!0,1,!1,1],Ig=[],fc=a=>{if(9<a&&0===--Hg[a+1]){var b=Hg[a];Hg[a]=void 0;var c=Ig[a];c&&(Ig[a]=void 0,c(b));Gg.push(a)}};fc.g="vp";var Y=a=>{if(!a)throw new W(`Cannot use deleted val. handle = ${a}`);return Hg[a]},ng=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Gg.pop()||Hg.length;Hg[b]=a;Hg[b+1]=1;return b}},Jg={name:"emscripten::val",v:a=>{var b=Y(a);fc(a);return b},F:(a,b)=>ng(b),K:Mf,H:null},Gb=a=>T(a,Jg);
Gb.g="vp";
var Kg=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.v((w(),y)[d])}:function(d){return this.v((w(),A)[d])};case 2:return c?function(d){return this.v((w(),z)[d>>1])}:function(d){return this.v((w(),F)[d>>1])};case 4:return c?function(d){return this.v((w(),G)[d>>2])}:function(d){return this.v((w(),H)[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Hb=(a,b,c,d,e)=>{b=V(b);e=0===e?"object":1===e?"number":"string";switch(e){case "object":function g(){}g.values={};
T(a,{name:b,constructor:g,valueType:e,v:function(k){return this.constructor.values[k]},F:(k,l)=>l.value,K:Kg(b,c,d),H:null});gg(b,g);break;case "number":var f={};T(a,{name:b,Ka:f,valueType:e,v:k=>k,F:(k,l)=>l,K:Kg(b,c,d),H:null});gg(b,f);delete h[b].Z;break;case "string":f={},T(a,{name:b,sb:{},mb:{},Ka:f,valueType:e,v:function(k){return this.mb[k]},F:function(k,l){return this.sb[l]},K:Kg(b,c,d),H:null}),gg(b,f),delete h[b].Z}};Hb.g="vpppii";
var Lg=(a,b)=>{var c=Of[a];if(void 0===c)throw a=`${b} has unknown type ${wg(a)}`,new W(a);return c},Ib=(a,b,c)=>{var d=Lg(a,"enum");b=V(b);switch(d.valueType){case "object":a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:De(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d;break;case "number":d.Ka[b]=c;break;case "string":d.sb[b]=c,d.mb[c]=b,d.Ka[b]=b}};Ib.g="vppi";
var Mg=(a,b)=>{switch(b){case 4:return function(c){return this.v((w(),La)[c>>2])};case 8:return function(c){return this.v((w(),Ma)[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Jb=(a,b,c)=>{b=V(b);T(a,{name:b,v:d=>d,F:(d,e)=>e,K:Mg(b,c),H:null})};Jb.g="vppp";var Kb=(a,b,c,d,e,f,g)=>{var k=Dg(b,c);a=V(a);a=Eg(a);e=X(d,e);gg(a,function(){xg(`Cannot call ${a} due to unbound types`,k)},b-1);U([],k,l=>{ug(a,Cg(a,[l[0],null].concat(l.slice(1)),null,e,f,g),b-1);return[]})};
Kb.g="vpippppii";var Lb=(a,b,c,d,e)=>{b=V(b);let f=k=>k;if(0===d){var g=32-8*c;f=k=>k<<g>>>g;e=f(e)}T(a,{name:b,v:f,F:(k,l)=>l,K:Vf(b,c,0!==d),H:null})};Lb.g="vpppii";var Ng=(a,b,c)=>{const d=(e,f)=>{let g=0;return{next(){if(g>=e)return{done:!0};const k=g;g++;return{value:f(k),done:!1}},[Symbol.iterator](){return this}}};a[Symbol.iterator]||(a[Symbol.iterator]=function(){const e=this[b]();return d(e,f=>this[c](f))})},Mb=(a,b,c,d)=>{c=V(c);d=V(d);U([],[a,b],e=>{Ng(e[0].s.ba,c,d);return[]})};Mb.g="vpppp";
var Nb=(a,b,c)=>{function d(f){var g=(w(),H)[f>>2];f=(w(),H)[f+4>>2];return new e((w(),y).buffer,f,g)}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=V(c);T(a,{name:c,v:d,K:d},{Sb:!0})};Nb.g="vpip";var Og=Object.assign({optional:!0},Jg),Ob=a=>{T(a,Og)};Ob.g="vpp";
var Pb=(a,b)=>{b=V(b);T(a,{name:b,v(c){var d=(w(),H)[c>>2];d=P(c+4,d,!0);L(c);return d},F(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new W("Cannot pass non-string to std::string");var f=e?Re(d):d.length;var g=Yc(4+f+1),k=g+4;(w(),H)[g>>2]=f;e?Te(d,k,f+1):(w(),A).set(d,k);null!==c&&c.push(L,g);return g},K:Mf,H(c){L(c)}})};Pb.g="vpp";
var Pg=new TextDecoder("utf-16le"),Qg=(a,b,c)=>{a>>=1;b=ne((w(),F),a,b/2,c);return Pg.decode((w(),F).slice(a,b))},Rg=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);(w(),z)[b>>1]=f;b+=2}(w(),z)[b>>1]=0;return b-d},Sg=a=>2*a.length,Tg=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=(w(),H)[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Ug=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=
0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;(w(),G)[b>>2]=f;b+=4;if(b+4>c)break}(w(),G)[b>>2]=0;return b-d},Vg=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Qb=(a,b,c)=>{c=V(c);if(2===b){var d=Qg;var e=Rg;var f=Sg}else d=Tg,e=Ug,f=Vg;T(a,{name:c,v:g=>{var k=(w(),H)[g>>2];k=d(g+4,k*b,!0);L(g);return k},F:(g,k)=>{if("string"!=typeof k)throw new W(`Cannot pass non-string to C++ string type ${c}`);var l=f(k),m=Yc(4+l+b);(w(),H)[m>>2]=l/b;e(k,m+4,l+b);null!==g&&
g.push(L,m);return m},K:Mf,H(g){L(g)}})};Qb.g="vppp";var Rb=(a,b,c,d,e,f)=>{Kf[a]={name:V(b),Qa:X(c,d),Y:X(e,f),bb:[]}};Rb.g="vpppppp";var Sb=(a,b,c,d,e,f,g,k,l,m)=>{Kf[a].bb.push({Hb:V(b),Ob:c,ma:X(d,e),Nb:f,mc:g,lc:X(k,l),nc:m})};Sb.g="vpppppppppp";var Tb=(a,b)=>{b=V(b);T(a,{fb:!0,name:b,v:()=>{},F:()=>{}})};Tb.g="vpp";
var Ub=(a,b,c,d)=>{function e(k){var l=P(a+36);If(`'Could not load dynamic lib: ${l}\n${k}`);--N;Zd(()=>M.get(c)(a,d))}function f(){--N;Zd(()=>M.get(b)(a,d))}N+=1;var g=Jf(a,{I:!0});g?g.then(f,e):e()};Ub.g="vpppp";function Wg(a){var b=Xg,c=b.P.pop()||b.fa.length;b.fa[c]=a;return c}function Yg(a){var b=Xg;b.fa[a]=void 0;b.P.push(a)}class Zg{fa=[void 0];P=[];get(a){return this.fa[a]}has(a){return void 0!==this.fa[a]}}
var Xg=new Zg,$g=()=>{var a={};a.promise=new Promise((b,c)=>{a.reject=c;a.resolve=b});a.id=Wg(a);return a},ah=async()=>{const a=$d,b=[];var c=$g();b.push(c.promise);ed(c.id);for(const d of Object.keys(Fd)){const e=Number(d);e===a||Gd.has(e)||(c=$g(),gd(e,c.id),Hd[e]=c,b.push(c.promise))}await Promise.all(b);Hd={}};function Vb(){if(p)return O(16,2);if($d)return ah();for(const a of Object.keys(Fd)){const b=Number(a);Gd.has(b)||hd(b)}}Vb.g="v";
function Wb(){var a=Yc(4*(la.length+1)),b=a;la.forEach(c=>{var d=(w(),H),e=b>>2,f=Re(c)+1,g=Yc(f);g&&Te(c,g,f);d[e]=g;b+=4});(w(),H)[b>>2]=0;return a}Wb.g="p";var Xb=a=>{Ba(a,!ba,1,!aa,262144,!1);Ca()};Xb.g="vp";var Da=a=>{Ud||(Atomics.waitAsync((w(),G),a>>2,a).value.then(Ga),a+=120,Atomics.store((w(),G),a>>2,1))};Da.g="vp";var Ga=()=>{var a=Xc();a&&Zd(()=>{Da(a);pd()})},Yb=(a,b)=>{a==b?setTimeout(Ga):p?postMessage({Ca:a,V:"checkMailbox"}):(a=Fd[a])&&a.postMessage({V:"checkMailbox"})};Yb.g="vpp";
var bh=[],Zb=(a,b,c,d,e,f,g)=>{bh.length=0;var k=e>>3;for(d=e+d>>3;k<d;){var l;(w(),I)[k++]?l=(w(),I)[k++]:l=(w(),Ma)[k++];bh.push(l)}a=b?Fe[b]:ch[a];$d=c;c=a(...bh);$d=0;if(f)c.then(m=>ld(f,g,m));else return c};Zb.g="dippippp";var $b=()=>{ae=!1;N=0};$b.g="v";var ac=a=>{p?postMessage({V:"cleanupThread",Ua:a}):Kd(a)};ac.g="vp";var bc=a=>{p?postMessage({V:"markAsFinished",Ua:a}):Md(a)};bc.g="vp";var cc=()=>{};cc.g="vp";var dc=(a,b)=>{a=Y(a);b=Y(b);a.set(b)};dc.g="vpp";
var dh=[],eh=a=>{var b=dh.length;dh.push(a);return b},fh=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Lg((w(),H)[b+4*d>>2],`parameter ${d}`);return c},gh=(a,b,c)=>{var d=[];a=a(d,c);d.length&&((w(),H)[b>>2]=ng(d));return a},hh={},ih=a=>{var b=hh[a];return void 0===b?V(a):b},ec=(a,b,c)=>{var [d,...e]=fh(a,b);b=d.F.bind(d);var f=e.map(l=>l.K.bind(l));a--;var g={toValue:Y};a=f.map((l,m)=>{var n=`argFromPtr${m}`;g[n]=l;return`${n}(args${m?"+"+8*m:""})`});switch(c){case 0:var k="toValue(handle)";break;
case 2:k="new (toValue(handle))";break;case 3:k="";break;case 1:g.getStringOrSymbol=ih,k="toValue(handle)[getStringOrSymbol(methodName)]"}k+=`(${a})`;d.fb||(g.toReturnWire=b,g.emval_returnValue=gh,k=`return emval_returnValue(toReturnWire, destructorsRef, ${k})`);k=`return function (handle, methodName, destructorsRef, args) {\n${k}\n}`;c=(new Function(Object.keys(g),k))(...Object.values(g));k=`methodCaller<(${e.map(l=>l.name)}) => ${d.name}>`;return eh(De(k,c))};ec.g="pipi";
var gc=a=>{if(!a)return ng(globalThis);a=ih(a);return ng(globalThis[a])};gc.g="pp";var hc=a=>{a=ih(a);return ng(h[a])};hc.g="pp";var ic=(a,b)=>{a=Y(a);b=Y(b);return ng(a[b])};ic.g="ppp";var jc=a=>{9<a&&(Hg[a+1]+=1)};jc.g="vp";var kc=(a,b)=>{a=Y(a);b=Y(b);return a instanceof b};kc.g="ipp";var lc=(a,b,c,d,e)=>dh[a](b,c,d,e);lc.g="dppppp";var mc=a=>{a=Y(a);return"number"==typeof a};mc.g="ip";var nc=a=>{a=Y(a);return"string"==typeof a};nc.g="ip";var oc=a=>ng(ih(a));oc.g="pp";
var pc=a=>{var b=Y(a);Lf(b);fc(a)};pc.g="vp";var qc=(a,b,c)=>{a=Y(a);b=Y(b);c=Y(c);a[b]=c};qc.g="vppp";var rc=a=>{a=Y(a);return ng(typeof a)};rc.g="pp";
function sc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);(w(),G)[b>>2]=a.getUTCSeconds();(w(),G)[b+4>>2]=a.getUTCMinutes();(w(),G)[b+8>>2]=a.getUTCHours();(w(),G)[b+12>>2]=a.getUTCDate();(w(),G)[b+16>>2]=a.getUTCMonth();(w(),G)[b+20>>2]=a.getUTCFullYear()-1900;(w(),G)[b+24>>2]=a.getUTCDay();a=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;(w(),G)[b+28>>2]=a}sc.g="vjp";
var jh=[0,31,60,91,121,152,182,213,244,274,305,335],kh=[0,31,59,90,120,151,181,212,243,273,304,334];
function tc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);(w(),G)[b>>2]=a.getSeconds();(w(),G)[b+4>>2]=a.getMinutes();(w(),G)[b+8>>2]=a.getHours();(w(),G)[b+12>>2]=a.getDate();(w(),G)[b+16>>2]=a.getMonth();(w(),G)[b+20>>2]=a.getFullYear()-1900;(w(),G)[b+24>>2]=a.getDay();var c=a.getFullYear();c=(0!==c%4||0===c%100&&0!==c%400?kh:jh)[a.getMonth()]+a.getDate()-1|0;(w(),G)[b+28>>2]=c;(w(),G)[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();
var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();a=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0;(w(),G)[b+32>>2]=a}tc.g="vjp";function uc(a,b,c,d,e,f,g){if(p)return O(17,1,a,b,c,d,e,f,g);e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{var k=S(d),l=FS.ja(k,a,e,b,c),m=l.A;(w(),G)[f>>2]=l.fa;(w(),H)[g>>2]=m;return 0}catch(n){if("undefined"==typeof FS||"ErrnoError"!==n.name)throw n;return-n.B}}uc.g="ipiiijpp";
function vc(a,b,c,d,e,f){if(p)return O(18,1,a,b,c,d,e,f);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=S(e);if(c&2){c=f;if(!FS.isFile(g.node.mode))throw new FS.h(43);if(!(d&2)){var k=(w(),A).slice(a,a+b);FS.la(g,k,c,b,d)}}}catch(l){if("undefined"==typeof FS||"ErrnoError"!==l.name)throw l;return-l.B}}vc.g="ippiiij";
var wc=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var g=Math.max(f,e);(w(),H)[a>>2]=60*g;(w(),G)[b>>2]=Number(f!=e);b=k=>{var l=Math.abs(k);return`UTC${0<=k?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(Te(a,c,17),Te(b,d,17)):(Te(a,d,17),Te(b,c,17))};wc.g="vpppp";var Dc=()=>performance.timeOrigin+performance.now();Dc.g="d";var zc=()=>Date.now();zc.g="d";
var lh=1;function xc(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(lh)a=performance.timeOrigin+performance.now();else return 52;a=Math.round(1E6*a);(w(),I)[c>>3]=BigInt(a);return 0}xc.g="iijp";var yc=()=>{};yc.g="v";var Ac=a=>t(P(a));Ac.g="vp";var Bc=()=>{N+=1;throw"unwind";};Bc.g="v";var Cc=()=>2147483648;Cc.g="p";var Ec=()=>navigator.hardwareConcurrency;Ec.g="i";var Fc=a=>{Yg(a)};Fc.g="vp";
var Gc=(a,b,c)=>{a=Xg.get(a);switch(b){case 0:a.resolve(c);break;case 1:a.resolve(Xg.get(c).promise);break;case 2:a.resolve(Xg.get(c).promise);Yg(c);break;case 3:a.reject(c)}};Gc.g="vpip";var Hc=a=>{var b=(w(),A).length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-qa.buffer.byteLength+65535)/65536|0;try{qa.grow(d);ra();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1};
Hc.g="ip";var mh={},oh=()=>{if(!nh){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in mh)void 0===mh[b]?delete a[b]:a[b]=mh[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);nh=c}return nh},nh;function Ic(a,b){if(p)return O(19,1,a,b);var c=0,d=0,e;for(e of oh()){var f=b+c;(w(),H)[a+d>>2]=f;c+=Te(e,f,Infinity)+1;d+=4}return 0}Ic.g="ipp";
function Jc(a,b){if(p)return O(20,1,a,b);var c=oh();(w(),H)[a>>2]=c.length;a=0;for(var d of c)a+=Re(d)+1;(w(),H)[b>>2]=a;return 0}Jc.g="ipp";function Lc(a){if(p)return O(21,1,a);try{var b=S(a);FS.close(b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.B}}Lc.g="ii";
function Mc(a,b){if(p)return O(22,1,a,b);try{var c=S(a),d=c.C?2:FS.isDir(c.mode)?3:FS.isLink(c.mode)?7:4;(w(),y)[b]=d;(w(),z)[b+2>>1]=0;(w(),I)[b+8>>3]=BigInt(0);(w(),I)[b+16>>3]=BigInt(0);return 0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return e.B}}Mc.g="iip";
function Nc(a,b,c,d){if(p)return O(23,1,a,b,c,d);try{a:{var e=S(a);a=b;for(var f,g=b=0;g<c;g++){var k=(w(),H)[a>>2],l=(w(),H)[a+4>>2];a+=8;var m=FS.read(e,(w(),y),k,l,f);if(0>m){var n=-1;break a}b+=m;if(m<l)break;"undefined"!=typeof f&&(f+=m)}n=b}(w(),H)[d>>2]=n;return 0}catch(q){if("undefined"==typeof FS||"ErrnoError"!==q.name)throw q;return q.B}}Nc.g="iippp";
function Oc(a,b,c,d){if(p)return O(24,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 22;var e=S(a);FS.llseek(e,b,c);(w(),I)[d>>3]=BigInt(e.position);e.Fa&&0===b&&0===c&&(e.Fa=null);return 0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return f.B}}Oc.g="iijip";
function Pc(a,b,c,d){if(p)return O(25,1,a,b,c,d);try{a:{var e=S(a);a=b;for(var f,g=b=0;g<c;g++){var k=(w(),H)[a>>2],l=(w(),H)[a+4>>2];a+=8;var m=FS.write(e,(w(),y),k,l,f);if(0>m){var n=-1;break a}b+=m;if(m<l)break;"undefined"!=typeof f&&(f+=m)}n=b}(w(),H)[d>>2]=n;return 0}catch(q){if("undefined"==typeof FS||"ErrnoError"!==q.name)throw q;return q.B}}Pc.g="iippp";var Sc=(a,b)=>We((w(),A).subarray(a,a+b));Sc.g="ipp";p||Wd();
(()=>{var a={kb:Promise.resolve(),canHandle:b=>!h.noWasmDecoding&&b.endsWith(".so"),handle:async(b,c)=>a.kb=a.kb.then(async()=>{try{var d=await Je(b,{I:!0,pa:!0},c,{})}catch(e){throw Error(`failed to instantiate wasm: ${c}: ${e}`);}ee[c]=d;return b})};de.push(a)})();FS.createPreloadedFile=(a,b,c,d,e,f,g,k,l,m)=>{mf(a,b,c,d,e,k,l,m).then(f).catch(g)};FS.Nc=mf;FS.da=Array(4096);FS.mount(Q,{},"/");FS.mkdir("/tmp");FS.mkdir("/home");FS.mkdir("/home/web_user");
(function(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=>0,write:(d,e,f,g)=>g,llseek:()=>0});FS.mkdev("/dev/null",FS.makedev(1,3));bf(FS.makedev(5,0),df);bf(FS.makedev(6,0),ef);FS.mkdev("/dev/tty",FS.makedev(5,0));FS.mkdev("/dev/tty1",FS.makedev(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(We(a),b=a.byteLength);return a[--b]};FS.createDevice("/dev","random",c);FS.createDevice("/dev","urandom",c);FS.mkdir("/dev/shm");FS.mkdir("/dev/shm/tmp")})();
(function(){FS.mkdir("/proc");var a=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var b=FS.createNode(a,"fd",16895,73);b.o={llseek:Q.o.llseek};b.m={ia(c,d){c=+d;var e=S(c);c={parent:null,mount:{ib:"fake"},m:{readlink:()=>e.path},id:c+1};return c.parent=c},sa(){return Array.from(FS.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();FS.Ib={MEMFS:Q};
(()=>{let a=dg.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof dg&&c instanceof dg))return!1;var d=this.l.D.s,e=this.l.A;c.l=c.l;var f=c.l.D.s;for(c=c.l.A;d.M;)e=d.ua(e),d=d.M;for(;f.M;)c=f.ua(c),f=f.M;return d===f&&e===c},clone:function(){this.l.A||Wf(this);if(this.l.qa)return this.l.count.value+=1,this;var c=$f,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.l;c=c(e.call(d,f,{l:{value:{count:g.count,ha:g.ha,qa:g.qa,A:g.A,D:g.D,J:g.J,R:g.R}}}));c.l.count.value+=1;c.l.ha=
!1;return c},["delete"](){this.l.A||Wf(this);if(this.l.ha&&!this.l.qa)throw new W("Object already scheduled for deletion");Zf(this);var c=this.l;--c.count.value;0===c.count.value&&(c.J?c.R.Y(c.J):c.D.s.Y(c.A));this.l.qa||(this.l.J=void 0,this.l.A=void 0)},isDeleted:function(){return!this.l.A},deleteLater:function(){this.l.A||Wf(this);if(this.l.ha&&!this.l.qa)throw new W("Object already scheduled for deletion");ag.push(this);1===ag.length&&cg&&cg(bg);this.l.ha=!0;return this}});const b=Symbol.dispose;
b&&(a[b]=a["delete"])})();
Object.assign(tg.prototype,{Lb(a){this.lb&&(a=this.lb(a));return a},Ya(a){this.Y?.(a)},K:Mf,v:function(a){function b(){return this.za?sg(this.s.ba,{D:this.ic,A:c,R:this,J:a}):sg(this.s.ba,{D:this,A:a})}var c=this.Lb(a);if(!c)return this.Ya(a),null;var d=rg(this.s,c);if(void 0!==d){if(0===d.l.count.value)return d.l.A=c,d.l.J=a,d.clone();d=d.clone();this.Ya(a);return d}d=this.s.Jb(c);d=eg[d];if(!d)return b.call(this);d=this.ya?d.Bb:d.pointerType;var e=pg(c,this.s,d.s);return null===e?b.call(this):this.za?
sg(d.s.ba,{D:d,A:e,R:this,J:a}):sg(d.s.ba,{D:d,A:e})}});Ld.push(()=>{mh.VIPS_DISC_THRESHOLD=2147483648;mh.VIPS_MAX_THREADS=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;mh.VIPS_CONCURRENCY=1});
Sa.push(()=>{const a=Object.getOwnPropertyDescriptor(h.SourceCustom.prototype,"onRead");Object.defineProperty(h.SourceCustom.prototype,"onRead",{set(c){return a.set.call(this,d=>ng(c(d)))}});const b=Object.getOwnPropertyDescriptor(h.TargetCustom.prototype,"onWrite");Object.defineProperty(h.TargetCustom.prototype,"onWrite",{set(c){return b.set.call(this,d=>c(Y(d)))}})});Object.assign(dg.prototype,{preventAutoDelete:function(){const a=ag.indexOf(this);-1<a&&ag.splice(a,1);this.l.ha=!1;return this}});
p||(h.wasmMemory?qa=h.wasmMemory:qa=new WebAssembly.Memory({initial:(h.INITIAL_MEMORY||268435456)/65536,maximum:32768,shared:!0}),ra());h.preloadPlugins&&(de=h.preloadPlugins);h.noExitRuntime&&(ae=h.noExitRuntime);h.print&&(ka=h.print);h.printErr&&(t=h.printErr);h.dynamicLibraries&&(la=h.dynamicLibraries);h.wasmBinary&&(ma=h.wasmBinary);h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();
h.ENV=mh;h.addRunDependency=Qd;h.removeRunDependency=Pd;h.addFunction=Ae;h.FS_preloadFile=mf;h.FS_unlink=(...a)=>FS.unlink(...a);h.FS_createPath=(...a)=>FS.createPath(...a);h.FS_createDevice=(...a)=>FS.createDevice(...a);h.FS=FS;h.FS_createDataFile=(...a)=>FS.createDataFile(...a);h.FS_createLazyFile=(...a)=>FS.createLazyFile(...a);h.setAutoDeleteLater=a=>{Xf=a};h.deletionQueue=ag;h.setDelayFunction=a=>{cg=a;ag.length&&cg&&cg(bg)};
var ch=[Rc,be,Cf,db,eb,fb,gb,hb,ib,jb,kb,lb,mb,nb,ob,pb,Vb,uc,vc,Ic,Jc,Lc,Mc,Nc,Oc,Pc],Fe={};function ph(a){for(var b=(w(),F)[a+6>>1];13===b&&!(16<(w(),H)[a>>2]);){var c=(w(),H)[a+8>>2],d=(w(),H)[c>>2];if(0===d){b=0;break}else if(0===(w(),H)[(c>>2)+1])a=d,b=(w(),F)[d+6>>1];else break}return[a,b]}
function Qc(a,b,c,d){w();var e=(w(),H)[(a>>2)+1],f=(w(),H)[(a>>2)+6],g=(w(),H)[(a>>2)+2],k=(w(),H)[(a>>2)+5];a=ph((w(),H)[(a>>2)+3])[1];var l=ud(),m=l,n=[],q=!1;if(15===a)throw Error("complex ret marshalling nyi");if(0>a||15<a)throw Error("Unexpected rtype "+a);if(4===a||13===a)n.push(c),q=!0;for(var u=0;u<f;u++){var r=(w(),H)[(d>>2)+u],v=ph((w(),H)[(g>>2)+u]),x=v[0];v=v[1];switch(v){case 1:case 10:case 9:n.push((w(),H)[r>>2]);break;case 2:n.push((w(),La)[r>>2]);break;case 3:n.push((w(),Ma)[r>>3]);
break;case 5:n.push((w(),A)[r]);break;case 6:n.push((w(),y)[r]);break;case 7:n.push((w(),F)[r>>1]);break;case 8:n.push((w(),z)[r>>1]);break;case 11:case 12:n.push((w(),Na)[r>>3]);break;case 4:n.push((w(),Na)[r>>3]);n.push((w(),Na)[(r>>3)+1]);break;case 13:v=(w(),H)[x>>2];x=(w(),F)[x+4>>1];m-=v;m&=~(x-1);(w(),y).subarray(m,m+v).set((w(),y).subarray(r,r+v));n.push(m);break;case 14:n.push((w(),H)[r>>2]);break;case 15:throw Error("complex marshalling nyi");default:throw Error("Unexpected type "+v);}}if(k&
1){k=[];for(u=e-1;u>=f;u--)switch(r=(w(),H)[(d>>2)+u],v=ph((w(),H)[(g>>2)+u]),x=v[0],v=v[1],v){case 5:case 6:--m;m&=-1;(w(),A)[m]=(w(),A)[r];break;case 7:case 8:m-=2;m&=-2;(w(),F)[m>>1]=(w(),F)[r>>1];break;case 1:case 9:case 10:case 2:m-=4;m&=-4;(w(),H)[m>>2]=(w(),H)[r>>2];break;case 3:case 11:case 12:m-=8;m&=-8;(w(),H)[m>>2]=(w(),H)[r>>2];(w(),H)[(m>>2)+1]=(w(),H)[(r>>2)+1];break;case 4:m-=16;m&=-8;(w(),H)[m>>2]=(w(),H)[r>>2];(w(),H)[(m>>2)+1]=(w(),H)[(r>>2)+1];(w(),H)[(m>>2)+2]=(w(),H)[(r>>2)+2];
(w(),H)[(m>>2)+3]=(w(),H)[(r>>2)+3];break;case 13:m-=4;m&=-4;k.push([m,r,(w(),H)[x>>2],(w(),F)[x+4>>1]]);break;case 14:m-=4;m&=-4;(w(),H)[m>>2]=(w(),H)[r>>2];break;case 15:throw Error("complex arg marshalling nyi");default:throw Error("Unexpected argtype "+v);}n.push(m);for(u=0;u<k.length;u++)e=k[u],d=e[0],r=e[1],v=e[2],x=e[3],m-=v,m&=~(x-1),(w(),y).subarray(m,m+v).set((w(),y).subarray(r,r+v)),(w(),H)[d>>2]=m}sd(m);td(0);b=M.get(b).apply(null,n);sd(l);if(!q)switch(a){case 0:break;case 1:case 9:case 10:(w(),
H)[c>>2]=b;break;case 2:(w(),La)[c>>2]=b;break;case 3:(w(),Ma)[c>>3]=b;break;case 5:case 6:(w(),A)[c+0]=b;break;case 7:case 8:(w(),F)[c>>1]=b;break;case 11:case 12:(w(),Na)[c>>3]=b;break;case 14:(w(),H)[c>>2]=b;break;case 15:throw Error("complex ret marshalling nyi");default:throw Error("Unexpected rtype "+a);}}Qc.g="viiii";var Xc,Yc,L,Zc,$c,ad,Ea,bd,cd,dd,ed,fd,gd,hd,jd,Ba,kd,Ha,ld,md,nd,od,pd,qd,Ta,rd,sd,td,ud,vd,wd,xd,yd,M,K;
function qh(a=[]){var b=Ee("main").Ta;if(b){a.unshift(da);var c=a.length,d=td(4*(c+1)),e=d,f;for(f of a)(w(),H)[e>>2]=Ue(f),e+=4;(w(),H)[e>>2]=0;try{var g=b(c,d);Kc(g,!0)}catch(k){Dd(k)}}}
function za(a=ca){function b(){h.calledRun=!0;if(!oa&&(Pa(),sa?.(h),h.onRuntimeInitialized?.(),h.noInitialRun||qh(a),!p)){if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();le.push(c)}Qa(le)}}if(0<Nd)Od=za;else if(p)sa?.(h),Pa();else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ld.push(h.preRun.shift());Qa(Ld);0<Nd?Od=za:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),
1);b()},1)):b()}}var Ra;p||(Ra=await (ya()),za());Ja?moduleRtn=h:moduleRtn=new Promise((a,b)=>{sa=a;ta=b});
;return moduleRtn}export default Vips;var isPthread=globalThis.name=="em-pthread";isPthread&&Vips();
