var Vips=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var h=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,p=ba&&"em-pthread"==globalThis.name;h.dynamicLibraries=h.dynamicLibraries||["vips-jxl.wasm","vips-heif.wasm"];h.workaroundCors&&(h.mainScriptUrlOrBlob=h.mainScriptUrlOrBlob||URL.createObjectURL(new Blob([`importScripts('${_scriptName}');`],{type:"application/javascript"})));var ca=[],da="./this.program";ba&&(_scriptName=self.location.href);var ea="";function fa(a){return h.locateFile?h.locateFile(a,ea):ea+a}var ha,ia;
if(aa||ba){try{ea=(new URL(".",_scriptName)).href}catch{}ba&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ha=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var ja=console.log.bind(console),t=console.error.bind(console),ka=[],la,ma,na=!1,oa;function w(){pa.buffer!=y.buffer&&qa()}var ra,sa,ta={},ua;
if(p){var va=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.V;if("load"===d){let e=[];self.onmessage=f=>e.push(f);ua=()=>{postMessage({V:"loaded"});for(let f of e)a(f);self.onmessage=a};ka=c.Eb;ta=c.oc;for(const f of c.Rb)if(!h[f]||h[f].proxy)h[f]=(...g)=>{postMessage({V:"callHandler",Qb:f,yb:g})},"print"==f&&(ja=h[f]),"printErr"==f&&(t=h[f]);pa=c.uc;qa();ma=c.vc;xa();ya()}else if("run"===d){za(c.X);Aa(c.X,0,0,1,0,0);Ba();Ca(c.X);va||(Da(),va=!0);try{Ea(c.rc,
c.Da)}catch(e){if("unwind"!=e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?va&&Fa():d&&(t(`worker: received unknown command ${d}`),t(c)))}catch(e){throw Ga(),e;}}self.onmessage=a}var Ha=!1,Ia=!1;function qa(){var a=pa.buffer;y=new Int8Array(a);z=new Int16Array(a);A=new Uint8Array(a);F=new Uint16Array(a);G=new Int32Array(a);H=new Uint32Array(a);Ka=new Float32Array(a);La=new Float64Array(a);I=new BigInt64Array(a);Ma=new BigUint64Array(a)}var Na=[];
function Oa(){Ha=!0;p?ua():(Pa(Na),h.noFSInit||FS.Ha||FS.init(),Qa.__wasm_call_ctors(),Pa(Ra),FS.eb=!1)}function J(a){h.onAbort?.(a);a=`Aborted(${a})`;t(a);na=!0;a+=". Build with -sASSERTIONS for more info.";Ha&&Sa();a=new WebAssembly.RuntimeError(a);sa?.(a);throw a;}var Ta;async function Ua(a){if(!la)try{var b=await ha(a);return new Uint8Array(b)}catch{}if(a==Ta&&la)a=new Uint8Array(la);else if(ia)a=ia(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Va(a,b){try{var c=await Ua(a);return await WebAssembly.instantiate(c,b)}catch(d){t(`failed to asynchronously prepare wasm: ${d}`),J(d)}}async function Wa(a){var b=Ta;if(!la)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){t(`wasm streaming compile failed: ${d}`),t("falling back to ArrayBuffer instantiation")}return Va(b,a)}
function Xa(){K={__assert_fail:Ya,__call_sighandler:Za,__lsan_ignore_object:ab,__pthread_create_js:bb,__syscall_dup:cb,__syscall_faccessat:db,__syscall_fcntl64:eb,__syscall_fstat64:fb,__syscall_ftruncate64:gb,__syscall_getcwd:hb,__syscall_ioctl:ib,__syscall_lstat64:jb,__syscall_newfstatat:kb,__syscall_openat:lb,__syscall_rmdir:mb,__syscall_stat64:nb,__syscall_unlinkat:ob,__throw_exception_with_stack_trace:pb,_abort_js:qb,_dlopen_js:rb,_dlsym_catchup_js:sb,_dlsym_js:tb,_embind_finalize_value_object:ub,
_embind_register_arithmetic_vector:vb,_embind_register_bigint:wb,_embind_register_bool:xb,_embind_register_class:Ab,_embind_register_class_class_function:Bb,_embind_register_class_constructor:Cb,_embind_register_class_function:Db,_embind_register_class_property:Eb,_embind_register_emval:Fb,_embind_register_enum:Gb,_embind_register_enum_value:Hb,_embind_register_float:Ib,_embind_register_function:Jb,_embind_register_integer:Kb,_embind_register_iterable:Lb,_embind_register_memory_view:Mb,_embind_register_optional:Nb,
_embind_register_std_string:Ob,_embind_register_std_wstring:Pb,_embind_register_value_object:Qb,_embind_register_value_object_field:Rb,_embind_register_void:Sb,_emscripten_dlopen_js:Tb,_emscripten_dlsync_threads:Ub,_emscripten_get_dynamic_libraries_js:Vb,_emscripten_init_main_thread_js:Wb,_emscripten_notify_mailbox_postmessage:Xb,_emscripten_receive_on_main_thread_js:Yb,_emscripten_runtime_keepalive_clear:Zb,_emscripten_thread_cleanup:$b,_emscripten_thread_exit_joinable:ac,_emscripten_thread_mailbox_await:Ca,
_emscripten_thread_set_strongref:bc,_emval_array_to_memory_view:cc,_emval_create_invoker:dc,_emval_decref:ec,_emval_get_global:fc,_emval_get_module_property:gc,_emval_get_property:hc,_emval_incref:ic,_emval_instanceof:jc,_emval_invoke:kc,_emval_is_number:lc,_emval_is_string:mc,_emval_new_cstring:nc,_emval_run_destructors:oc,_emval_set_property:pc,_emval_typeof:qc,_gmtime_js:rc,_localtime_js:sc,_mmap_js:tc,_munmap_js:uc,_tzset_js:vc,clock_time_get:wc,emscripten_check_blocking_allowed:xc,emscripten_date_now:yc,
emscripten_err:zc,emscripten_exit_with_live_runtime:Ac,emscripten_get_heap_max:Bc,emscripten_get_now:Cc,emscripten_num_logical_cores:Dc,emscripten_promise_destroy:Ec,emscripten_promise_resolve:Fc,emscripten_resize_heap:Gc,environ_get:Hc,environ_sizes_get:Ic,exit:Jc,fd_close:Kc,fd_fdstat_get:Lc,fd_read:Mc,fd_seek:Nc,fd_write:Oc,ffi_call_js:Pc,memory:pa,proc_exit:Qc,random_get:Rc};var a=new Proxy(new Set(["__lsan_ignore_object"]),Sc);return{env:K,wasi_snapshot_preview1:K,"GOT.mem":a,"GOT.func":a}}
async function xa(){function a(d,e){var f=Qa=d.exports;Tc(Qa);var g=Uc(e);Vc(Qa._emscripten_tls_init,d.exports,g);d=Qa;Wc=d.pthread_self;Xc=d.malloc;h._main=d.main;L=d.free;Yc=d.fflush;Zc=d.calloc;h.__ZnamSt11align_val_t=d._ZnamSt11align_val_t;$c=d.__getTypeName;Da=d._embind_initialize_bindings;h._emscripten_builtin_free=d.emscripten_builtin_free;ad=d.emscripten_builtin_memalign;h._emscripten_builtin_malloc=d.emscripten_builtin_malloc;bd=d.__funcs_on_exit;h.___libc_calloc=d.__libc_calloc;h.___libc_free=
d.__libc_free;h.___libc_malloc=d.__libc_malloc;cd=d.__dl_seterr;dd=d._emscripten_dlsync_self_async;ed=d._emscripten_dlsync_self;fd=d._emscripten_proxy_dlsync_async;gd=d._emscripten_proxy_dlsync;hd=d._emscripten_find_dylib;Aa=d._emscripten_thread_init;jd=d.__set_thread_state;Ga=d._emscripten_thread_crashed;kd=d._emscripten_run_js_on_main_thread_done;ld=d._emscripten_run_js_on_main_thread;md=d._emscripten_thread_free_data;nd=d._emscripten_thread_exit;h._strndup=d.strndup;od=d._emscripten_check_mailbox;
h.__ZdaPvm=d._ZdaPvm;h.___libc_realloc=d.__libc_realloc;h._emscripten_builtin_calloc=d.emscripten_builtin_calloc;h._emscripten_builtin_realloc=d.emscripten_builtin_realloc;h._malloc_size=d.malloc_size;h._malloc_usable_size=d.malloc_usable_size;h._reallocf=d.reallocf;pd=d.emscripten_get_sbrk_ptr;Sa=d.__trap;qd=d.emscripten_stack_set_limits;rd=d._emscripten_stack_restore;sd=d._emscripten_stack_alloc;td=d.emscripten_stack_get_current;ud=d.__thrown_object_from_unwind_exception;vd=d.__get_exception_message;
M=d.__indirect_function_table;wd=d.__heap_base.value;xd=d.__cpp_exception;yd(f);zd("__main__",0,K);Ad();ma=e;return Qa}var b=Xa();if(h.instantiateWasm)return new Promise(d=>{h.instantiateWasm(b,(e,f)=>{d(a(e,f))})});if(p){var c=new WebAssembly.Instance(ma,Xa());return a(c,ma)}Ta??=fa("vips.wasm");return function(d){return a(d.instance,d.module)}(await Wa(b))}var Cd=a=>{if(!(a instanceof Bd||"unwind"==a))throw a;};
class Bd{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var N=0,Dd=a=>{a.terminate();a.onmessage=()=>{}},Jd=a=>{var b=Ed[a];Fd.delete(a);a in Gd&&Gd[a].resolve();a=b.X;delete Ed[a];Hd.push(b);Id.splice(Id.indexOf(b),1);b.X=0;md(a)},Pa=a=>{for(;0<a.length;)a.shift()(h)},Kd=[],Ld=a=>{Fd.add(a);a in Gd&&Gd[a].resolve()},Md=0,Nd=null,Od=()=>{Md--;h.monitorRunDependencies?.(Md);if(0==Md&&Nd){var a=Nd;Nd=null;a()}},Pd=()=>{Md++;h.monitorRunDependencies?.(Md)},Sd=a=>{0==Hd.length&&(Qd(),Rd(Hd[0]));var b=Hd.pop();if(!b)return 6;Id.push(b);Ed[a.X]=b;b.X=a.X;b.postMessage({V:"run",
rc:a.qc,Da:a.Da,X:a.X},a.rb);return 0},Td=!Atomics.waitAsync||globalThis.navigator?.userAgent&&91>Number((navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./)||[])[2]),Hd=[],Id=[],Ud=[],Ed={};function Vd(){for(var a=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;a--;)Qd();Kd.push(async()=>{var b=Wd();Pd("loading-workers");await b;Od("loading-workers")});Gd={};Fd=new Set}var Xd=()=>{for(var a of Id)Dd(a);for(a of Hd)Dd(a);Hd=[];Id=[];Ed={}};function Ba(){Ud.forEach(a=>a())}
var Rd=a=>new Promise(b=>{a.onmessage=f=>{var g=f.data;f=g.V;if(g.Ca&&g.Ca!=Wc()){var k=Ed[g.Ca];k?k.postMessage(g,g.rb):t(`worker sent message (${f}) to pthread (${g.Ca}) that no longer exists`)}else if("checkMailbox"===f)Fa();else if("spawnThread"===f)Sd(g);else if("cleanupThread"===f)Yd(()=>Jd(g.Ua));else if("markAsFinished"===f)Ld(g.Ua);else if("loaded"===f)a.loaded=!0,b(a);else if("setimmediate"===g.target)a.postMessage(g);else if("callHandler"===f)h[g.Qb](...g.yb);else f&&t(`worker sent an unknown command ${f}`)};
a.onerror=f=>{t(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)h.propertyIsEnumerable(e)&&c.push(e);a.postMessage({V:"load",Rb:c,uc:pa,vc:ma,Eb:ka,oc:ta})});async function Wd(){if(!p)return Promise.all(Hd.map(Rd))}function Qd(){var a=_scriptName;h.mainScriptUrlOrBlob&&(a=h.mainScriptUrlOrBlob,"string"!=typeof a&&(a=URL.createObjectURL(a)));a=new Worker(a,{name:"em-pthread"});Hd.push(a)}
var Fd,Gd,Zd,O=(a,b,...c)=>{var d=16*c.length,e=td(),f=sd(d),g=f>>3,k;for(k of c)"bigint"==typeof k?((w(),I)[g++]=1n,(w(),I)[g++]=k):((w(),I)[g++]=0n,(w(),La)[g++]=k);a=ld(a,0,d,f,b);rd(e);return a};function Qc(a){if(p)return O(0,1,a);oa=a;$d||0<N||(Xd(),h.onExit?.(a),na=!0);throw new Bd(a);}Qc.g="vi";function ae(a){if(p)return O(1,0,a);Jc(a)}
var Jc=a=>{oa=a;if(p)throw ae(a),"unwind";if(!($d||0<N||p)){bd();FS.Ha=!1;Yc(0);for(var b of FS.streams)b&&FS.close(b);Xd();b=Wc();jd(0,0,0,1);Td||Atomics.notify((w(),G),b>>2);Ia=!0}Qc(a)};Jc.g="vi";var Yd=a=>{if(!Ia&&!na)try{a()}catch(b){Cd(b)}finally{if(!(Ia||$d||0<N))try{p?Wc()&&nd(oa):Jc(oa)}catch(b){Cd(b)}}},be=a=>{N+=1;setTimeout(()=>{--N;Yd(a)},1E4)},ce=[],de={},ee=!1;
function fe(){function a(){ee=document.pointerLockElement===h.canvas}if(!ge){ge=!0;ce.push({canHandle:c=>!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c),handle:async(c,d)=>{var e=new Blob([c],{type:he(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:he(d)}));var f=URL.createObjectURL(e);return new Promise((g,k)=>{var l=new Image;l.onload=()=>{var m=document.createElement("canvas");m.width=l.width;m.height=l.height;m.getContext("2d").drawImage(l,0,0);URL.revokeObjectURL(f);
g(c)};l.onerror=()=>{t(`Image ${f} could not be decoded`);k()};l.src=f})}});ce.push({canHandle:c=>!h.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(c,d)=>new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,k=URL.createObjectURL(new Blob([c],{type:he(d)})),l=new Audio;l.addEventListener("canplaythrough",()=>f(l),!1);l.onerror=()=>{if(!g){t(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);for(var m="",n=0,q=0,u=0;u<c.length;u++)for(n=n<<
8|c[u],q+=8;6<=q;){var r=n>>q-6&63;q-=6;m+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[r]}2==q?(m+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(n&3)<<4],m+="=="):4==q&&(m+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(n&15)<<2],m+="=");l.src="data:audio/x-"+d.slice(-3)+";base64,"+m;f(l)}};l.src=k;be(()=>{f(l)})})});var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!ee&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}function he(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}var ie={},ge,je={},Sc={get(a,b){var c=je[b];c||=je[b]=new WebAssembly.Global({value:"i32",mutable:!0},-1);a.has(b)||(c.required=!0);return c}},z,G,I,y,Ka,La,F,H,Ma,A,ke=[];
function za(a){var b=(w(),H)[a+48>>2];a=(w(),H)[a+52>>2];qd(b,b-a);rd(b)}
var le=new TextDecoder,me=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},ne=(a,b=0,c)=>{c=me(a,b,c);return le.decode(a.buffer?a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c):new Uint8Array(a.slice(b,c)))},Uc=a=>{function b(){for(var q=0,u=1;;){var r=a[f++];q+=(r&127)*u;u*=128;if(!(r&128))break}return q}function c(){var q=b();f+=q;return ne(a,f-q,q)}function d(){for(var q=b(),u=[];q--;)u.push(c());return u}function e(q,u){if(q)throw Error(u);}var f=0,g=0;if(a instanceof
WebAssembly.Module)g=WebAssembly.Module.customSections(a,"dylink.0"),e(0===g.length,"need dylink section"),a=new Uint8Array(g[0]),g=a.length;else{g=1836278016==(new Uint32Array((new Uint8Array(a.subarray(0,24))).buffer))[0];e(!g,"need to see wasm magic number");e(0!==a[8],"need the dylink section to be first");f=9;g=b();g=f+g;var k=c();e("dylink.0"!==k)}for(k={Na:[],qb:new Set,tb:new Set,nb:[]};f<g;){var l=a[f++],m=b();if(1===l)k.Ma=b(),k.Zb=b(),k.ta=b(),k.Pc=b();else if(2===l)k.Na=d();else if(3===
l)for(l=b();l--;){m=c();var n=b();n&256&&k.qb.add(m)}else if(4===l)for(l=b();l--;)c(),m=c(),n=b(),1==(n&3)&&k.tb.add(m);else 5===l?k.nb=d():f+=m}return k},Ea=(a,b)=>{$d=N=0;ed();a=M.get(a)(b);$d||0<N?oa=a:nd(a)},zd=(a,b,c)=>{c={Aa:Infinity,name:a,exports:c,global:!0};oe[a]=c;void 0!=b&&(pe[b]=c);return c},oe={},pe={},qe=(a,b)=>Math.ceil(a/b)*b,re=a=>{if(Ha)return Zc(a,1);var b=wd;wd=a=b+16*Math.ceil(a/16);if(!p){var c=pd();(w(),H)[c>>2]=a}return b},te=(a,b)=>{if(se)for(var c=a;c<a+b;c++){var d=M.get(c);
d&&se.set(d,c)}},se,ue=a=>{se||(se=new WeakMap,te(0,M.length));return se.get(a)||0},ve=[],we=a=>{const b=a.length;return[b%128|128,b>>7,...a]},xe={i:127,p:127,j:126,f:125,d:124,e:111},ye=a=>we(Array.from(a,b=>xe[b])),ze=(a,b)=>{var c=ue(a);if(c)return c;c=ve.length?ve.pop():M.grow(1);try{M.set(c,a)}catch(d){if(!(d instanceof TypeError))throw d;b=Uint8Array.of(0,97,115,109,1,0,0,0,1,...we([1,96,...ye(b.slice(1)),...ye("v"===b[0]?"":b[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(b);
b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f;M.set(c,b)}se.set(a,c);return c},yd=(a,b)=>{for(var c in a){var d=c;if(!"memory __memory_base __table_base __stack_pointer __indirect_function_table __cpp_exception __c_longjmp __wasm_apply_data_relocs __dso_handle __tls_size __tls_align __set_stack_limits _emscripten_tls_init __wasm_init_tls __wasm_call_ctors __start_em_asm __stop_em_asm __start_em_js __stop_em_js".split(" ").includes(d)&&!d.startsWith("__em_js__")){d=a[c];var e=je[c]&&-1!=je[c].value;
if(b||!e){if("function"==typeof d)d=ze(d);else if("number"!=typeof d.value)continue;let f;je[f=c]??(je[f]=new WebAssembly.Global({value:"i32",mutable:!0}));je[c].value=d}}}},Ae=(a,b=0)=>{var c={},d;for(d in a){var e=d;var f=a[d];a:{if(f instanceof WebAssembly.Global)try{f.value=f.value}catch{var g=!0;break a}g=!1}f=g?new WebAssembly.Global({value:"i32"},f.value+b):f;c[e]=f}return c},Be=a=>{a=K[a];return!a||a.Sa?!1:!0},Ce=(a,b)=>Object.defineProperty(b,"name",{value:a}),De=a=>{var b;Be(a)&&(b=K[a]);
return{Ta:b,name:a}},Ra=[],P=(a,b,c)=>{if(!a)return"";b=me((w(),A),a,b,c);return le.decode((w(),A).slice(a,b))},Ie=(a,b,c,d,e)=>{function f(){function l(D,B){function E(wa,Z){wa=[];for(var yb=0;;yb++){var $a="$"+yb;if(!Z.includes($a))break;wa.push($a)}wa=wa.join(",");Ee[C]=eval(`(${wa}) => { ${Z} };`)}function R(wa,Z,yb){var $a=[];Z=Z.slice(1,-1);if("void"!=Z){Z=Z.split(",");for(var xg of Z)Z=xg.split(" ").pop(),$a.push(Z.replaceAll("*",""))}r[wa]=eval(`(${$a}) => ${yb};`)}!p&&c&&(ta[c]=D);te(u,g.ta);
r=Ae(B.exports,q);yd(r);b.xb||Fe();if("__start_em_asm"in r){var C=r.__start_em_asm.value;for(D=r.__stop_em_asm.value;C<D;){var Ja=P(C);E(C,Ja);C=(w(),A).indexOf(0,C)+1}}for(var zb in r)if(zb.startsWith("__em_js__")){C=r[zb].value;Ja=P(C);var [yg,zg]=Ja.split("<::>");R(zb.replace("__em_js__",""),yg,zg);delete r[zb]}Vc(r._emscripten_tls_init,B.exports,g);m&&((B=r.__wasm_apply_data_relocs)&&(Ha?B():Na.push(B)),(B=r.__wasm_call_ctors)&&(Ha?B():Ra.push(B)));return r}var m=!e||!(w(),y)[e+8];if(m){var n=
Math.pow(2,g.Zb),q=g.Ma?qe(re(g.Ma+n),n):0,u=g.ta?M.length:0;e&&((w(),y)[e+8]=1,(w(),H)[e+12>>2]=q,(w(),G)[e+16>>2]=g.Ma,(w(),H)[e+20>>2]=u,(w(),G)[e+24>>2]=g.ta)}else q=(w(),H)[e+12>>2],u=(w(),H)[e+20>>2];g.ta&&M.grow(g.ta);var r;n=new Proxy({},{get(D,B){switch(B){case "__memory_base":return q;case "__table_base":return u}if(B in K&&!K[B].Sa)return K[B];if(!(B in D)){var E;D[B]=(...R)=>{if(!E){var C=De(B).Ta;!C&&d&&(C=d[B]);C||=r[B];E=C}return E(...R)}}return D[B]}});var v=new Proxy(g.tb,Sc),x={"GOT.mem":v,
"GOT.func":v,env:n,wasi_snapshot_preview1:n};if(b.I)return(async()=>{var D;a instanceof WebAssembly.Module?D=new WebAssembly.Instance(a,x):{module:a,instance:D}=await WebAssembly.instantiate(a,x);return l(a,D)})();n=a instanceof WebAssembly.Module?a:new WebAssembly.Module(a);v=new WebAssembly.Instance(n,x);return l(n,v)}var g=Uc(a);b={...b,Ra:{dc:c,hc:g.nb}};if(b.I)return g.Na.reduce((l,m)=>l.then(()=>{m=Ge(m,b.Ra)??m;return He(m,b,d)}),Promise.resolve()).then(f);for(var k of g.Na)k=Ge(k,b.Ra)??k,
He(k,b,d);return f()},Tc=a=>{var b,c;for([b,c]of Object.entries(a))Be(b)||(K[b]=c)},Je=async a=>{a=await ha(a);return new Uint8Array(a)},Ke=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Le=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ke(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Me=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Ne=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Oe=(a,b)=>Le(a+"/"+b),Pe=a=>{var b=td();a=a();rd(b);return a},Qe=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Re=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=
g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Se=(a,b,c)=>Re(a,(w(),A),b,c),Te=a=>{var b=Qe(a)+1,c=sd(b);Se(a,c,b);return c},Ue=()=>a=>(a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),0),Ve=a=>(Ve=Ue())(a),We=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:FS.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");
if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ke(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Xe=(a,b)=>{function c(g){for(var k=0;k<g.length&&""===g[k];k++);for(var l=g.length-1;0<=l&&""===g[l];l--);return k>l?[]:g.slice(k,l-k+1)}a=We(a).slice(1);b=We(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Ye=[],Ze=a=>{var b=
Array(Qe(a)+1);a=Re(a,b,0,b.length);b.length=a;return b},$e=[];function af(a,b){$e[a]={input:[],output:[],ea:b};FS.registerDevice(a,bf)}
var bf={open(a){var b=$e[a.node.ra];if(!b)throw new FS.h(43);a.C=b;a.seekable=!1},close(a){a.C.ea.xa(a.C)},xa(a){a.C.ea.xa(a.C)},read(a,b,c,d){if(!a.C||!a.C.ea.cb)throw new FS.h(60);for(var e=0,f=0;f<d;f++){try{var g=a.C.ea.cb(a.C)}catch(k){throw new FS.h(29);}if(void 0===g&&0===e)throw new FS.h(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.$=Date.now());return e},write(a,b,c,d){if(!a.C||!a.C.ea.Pa)throw new FS.h(60);try{for(var e=0;e<d;e++)a.C.ea.Pa(a.C,b[c+e])}catch(f){throw new FS.h(29);
}d&&(a.node.O=a.node.N=Date.now());return e}},cf={cb(){a:{if(!Ye.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ye=Ze(a)}a=Ye.shift()}return a},Pa(a,b){null===b||10===b?(ja(ne(a.output)),a.output=[]):0!=b&&a.output.push(b)},xa(a){0<a.output?.length&&(ja(ne(a.output)),a.output=[])},Ub(){return{Bc:25856,Dc:5,Ac:191,Cc:35387,zc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Vb(){return 0},Wb(){return[24,
80]}},df={Pa(a,b){null===b||10===b?(t(ne(a.output)),a.output=[]):0!=b&&a.output.push(b)},xa(a){0<a.output?.length&&(t(ne(a.output)),a.output=[])}},ef=a=>{a=65536*Math.ceil(a/65536);var b=ad(65536,a);b&&(w(),A).fill(0,b,b+a);return b},Q={W:null,mount(){return Q.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=FS.isBlkdev(c))||(e=4096===(c&61440));if(e)throw new FS.h(63);Q.W||(Q.W={dir:{node:{S:Q.m.S,U:Q.m.U,ia:Q.m.ia,ca:Q.m.ca,rename:Q.m.rename,unlink:Q.m.unlink,rmdir:Q.m.rmdir,sa:Q.m.sa,
symlink:Q.m.symlink},stream:{llseek:Q.o.llseek}},file:{node:{S:Q.m.S,U:Q.m.U},stream:{llseek:Q.o.llseek,read:Q.o.read,write:Q.o.write,ja:Q.o.ja,la:Q.o.la}},link:{node:{S:Q.m.S,U:Q.m.U,readlink:Q.m.readlink},stream:{}},Wa:{node:{S:Q.m.S,U:Q.m.U},stream:FS.Ab}});c=FS.createNode(a,b,c,d);FS.isDir(c.mode)?(c.m=Q.W.dir.node,c.o=Q.W.dir.stream,c.u={}):FS.isFile(c.mode)?(c.m=Q.W.file.node,c.o=Q.W.file.stream,c.L=0,c.u=Q.Fb??(Q.Fb=new Uint8Array(0))):FS.isLink(c.mode)?(c.m=Q.W.link.node,c.o=Q.W.link.stream):
FS.isChrdev(c.mode)&&(c.m=Q.W.Wa.node,c.o=Q.W.Wa.stream);c.$=c.O=c.N=Date.now();a&&(a.u[b]=c,a.$=a.O=a.N=c.$);return c},m:{S(a){var b={};b.Cb=FS.isChrdev(a.mode)?a.id:1;b.Tb=a.id;b.mode=a.mode;b.$b=1;b.uid=0;b.Pb=0;b.ra=a.ra;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.L:FS.isLink(a.mode)?b.size=a.link.length:b.size=0;b.$=new Date(a.$);b.O=new Date(a.O);b.N=new Date(a.N);b.zb=4096;b.Va=Math.ceil(b.size/b.zb);return b},U(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=
b[c]);void 0!==b.size&&(b=b.size,a.L!=b&&(c=a.u,a.u=new Uint8Array(b),a.u.set(c.subarray(0,Math.min(b,a.L))),a.L=b))},ia(){Q.Ea||(Q.Ea=new FS.h(44),Q.Ea.stack="<generic error, no stack>");throw Q.Ea;},ca(a,b,c,d){return Q.createNode(a,b,c,d)},rename(a,b,c){try{var d=ff(b,c)}catch(f){}if(d){if(FS.isDir(a.mode))for(var e in d.u)throw new FS.h(55);gf(d)}delete a.parent.u[a.name];b.u[c]=a;a.name=c;b.N=b.O=a.parent.N=a.parent.O=Date.now()},unlink(a,b){delete a.u[b];a.N=a.O=Date.now()},rmdir(a,b){var c=
ff(a,b),d;for(d in c.u)throw new FS.h(55);delete a.u[b];a.N=a.O=Date.now()},sa(a){return[".","..",...Object.keys(a.u)]},symlink(a,b,c){a=Q.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(!FS.isLink(a.mode))throw new FS.h(28);return a.link}},o:{read(a,b,c,d,e){if(e>=a.node.L)return 0;d=Math.min(a.node.L-e,d);b.set(a.node.u.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===(w(),y).buffer&&(f=!1);if(!d)return 0;a=a.node;a.O=a.N=Date.now();if(f)a.u=b.subarray(c,c+d),a.L=d;else if(0===
a.L&&0===e)a.u=b.slice(c,c+d),a.L=d;else{f=e+d;var g=a.u.length;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.u.subarray(0,a.L),a.u=new Uint8Array(f),a.u.set(g));a.u.set(b.subarray(c,c+d),e);a.L=Math.max(a.L,e+d)}return d},llseek(a,b,c){1===c?b+=a.position:2===c&&FS.isFile(a.node.mode)&&(b+=a.node.L);if(0>b)throw new FS.h(28);return b},ja(a,b,c,d,e){if(!FS.isFile(a.node.mode))throw new FS.h(43);a=a.node.u;if(e&2||a.buffer!==(w(),y).buffer){d=!0;e=ef(b);if(!e)throw new FS.h(48);
if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);(w(),y).set(a,e)}}else d=!1,e=a.byteOffset;return{A:e,fa:d}},la(a,b,c,d){Q.o.write(a,b,0,d,c,!1);return 0}}},hf=a=>{"string"==typeof a&&(a=Ze(a));a.subarray||(a=new Uint8Array(a));return a},jf=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},kf=async(a,b)=>{"undefined"!=typeof ie&&fe();for(var c of ce)if(c.canHandle(b))return c.handle(a,b);return a},lf=async(a,b,c,d,e,f,g,k)=>{var l=b?We(Le(a+"/"+b)):
a,m=`cp ${l}`;Pd(m);try{var n=c;"string"==typeof c&&(n=await Je(c));n=await kf(n,l);k?.();f||FS.createDataFile(a,b,n,d,e,g)}finally{Od(m)}};function ff(a,b){var c=FS.isDir(a.mode)?(c=mf(a,"x"))?c:a.m.ia?0:2:54;if(c)throw new FS.h(c);for(c=FS.da[nf(a.id,b)];c;c=c.ka){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return FS.ia(a,b)}function gf(a){var b=nf(a.parent.id,a.name);if(FS.da[b]===a)FS.da[b]=a.ka;else for(b=FS.da[b];b;){if(b.ka===a){b.ka=a.ka;break}b=b.ka}}
function nf(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%FS.da.length}function of(a){var b=nf(a.parent.id,a.name);a.ka=FS.da[b];FS.da[b]=a}function mf(a,b){return FS.eb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function pf(a,b){if(!FS.isDir(a.mode))return 54;try{return ff(a,b),20}catch(c){}return mf(a,"wx")}
function qf(a,b,c){try{var d=ff(a,b)}catch(e){return e.B}if(a=mf(a,"wx"))return a;if(c){if(!FS.isDir(d.mode))return 54;if(FS.na(d)||FS.getPath(d)===FS.cwd())return 10}else if(FS.isDir(d.mode))return 31;return 0}function rf(a,b){if(!a)throw new FS.h(b);return a}function S(a){a=FS.Mb(a);if(!a)throw new FS.h(8);return a}function sf(a,b=-1){a=Object.assign(new FS.vb,a);if(-1==b)a:{for(b=0;b<=FS.wb;b++)if(!FS.streams[b])break a;throw new FS.h(33);}a.aa=b;return FS.streams[b]=a}
function tf(a,b=-1){a=sf(a,b);a.o?.Fc?.(a);return a}function uf(a,b,c){var d=a?.o.U;a=d?a:b;d??=b.m.U;rf(d,63);try{d(a,c)}catch(e){if(e instanceof RangeError)throw new FS.h(22);throw e;}}function vf(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.oa)}return b}function wf(a){var b={yc:4096,Ic:4096,Va:1E6,xc:5E5,wc:5E5,files:FS.Oa,Gc:FS.Oa-1,Jc:42,flags:2,Mc:255};a.m.pb&&Object.assign(b,a.m.pb(a.mount.bc.root));return b}
function xf(a,b,c,d){uf(a,b,{mode:c&4095|b.mode&-4096,N:Date.now(),$a:d})}function yf(a,b,c){if(FS.isDir(b.mode))throw new FS.h(31);if(!FS.isFile(b.mode))throw new FS.h(28);var d=mf(b,"w");if(d)throw new FS.h(d);uf(a,b,{size:c,timestamp:Date.now()})}function zf(a,b,c,d){a="string"==typeof a?a:FS.getPath(a);b=Le(a+"/"+b);return FS.create(b,jf(c,d))}
function Af(a){if(!(a.Xb||a.Yb||a.link||a.u))if(globalThis.XMLHttpRequest)J("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.u=ia(a.url)}catch(b){throw new FS.h(29);}}
var FS={root:null,oa:[],Za:{},streams:[],Oa:1,da:null,Xa:"/",Ha:!1,eb:!0,Ib:null,Ba:0,h:class{name="ErrnoError";constructor(a){this.B=a}},vb:class{P={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.P.flags}set flags(a){this.P.flags=a}get position(){return this.P.position}set position(a){this.P.position=a}},ub:class{m={};o={};T=null;constructor(a,b,c,d){a||=this;this.parent=a;this.mount=a.mount;this.id=FS.Oa++;this.name=b;this.mode=c;this.ra=d;this.$=this.O=
this.N=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Yb(){return FS.isDir(this.mode)}get Xb(){return FS.isChrdev(this.mode)}},lookupPath(a,b={}){if(!a)throw new FS.h(44);b.wa??(b.wa=!0);"/"===a.charAt(0)||(a=FS.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=FS.root,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;
if("."!==a[f])if(".."===a[f])if(e=Me(e),FS.na(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Le(e+"/"+a[f]);try{d=ff(d,a[f])}catch(k){if(44===k?.B&&g&&b.ac)return{path:e};throw k;}!d.T||g&&!b.wa||(d=d.T.root);if(FS.isLink(d.mode)&&(!g||b.follow)){if(!d.m.readlink)throw new FS.h(52);d=d.m.readlink(d);"/"===d.charAt(0)||(d=Me(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new FS.h(32);},getPath(a){for(var b;;){if(FS.na(a))return a=a.mount.ib,
b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},createNode(a,b,c,d){a=new FS.ub(a,b,c,d);of(a);return a},na(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isDir(a){return 16384===(a&61440)},isLink(a){return 40960===(a&61440)},isChrdev(a){return 8192===(a&61440)},isBlkdev(a){return 24576===(a&61440)},isSocket(a){return 49152===(a&49152)},wb:4096,Mb:a=>FS.streams[a],Ab:{open(a){a.o=FS.Kb(a.node.ra).o;a.o.open?.(a)},llseek(){throw new FS.h(70);}},La:a=>a>>
8,Kc:a=>a&255,makedev:(a,b)=>a<<8|b,registerDevice(a,b){FS.Za[a]={o:b}},Kb:a=>FS.Za[a],syncfs(a,b){function c(k){FS.Ba--;return b(k)}function d(k){if(k){if(!d.Gb)return d.Gb=!0,c(k)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);FS.Ba++;1<FS.Ba&&t(`warning: ${FS.Ba} FS.syncfs operations in flight at once, probably just doing extra work`);var e=vf(FS.root.mount),f=0,g;for(g of e)g.type.syncfs?g.type.syncfs(g,a,d):d(null)},mount(a,b,c){var d="/"===c;if(d&&FS.root)throw new FS.h(10);if(!d&&
c){var e=FS.lookupPath(c,{wa:!1});c=e.path;e=e.node;if(e.T)throw new FS.h(10);if(!FS.isDir(e.mode))throw new FS.h(54);}b={type:a,bc:b,ib:c,oa:[]};a=a.mount(b);a.mount=b;b.root=a;d?FS.root=a:e&&(e.T=b,e.mount&&e.mount.oa.push(b));return a},unmount(a){a=FS.lookupPath(a,{wa:!1});if(!a.node.T)throw new FS.h(28);a=a.node;var b=a.T,c=vf(b);for([,e]of Object.entries(FS.da))for(;e;){var d=e.ka;c.includes(e.mount)&&gf(e);var e=d}a.T=null;a.mount.oa.splice(a.mount.oa.indexOf(b),1)},ia(a,b){return a.m.ia(a,
b)},ca(a,b,c){var d=FS.lookupPath(a,{parent:!0}).node;a=Ne(a);if(!a)throw new FS.h(28);if("."===a||".."===a)throw new FS.h(20);var e=pf(d,a);if(e)throw new FS.h(e);if(!d.m.ca)throw new FS.h(63);return d.m.ca(d,a,b,c)},pb(a){return wf(FS.lookupPath(a,{follow:!0}).node)},Oc(a){return wf(a.node)},create(a,b=438){return FS.ca(a,b&4095|32768,0)},mkdir(a,b=511){return FS.ca(a,b&1023|16384,0)},Lc(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{FS.mkdir(d,b)}catch(f){if(20!=
f.B)throw f;}}},mkdev(a,b,c){"undefined"==typeof c&&(c=b,b=438);return FS.ca(a,b|8192,c)},symlink(a,b){if(!We(a))throw new FS.h(44);var c=FS.lookupPath(b,{parent:!0}).node;if(!c)throw new FS.h(44);b=Ne(b);var d=pf(c,b);if(d)throw new FS.h(d);if(!c.m.symlink)throw new FS.h(63);return c.m.symlink(c,b,a)},rename(a,b){var c=Me(a),d=Me(b),e=Ne(a),f=Ne(b);var g=FS.lookupPath(a,{parent:!0});var k=g.node;g=FS.lookupPath(b,{parent:!0});g=g.node;if(!k||!g)throw new FS.h(44);if(k.mount!==g.mount)throw new FS.h(75);
var l=ff(k,e);a=Xe(a,d);if("."!==a.charAt(0))throw new FS.h(28);a=Xe(b,c);if("."!==a.charAt(0))throw new FS.h(55);try{var m=ff(g,f)}catch(n){}if(l!==m){b=FS.isDir(l.mode);if(e=qf(k,e,b))throw new FS.h(e);if(e=m?qf(g,f,b):pf(g,f))throw new FS.h(e);if(!k.m.rename)throw new FS.h(63);if(l.T||m&&m.T)throw new FS.h(10);if(g!==k&&(e=mf(k,"w")))throw new FS.h(e);gf(l);try{k.m.rename(l,g,f),l.parent=g}catch(n){throw n;}finally{of(l)}}},rmdir(a){var b=FS.lookupPath(a,{parent:!0}).node;a=Ne(a);var c=ff(b,a),
d=qf(b,a,!0);if(d)throw new FS.h(d);if(!b.m.rmdir)throw new FS.h(63);if(c.T)throw new FS.h(10);b.m.rmdir(b,a);gf(c)},sa(a){a=FS.lookupPath(a,{follow:!0}).node;return rf(a.m.sa,54)(a)},unlink(a){var b=FS.lookupPath(a,{parent:!0}).node;if(!b)throw new FS.h(44);a=Ne(a);var c=ff(b,a),d=qf(b,a,!1);if(d)throw new FS.h(d);if(!b.m.unlink)throw new FS.h(63);if(c.T)throw new FS.h(10);b.m.unlink(b,a);gf(c)},readlink(a){a=FS.lookupPath(a).node;if(!a)throw new FS.h(44);if(!a.m.readlink)throw new FS.h(28);return a.m.readlink(a)},
stat(a,b){a=FS.lookupPath(a,{follow:!b}).node;return rf(a.m.S,63)(a)},lstat(a){return FS.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?FS.lookupPath(a,{follow:!c}).node:a;xf(null,a,b,c)},lchmod(a,b){FS.chmod(a,b,!0)},fchmod(a,b){a=S(a);xf(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?FS.lookupPath(a,{follow:!d}).node:a;uf(null,a,{timestamp:Date.now(),$a:d})},lchown(a,b,c){FS.chown(a,b,c,!0)},fchown(a){a=S(a);uf(a,a.node,{timestamp:Date.now(),$a:!1})},truncate(a,b){if(0>b)throw new FS.h(28);
a="string"==typeof a?FS.lookupPath(a,{follow:!0}).node:a;yf(null,a,b)},ftruncate(a,b){a=S(a);if(0>b||0===(a.flags&2097155))throw new FS.h(28);yf(a,a.node,b)},utime(a,b,c){a=FS.lookupPath(a,{follow:!0}).node;rf(a.m.U,63)(a,{$:b,O:c})},open(a,b,c=438){if(""===a)throw new FS.h(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");
var f=FS.lookupPath(a,{follow:!(b&131072),ac:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new FS.h(20);}else{if(e)throw new FS.h(31);d=FS.ca(a,c|511,0);f=!0}if(!d)throw new FS.h(44);FS.isChrdev(d.mode)&&(b&=-513);if(b&65536&&!FS.isDir(d.mode))throw new FS.h(54);if(!f){e=d;a=b;if(e)if(FS.isLink(e.mode))e=32;else{var g=["r","w","rw"][a&3];a&512&&(g+="w");e=FS.isDir(e.mode)&&("r"!==g||a&576)?31:mf(e,g)}else e=44;if(e)throw new FS.h(e);}b&512&&!f&&FS.truncate(d,0);b&=-131713;b=sf({node:d,
path:FS.getPath(d),flags:b,seekable:!0,position:0,o:d.o,tc:[],error:!1});b.o.open&&b.o.open(b);f&&FS.chmod(d,c&511);return b},close(a){if(null===a.aa)throw new FS.h(8);a.Fa&&(a.Fa=null);try{a.o.close&&a.o.close(a)}catch(b){throw b;}finally{FS.streams[a.aa]=null}a.aa=null},llseek(a,b,c){if(null===a.aa)throw new FS.h(8);if(!a.seekable||!a.o.llseek)throw new FS.h(70);if(0!=c&&1!=c&&2!=c)throw new FS.h(28);a.position=a.o.llseek(a,b,c);a.tc=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new FS.h(28);
if(null===a.aa)throw new FS.h(8);if(1===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.read)throw new FS.h(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new FS.h(28);if(null===a.aa)throw new FS.h(8);if(0===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.write)throw new FS.h(28);a.seekable&&
a.flags&1024&&FS.llseek(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.write(a,b,c,d,e,f);g||(a.position+=b);return b},ja(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new FS.h(2);if(1===(a.flags&2097155))throw new FS.h(2);if(!a.o.ja)throw new FS.h(43);if(!b)throw new FS.h(28);return a.o.ja(a,b,c,d,e)},la(a,b,c,d,e){return a.o.la?a.o.la(a,b,c,d,e):0},Ia(a,b,c){if(!a.o.Ia)throw new FS.h(59);return a.o.Ia(a,b,c)},readFile(a,b={}){b.flags=
b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&J(`Invalid encoding type "${b.encoding}"`);var c=FS.open(a,b.flags);a=FS.stat(a).size;var d=new Uint8Array(a);FS.read(c,d,0,a,0);"utf8"===b.encoding&&(d=ne(d));FS.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=FS.open(a,c.flags,c.mode);b=hf(b);FS.write(a,b,0,b.byteLength,void 0,c.Ec);FS.close(a)},cwd:()=>FS.Xa,chdir(a){a=FS.lookupPath(a,{follow:!0});if(null===a.node)throw new FS.h(44);if(!FS.isDir(a.node.mode))throw new FS.h(54);
var b=mf(a.node,"x");if(b)throw new FS.h(b);FS.Xa=a.path},init(a,b,c){FS.Ha=!0;a??=h.stdin;b??=h.stdout;c??=h.stderr;a?FS.createDevice("/dev","stdin",a):FS.symlink("/dev/tty","/dev/stdin");b?FS.createDevice("/dev","stdout",null,b):FS.symlink("/dev/tty","/dev/stdout");c?FS.createDevice("/dev","stderr",null,c):FS.symlink("/dev/tty1","/dev/stderr");FS.open("/dev/stdin",0);FS.open("/dev/stdout",1);FS.open("/dev/stderr",1)},Hc(a,b){a=FS.analyzePath(a,b);return a.ab?a.object:null},analyzePath(a,b){try{var c=
FS.lookupPath(a,{follow:!b});a=c.path}catch(e){}var d={na:!1,ab:!1,error:0,name:null,path:null,object:null,cc:!1,fc:null,ec:null};try{c=FS.lookupPath(a,{parent:!0}),d.cc=!0,d.fc=c.path,d.ec=c.node,d.name=Ne(a),c=FS.lookupPath(a,{follow:!b}),d.ab=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.na="/"===c.path}catch(e){d.error=e.B}return d},createPath(a,b){a="string"==typeof a?a:FS.getPath(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Le(a+"/"+c);try{FS.mkdir(d)}catch(e){if(20!=
e.B)throw e;}a=d}}return d},createDataFile(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:FS.getPath(a),g=b?Le(a+"/"+b):a);a=jf(d,e);g=FS.create(g,a);c&&(c=hf(c),FS.chmod(g,a|146),b=FS.open(g,577),FS.write(b,c,0,c.length,0,f),FS.close(b),FS.chmod(g,a))},createDevice(a,b,c,d){a=Oe("string"==typeof a?a:FS.getPath(a),b);b=jf(!!c,!!d);var e;(e=FS.createDevice).La??(e.La=64);e=FS.makedev(FS.createDevice.La++,0);FS.registerDevice(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,k,l){for(var m=
0,n=0;n<l;n++){try{var q=c()}catch(u){throw new FS.h(29);}if(void 0===q&&0===m)throw new FS.h(6);if(null===q||void 0===q)break;m++;g[k+n]=q}m&&(f.node.$=Date.now());return m},write(f,g,k,l){for(var m=0;m<l;m++)try{d(g[k+m])}catch(n){throw new FS.h(29);}l&&(f.node.O=f.node.N=Date.now());return m}});return FS.mkdev(a,b,e)},createLazyFile(a,b,c,d,e){function f(n,q,u,r,v){n=n.node.u;if(v>=n.length)return 0;r=Math.min(n.length-v,r);if(n.slice)for(var x=0;x<r;x++)q[u+x]=n[v+x];else for(x=0;x<r;x++)q[u+
x]=n.get(v+x);return r}class g{Ga=!1;P=[];ma=void 0;hb=0;gb=0;get(n){if(!(n>this.length-1||0>n)){var q=n%this.ob;return this.ma(n/this.ob|0)[q]}}sc(n){this.ma=n}jb(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);200<=n.status&&300>n.status||304===n.status||J("Couldn't load "+c+". Status: "+n.status);var q=Number(n.getResponseHeader("Content-length")),u,r=(u=n.getResponseHeader("Accept-Ranges"))&&"bytes"===u;n=(u=n.getResponseHeader("Content-Encoding"))&&"gzip"===u;var v=1048576;r||(v=
q);var x=this;x.sc(D=>{var B=D*v,E=(D+1)*v-1;E=Math.min(E,q-1);if("undefined"==typeof x.P[D]){var R=x.P;B>E&&J("invalid range ("+B+", "+E+") or no bytes requested!");E>q-1&&J("only "+q+" bytes available! programmer error!");var C=new XMLHttpRequest;C.open("GET",c,!1);q!==v&&C.setRequestHeader("Range","bytes="+B+"-"+E);C.responseType="arraybuffer";C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");C.send(null);200<=C.status&&300>C.status||304===C.status||J("Couldn't load "+
c+". Status: "+C.status);B=void 0!==C.response?new Uint8Array(C.response||[]):Ze(C.responseText||"");R[D]=B}"undefined"==typeof x.P[D]&&J("doXHR failed!");return x.P[D]});if(n||!q)v=q=1,v=q=this.ma(0).length,ja("LazyFiles on gzip forces download of the whole file when length is accessed");this.hb=q;this.gb=v;this.Ga=!0}get length(){this.Ga||this.jb();return this.hb}get ob(){this.Ga||this.jb();return this.gb}}if(globalThis.XMLHttpRequest){ba||J("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var k=new g;var l=void 0}else l=c,k=void 0;var m=zf(a,b,d,e);k?m.u=k:l&&(m.u=null,m.url=l);Object.defineProperties(m,{L:{get:function(){return this.u.length}}});a={};for(const [n,q]of Object.entries(m.o))a[n]=(...u)=>{Af(m);return q(...u)};a.read=(n,q,u,r,v)=>{Af(m);return f(n,q,u,r,v)};a.ja=(n,q,u)=>{Af(m);var r=ef(q);if(!r)throw new FS.h(48);f(n,(w(),y),r,q,u);return{A:r,fa:!0}};m.o=a;return m}},Ge=(a,b)=>{if(Ha){if("/"===a.charAt(0))try{return FS.lookupPath(a),a}catch(d){return}var c=(b?.hc||[]).map(d=>
{var e=b?.dc;return d.startsWith("$ORIGIN")?d.replace("$ORIGIN",Me(e)):d});return Pe(()=>{var d=sd(512),e=Te(c.join(":")),f=Te(a);return(d=hd(d,e,f,512))?P(d):void 0})}};
function He(a,b={global:!0,pa:!0},c,d){function e(){var l=ta[a];if(l)return b.I?Promise.resolve(l):l;if(d){l=(w(),H)[d+28>>2];var m=(w(),H)[d+32>>2];if(l&&m)return l=(w(),y).slice(l,l+m),b.I?Promise.resolve(l):l}if(l=Ge(a,b.Ra))return l=FS.readFile(l,{encoding:"binary"}),b.I?Promise.resolve(l):l;l=fa(a);if(b.I)return Je(l);if(!ia)throw Error(`${l}: file not found, and synchronous loading of external files is not available`);return ia(l)}function f(){var l=de[a];return l?b.I?Promise.resolve(l):l:b.I?
e().then(m=>Ie(m,b,a,c,d)):Ie(e(),b,a,c,d)}function g(l){k.global?Tc(l):c&&Object.assign(c,l);k.exports=l}var k=oe[a];if(k)return b.global?k.global||(k.global=!0,Tc(k.exports)):c&&Object.assign(c,k.exports),b.pa&&Infinity!==k.Aa&&(k.Aa=Infinity),k.Aa++,d&&(pe[d]=k),b.I?Promise.resolve(!0):!0;k=zd(a,d,"loading");k.Aa=b.pa?Infinity:1;k.global=b.global;if(b.I)return f().then(l=>{g(l);return!0});g(f());return!0}
var Fe=()=>{var a,b;for([a,b]of Object.entries(je))if(-1==b.value){var c=De(a).Ta;if(c||b.required)if("function"==typeof c)b.value=ze(c,c.g);else if("number"==typeof c)b.value=c;else if("number"==typeof c.value)b.value=c;else throw Error(`bad export type for '${a}': ${typeof c} (${c})`);else b.value=0}},Ad=async()=>{if(ka.length){Pd("loadDylibs");for(var a of ka)await He(a,{I:!0,global:!0,pa:!0,xb:!0});Fe();Od("loadDylibs")}else Fe()},$d=!1,Vc=(a,b,c)=>{function d(){var e=a();if(e){var f={};c.qb.forEach(g=>
f[g]=b[g]);yd(Ae(f,e),!0)}}Ud.push(d);Ha&&d()},pa,Ya=(a,b,c,d)=>J(`Assertion failed: ${P(a)}, at: `+[b?P(b):"unknown filename",c,d?P(d):"unknown function"]);Ya.g="vppip";var Za=(a,b)=>M.get(a)(b);Za.g="vpi";function ab(...a){return K.__lsan_ignore_object(...a)}ab.Sa=!0;function Bf(a,b,c,d){return p?O(2,1,a,b,c,d):bb(a,b,c,d)}
var bb=(a,b,c,d)=>{if(!globalThis.SharedArrayBuffer)return 6;var e=[];if(p&&0===e.length)return Bf(a,b,c,d);a={qc:c,X:a,Da:d,rb:e};return p?(a.V="spawnThread",postMessage(a,e),0):Sd(a)};bb.g="ipppp";var Cf=18;function Df(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?FS.cwd():S(a).path;if(0==b.length){if(!c)throw new FS.h(44);return a}return a+"/"+b}
function Ef(a,b){(w(),H)[a>>2]=b.Cb;(w(),H)[a+4>>2]=b.mode;(w(),H)[a+8>>2]=b.$b;(w(),H)[a+12>>2]=b.uid;(w(),H)[a+16>>2]=b.Pb;(w(),H)[a+20>>2]=b.ra;(w(),I)[a+24>>3]=BigInt(b.size);(w(),G)[a+32>>2]=4096;(w(),G)[a+36>>2]=b.Va;var c=b.$.getTime(),d=b.O.getTime(),e=b.N.getTime();(w(),I)[a+40>>3]=BigInt(Math.floor(c/1E3));(w(),H)[a+48>>2]=c%1E3*1E6;(w(),I)[a+56>>3]=BigInt(Math.floor(d/1E3));(w(),H)[a+64>>2]=d%1E3*1E6;(w(),I)[a+72>>3]=BigInt(Math.floor(e/1E3));(w(),H)[a+80>>2]=e%1E3*1E6;(w(),I)[a+88>>3]=
BigInt(b.Tb);return 0}var Ff=void 0;function cb(a){if(p)return O(3,1,a);try{var b=S(a);return tf(b).aa}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}cb.g="ii";function db(a,b,c,d){if(p)return O(4,1,a,b,c,d);try{b=P(b);b=Df(a,b);if(c&-8)return-28;var e=FS.lookupPath(b,{follow:!0}).node;if(!e)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&mf(e,a)?-2:0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}db.g="iipii";
var Gf=()=>{var a=(w(),G)[+Ff>>2];Ff+=4;return a};function eb(a,b,c){if(p)return O(5,1,a,b,c);Ff=c;try{var d=S(a);switch(b){case 0:var e=Gf();if(0>e)break;for(;FS.streams[e];)e++;return tf(d,e).aa;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Gf(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=Gf(),(w(),z)[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}eb.g="iiip";
function fb(a,b){if(p)return O(6,1,a,b);try{var c=S(a),d=c.node,e=c.o.S;a=e?c:d;e??=d.m.S;rf(e,63);var f=e(a);return Ef(b,f)}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.B}}fb.g="iip";function gb(a,b){if(p)return O(7,1,a,b);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return-22;FS.ftruncate(a,b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}gb.g="iij";
function hb(a,b){if(p)return O(8,1,a,b);try{if(0===b)return-28;var c=FS.cwd(),d=Qe(c)+1;if(b<d)return-68;Se(c,a,b);return d}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.B}}hb.g="ipp";
function ib(a,b,c){if(p)return O(9,1,a,b,c);Ff=c;try{var d=S(a);switch(b){case 21509:return d.C?0:-59;case 21505:if(!d.C)return-59;if(d.C.ea.Ub){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Gf();(w(),G)[e>>2]=25856;(w(),G)[e+4>>2]=5;(w(),G)[e+8>>2]=191;(w(),G)[e+12>>2]=35387;for(var f=0;32>f;f++)(w(),y)[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.C?0:-59;case 21506:case 21507:case 21508:if(!d.C)return-59;if(d.C.ea.Vb)for(e=Gf(),w(),w(),
w(),w(),a=[],f=0;32>f;f++)a.push((w(),y)[e+f+17]);return 0;case 21519:if(!d.C)return-59;e=Gf();return(w(),G)[e>>2]=0;case 21520:return d.C?-28:-59;case 21537:case 21531:return e=Gf(),FS.Ia(d,b,e);case 21523:if(!d.C)return-59;d.C.ea.Wb&&(f=[24,80],e=Gf(),(w(),z)[e>>1]=f[0],(w(),z)[e+2>>1]=f[1]);return 0;case 21524:return d.C?0:-59;case 21515:return d.C?0:-59;default:return-28}}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.B}}ib.g="iiip";
function jb(a,b){if(p)return O(10,1,a,b);try{return a=P(a),Ef(b,FS.lstat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}jb.g="ipp";function kb(a,b,c,d){if(p)return O(11,1,a,b,c,d);try{b=P(b);var e=d&256;b=Df(a,b,d&4096);return Ef(c,e?FS.lstat(b):FS.stat(b))}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}kb.g="iippi";
function lb(a,b,c,d){if(p)return O(12,1,a,b,c,d);Ff=d;try{b=P(b);b=Df(a,b);var e=d?Gf():0;c&64&&(e&=~Cf);return FS.open(b,c,e).aa}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}lb.g="iipip";function mb(a){if(p)return O(13,1,a);try{return a=P(a),FS.rmdir(a),0}catch(b){if("undefined"==typeof FS||"ErrnoError"!==b.name)throw b;return-b.B}}mb.g="ip";
function nb(a,b){if(p)return O(14,1,a,b);try{return a=P(a),Ef(b,FS.stat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}nb.g="ipp";function ob(a,b,c){if(p)return O(15,1,a,b,c);try{b=P(b);b=Df(a,b);if(c)if(512===c)FS.rmdir(b);else return-28;else FS.unlink(b);return 0}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.B}}ob.g="iipi";
var pb=a=>{a=new WebAssembly.Exception(xd,[a],{traceStack:!0});var b=a.getArg(xd,0);var c=ud(b);b=td();var d=sd(4),e=sd(4);vd(c,d,e);c=(w(),H)[d>>2];e=(w(),H)[e>>2];d=P(c);L(c);if(e){var f=P(e);L(e)}rd(b);a.message=[d,f];throw a;},qb=()=>J("");qb.g="v";
var Hf=a=>{var b=td();a=Te(a);cd(a,0);rd(b)},If=(a,b)=>{var c=P(a+36),d=(w(),G)[a+4>>2];c=Le(c);var e=!!(d&256),f=e?null:{};d={global:e,pa:!!(d&4096),I:b.I};if(b.I)return He(c,d,f,a);try{return He(c,d,f,a)}catch(g){return Hf(`could not load dynamic lib: ${c}\n${g}`),0}},rb=a=>If(a,{I:!1});rb.g="pp";var sb=(a,b)=>{a=pe[a].exports;b=Object.keys(a)[b];b=a[b];return ze(b,b.g)};sb.g="ppi";
var tb=(a,b,c)=>{b=P(b);var d=pe[a];a=Object.keys(d.exports).indexOf(b);if(-1==a||d.exports[b].Sa)return Hf(`Tried to lookup unknown symbol "${b}" in dynamic lib: ${d.name}`),0;b=d.exports[b];"function"==typeof b&&((d=ue(b))?b=d:(b=ze(b,b.g),(w(),H)[c>>2]=a));return b};tb.g="pppp";var Jf={},Kf=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Lf(a){return this.v((w(),H)[a>>2])}
var Mf={},Nf={},Of={},Pf=class extends Error{constructor(a){super(a);this.name="InternalError"}},U=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new Pf("Mismatched type converter count");for(var l=0;l<a.length;++l)T(a[l],k[l])}a.forEach(k=>Of[k]=b);var e=Array(b.length),f=[],g=0;for(let [k,l]of b.entries())Nf.hasOwnProperty(l)?e[k]=Nf[l]:(f.push(l),Mf.hasOwnProperty(l)||(Mf[l]=[]),Mf[l].push(()=>{e[k]=Nf[l];++g;g===f.length&&d(e)}));0===f.length&&d(e)},ub=a=>{var b=Jf[a];delete Jf[a];
var c=b.Qa,d=b.Y,e=b.bb,f=e.map(g=>g.Ob).concat(e.map(g=>g.mc));U([a],f,g=>{var k={},l,m;for([l,m]of e.entries()){const n=g[l],q=m.ma,u=m.Nb,r=g[l+e.length],v=m.lc,x=m.nc;k[m.Hb]={read:D=>n.v(q(u,D)),write:(D,B)=>{var E=[];v(x,D,r.F(E,B));Kf(E)},optional:n.optional}}return[{name:b.name,v:n=>{var q={},u;for(u in k)q[u]=k[u].read(n);d(n);return q},F:(n,q)=>{for(var u in k)if(!(u in q||k[u].optional))throw new TypeError(`Missing field: "${u}"`);var r=c();for(u in k)k[u].write(r,q[u]);null!==n&&n.push(d,
r);return r},K:Lf,H:d}]})};ub.g="vp";var V=a=>{for(var b="";;){var c=(w(),A)[a++];if(!c)return b;b+=String.fromCharCode(c)}},W=class extends Error{constructor(a){super(a);this.name="BindingError"}},Qf=a=>{throw new W(a);};
function Rf(a,b,c={}){var d=b.name;if(!a)throw new W(`type "${d}" must have a positive integer typeid pointer`);if(Nf.hasOwnProperty(a)){if(c.Sb)return;throw new W(`Cannot register type '${d}' twice`);}Nf[a]=b;delete Of[a];Mf.hasOwnProperty(a)&&(b=Mf[a],delete Mf[a],b.forEach(e=>e()))}function T(a,b,c={}){return Rf(a,b,c)}
var Sf=(a,b)=>{switch(b){case 4:return w(),Ka;case 8:return w(),La;default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Tf=(a,b,c)=>{switch(b){case 1:return c?(w(),y):(w(),A);case 2:return c?(w(),z):(w(),F);case 4:return c?(w(),G):(w(),H);case 8:return c?(w(),I):(w(),Ma);default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},vb=(a,b,c,d,e)=>{b=V(b);var f=d?Sf(b,c):Tf(b,c,e),g=Math.log2(c);T(a,{name:b,v:k=>{var l=(w(),H)[k>>2],m=k+Math.max(4,c)>>g;l=Array.from(f.subarray(m,
m+l));L(k);return l},F:(k,l)=>{"number"==typeof l&&(l=[l]);if(!Array.isArray(l))throw new W(`Cannot pass non-array to C++ vector type ${b}`);l=Array.prototype.concat.apply([],l);var m=l.length,n=Math.max(4,c),q=Xc(n+m*c);n=q+n>>g;(w(),H)[q>>2]=m;f.set(l,n);null!==k&&k.push(L,q);return q},K:Lf,H(k){L(k)}})};vb.g="vpppii";
var Uf=(a,b,c)=>{switch(b){case 1:return c?d=>(w(),y)[d]:d=>(w(),A)[d];case 2:return c?d=>(w(),z)[d>>1]:d=>(w(),F)[d>>1];case 4:return c?d=>(w(),G)[d>>2]:d=>(w(),H)[d>>2];case 8:return c?d=>(w(),I)[d>>3]:d=>(w(),Ma)[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},wb=(a,b,c,d,e)=>{b=V(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=k=>BigInt.asUintN(g,k);e=f(e)}T(a,{name:b,v:f,F:(g,k)=>{"number"==typeof k&&(k=BigInt(k));return k},K:Uf(b,c,!d),H:null})};wb.g="vpppjj";
var xb=(a,b,c,d)=>{b=V(b);T(a,{name:b,v:function(e){return!!e},F:function(e,f){return f?c:d},K:function(e){return this.v((w(),A)[e])},H:null})};xb.g="vppii";
var Vf=a=>{throw new W(a.l.D.s.name+" instance already deleted");},Wf=!1,Xf=!1,Yf=()=>{},Zf=a=>{if(Wf)return Zf=b=>b.deleteLater(),Zf(a);if(!globalThis.FinalizationRegistry)return Zf=b=>b,a;Xf=new FinalizationRegistry(b=>{b=b.l;--b.count.value;0===b.count.value&&(b.J?b.R.Y(b.J):b.D.s.Y(b.A))});Zf=b=>{var c=b.l;c.J&&Xf.register(b,{l:c},b);return b};Yf=b=>{Xf.unregister(b)};return Zf(a)},$f=[],ag=()=>{for(;$f.length;){var a=$f.pop();a.l.ha=!1;a["delete"]()}},bg;function cg(){}
var dg={},eg=(a,b,c)=>{if(void 0===a[b].G){var d=a[b];a[b]=function(...e){if(!a[b].G.hasOwnProperty(e.length))throw new W(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].G})!`);return a[b].G[e.length].apply(this,e)};a[b].G=[];a[b].G[d.Z]=d}},fg=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].G&&void 0!==h[a].G[c])throw new W(`Cannot register public name '${a}' twice`);eg(h,a,a);if(h[a].G.hasOwnProperty(c))throw new W(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].G[c]=b}else h[a]=b,h[a].Z=c},gg=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function hg(a,b,c,d,e,f,g,k){this.name=a;this.constructor=b;this.ba=c;this.Y=d;this.M=e;this.Jb=f;this.ua=g;this.Db=k;this.jc=[]}
var ig=(a,b,c)=>{for(;b!==c;){if(!b.ua)throw new W(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ua(a);b=b.M}return a},jg=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function kg(a,b){if(null===b){if(this.Ja)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new W(`Cannot pass "${jg(b)}" as a ${this.name}`);if(!b.l.A)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);return ig(b.l.A,b.l.D.s,this.s)}
function lg(a,b){if(null===b){if(this.Ja)throw new W(`null is not a valid ${this.name}`);if(this.za){var c=this.Qa();null!==a&&a.push(this.Y,c);return c}return 0}if(!b||!b.l)throw new W(`Cannot pass "${jg(b)}" as a ${this.name}`);if(!b.l.A)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ya&&b.l.D.ya)throw new W(`Cannot convert argument of type ${b.l.R?b.l.R.name:b.l.D.name} to parameter type ${this.name}`);c=ig(b.l.A,b.l.D.s,this.s);if(this.za){if(void 0===b.l.J)throw new W("Passing raw pointer to smart pointer is illegal");
switch(this.pc){case 0:if(b.l.R===this)c=b.l.J;else throw new W(`Cannot convert argument of type ${b.l.R?b.l.R.name:b.l.D.name} to parameter type ${this.name}`);break;case 1:c=b.l.J;break;case 2:if(b.l.R===this)c=b.l.J;else{var d=b.clone();c=this.kc(c,mg(()=>d["delete"]()));null!==a&&a.push(this.Y,c)}break;default:throw new W("Unsupported sharing policy");}}return c}
function ng(a,b){if(null===b){if(this.Ja)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new W(`Cannot pass "${jg(b)}" as a ${this.name}`);if(!b.l.A)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.l.D.ya)throw new W(`Cannot convert argument of type ${b.l.D.name} to parameter type ${this.name}`);return ig(b.l.A,b.l.D.s,this.s)}
var og=(a,b,c)=>{if(b===c)return a;if(void 0===c.M)return null;a=og(a,b,c.M);return null===a?null:c.Db(a)},pg={},qg=(a,b)=>{if(void 0===b)throw new W("ptr should not be undefined");for(;a.M;)b=a.ua(b),a=a.M;return pg[b]},rg=(a,b)=>{if(!b.D||!b.A)throw new Pf("makeClassHandle requires ptr and ptrType");if(!!b.R!==!!b.J)throw new Pf("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Zf(Object.create(a,{l:{value:b,writable:!0}}))};
function sg(a,b,c,d,e,f,g,k,l,m,n){this.name=a;this.s=b;this.Ja=c;this.ya=d;this.za=e;this.ic=f;this.pc=g;this.lb=k;this.Qa=l;this.kc=m;this.Y=n;e||void 0!==b.M?this.F=lg:(this.F=d?kg:ng,this.H=null)}var tg=(a,b,c)=>{if(!h.hasOwnProperty(a))throw new Pf("Replacing nonexistent public symbol");void 0!==h[a].G&&void 0!==c?h[a].G[c]=b:(h[a]=b,h[a].Z=c)},X=(a,b)=>{a=V(a);var c=M.get(b);if("function"!=typeof c)throw new W(`unknown function pointer with signature ${a}: ${b}`);return c};
class ug extends Error{}
var vg=a=>{a=$c(a);var b=V(a);L(a);return b},wg=(a,b)=>{function c(f){e[f]||Nf[f]||(Of[f]?Of[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new ug(`${a}: `+d.map(vg).join([", "]));},Ab=(a,b,c,d,e,f,g,k,l,m,n,q,u)=>{n=V(n);f=X(e,f);k&&=X(g,k);m&&=X(l,m);u=X(q,u);var r=gg(n);fg(r,function(){wg(`Cannot construct ${n} due to unbound types`,[d])});U([a,b,c],d?[d]:[],v=>{v=v[0];if(d){var x=v.s;var D=x.ba}else D=cg.prototype;v=Ce(n,function(...C){if(Object.getPrototypeOf(this)!==B)throw new W(`Use 'new' to construct ${n}`);
if(void 0===E.ga)throw new W(`${n} has no accessible constructor`);var Ja=E.ga[C.length];if(void 0===Ja)throw new W(`Tried to invoke ctor of ${n} with invalid number of parameters (${C.length}) - expected (${Object.keys(E.ga).toString()}) parameters instead!`);return Ja.apply(this,C)});var B=Object.create(D,{constructor:{value:v}});v.prototype=B;var E=new hg(n,v,B,u,x,f,k,m);if(E.M){var R;(R=E.M).va??(R.va=[]);E.M.va.push(E)}x=new sg(n,E,!0,!1,!1);R=new sg(n+"*",E,!1,!1,!1);D=new sg(n+" const*",E,
!1,!0,!1);dg[a]={pointerType:R,Bb:D};tg(r,v);return[x,R,D]})};Ab.g="vppppppppppppp";function Ag(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].H)return!0;return!1}
function Bg(a,b,c,d,e,f){var g=b.length;if(2>g)throw new W("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,l=Ag(b);c=!b[0].fb;var m=b[0],n=b[1];d=[a,Qf,d,e,Kf,m.v.bind(m),n?.F.bind(n)];for(e=2;e<g;++e)m=b[e],d.push(m.F.bind(m));if(!l)for(e=k?1:2;e<b.length;++e)null!==b[e].H&&d.push(b[e].H);l=Ag(b);e=b.length-2;n=[];m=["fn"];k&&m.push("thisWired");for(g=0;g<e;++g)n.push(`arg${g}`),m.push(`arg${g}Wired`);n=n.join(",");m=m.join(",");n=`return function (${n}) {\n`;
l&&(n+="var destructors = [];\n");var q=l?"destructors":"null",u="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");k&&(n+=`var thisWired = toClassParamWire(${q}, this);\n`);for(g=0;g<e;++g){var r=`toArg${g}Wire`;n+=`var arg${g}Wired = ${r}(${q}, arg${g});\n`;u.push(r)}n+=(c||f?"var rv = ":"")+`invoker(${m});\n`;if(l)n+="runDestructors(destructors);\n";else for(g=k?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].H&&(n+=`${f}_dtor(${f});\n`,
u.push(`${f}_dtor`));c&&(n+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(u,n+"}\n"))(...d);return Ce(a,b)}
var Cg=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push((w(),H)[b+4*d>>2]);return c},Dg=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Bb=(a,b,c,d,e,f,g,k)=>{var l=Cg(c,d);b=V(b);b=Dg(b);f=X(e,f);U([],[a],m=>{function n(){wg(`Cannot call ${q} due to unbound types`,l)}m=m[0];var q=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var u=m.s.constructor;void 0===u[b]?(n.Z=c-1,u[b]=n):(eg(u,b,q),u[b].G[c-1]=n);U([],l,r=>{r=Bg(q,[r[0],null].concat(r.slice(1)),null,f,g,k);void 0===
u[b].G?(r.Z=c-1,u[b]=r):u[b].G[c-1]=r;if(m.s.va)for(const v of m.s.va)v.constructor.hasOwnProperty(b)||(v.constructor[b]=r);return[]});return[]})};Bb.g="vppippppii";
var Cb=(a,b,c,d,e,f)=>{var g=Cg(b,c);e=X(d,e);U([],[a],k=>{k=k[0];var l=`constructor ${k.name}`;void 0===k.s.ga&&(k.s.ga=[]);if(void 0!==k.s.ga[b-1])throw new W(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);k.s.ga[b-1]=()=>{wg(`Cannot construct ${k.name} due to unbound types`,g)};U([],g,m=>{m.splice(1,0,null);k.s.ga[b-1]=Bg(l,m,null,e,f);return[]});
return[]})};Cb.g="vpipppp";var Db=(a,b,c,d,e,f,g,k,l)=>{var m=Cg(c,d);b=V(b);b=Dg(b);f=X(e,f);U([],[a],n=>{function q(){wg(`Cannot call ${u} due to unbound types`,m)}n=n[0];var u=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&n.s.jc.push(b);var r=n.s.ba,v=r[b];void 0===v||void 0===v.G&&v.className!==n.name&&v.Z===c-2?(q.Z=c-2,q.className=n.name,r[b]=q):(eg(r,b,u),r[b].G[c-2]=q);U([],m,x=>{x=Bg(u,x,n,f,g,l);void 0===r[b].G?(x.Z=c-2,r[b]=x):r[b].G[c-2]=x;return[]});return[]})};
Db.g="vppippppiii";
var Eg=(a,b,c)=>{if(!(a instanceof Object))throw new W(`${c} with invalid "this": ${a}`);if(!(a instanceof b.s.constructor))throw new W(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.l.A)throw new W(`cannot call emscripten binding method ${c} on deleted object`);return ig(a.l.A,a.l.D.s,b.s)},Eb=(a,b,c,d,e,f,g,k,l,m)=>{b=V(b);e=X(d,e);U([],[a],n=>{n=n[0];var q=`${n.name}.${b}`,u={get(){wg(`Cannot access ${q} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};u.set=l?
()=>wg(`Cannot access ${q} due to unbound types`,[c,g]):()=>{throw new W(q+" is a read-only property");};Object.defineProperty(n.s.ba,b,u);U([],l?[c,g]:[c],r=>{var v=r[0],x={get(){var B=Eg(this,n,q+" getter");return v.v(e(f,B))},enumerable:!0};if(l){l=X(k,l);var D=r[1];x.set=function(B){var E=Eg(this,n,q+" setter"),R=[];l(m,E,D.F(R,B));Kf(R)}}Object.defineProperty(n.s.ba,b,x);return[]});return[]})};Eb.g="vpppppppppp";
var Fg=[],Gg=[0,1,,1,null,1,!0,1,!1,1],Hg=[],ec=a=>{if(9<a&&0===--Gg[a+1]){var b=Gg[a];Gg[a]=void 0;var c=Hg[a];c&&(Hg[a]=void 0,c(b));Fg.push(a)}};ec.g="vp";var Y=a=>{if(!a)throw new W(`Cannot use deleted val. handle = ${a}`);return Gg[a]},mg=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Fg.pop()||Gg.length;Gg[b]=a;Gg[b+1]=1;return b}},Ig={name:"emscripten::val",v:a=>{var b=Y(a);ec(a);return b},F:(a,b)=>mg(b),K:Lf,H:null},Fb=a=>T(a,Ig);
Fb.g="vp";
var Jg=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.v((w(),y)[d])}:function(d){return this.v((w(),A)[d])};case 2:return c?function(d){return this.v((w(),z)[d>>1])}:function(d){return this.v((w(),F)[d>>1])};case 4:return c?function(d){return this.v((w(),G)[d>>2])}:function(d){return this.v((w(),H)[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Gb=(a,b,c,d,e)=>{b=V(b);e=0===e?"object":1===e?"number":"string";switch(e){case "object":function g(){}g.values={};
T(a,{name:b,constructor:g,valueType:e,v:function(k){return this.constructor.values[k]},F:(k,l)=>l.value,K:Jg(b,c,d),H:null});fg(b,g);break;case "number":var f={};T(a,{name:b,Ka:f,valueType:e,v:k=>k,F:(k,l)=>l,K:Jg(b,c,d),H:null});fg(b,f);delete h[b].Z;break;case "string":f={},T(a,{name:b,sb:{},mb:{},Ka:f,valueType:e,v:function(k){return this.mb[k]},F:function(k,l){return this.sb[l]},K:Jg(b,c,d),H:null}),fg(b,f),delete h[b].Z}};Gb.g="vpppii";
var Kg=(a,b)=>{var c=Nf[a];if(void 0===c)throw a=`${b} has unknown type ${vg(a)}`,new W(a);return c},Hb=(a,b,c)=>{var d=Kg(a,"enum");b=V(b);switch(d.valueType){case "object":a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Ce(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d;break;case "number":d.Ka[b]=c;break;case "string":d.sb[b]=c,d.mb[c]=b,d.Ka[b]=b}};Hb.g="vppi";
var Lg=(a,b)=>{switch(b){case 4:return function(c){return this.v((w(),Ka)[c>>2])};case 8:return function(c){return this.v((w(),La)[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ib=(a,b,c)=>{b=V(b);T(a,{name:b,v:d=>d,F:(d,e)=>e,K:Lg(b,c),H:null})};Ib.g="vppp";var Jb=(a,b,c,d,e,f,g)=>{var k=Cg(b,c);a=V(a);a=Dg(a);e=X(d,e);fg(a,function(){wg(`Cannot call ${a} due to unbound types`,k)},b-1);U([],k,l=>{tg(a,Bg(a,[l[0],null].concat(l.slice(1)),null,e,f,g),b-1);return[]})};
Jb.g="vpippppii";var Kb=(a,b,c,d,e)=>{b=V(b);let f=k=>k;if(0===d){var g=32-8*c;f=k=>k<<g>>>g;e=f(e)}T(a,{name:b,v:f,F:(k,l)=>l,K:Uf(b,c,0!==d),H:null})};Kb.g="vpppii";var Mg=(a,b,c)=>{const d=(e,f)=>{let g=0;return{next(){if(g>=e)return{done:!0};const k=g;g++;return{value:f(k),done:!1}},[Symbol.iterator](){return this}}};a[Symbol.iterator]||(a[Symbol.iterator]=function(){const e=this[b]();return d(e,f=>this[c](f))})},Lb=(a,b,c,d)=>{c=V(c);d=V(d);U([],[a,b],e=>{Mg(e[0].s.ba,c,d);return[]})};Lb.g="vpppp";
var Mb=(a,b,c)=>{function d(f){var g=(w(),H)[f>>2];f=(w(),H)[f+4>>2];return new e((w(),y).buffer,f,g)}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=V(c);T(a,{name:c,v:d,K:d},{Sb:!0})};Mb.g="vpip";var Ng=Object.assign({optional:!0},Ig),Nb=a=>{T(a,Ng)};Nb.g="vpp";
var Ob=(a,b)=>{b=V(b);T(a,{name:b,v(c){var d=(w(),H)[c>>2];d=P(c+4,d,!0);L(c);return d},F(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new W("Cannot pass non-string to std::string");var f=e?Qe(d):d.length;var g=Xc(4+f+1),k=g+4;(w(),H)[g>>2]=f;e?Se(d,k,f+1):(w(),A).set(d,k);null!==c&&c.push(L,g);return g},K:Lf,H(c){L(c)}})};Ob.g="vpp";
var Og=new TextDecoder("utf-16le"),Pg=(a,b,c)=>{a>>=1;b=me((w(),F),a,b/2,c);return Og.decode((w(),F).slice(a,b))},Qg=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);(w(),z)[b>>1]=f;b+=2}(w(),z)[b>>1]=0;return b-d},Rg=a=>2*a.length,Sg=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=(w(),H)[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Tg=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=
0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;(w(),G)[b>>2]=f;b+=4;if(b+4>c)break}(w(),G)[b>>2]=0;return b-d},Ug=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Pb=(a,b,c)=>{c=V(c);if(2===b){var d=Pg;var e=Qg;var f=Rg}else d=Sg,e=Tg,f=Ug;T(a,{name:c,v:g=>{var k=(w(),H)[g>>2];k=d(g+4,k*b,!0);L(g);return k},F:(g,k)=>{if("string"!=typeof k)throw new W(`Cannot pass non-string to C++ string type ${c}`);var l=f(k),m=Xc(4+l+b);(w(),H)[m>>2]=l/b;e(k,m+4,l+b);null!==g&&
g.push(L,m);return m},K:Lf,H(g){L(g)}})};Pb.g="vppp";var Qb=(a,b,c,d,e,f)=>{Jf[a]={name:V(b),Qa:X(c,d),Y:X(e,f),bb:[]}};Qb.g="vpppppp";var Rb=(a,b,c,d,e,f,g,k,l,m)=>{Jf[a].bb.push({Hb:V(b),Ob:c,ma:X(d,e),Nb:f,mc:g,lc:X(k,l),nc:m})};Rb.g="vpppppppppp";var Sb=(a,b)=>{b=V(b);T(a,{fb:!0,name:b,v:()=>{},F:()=>{}})};Sb.g="vpp";
var Tb=(a,b,c,d)=>{function e(k){var l=P(a+36);Hf(`'Could not load dynamic lib: ${l}\n${k}`);--N;Yd(()=>M.get(c)(a,d))}function f(){--N;Yd(()=>M.get(b)(a,d))}N+=1;var g=If(a,{I:!0});g?g.then(f,e):e()};Tb.g="vpppp";function Vg(a){var b=Wg,c=b.P.pop()||b.fa.length;b.fa[c]=a;return c}function Xg(a){var b=Wg;b.fa[a]=void 0;b.P.push(a)}class Yg{fa=[void 0];P=[];get(a){return this.fa[a]}has(a){return void 0!==this.fa[a]}}
var Wg=new Yg,Zg=()=>{var a={};a.promise=new Promise((b,c)=>{a.reject=c;a.resolve=b});a.id=Vg(a);return a},$g=async()=>{const a=Zd,b=[];var c=Zg();b.push(c.promise);dd(c.id);for(const d of Object.keys(Ed)){const e=Number(d);e===a||Fd.has(e)||(c=Zg(),fd(e,c.id),Gd[e]=c,b.push(c.promise))}await Promise.all(b);Gd={}};function Ub(){if(p)return O(16,2);if(Zd)return $g();for(const a of Object.keys(Ed)){const b=Number(a);Fd.has(b)||gd(b)}}Ub.g="v";
function Vb(){var a=Xc(4*(ka.length+1)),b=a;ka.forEach(c=>{var d=(w(),H),e=b>>2,f=Qe(c)+1,g=Xc(f);g&&Se(c,g,f);d[e]=g;b+=4});(w(),H)[b>>2]=0;return a}Vb.g="p";var Wb=a=>{Aa(a,!ba,1,!aa,262144,!1);Ba()};Wb.g="vp";var Ca=a=>{Td||(Atomics.waitAsync((w(),G),a>>2,a).value.then(Fa),a+=120,Atomics.store((w(),G),a>>2,1))};Ca.g="vp";var Fa=()=>{var a=Wc();a&&Yd(()=>{Ca(a);od()})},Xb=(a,b)=>{a==b?setTimeout(Fa):p?postMessage({Ca:a,V:"checkMailbox"}):(a=Ed[a])&&a.postMessage({V:"checkMailbox"})};Xb.g="vpp";
var ah=[],Yb=(a,b,c,d,e,f,g)=>{ah.length=0;var k=e>>3;for(d=e+d>>3;k<d;){var l;(w(),I)[k++]?l=(w(),I)[k++]:l=(w(),La)[k++];ah.push(l)}a=b?Ee[b]:bh[a];Zd=c;c=a(...ah);Zd=0;if(f)c.then(m=>kd(f,g,m));else return c};Yb.g="dippippp";var Zb=()=>{$d=!1;N=0};Zb.g="v";var $b=a=>{p?postMessage({V:"cleanupThread",Ua:a}):Jd(a)};$b.g="vp";var ac=a=>{p?postMessage({V:"markAsFinished",Ua:a}):Ld(a)};ac.g="vp";var bc=()=>{};bc.g="vp";var cc=(a,b)=>{a=Y(a);b=Y(b);a.set(b)};cc.g="vpp";
var ch=[],dh=a=>{var b=ch.length;ch.push(a);return b},eh=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Kg((w(),H)[b+4*d>>2],`parameter ${d}`);return c},fh=(a,b,c)=>{var d=[];a=a(d,c);d.length&&((w(),H)[b>>2]=mg(d));return a},gh={},hh=a=>{var b=gh[a];return void 0===b?V(a):b},dc=(a,b,c)=>{var [d,...e]=eh(a,b);b=d.F.bind(d);var f=e.map(l=>l.K.bind(l));a--;var g={toValue:Y};a=f.map((l,m)=>{var n=`argFromPtr${m}`;g[n]=l;return`${n}(args${m?"+"+8*m:""})`});switch(c){case 0:var k="toValue(handle)";break;
case 2:k="new (toValue(handle))";break;case 3:k="";break;case 1:g.getStringOrSymbol=hh,k="toValue(handle)[getStringOrSymbol(methodName)]"}k+=`(${a})`;d.fb||(g.toReturnWire=b,g.emval_returnValue=fh,k=`return emval_returnValue(toReturnWire, destructorsRef, ${k})`);k=`return function (handle, methodName, destructorsRef, args) {\n${k}\n}`;c=(new Function(Object.keys(g),k))(...Object.values(g));k=`methodCaller<(${e.map(l=>l.name)}) => ${d.name}>`;return dh(Ce(k,c))};dc.g="pipi";
var fc=a=>{if(!a)return mg(globalThis);a=hh(a);return mg(globalThis[a])};fc.g="pp";var gc=a=>{a=hh(a);return mg(h[a])};gc.g="pp";var hc=(a,b)=>{a=Y(a);b=Y(b);return mg(a[b])};hc.g="ppp";var ic=a=>{9<a&&(Gg[a+1]+=1)};ic.g="vp";var jc=(a,b)=>{a=Y(a);b=Y(b);return a instanceof b};jc.g="ipp";var kc=(a,b,c,d,e)=>ch[a](b,c,d,e);kc.g="dppppp";var lc=a=>{a=Y(a);return"number"==typeof a};lc.g="ip";var mc=a=>{a=Y(a);return"string"==typeof a};mc.g="ip";var nc=a=>mg(hh(a));nc.g="pp";
var oc=a=>{var b=Y(a);Kf(b);ec(a)};oc.g="vp";var pc=(a,b,c)=>{a=Y(a);b=Y(b);c=Y(c);a[b]=c};pc.g="vppp";var qc=a=>{a=Y(a);return mg(typeof a)};qc.g="pp";
function rc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);(w(),G)[b>>2]=a.getUTCSeconds();(w(),G)[b+4>>2]=a.getUTCMinutes();(w(),G)[b+8>>2]=a.getUTCHours();(w(),G)[b+12>>2]=a.getUTCDate();(w(),G)[b+16>>2]=a.getUTCMonth();(w(),G)[b+20>>2]=a.getUTCFullYear()-1900;(w(),G)[b+24>>2]=a.getUTCDay();a=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;(w(),G)[b+28>>2]=a}rc.g="vjp";
var ih=[0,31,60,91,121,152,182,213,244,274,305,335],jh=[0,31,59,90,120,151,181,212,243,273,304,334];
function sc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);(w(),G)[b>>2]=a.getSeconds();(w(),G)[b+4>>2]=a.getMinutes();(w(),G)[b+8>>2]=a.getHours();(w(),G)[b+12>>2]=a.getDate();(w(),G)[b+16>>2]=a.getMonth();(w(),G)[b+20>>2]=a.getFullYear()-1900;(w(),G)[b+24>>2]=a.getDay();var c=a.getFullYear();c=(0!==c%4||0===c%100&&0!==c%400?jh:ih)[a.getMonth()]+a.getDate()-1|0;(w(),G)[b+28>>2]=c;(w(),G)[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();
var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();a=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0;(w(),G)[b+32>>2]=a}sc.g="vjp";function tc(a,b,c,d,e,f,g){if(p)return O(17,1,a,b,c,d,e,f,g);e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{var k=S(d),l=FS.ja(k,a,e,b,c),m=l.A;(w(),G)[f>>2]=l.fa;(w(),H)[g>>2]=m;return 0}catch(n){if("undefined"==typeof FS||"ErrnoError"!==n.name)throw n;return-n.B}}tc.g="ipiiijpp";
function uc(a,b,c,d,e,f){if(p)return O(18,1,a,b,c,d,e,f);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=S(e);if(c&2){c=f;if(!FS.isFile(g.node.mode))throw new FS.h(43);if(!(d&2)){var k=(w(),A).slice(a,a+b);FS.la(g,k,c,b,d)}}}catch(l){if("undefined"==typeof FS||"ErrnoError"!==l.name)throw l;return-l.B}}uc.g="ippiiij";
var vc=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var g=Math.max(f,e);(w(),H)[a>>2]=60*g;(w(),G)[b>>2]=Number(f!=e);b=k=>{var l=Math.abs(k);return`UTC${0<=k?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(Se(a,c,17),Se(b,d,17)):(Se(a,d,17),Se(b,c,17))};vc.g="vpppp";var Cc=()=>performance.timeOrigin+performance.now();Cc.g="d";var yc=()=>Date.now();yc.g="d";
var kh=1;function wc(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(kh)a=performance.timeOrigin+performance.now();else return 52;a=Math.round(1E6*a);(w(),I)[c>>3]=BigInt(a);return 0}wc.g="iijp";var xc=()=>{};xc.g="v";var zc=a=>t(P(a));zc.g="vp";var Ac=()=>{N+=1;throw"unwind";};Ac.g="v";var Bc=()=>2147483648;Bc.g="p";var Dc=()=>navigator.hardwareConcurrency;Dc.g="i";var Ec=a=>{Xg(a)};Ec.g="vp";
var Fc=(a,b,c)=>{a=Wg.get(a);switch(b){case 0:a.resolve(c);break;case 1:a.resolve(Wg.get(c).promise);break;case 2:a.resolve(Wg.get(c).promise);Xg(c);break;case 3:a.reject(c)}};Fc.g="vpip";var Gc=a=>{var b=(w(),A).length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-pa.buffer.byteLength+65535)/65536|0;try{pa.grow(d);qa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1};
Gc.g="ip";var lh={},nh=()=>{if(!mh){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in lh)void 0===lh[b]?delete a[b]:a[b]=lh[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);mh=c}return mh},mh;function Hc(a,b){if(p)return O(19,1,a,b);var c=0,d=0,e;for(e of nh()){var f=b+c;(w(),H)[a+d>>2]=f;c+=Se(e,f,Infinity)+1;d+=4}return 0}Hc.g="ipp";
function Ic(a,b){if(p)return O(20,1,a,b);var c=nh();(w(),H)[a>>2]=c.length;a=0;for(var d of c)a+=Qe(d)+1;(w(),H)[b>>2]=a;return 0}Ic.g="ipp";function Kc(a){if(p)return O(21,1,a);try{var b=S(a);FS.close(b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.B}}Kc.g="ii";
function Lc(a,b){if(p)return O(22,1,a,b);try{var c=S(a),d=c.C?2:FS.isDir(c.mode)?3:FS.isLink(c.mode)?7:4;(w(),y)[b]=d;(w(),z)[b+2>>1]=0;(w(),I)[b+8>>3]=BigInt(0);(w(),I)[b+16>>3]=BigInt(0);return 0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return e.B}}Lc.g="iip";
function Mc(a,b,c,d){if(p)return O(23,1,a,b,c,d);try{a:{var e=S(a);a=b;for(var f,g=b=0;g<c;g++){var k=(w(),H)[a>>2],l=(w(),H)[a+4>>2];a+=8;var m=FS.read(e,(w(),y),k,l,f);if(0>m){var n=-1;break a}b+=m;if(m<l)break;"undefined"!=typeof f&&(f+=m)}n=b}(w(),H)[d>>2]=n;return 0}catch(q){if("undefined"==typeof FS||"ErrnoError"!==q.name)throw q;return q.B}}Mc.g="iippp";
function Nc(a,b,c,d){if(p)return O(24,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 22;var e=S(a);FS.llseek(e,b,c);(w(),I)[d>>3]=BigInt(e.position);e.Fa&&0===b&&0===c&&(e.Fa=null);return 0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return f.B}}Nc.g="iijip";
function Oc(a,b,c,d){if(p)return O(25,1,a,b,c,d);try{a:{var e=S(a);a=b;for(var f,g=b=0;g<c;g++){var k=(w(),H)[a>>2],l=(w(),H)[a+4>>2];a+=8;var m=FS.write(e,(w(),y),k,l,f);if(0>m){var n=-1;break a}b+=m;if(m<l)break;"undefined"!=typeof f&&(f+=m)}n=b}(w(),H)[d>>2]=n;return 0}catch(q){if("undefined"==typeof FS||"ErrnoError"!==q.name)throw q;return q.B}}Oc.g="iippp";var Rc=(a,b)=>Ve((w(),A).subarray(a,a+b));Rc.g="ipp";p||Vd();
(()=>{var a={kb:Promise.resolve(),canHandle:b=>!h.noWasmDecoding&&b.endsWith(".so"),handle:async(b,c)=>a.kb=a.kb.then(async()=>{try{var d=await Ie(b,{I:!0,pa:!0},c,{})}catch(e){throw Error(`failed to instantiate wasm: ${c}: ${e}`);}de[c]=d;return b})};ce.push(a)})();FS.createPreloadedFile=(a,b,c,d,e,f,g,k,l,m)=>{lf(a,b,c,d,e,k,l,m).then(f).catch(g)};FS.Nc=lf;FS.da=Array(4096);FS.mount(Q,{},"/");FS.mkdir("/tmp");FS.mkdir("/home");FS.mkdir("/home/web_user");
(function(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=>0,write:(d,e,f,g)=>g,llseek:()=>0});FS.mkdev("/dev/null",FS.makedev(1,3));af(FS.makedev(5,0),cf);af(FS.makedev(6,0),df);FS.mkdev("/dev/tty",FS.makedev(5,0));FS.mkdev("/dev/tty1",FS.makedev(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ve(a),b=a.byteLength);return a[--b]};FS.createDevice("/dev","random",c);FS.createDevice("/dev","urandom",c);FS.mkdir("/dev/shm");FS.mkdir("/dev/shm/tmp")})();
(function(){FS.mkdir("/proc");var a=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var b=FS.createNode(a,"fd",16895,73);b.o={llseek:Q.o.llseek};b.m={ia(c,d){c=+d;var e=S(c);c={parent:null,mount:{ib:"fake"},m:{readlink:()=>e.path},id:c+1};return c.parent=c},sa(){return Array.from(FS.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();FS.Ib={MEMFS:Q};
(()=>{let a=cg.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof cg&&c instanceof cg))return!1;var d=this.l.D.s,e=this.l.A;c.l=c.l;var f=c.l.D.s;for(c=c.l.A;d.M;)e=d.ua(e),d=d.M;for(;f.M;)c=f.ua(c),f=f.M;return d===f&&e===c},clone:function(){this.l.A||Vf(this);if(this.l.qa)return this.l.count.value+=1,this;var c=Zf,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.l;c=c(e.call(d,f,{l:{value:{count:g.count,ha:g.ha,qa:g.qa,A:g.A,D:g.D,J:g.J,R:g.R}}}));c.l.count.value+=1;c.l.ha=
!1;return c},["delete"](){this.l.A||Vf(this);if(this.l.ha&&!this.l.qa)throw new W("Object already scheduled for deletion");Yf(this);var c=this.l;--c.count.value;0===c.count.value&&(c.J?c.R.Y(c.J):c.D.s.Y(c.A));this.l.qa||(this.l.J=void 0,this.l.A=void 0)},isDeleted:function(){return!this.l.A},deleteLater:function(){this.l.A||Vf(this);if(this.l.ha&&!this.l.qa)throw new W("Object already scheduled for deletion");$f.push(this);1===$f.length&&bg&&bg(ag);this.l.ha=!0;return this}});const b=Symbol.dispose;
b&&(a[b]=a["delete"])})();
Object.assign(sg.prototype,{Lb(a){this.lb&&(a=this.lb(a));return a},Ya(a){this.Y?.(a)},K:Lf,v:function(a){function b(){return this.za?rg(this.s.ba,{D:this.ic,A:c,R:this,J:a}):rg(this.s.ba,{D:this,A:a})}var c=this.Lb(a);if(!c)return this.Ya(a),null;var d=qg(this.s,c);if(void 0!==d){if(0===d.l.count.value)return d.l.A=c,d.l.J=a,d.clone();d=d.clone();this.Ya(a);return d}d=this.s.Jb(c);d=dg[d];if(!d)return b.call(this);d=this.ya?d.Bb:d.pointerType;var e=og(c,this.s,d.s);return null===e?b.call(this):this.za?
rg(d.s.ba,{D:d,A:e,R:this,J:a}):rg(d.s.ba,{D:d,A:e})}});Kd.push(()=>{lh.VIPS_DISC_THRESHOLD=2147483648;lh.VIPS_MAX_THREADS=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;lh.VIPS_CONCURRENCY=1});
Ra.push(()=>{const a=Object.getOwnPropertyDescriptor(h.SourceCustom.prototype,"onRead");Object.defineProperty(h.SourceCustom.prototype,"onRead",{set(c){return a.set.call(this,d=>mg(c(d)))}});const b=Object.getOwnPropertyDescriptor(h.TargetCustom.prototype,"onWrite");Object.defineProperty(h.TargetCustom.prototype,"onWrite",{set(c){return b.set.call(this,d=>c(Y(d)))}})});Object.assign(cg.prototype,{preventAutoDelete:function(){const a=$f.indexOf(this);-1<a&&$f.splice(a,1);this.l.ha=!1;return this}});
p||(h.wasmMemory?pa=h.wasmMemory:pa=new WebAssembly.Memory({initial:(h.INITIAL_MEMORY||268435456)/65536,maximum:32768,shared:!0}),qa());h.preloadPlugins&&(ce=h.preloadPlugins);h.noExitRuntime&&($d=h.noExitRuntime);h.print&&(ja=h.print);h.printErr&&(t=h.printErr);h.dynamicLibraries&&(ka=h.dynamicLibraries);h.wasmBinary&&(la=h.wasmBinary);h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();
h.ENV=lh;h.addRunDependency=Pd;h.removeRunDependency=Od;h.addFunction=ze;h.FS_preloadFile=lf;h.FS_unlink=(...a)=>FS.unlink(...a);h.FS_createPath=(...a)=>FS.createPath(...a);h.FS_createDevice=(...a)=>FS.createDevice(...a);h.FS=FS;h.FS_createDataFile=(...a)=>FS.createDataFile(...a);h.FS_createLazyFile=(...a)=>FS.createLazyFile(...a);h.setAutoDeleteLater=a=>{Wf=a};h.deletionQueue=$f;h.setDelayFunction=a=>{bg=a;$f.length&&bg&&bg(ag)};
var bh=[Qc,ae,Bf,cb,db,eb,fb,gb,hb,ib,jb,kb,lb,mb,nb,ob,Ub,tc,uc,Hc,Ic,Kc,Lc,Mc,Nc,Oc],Ee={};function oh(a){for(var b=(w(),F)[a+6>>1];13===b&&!(16<(w(),H)[a>>2]);){var c=(w(),H)[a+8>>2],d=(w(),H)[c>>2];if(0===d){b=0;break}else if(0===(w(),H)[(c>>2)+1])a=d,b=(w(),F)[d+6>>1];else break}return[a,b]}
function Pc(a,b,c,d){w();var e=(w(),H)[(a>>2)+1],f=(w(),H)[(a>>2)+6],g=(w(),H)[(a>>2)+2],k=(w(),H)[(a>>2)+5];a=oh((w(),H)[(a>>2)+3])[1];var l=td(),m=l,n=[],q=!1;if(15===a)throw Error("complex ret marshalling nyi");if(0>a||15<a)throw Error("Unexpected rtype "+a);if(4===a||13===a)n.push(c),q=!0;for(var u=0;u<f;u++){var r=(w(),H)[(d>>2)+u],v=oh((w(),H)[(g>>2)+u]),x=v[0];v=v[1];switch(v){case 1:case 10:case 9:n.push((w(),H)[r>>2]);break;case 2:n.push((w(),Ka)[r>>2]);break;case 3:n.push((w(),La)[r>>3]);
break;case 5:n.push((w(),A)[r]);break;case 6:n.push((w(),y)[r]);break;case 7:n.push((w(),F)[r>>1]);break;case 8:n.push((w(),z)[r>>1]);break;case 11:case 12:n.push((w(),Ma)[r>>3]);break;case 4:n.push((w(),Ma)[r>>3]);n.push((w(),Ma)[(r>>3)+1]);break;case 13:v=(w(),H)[x>>2];x=(w(),F)[x+4>>1];m-=v;m&=~(x-1);(w(),y).subarray(m,m+v).set((w(),y).subarray(r,r+v));n.push(m);break;case 14:n.push((w(),H)[r>>2]);break;case 15:throw Error("complex marshalling nyi");default:throw Error("Unexpected type "+v);}}if(k&
1){k=[];for(u=e-1;u>=f;u--)switch(r=(w(),H)[(d>>2)+u],v=oh((w(),H)[(g>>2)+u]),x=v[0],v=v[1],v){case 5:case 6:--m;m&=-1;(w(),A)[m]=(w(),A)[r];break;case 7:case 8:m-=2;m&=-2;(w(),F)[m>>1]=(w(),F)[r>>1];break;case 1:case 9:case 10:case 2:m-=4;m&=-4;(w(),H)[m>>2]=(w(),H)[r>>2];break;case 3:case 11:case 12:m-=8;m&=-8;(w(),H)[m>>2]=(w(),H)[r>>2];(w(),H)[(m>>2)+1]=(w(),H)[(r>>2)+1];break;case 4:m-=16;m&=-8;(w(),H)[m>>2]=(w(),H)[r>>2];(w(),H)[(m>>2)+1]=(w(),H)[(r>>2)+1];(w(),H)[(m>>2)+2]=(w(),H)[(r>>2)+2];
(w(),H)[(m>>2)+3]=(w(),H)[(r>>2)+3];break;case 13:m-=4;m&=-4;k.push([m,r,(w(),H)[x>>2],(w(),F)[x+4>>1]]);break;case 14:m-=4;m&=-4;(w(),H)[m>>2]=(w(),H)[r>>2];break;case 15:throw Error("complex arg marshalling nyi");default:throw Error("Unexpected argtype "+v);}n.push(m);for(u=0;u<k.length;u++)e=k[u],d=e[0],r=e[1],v=e[2],x=e[3],m-=v,m&=~(x-1),(w(),y).subarray(m,m+v).set((w(),y).subarray(r,r+v)),(w(),H)[d>>2]=m}rd(m);sd(0);b=M.get(b).apply(null,n);rd(l);if(!q)switch(a){case 0:break;case 1:case 9:case 10:(w(),
H)[c>>2]=b;break;case 2:(w(),Ka)[c>>2]=b;break;case 3:(w(),La)[c>>3]=b;break;case 5:case 6:(w(),A)[c+0]=b;break;case 7:case 8:(w(),F)[c>>1]=b;break;case 11:case 12:(w(),Ma)[c>>3]=b;break;case 14:(w(),H)[c>>2]=b;break;case 15:throw Error("complex ret marshalling nyi");default:throw Error("Unexpected rtype "+a);}}Pc.g="viiii";var Wc,Xc,L,Yc,Zc,$c,Da,ad,bd,cd,dd,ed,fd,gd,hd,Aa,jd,Ga,kd,ld,md,nd,od,pd,Sa,qd,rd,sd,td,ud,vd,wd,xd,M,K;
function ph(a=[]){var b=De("main").Ta;if(b){a.unshift(da);var c=a.length,d=sd(4*(c+1)),e=d,f;for(f of a)(w(),H)[e>>2]=Te(f),e+=4;(w(),H)[e>>2]=0;try{var g=b(c,d);Jc(g,!0)}catch(k){Cd(k)}}}
function ya(a=ca){function b(){h.calledRun=!0;if(!na&&(Oa(),ra?.(h),h.onRuntimeInitialized?.(),h.noInitialRun||ph(a),!p)){if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();ke.push(c)}Pa(ke)}}if(0<Md)Nd=ya;else if(p)ra?.(h),Oa();else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Kd.push(h.preRun.shift());Pa(Kd);0<Md?Nd=ya:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),
1);b()},1)):b()}}var Qa;p||(Qa=await (xa()),ya());Ha?moduleRtn=h:moduleRtn=new Promise((a,b)=>{ra=a;sa=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=Vips;module.exports.default=Vips}else if(typeof define==="function"&&define["amd"])define([],()=>Vips);var isPthread=globalThis.name=="em-pthread";isPthread&&Vips();
