var Vips=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var n=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,r=ba&&"em-pthread"==globalThis.name;n.dynamicLibraries=n.dynamicLibraries||["vips-jxl.wasm","vips-heif.wasm"];n.workaroundCors&&(n.mainScriptUrlOrBlob=n.mainScriptUrlOrBlob||URL.createObjectURL(new Blob([`importScripts('${_scriptName}');`],{type:"application/javascript"})));var ca=[],da="./this.program";ba&&(_scriptName=self.location.href);var ea="";function fa(a){return n.locateFile?n.locateFile(a,ea):ea+a}var ha,ia;
if(aa||ba){try{ea=(new URL(".",_scriptName)).href}catch{}ba&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ha=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var ja=console.log.bind(console),w=console.error.bind(console),ka=[],la,ma,na=!1,oa,pa,qa,ra={},sa;
if(r){var ta=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.V;if("load"===d){let e=[];self.onmessage=f=>e.push(f);sa=()=>{postMessage({V:"loaded"});for(let f of e)a(f);self.onmessage=a};ka=c.Gb;ra=c.pc;for(const f of c.Sb)if(!n[f]||n[f].proxy)n[f]=(...g)=>{postMessage({V:"callHandler",Rb:f,Ab:g})},"print"==f&&(ja=n[f]),"printErr"==f&&(w=n[f]);va=c.vc;wa();ma=c.wc;xa();ya()}else if("run"===d){za(c.X);Aa(c.X,0,0,1,0,0);Ba();Ca(c.X);ta||(Da(),ta=!0);try{Ea(c.sc,
c.Ea)}catch(e){if("unwind"!=e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?ta&&Fa():d&&(w(`worker: received unknown command ${d}`),w(c)))}catch(e){throw Ga(),e;}}self.onmessage=a}var Ha=!1,Ja=!1;function wa(){var a=va.buffer;x=new Int8Array(a);y=new Int16Array(a);A=new Uint8Array(a);E=new Uint16Array(a);F=new Int32Array(a);G=new Uint32Array(a);Ka=new Float32Array(a);La=new Float64Array(a);H=new BigInt64Array(a);Ma=new BigUint64Array(a)}var Na=[];
function Oa(){Ha=!0;r?sa():(Pa(Na),n.noFSInit||FS.Ia||FS.init(),Qa.__wasm_call_ctors(),Pa(Ra),FS.fb=!1)}function I(a){n.onAbort?.(a);a=`Aborted(${a})`;w(a);na=!0;a+=". Build with -sASSERTIONS for more info.";Ha&&Sa();a=new WebAssembly.RuntimeError(a);qa?.(a);throw a;}var Ta;async function Ua(a){if(!la)try{var b=await ha(a);return new Uint8Array(b)}catch{}if(a==Ta&&la)a=new Uint8Array(la);else if(ia)a=ia(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Va(a,b){try{var c=await Ua(a);return await WebAssembly.instantiate(c,b)}catch(d){w(`failed to asynchronously prepare wasm: ${d}`),I(d)}}async function Wa(a){var b=Ta;if(!la)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){w(`wasm streaming compile failed: ${d}`),w("falling back to ArrayBuffer instantiation")}return Va(b,a)}
function Xa(){J={__assert_fail:Ya,__call_sighandler:Za,__lsan_ignore_object:ab,__pthread_create_js:bb,__syscall_dup:cb,__syscall_faccessat:db,__syscall_fcntl64:eb,__syscall_fstat64:fb,__syscall_ftruncate64:gb,__syscall_getcwd:hb,__syscall_ioctl:ib,__syscall_lstat64:jb,__syscall_newfstatat:kb,__syscall_openat:lb,__syscall_poll:mb,__syscall_rmdir:nb,__syscall_stat64:ob,__syscall_unlinkat:pb,__throw_exception_with_stack_trace:qb,_abort_js:rb,_dlopen_js:sb,_dlsym_catchup_js:tb,_dlsym_js:ub,_embind_finalize_value_object:vb,
_embind_register_arithmetic_vector:yb,_embind_register_bigint:zb,_embind_register_bool:Ab,_embind_register_class:Bb,_embind_register_class_class_function:Cb,_embind_register_class_constructor:Db,_embind_register_class_function:Eb,_embind_register_class_property:Fb,_embind_register_emval:Gb,_embind_register_enum:Hb,_embind_register_enum_value:Ib,_embind_register_float:Jb,_embind_register_function:Kb,_embind_register_integer:Lb,_embind_register_iterable:Mb,_embind_register_memory_view:Nb,_embind_register_optional:Ob,
_embind_register_std_string:Pb,_embind_register_std_wstring:Qb,_embind_register_value_object:Rb,_embind_register_value_object_field:Sb,_embind_register_void:Tb,_emscripten_dlopen_js:Ub,_emscripten_dlsync_threads:Vb,_emscripten_get_dynamic_libraries_js:Wb,_emscripten_init_main_thread_js:Xb,_emscripten_notify_mailbox_postmessage:Yb,_emscripten_receive_on_main_thread_js:Zb,_emscripten_runtime_keepalive_clear:$b,_emscripten_thread_cleanup:ac,_emscripten_thread_exit_joinable:bc,_emscripten_thread_mailbox_await:Ca,
_emscripten_thread_set_strongref:cc,_emval_array_to_memory_view:dc,_emval_create_invoker:ec,_emval_decref:fc,_emval_get_global:gc,_emval_get_module_property:hc,_emval_get_property:ic,_emval_incref:jc,_emval_instanceof:kc,_emval_invoke:lc,_emval_is_number:mc,_emval_is_string:nc,_emval_new_cstring:oc,_emval_run_destructors:pc,_emval_set_property:qc,_emval_typeof:rc,_gmtime_js:sc,_localtime_js:tc,_mmap_js:uc,_munmap_js:vc,_tzset_js:wc,clock_time_get:xc,emscripten_check_blocking_allowed:yc,emscripten_date_now:zc,
emscripten_err:Ac,emscripten_exit_with_live_runtime:Bc,emscripten_get_heap_max:Cc,emscripten_get_now:Dc,emscripten_num_logical_cores:Ec,emscripten_promise_destroy:Fc,emscripten_promise_resolve:Gc,emscripten_resize_heap:Hc,environ_get:Ic,environ_sizes_get:Jc,exit:Kc,fd_close:Lc,fd_fdstat_get:Mc,fd_read:Nc,fd_seek:Oc,fd_write:Pc,ffi_call_js:Qc,heif_error_success:Rc,memory:va,proc_exit:Sc,random_get:Tc};var a=new Proxy(new Set(["__lsan_ignore_object"]),Uc);return{env:J,wasi_snapshot_preview1:J,"GOT.mem":a,
"GOT.func":a}}
async function xa(){function a(d,e){var f=Qa=d.exports;Vc(Qa);var g=Wc(e);Xc(Qa._emscripten_tls_init,d.exports,g);d=Qa;Yc=d.pthread_self;Zc=d.malloc;n._main=d.main;K=d.free;$c=d.fflush;ad=d.calloc;n.__ZnamSt11align_val_t=d._ZnamSt11align_val_t;bd=d.__getTypeName;Da=d._embind_initialize_bindings;n._emscripten_builtin_free=d.emscripten_builtin_free;cd=d.emscripten_builtin_memalign;n._emscripten_builtin_malloc=d.emscripten_builtin_malloc;dd=d.__funcs_on_exit;n.___libc_calloc=d.__libc_calloc;n.___libc_free=
d.__libc_free;n.___libc_malloc=d.__libc_malloc;ed=d.__dl_seterr;fd=d._emscripten_dlsync_self_async;gd=d._emscripten_dlsync_self;hd=d._emscripten_proxy_dlsync_async;jd=d._emscripten_proxy_dlsync;kd=d._emscripten_find_dylib;Aa=d._emscripten_thread_init;ld=d.__set_thread_state;Ga=d._emscripten_thread_crashed;md=d._emscripten_run_js_on_main_thread_done;nd=d._emscripten_run_js_on_main_thread;od=d._emscripten_thread_free_data;pd=d._emscripten_thread_exit;n._strndup=d.strndup;qd=d._emscripten_check_mailbox;
n.__ZdaPvm=d._ZdaPvm;n.___libc_realloc=d.__libc_realloc;n._emscripten_builtin_calloc=d.emscripten_builtin_calloc;n._emscripten_builtin_realloc=d.emscripten_builtin_realloc;n._malloc_size=d.malloc_size;n._malloc_usable_size=d.malloc_usable_size;n._reallocf=d.reallocf;rd=d.emscripten_get_sbrk_ptr;Sa=d.__trap;sd=d.emscripten_stack_set_limits;td=d._emscripten_stack_restore;ud=d._emscripten_stack_alloc;vd=d.emscripten_stack_get_current;wd=d.__thrown_object_from_unwind_exception;xd=d.__get_exception_message;
M=d.__indirect_function_table;yd=d.__cpp_exception;zd=d.__heap_base.value;Ad(f);Bd("__main__",0,J);Cd();ma=e;return Qa}var b=Xa();if(n.instantiateWasm)return new Promise(d=>{n.instantiateWasm(b,(e,f)=>{d(a(e,f))})});if(r){var c=new WebAssembly.Instance(ma,Xa());return a(c,ma)}Ta??=fa("vips.wasm");return function(d){return a(d.instance,d.module)}(await Wa(b))}var Ed=a=>{if(!(a instanceof Dd||"unwind"==a))throw a;};
class Dd{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var N=0,Fd=a=>{a.terminate();a.onmessage=()=>{}},Ld=a=>{var b=Gd[a];Hd.delete(a);a in Id&&Id[a].resolve();a=b.X;delete Gd[a];Jd.push(b);Kd.splice(Kd.indexOf(b),1);b.X=0;od(a)},Pa=a=>{for(;0<a.length;)a.shift()(n)},Md=[],Nd=a=>{Hd.add(a);a in Id&&Id[a].resolve()},Od=0,Pd=null,Qd=()=>{Od--;n.monitorRunDependencies?.(Od);if(0==Od&&Pd){var a=Pd;Pd=null;a()}},Rd=()=>{Od++;n.monitorRunDependencies?.(Od)},Ud=a=>{0==Jd.length&&(Sd(),Td(Jd[0]));var b=Jd.pop();if(!b)return 6;Kd.push(b);Gd[a.X]=b;b.X=a.X;b.postMessage({V:"run",
sc:a.rc,Ea:a.Ea,X:a.X},a.tb);return 0},Vd=!Atomics.waitAsync||globalThis.navigator?.userAgent&&91>Number((navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./)||[])[2]),Jd=[],Kd=[],Wd=[],Gd={};function Xd(){for(var a=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;a--;)Sd();Md.push(async()=>{var b=Yd();Rd("loading-workers");await b;Qd("loading-workers")});Id={};Hd=new Set}var Zd=()=>{for(var a of Kd)Fd(a);for(a of Jd)Fd(a);Jd=[];Kd=[];Gd={}};function Ba(){Wd.forEach(a=>a())}
var Td=a=>new Promise(b=>{a.onmessage=f=>{var g=f.data;f=g.V;if(g.Da&&g.Da!=Yc()){var h=Gd[g.Da];h?h.postMessage(g,g.tb):w(`worker sent message (${f}) to pthread (${g.Da}) that no longer exists`)}else if("checkMailbox"===f)Fa();else if("spawnThread"===f)Ud(g);else if("cleanupThread"===f)$d(()=>Ld(g.Ua));else if("markAsFinished"===f)Nd(g.Ua);else if("loaded"===f)a.loaded=!0,b(a);else if("setimmediate"===g.target)a.postMessage(g);else if("callHandler"===f)n[g.Rb](...g.Ab);else f&&w(`worker sent an unknown command ${f}`)};
a.onerror=f=>{w(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)n.propertyIsEnumerable(e)&&c.push(e);a.postMessage({V:"load",Sb:c,vc:va,wc:ma,Gb:ka,pc:ra})});async function Yd(){if(!r)return Promise.all(Jd.map(Td))}function Sd(){var a=_scriptName;n.mainScriptUrlOrBlob&&(a=n.mainScriptUrlOrBlob,"string"!=typeof a&&(a=URL.createObjectURL(a)));a=new Worker(a,{name:"em-pthread"});Jd.push(a)}
var Hd,Id,ae,O=(a,b,...c)=>{var d=16*c.length,e=vd(),f=ud(d),g=f>>3,h;for(h of c)"bigint"==typeof h?(H[g++]=1n,H[g++]=h):(H[g++]=0n,La[g++]=h);a=nd(a,0,d,f,b);td(e);return a};function Sc(a){if(r)return O(0,1,a);oa=a;be||0<N||(Zd(),n.onExit?.(a),na=!0);throw new Dd(a);}Sc.g="vi";function ce(a){if(r)return O(1,0,a);Kc(a)}var Kc=a=>{oa=a;if(r)throw ce(a),"unwind";if(!(be||0<N||r)){dd();FS.Ia=!1;$c(0);for(var b of FS.streams)b&&FS.close(b);Zd();b=Yc();ld(0,0,0,1);Vd||Atomics.notify(F,b>>2);Ja=!0}Sc(a)};
Kc.g="vi";var $d=a=>{if(!Ja&&!na)try{a()}catch(b){Ed(b)}finally{if(!(Ja||be||0<N))try{r?Yc()&&pd(oa):Kc(oa)}catch(b){Ed(b)}}},de=a=>{N+=1;setTimeout(()=>{--N;$d(a)},1E4)},ee=[],fe={},ge=!1;
function he(){function a(){ge=document.pointerLockElement===n.canvas}if(!ie){ie=!0;ee.push({canHandle:c=>!n.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c),handle:async(c,d)=>{var e=new Blob([c],{type:je(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:je(d)}));var f=URL.createObjectURL(e);return new Promise((g,h)=>{var k=new Image;k.onload=()=>{var l=document.createElement("canvas");l.width=k.width;l.height=k.height;l.getContext("2d").drawImage(k,0,0);URL.revokeObjectURL(f);
g(c)};k.onerror=()=>{w(`Image ${f} could not be decoded`);h()};k.src=f})}});ee.push({canHandle:c=>!n.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(c,d)=>new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,h=URL.createObjectURL(new Blob([c],{type:je(d)})),k=new Audio;k.addEventListener("canplaythrough",()=>f(k),!1);k.onerror=()=>{if(!g){w(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);for(var l="",m=0,q=0,t=0;t<c.length;t++)for(m=m<<
8|c[t],q+=8;6<=q;){var p=m>>q-6&63;q-=6;l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[p]}2==q?(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(m&3)<<4],l+="=="):4==q&&(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(m&15)<<2],l+="=");k.src="data:audio/x-"+d.slice(-3)+";base64,"+l;f(k)}};k.src=h;de(()=>{f(k)})})});var b=n.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),n.elementPointerLock&&b.addEventListener("click",
c=>{!ge&&n.canvas.requestPointerLock&&(n.canvas.requestPointerLock(),c.preventDefault())},!1))}}function je(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}var ke={},ie,le={},Uc={get(a,b){var c=le[b];c||=le[b]=new WebAssembly.Global({value:"i32",mutable:!0},-1);a.has(b)||(c.required=!0);return c}},y,F,H,x,Ka,La,E,G,Ma,A,me=[];function za(a){var b=G[a+48>>2];sd(b,b-G[a+52>>2]);td(b)}
var ne=new TextDecoder,oe=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},pe=(a,b=0,c)=>{c=oe(a,b,c);return ne.decode(a.buffer?a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c):new Uint8Array(a.slice(b,c)))},Wc=a=>{function b(){for(var q=0,t=1;;){var p=a[f++];q+=(p&127)*t;t*=128;if(!(p&128))break}return q}function c(){var q=b();f+=q;return pe(a,f-q,q)}function d(){for(var q=b(),t=[];q--;)t.push(c());return t}function e(q,t){if(q)throw Error(t);}var f=0,g=0;if(a instanceof
WebAssembly.Module)g=WebAssembly.Module.customSections(a,"dylink.0"),e(0===g.length,"need dylink section"),a=new Uint8Array(g[0]),g=a.length;else{g=1836278016==(new Uint32Array((new Uint8Array(a.subarray(0,24))).buffer))[0];e(!g,"need to see wasm magic number");e(0!==a[8],"need the dylink section to be first");f=9;g=b();g=f+g;var h=c();e("dylink.0"!==h)}for(h={Oa:[],sb:new Set,vb:new Set,pb:[]};f<g;){var k=a[f++],l=b();if(1===k)h.Na=b(),h.$b=b(),h.ta=b(),h.Qc=b();else if(2===k)h.Oa=d();else if(3===
k)for(k=b();k--;){l=c();var m=b();m&256&&h.sb.add(l)}else if(4===k)for(k=b();k--;)c(),l=c(),m=b(),1==(m&3)&&h.vb.add(l);else 5===k?h.pb=d():f+=l}return h},Ea=(a,b)=>{be=N=0;gd();a=M.get(a)(b);be||0<N?oa=a:pd(a)},Bd=(a,b,c)=>{c={Aa:Infinity,name:a,exports:c,global:!0};qe[a]=c;void 0!=b&&(re[b]=c);return c},qe={},re={},se=(a,b)=>Math.ceil(a/b)*b,te=a=>{if(Ha)return ad(a,1);var b=zd;zd=a=b+16*Math.ceil(a/16);if(!r){var c=rd();G[c>>2]=a}return b},ve=(a,b)=>{if(ue)for(var c=a;c<a+b;c++){var d=M.get(c);
d&&ue.set(d,c)}},ue,we=a=>{ue||(ue=new WeakMap,ve(0,M.length));return ue.get(a)||0},xe=[],ye=a=>{const b=a.length;return[b%128|128,b>>7,...a]},ze={i:127,p:127,j:126,f:125,d:124,e:111},Ae=a=>ye(Array.from(a,b=>ze[b])),Be=(a,b)=>{var c=we(a);if(c)return c;c=xe.length?xe.pop():M.grow(1);try{M.set(c,a)}catch(d){if(!(d instanceof TypeError))throw d;b=Uint8Array.of(0,97,115,109,1,0,0,0,1,...ye([1,96,...Ae(b.slice(1)),...Ae("v"===b[0]?"":b[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(b);
b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f;M.set(c,b)}ue.set(a,c);return c},Ad=(a,b)=>{for(var c in a){var d=c;if(!"memory __memory_base __table_base __stack_pointer __indirect_function_table __cpp_exception __c_longjmp __wasm_apply_data_relocs __dso_handle __tls_size __tls_align __set_stack_limits _emscripten_tls_init __wasm_init_tls __wasm_call_ctors __start_em_asm __stop_em_asm __start_em_js __stop_em_js".split(" ").includes(d)&&!d.startsWith("__em_js__")){d=a[c];var e=le[c]&&-1!=le[c].value;
if(b||!e){if("function"==typeof d)d=Be(d);else if("number"!=typeof d.value)continue;let f;le[f=c]??(le[f]=new WebAssembly.Global({value:"i32",mutable:!0}));le[c].value=d}}}},Ce=(a,b=0)=>{var c={},d;for(d in a){var e=d;var f=a[d];a:{if(f instanceof WebAssembly.Global)try{f.value=f.value}catch{var g=!0;break a}g=!1}f=g?new WebAssembly.Global({value:"i32"},f.value+b):f;c[e]=f}return c},De=a=>{a=J[a];return!a||a.Ba?!1:!0},Ee=(a,b)=>Object.defineProperty(b,"name",{value:a}),Fe=a=>{var b;De(a)&&(b=J[a]);
return{Ta:b,name:a}},Ra=[],P=(a,b,c)=>a?ne.decode(A.slice(a,oe(A,a,b,c))):"",Ke=(a,b,c,d,e)=>{function f(){function k(C,z){function B(ua,Y){ua=[];for(var wb=0;;wb++){var $a="$"+wb;if(!Y.includes($a))break;ua.push($a)}ua=ua.join(",");Ge[D]=eval(`(${ua}) => { ${Y} };`)}function L(ua,Y,wb){var $a=[];Y=Y.slice(1,-1);if("void"!=Y){Y=Y.split(",");for(var yg of Y)Y=yg.split(" ").pop(),$a.push(Y.replaceAll("*",""))}p[ua]=eval(`(${$a}) => ${wb};`)}!r&&c&&(ra[c]=C);ve(t,g.ta);p=Ce(z.exports,q);Ad(p);b.zb||
He();if("__start_em_asm"in p){var D=p.__start_em_asm.value;for(C=p.__stop_em_asm.value;D<C;){var Ia=P(D);B(D,Ia);D=A.indexOf(0,D)+1}}for(var xb in p)if(xb.startsWith("__em_js__")){D=p[xb].value;Ia=P(D);var [zg,Ag]=Ia.split("<::>");L(xb.replace("__em_js__",""),zg,Ag);delete p[xb]}Xc(p._emscripten_tls_init,z.exports,g);l&&((z=p.__wasm_apply_data_relocs)&&(Ha?z():Na.push(z)),(z=p.__wasm_call_ctors)&&(Ha?z():Ra.push(z)));return p}var l=!e||!x[e+8];if(l){var m=Math.pow(2,g.$b),q=g.Na?se(te(g.Na+m),m):
0,t=g.ta?M.length:0;e&&(x[e+8]=1,G[e+12>>2]=q,F[e+16>>2]=g.Na,G[e+20>>2]=t,F[e+24>>2]=g.ta)}else q=G[e+12>>2],t=G[e+20>>2];g.ta&&M.grow(g.ta);var p;m=new Proxy({},{get(C,z){switch(z){case "__memory_base":return q;case "__table_base":return t}if(z in J&&!J[z].Ba)return J[z];if(!(z in C)){var B;C[z]=(...L)=>{if(!B){var D=Fe(z).Ta;!D&&d&&(D=d[z]);D||=p[z];B=D}return B(...L)}}return C[z]}});var u=new Proxy(g.vb,Uc),v={"GOT.mem":u,"GOT.func":u,env:m,wasi_snapshot_preview1:m};if(b.I)return(async()=>{var C;
a instanceof WebAssembly.Module?C=new WebAssembly.Instance(a,v):{module:a,instance:C}=await WebAssembly.instantiate(a,v);return k(a,C)})();m=a instanceof WebAssembly.Module?a:new WebAssembly.Module(a);u=new WebAssembly.Instance(m,v);return k(m,u)}var g=Wc(a);b={...b,Sa:{ec:c,ic:g.pb}};if(b.I)return g.Oa.reduce((k,l)=>k.then(()=>{l=Ie(l,b.Sa)??l;return Je(l,b,d)}),Promise.resolve()).then(f);for(var h of g.Oa)h=Ie(h,b.Sa)??h,Je(h,b,d);return f()},Vc=a=>{var b,c;for([b,c]of Object.entries(a))De(b)||
(J[b]=c)},Le=async a=>{a=await ha(a);return new Uint8Array(a)},Me=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ne=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Me(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Oe=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";
b&&=b.slice(0,-1);return a+b},Pe=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Qe=(a,b)=>Ne(a+"/"+b),Re=a=>{var b=vd();a=a();td(b);return a},Se=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Q=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=
224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Te=a=>{var b=Se(a)+1,c=ud(b);Q(a,A,c,b);return c},Ue=()=>a=>(a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),0),Ve=a=>(Ve=Ue())(a),We=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:FS.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===
c.charAt(0)}b=Me(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Xe=(a,b)=>{function c(g){for(var h=0;h<g.length&&""===g[h];h++);for(var k=g.length-1;0<=k&&""===g[k];k--);return h>k?[]:g.slice(h,k-h+1)}a=We(a).slice(1);b=We(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Ye=[],Ze=a=>{var b=Array(Se(a)+1);a=Q(a,b,0,b.length);
b.length=a;return b},$e=[];function af(a,b){$e[a]={input:[],output:[],ea:b};FS.registerDevice(a,bf)}
var bf={open(a){var b=$e[a.node.ra];if(!b)throw new FS.h(43);a.C=b;a.seekable=!1},close(a){a.C.ea.xa(a.C)},xa(a){a.C.ea.xa(a.C)},read(a,b,c,d){if(!a.C||!a.C.ea.eb)throw new FS.h(60);for(var e=0,f=0;f<d;f++){try{var g=a.C.ea.eb(a.C)}catch(h){throw new FS.h(29);}if(void 0===g&&0===e)throw new FS.h(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.$=Date.now());return e},write(a,b,c,d){if(!a.C||!a.C.ea.Qa)throw new FS.h(60);try{for(var e=0;e<d;e++)a.C.ea.Qa(a.C,b[c+e])}catch(f){throw new FS.h(29);
}d&&(a.node.O=a.node.N=Date.now());return e}},cf={eb(){a:{if(!Ye.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ye=Ze(a)}a=Ye.shift()}return a},Qa(a,b){null===b||10===b?(ja(pe(a.output)),a.output=[]):0!=b&&a.output.push(b)},xa(a){0<a.output?.length&&(ja(pe(a.output)),a.output=[])},Vb(){return{Cc:25856,Ec:5,Bc:191,Dc:35387,Ac:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Wb(){return 0},Xb(){return[24,
80]}},df={Qa(a,b){null===b||10===b?(w(pe(a.output)),a.output=[]):0!=b&&a.output.push(b)},xa(a){0<a.output?.length&&(w(pe(a.output)),a.output=[])}},ef=a=>{a=65536*Math.ceil(a/65536);var b=cd(65536,a);b&&A.fill(0,b,b+a);return b},R={W:null,mount(){return R.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=FS.isBlkdev(c))||(e=4096===(c&61440));if(e)throw new FS.h(63);R.W||(R.W={dir:{node:{S:R.m.S,U:R.m.U,ia:R.m.ia,ca:R.m.ca,rename:R.m.rename,unlink:R.m.unlink,rmdir:R.m.rmdir,sa:R.m.sa,symlink:R.m.symlink},
stream:{llseek:R.o.llseek}},file:{node:{S:R.m.S,U:R.m.U},stream:{llseek:R.o.llseek,read:R.o.read,write:R.o.write,ja:R.o.ja,la:R.o.la}},link:{node:{S:R.m.S,U:R.m.U,readlink:R.m.readlink},stream:{}},Wa:{node:{S:R.m.S,U:R.m.U},stream:FS.Cb}});c=FS.createNode(a,b,c,d);FS.isDir(c.mode)?(c.m=R.W.dir.node,c.o=R.W.dir.stream,c.u={}):FS.isFile(c.mode)?(c.m=R.W.file.node,c.o=R.W.file.stream,c.L=0,c.u=R.Hb??(R.Hb=new Uint8Array(0))):FS.isLink(c.mode)?(c.m=R.W.link.node,c.o=R.W.link.stream):FS.isChrdev(c.mode)&&
(c.m=R.W.Wa.node,c.o=R.W.Wa.stream);c.$=c.O=c.N=Date.now();a&&(a.u[b]=c,a.$=a.O=a.N=c.$);return c},m:{S(a){var b={};b.Eb=FS.isChrdev(a.mode)?a.id:1;b.Ub=a.id;b.mode=a.mode;b.ac=1;b.uid=0;b.Qb=0;b.ra=a.ra;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.L:FS.isLink(a.mode)?b.size=a.link.length:b.size=0;b.$=new Date(a.$);b.O=new Date(a.O);b.N=new Date(a.N);b.Bb=4096;b.Va=Math.ceil(b.size/b.Bb);return b},U(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&
(b=b.size,a.L!=b&&(c=a.u,a.u=new Uint8Array(b),a.u.set(c.subarray(0,Math.min(b,a.L))),a.L=b))},ia(){R.Fa||(R.Fa=new FS.h(44),R.Fa.stack="<generic error, no stack>");throw R.Fa;},ca(a,b,c,d){return R.createNode(a,b,c,d)},rename(a,b,c){try{var d=ff(b,c)}catch(f){}if(d){if(FS.isDir(a.mode))for(var e in d.u)throw new FS.h(55);gf(d)}delete a.parent.u[a.name];b.u[c]=a;a.name=c;b.N=b.O=a.parent.N=a.parent.O=Date.now()},unlink(a,b){delete a.u[b];a.N=a.O=Date.now()},rmdir(a,b){var c=ff(a,b),d;for(d in c.u)throw new FS.h(55);
delete a.u[b];a.N=a.O=Date.now()},sa(a){return[".","..",...Object.keys(a.u)]},symlink(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(!FS.isLink(a.mode))throw new FS.h(28);return a.link}},o:{read(a,b,c,d,e){if(e>=a.node.L)return 0;d=Math.min(a.node.L-e,d);b.set(a.node.u.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.O=a.N=Date.now();if(f)a.u=b.subarray(c,c+d),a.L=d;else if(0===a.L&&0===e)a.u=b.slice(c,c+d),a.L=d;else{f=e+d;var g=a.u.length;g>=f||(f=
Math.max(f,g*(1048576>g?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.u.subarray(0,a.L),a.u=new Uint8Array(f),a.u.set(g));a.u.set(b.subarray(c,c+d),e);a.L=Math.max(a.L,e+d)}return d},llseek(a,b,c){1===c?b+=a.position:2===c&&FS.isFile(a.node.mode)&&(b+=a.node.L);if(0>b)throw new FS.h(28);return b},ja(a,b,c,d,e){if(!FS.isFile(a.node.mode))throw new FS.h(43);a=a.node.u;if(e&2||a.buffer!==x.buffer){d=!0;e=ef(b);if(!e)throw new FS.h(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);x.set(a,e)}}else d=!1,e=a.byteOffset;return{A:e,fa:d}},la(a,b,c,d){R.o.write(a,b,0,d,c,!1);return 0}}},hf=a=>{"string"==typeof a&&(a=Ze(a));a.subarray||(a=new Uint8Array(a));return a},jf=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},kf=async(a,b)=>{"undefined"!=typeof ke&&he();for(var c of ee)if(c.canHandle(b))return c.handle(a,b);return a},lf=async(a,b,c,d,e,f,g,h)=>{var k=b?We(Ne(a+"/"+b)):a,l=`cp ${k}`;Rd(l);try{var m=c;"string"==typeof c&&(m=await Le(c));m=await kf(m,k);h?.();f||FS.createDataFile(a,
b,m,d,e,g)}finally{Qd(l)}};function ff(a,b){var c=FS.isDir(a.mode)?(c=mf(a,"x"))?c:a.m.ia?0:2:54;if(c)throw new FS.h(c);for(c=FS.da[nf(a.id,b)];c;c=c.ka){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return FS.ia(a,b)}function gf(a){var b=nf(a.parent.id,a.name);if(FS.da[b]===a)FS.da[b]=a.ka;else for(b=FS.da[b];b;){if(b.ka===a){b.ka=a.ka;break}b=b.ka}}function nf(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%FS.da.length}
function of(a){var b=nf(a.parent.id,a.name);a.ka=FS.da[b];FS.da[b]=a}function mf(a,b){return FS.fb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function pf(a,b){if(!FS.isDir(a.mode))return 54;try{return ff(a,b),20}catch(c){}return mf(a,"wx")}
function qf(a,b,c){try{var d=ff(a,b)}catch(e){return e.B}if(a=mf(a,"wx"))return a;if(c){if(!FS.isDir(d.mode))return 54;if(FS.na(d)||FS.getPath(d)===FS.cwd())return 10}else if(FS.isDir(d.mode))return 31;return 0}function rf(a,b){if(!a)throw new FS.h(b);return a}function S(a){a=FS.cb(a);if(!a)throw new FS.h(8);return a}function sf(a,b=-1){a=Object.assign(new FS.xb,a);if(-1==b)a:{for(b=0;b<=FS.yb;b++)if(!FS.streams[b])break a;throw new FS.h(33);}a.aa=b;return FS.streams[b]=a}
function tf(a,b=-1){a=sf(a,b);a.o?.Gc?.(a);return a}function uf(a,b,c){var d=a?.o.U;a=d?a:b;d??=b.m.U;rf(d,63);try{d(a,c)}catch(e){if(e instanceof RangeError)throw new FS.h(22);throw e;}}function vf(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.oa)}return b}function wf(a){var b={zc:4096,Jc:4096,Va:1E6,yc:5E5,xc:5E5,files:FS.Pa,Hc:FS.Pa-1,Kc:42,flags:2,Nc:255};a.m.rb&&Object.assign(b,a.m.rb(a.mount.cc.root));return b}
function xf(a,b,c,d){uf(a,b,{mode:c&4095|b.mode&-4096,N:Date.now(),$a:d})}function yf(a,b,c){if(FS.isDir(b.mode))throw new FS.h(31);if(!FS.isFile(b.mode))throw new FS.h(28);var d=mf(b,"w");if(d)throw new FS.h(d);uf(a,b,{size:c,timestamp:Date.now()})}function zf(a,b,c,d){a="string"==typeof a?a:FS.getPath(a);b=Ne(a+"/"+b);return FS.create(b,jf(c,d))}
function Af(a){if(!(a.Yb||a.Zb||a.link||a.u))if(globalThis.XMLHttpRequest)I("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.u=ia(a.url)}catch(b){throw new FS.h(29);}}
var FS={root:null,oa:[],Za:{},streams:[],Pa:1,da:null,Xa:"/",Ia:!1,fb:!0,Kb:null,Ca:0,h:class{name="ErrnoError";constructor(a){this.B=a}},xb:class{P={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.P.flags}set flags(a){this.P.flags=a}get position(){return this.P.position}set position(a){this.P.position=a}},wb:class{m={};o={};T=null;constructor(a,b,c,d){a||=this;this.parent=a;this.mount=a.mount;this.id=FS.Pa++;this.name=b;this.mode=c;this.ra=d;this.$=this.O=
this.N=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Zb(){return FS.isDir(this.mode)}get Yb(){return FS.isChrdev(this.mode)}},lookupPath(a,b={}){if(!a)throw new FS.h(44);b.wa??(b.wa=!0);"/"===a.charAt(0)||(a=FS.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(h=>!!h);for(var d=FS.root,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;
if("."!==a[f])if(".."===a[f])if(e=Oe(e),FS.na(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Ne(e+"/"+a[f]);try{d=ff(d,a[f])}catch(h){if(44===h?.B&&g&&b.bc)return{path:e};throw h;}!d.T||g&&!b.wa||(d=d.T.root);if(FS.isLink(d.mode)&&(!g||b.follow)){if(!d.m.readlink)throw new FS.h(52);d=d.m.readlink(d);"/"===d.charAt(0)||(d=Oe(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new FS.h(32);},getPath(a){for(var b;;){if(FS.na(a))return a=a.mount.jb,
b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},createNode(a,b,c,d){a=new FS.wb(a,b,c,d);of(a);return a},na(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isDir(a){return 16384===(a&61440)},isLink(a){return 40960===(a&61440)},isChrdev(a){return 8192===(a&61440)},isBlkdev(a){return 24576===(a&61440)},isSocket(a){return 49152===(a&49152)},yb:4096,cb:a=>FS.streams[a],Cb:{open(a){a.o=FS.Mb(a.node.ra).o;a.o.open?.(a)},llseek(){throw new FS.h(70);}},Ma:a=>a>>
8,Lc:a=>a&255,makedev:(a,b)=>a<<8|b,registerDevice(a,b){FS.Za[a]={o:b}},Mb:a=>FS.Za[a],syncfs(a,b){function c(h){FS.Ca--;return b(h)}function d(h){if(h){if(!d.Ib)return d.Ib=!0,c(h)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);FS.Ca++;1<FS.Ca&&w(`warning: ${FS.Ca} FS.syncfs operations in flight at once, probably just doing extra work`);var e=vf(FS.root.mount),f=0,g;for(g of e)g.type.syncfs?g.type.syncfs(g,a,d):d(null)},mount(a,b,c){var d="/"===c;if(d&&FS.root)throw new FS.h(10);if(!d&&
c){var e=FS.lookupPath(c,{wa:!1});c=e.path;e=e.node;if(e.T)throw new FS.h(10);if(!FS.isDir(e.mode))throw new FS.h(54);}b={type:a,cc:b,jb:c,oa:[]};a=a.mount(b);a.mount=b;b.root=a;d?FS.root=a:e&&(e.T=b,e.mount&&e.mount.oa.push(b));return a},unmount(a){a=FS.lookupPath(a,{wa:!1});if(!a.node.T)throw new FS.h(28);a=a.node;var b=a.T,c=vf(b);for([,e]of Object.entries(FS.da))for(;e;){var d=e.ka;c.includes(e.mount)&&gf(e);var e=d}a.T=null;a.mount.oa.splice(a.mount.oa.indexOf(b),1)},ia(a,b){return a.m.ia(a,
b)},ca(a,b,c){var d=FS.lookupPath(a,{parent:!0}).node;a=Pe(a);if(!a)throw new FS.h(28);if("."===a||".."===a)throw new FS.h(20);var e=pf(d,a);if(e)throw new FS.h(e);if(!d.m.ca)throw new FS.h(63);return d.m.ca(d,a,b,c)},rb(a){return wf(FS.lookupPath(a,{follow:!0}).node)},Pc(a){return wf(a.node)},create(a,b=438){return FS.ca(a,b&4095|32768,0)},mkdir(a,b=511){return FS.ca(a,b&1023|16384,0)},Mc(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{FS.mkdir(d,b)}catch(f){if(20!=
f.B)throw f;}}},mkdev(a,b,c){"undefined"==typeof c&&(c=b,b=438);return FS.ca(a,b|8192,c)},symlink(a,b){if(!We(a))throw new FS.h(44);var c=FS.lookupPath(b,{parent:!0}).node;if(!c)throw new FS.h(44);b=Pe(b);var d=pf(c,b);if(d)throw new FS.h(d);if(!c.m.symlink)throw new FS.h(63);return c.m.symlink(c,b,a)},rename(a,b){var c=Oe(a),d=Oe(b),e=Pe(a),f=Pe(b);var g=FS.lookupPath(a,{parent:!0});var h=g.node;g=FS.lookupPath(b,{parent:!0});g=g.node;if(!h||!g)throw new FS.h(44);if(h.mount!==g.mount)throw new FS.h(75);
var k=ff(h,e);a=Xe(a,d);if("."!==a.charAt(0))throw new FS.h(28);a=Xe(b,c);if("."!==a.charAt(0))throw new FS.h(55);try{var l=ff(g,f)}catch(m){}if(k!==l){b=FS.isDir(k.mode);if(e=qf(h,e,b))throw new FS.h(e);if(e=l?qf(g,f,b):pf(g,f))throw new FS.h(e);if(!h.m.rename)throw new FS.h(63);if(k.T||l&&l.T)throw new FS.h(10);if(g!==h&&(e=mf(h,"w")))throw new FS.h(e);gf(k);try{h.m.rename(k,g,f),k.parent=g}catch(m){throw m;}finally{of(k)}}},rmdir(a){var b=FS.lookupPath(a,{parent:!0}).node;a=Pe(a);var c=ff(b,a),
d=qf(b,a,!0);if(d)throw new FS.h(d);if(!b.m.rmdir)throw new FS.h(63);if(c.T)throw new FS.h(10);b.m.rmdir(b,a);gf(c)},sa(a){a=FS.lookupPath(a,{follow:!0}).node;return rf(a.m.sa,54)(a)},unlink(a){var b=FS.lookupPath(a,{parent:!0}).node;if(!b)throw new FS.h(44);a=Pe(a);var c=ff(b,a),d=qf(b,a,!1);if(d)throw new FS.h(d);if(!b.m.unlink)throw new FS.h(63);if(c.T)throw new FS.h(10);b.m.unlink(b,a);gf(c)},readlink(a){a=FS.lookupPath(a).node;if(!a)throw new FS.h(44);if(!a.m.readlink)throw new FS.h(28);return a.m.readlink(a)},
stat(a,b){a=FS.lookupPath(a,{follow:!b}).node;return rf(a.m.S,63)(a)},lstat(a){return FS.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?FS.lookupPath(a,{follow:!c}).node:a;xf(null,a,b,c)},lchmod(a,b){FS.chmod(a,b,!0)},fchmod(a,b){a=S(a);xf(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?FS.lookupPath(a,{follow:!d}).node:a;uf(null,a,{timestamp:Date.now(),$a:d})},lchown(a,b,c){FS.chown(a,b,c,!0)},fchown(a){a=S(a);uf(a,a.node,{timestamp:Date.now(),$a:!1})},truncate(a,b){if(0>b)throw new FS.h(28);
a="string"==typeof a?FS.lookupPath(a,{follow:!0}).node:a;yf(null,a,b)},ftruncate(a,b){a=S(a);if(0>b||0===(a.flags&2097155))throw new FS.h(28);yf(a,a.node,b)},utime(a,b,c){a=FS.lookupPath(a,{follow:!0}).node;rf(a.m.U,63)(a,{$:b,O:c})},open(a,b,c=438){if(""===a)throw new FS.h(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");
var f=FS.lookupPath(a,{follow:!(b&131072),bc:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new FS.h(20);}else{if(e)throw new FS.h(31);d=FS.ca(a,c|511,0);f=!0}if(!d)throw new FS.h(44);FS.isChrdev(d.mode)&&(b&=-513);if(b&65536&&!FS.isDir(d.mode))throw new FS.h(54);if(!f){e=d;a=b;if(e)if(FS.isLink(e.mode))e=32;else{var g=["r","w","rw"][a&3];a&512&&(g+="w");e=FS.isDir(e.mode)&&("r"!==g||a&576)?31:mf(e,g)}else e=44;if(e)throw new FS.h(e);}b&512&&!f&&FS.truncate(d,0);b&=-131713;b=sf({node:d,
path:FS.getPath(d),flags:b,seekable:!0,position:0,o:d.o,uc:[],error:!1});b.o.open&&b.o.open(b);f&&FS.chmod(d,c&511);return b},close(a){if(null===a.aa)throw new FS.h(8);a.Ga&&(a.Ga=null);try{a.o.close&&a.o.close(a)}catch(b){throw b;}finally{FS.streams[a.aa]=null}a.aa=null},llseek(a,b,c){if(null===a.aa)throw new FS.h(8);if(!a.seekable||!a.o.llseek)throw new FS.h(70);if(0!=c&&1!=c&&2!=c)throw new FS.h(28);a.position=a.o.llseek(a,b,c);a.uc=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new FS.h(28);
if(null===a.aa)throw new FS.h(8);if(1===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.read)throw new FS.h(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new FS.h(28);if(null===a.aa)throw new FS.h(8);if(0===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.write)throw new FS.h(28);a.seekable&&
a.flags&1024&&FS.llseek(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.write(a,b,c,d,e,f);g||(a.position+=b);return b},ja(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new FS.h(2);if(1===(a.flags&2097155))throw new FS.h(2);if(!a.o.ja)throw new FS.h(43);if(!b)throw new FS.h(28);return a.o.ja(a,b,c,d,e)},la(a,b,c,d,e){return a.o.la?a.o.la(a,b,c,d,e):0},Ja(a,b,c){if(!a.o.Ja)throw new FS.h(59);return a.o.Ja(a,b,c)},readFile(a,b={}){b.flags=
b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&I(`Invalid encoding type "${b.encoding}"`);var c=FS.open(a,b.flags);a=FS.stat(a).size;var d=new Uint8Array(a);FS.read(c,d,0,a,0);"utf8"===b.encoding&&(d=pe(d));FS.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=FS.open(a,c.flags,c.mode);b=hf(b);FS.write(a,b,0,b.byteLength,void 0,c.Fc);FS.close(a)},cwd:()=>FS.Xa,chdir(a){a=FS.lookupPath(a,{follow:!0});if(null===a.node)throw new FS.h(44);if(!FS.isDir(a.node.mode))throw new FS.h(54);
var b=mf(a.node,"x");if(b)throw new FS.h(b);FS.Xa=a.path},init(a,b,c){FS.Ia=!0;a??=n.stdin;b??=n.stdout;c??=n.stderr;a?FS.createDevice("/dev","stdin",a):FS.symlink("/dev/tty","/dev/stdin");b?FS.createDevice("/dev","stdout",null,b):FS.symlink("/dev/tty","/dev/stdout");c?FS.createDevice("/dev","stderr",null,c):FS.symlink("/dev/tty1","/dev/stderr");FS.open("/dev/stdin",0);FS.open("/dev/stdout",1);FS.open("/dev/stderr",1)},Ic(a,b){a=FS.analyzePath(a,b);return a.ab?a.object:null},analyzePath(a,b){try{var c=
FS.lookupPath(a,{follow:!b});a=c.path}catch(e){}var d={na:!1,ab:!1,error:0,name:null,path:null,object:null,dc:!1,hc:null,fc:null};try{c=FS.lookupPath(a,{parent:!0}),d.dc=!0,d.hc=c.path,d.fc=c.node,d.name=Pe(a),c=FS.lookupPath(a,{follow:!b}),d.ab=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.na="/"===c.path}catch(e){d.error=e.B}return d},createPath(a,b){a="string"==typeof a?a:FS.getPath(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ne(a+"/"+c);try{FS.mkdir(d)}catch(e){if(20!=
e.B)throw e;}a=d}}return d},createDataFile(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:FS.getPath(a),g=b?Ne(a+"/"+b):a);a=jf(d,e);g=FS.create(g,a);c&&(c=hf(c),FS.chmod(g,a|146),b=FS.open(g,577),FS.write(b,c,0,c.length,0,f),FS.close(b),FS.chmod(g,a))},createDevice(a,b,c,d){a=Qe("string"==typeof a?a:FS.getPath(a),b);b=jf(!!c,!!d);var e;(e=FS.createDevice).Ma??(e.Ma=64);e=FS.makedev(FS.createDevice.Ma++,0);FS.registerDevice(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,h,k){for(var l=
0,m=0;m<k;m++){try{var q=c()}catch(t){throw new FS.h(29);}if(void 0===q&&0===l)throw new FS.h(6);if(null===q||void 0===q)break;l++;g[h+m]=q}l&&(f.node.$=Date.now());return l},write(f,g,h,k){for(var l=0;l<k;l++)try{d(g[h+l])}catch(m){throw new FS.h(29);}k&&(f.node.O=f.node.N=Date.now());return l}});return FS.mkdev(a,b,e)},createLazyFile(a,b,c,d,e){function f(m,q,t,p,u){m=m.node.u;if(u>=m.length)return 0;p=Math.min(m.length-u,p);if(m.slice)for(var v=0;v<p;v++)q[t+v]=m[u+v];else for(v=0;v<p;v++)q[t+
v]=m.get(u+v);return p}class g{Ha=!1;P=[];ma=void 0;ib=0;hb=0;get(m){if(!(m>this.length-1||0>m)){var q=m%this.qb;return this.ma(m/this.qb|0)[q]}}tc(m){this.ma=m}kb(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);200<=m.status&&300>m.status||304===m.status||I("Couldn't load "+c+". Status: "+m.status);var q=Number(m.getResponseHeader("Content-length")),t,p=(t=m.getResponseHeader("Accept-Ranges"))&&"bytes"===t;m=(t=m.getResponseHeader("Content-Encoding"))&&"gzip"===t;var u=1048576;p||(u=
q);var v=this;v.tc(C=>{var z=C*u,B=(C+1)*u-1;B=Math.min(B,q-1);if("undefined"==typeof v.P[C]){var L=v.P;z>B&&I("invalid range ("+z+", "+B+") or no bytes requested!");B>q-1&&I("only "+q+" bytes available! programmer error!");var D=new XMLHttpRequest;D.open("GET",c,!1);q!==u&&D.setRequestHeader("Range","bytes="+z+"-"+B);D.responseType="arraybuffer";D.overrideMimeType&&D.overrideMimeType("text/plain; charset=x-user-defined");D.send(null);200<=D.status&&300>D.status||304===D.status||I("Couldn't load "+
c+". Status: "+D.status);z=void 0!==D.response?new Uint8Array(D.response||[]):Ze(D.responseText||"");L[C]=z}"undefined"==typeof v.P[C]&&I("doXHR failed!");return v.P[C]});if(m||!q)u=q=1,u=q=this.ma(0).length,ja("LazyFiles on gzip forces download of the whole file when length is accessed");this.ib=q;this.hb=u;this.Ha=!0}get length(){this.Ha||this.kb();return this.ib}get qb(){this.Ha||this.kb();return this.hb}}if(globalThis.XMLHttpRequest){ba||I("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var h=new g;var k=void 0}else k=c,h=void 0;var l=zf(a,b,d,e);h?l.u=h:k&&(l.u=null,l.url=k);Object.defineProperties(l,{L:{get:function(){return this.u.length}}});a={};for(const [m,q]of Object.entries(l.o))a[m]=(...t)=>{Af(l);return q(...t)};a.read=(m,q,t,p,u)=>{Af(l);return f(m,q,t,p,u)};a.ja=(m,q,t)=>{Af(l);var p=ef(q);if(!p)throw new FS.h(48);f(m,x,p,q,t);return{A:p,fa:!0}};l.o=a;return l}},Ie=(a,b)=>{if(Ha){if("/"===a.charAt(0))try{return FS.lookupPath(a),a}catch(d){return}var c=(b?.ic||[]).map(d=>
{var e=b?.ec;return d.startsWith("$ORIGIN")?d.replace("$ORIGIN",Oe(e)):d});return Re(()=>{var d=ud(512),e=Te(c.join(":")),f=Te(a);return(d=kd(d,e,f,512))?P(d):void 0})}};
function Je(a,b={global:!0,pa:!0},c,d){function e(){var k=ra[a];if(k)return b.I?Promise.resolve(k):k;if(d){k=G[d+28>>2];var l=G[d+32>>2];if(k&&l)return k=x.slice(k,k+l),b.I?Promise.resolve(k):k}if(k=Ie(a,b.Sa))return k=FS.readFile(k,{encoding:"binary"}),b.I?Promise.resolve(k):k;k=fa(a);if(b.I)return Le(k);if(!ia)throw Error(`${k}: file not found, and synchronous loading of external files is not available`);return ia(k)}function f(){var k=fe[a];return k?b.I?Promise.resolve(k):k:b.I?e().then(l=>Ke(l,
b,a,c,d)):Ke(e(),b,a,c,d)}function g(k){h.global?Vc(k):c&&Object.assign(c,k);h.exports=k}var h=qe[a];if(h)return b.global?h.global||(h.global=!0,Vc(h.exports)):c&&Object.assign(c,h.exports),b.pa&&Infinity!==h.Aa&&(h.Aa=Infinity),h.Aa++,d&&(re[d]=h),b.I?Promise.resolve(!0):!0;h=Bd(a,d,"loading");h.Aa=b.pa?Infinity:1;h.global=b.global;if(b.I)return f().then(k=>{g(k);return!0});g(f());return!0}
var He=()=>{var a,b;for([a,b]of Object.entries(le))if(-1==b.value){var c=Fe(a).Ta;if(c||b.required)if("function"==typeof c)b.value=Be(c,c.g);else if("number"==typeof c)b.value=c;else if("number"==typeof c.value)b.value=c;else throw Error(`bad export type for '${a}': ${typeof c} (${c})`);else b.value=0}},Cd=async()=>{if(ka.length){Rd("loadDylibs");for(var a of ka)await Je(a,{I:!0,global:!0,pa:!0,zb:!0});He();Qd("loadDylibs")}else He()},be=!1,Xc=(a,b,c)=>{function d(){var e=a();if(e){var f={};c.sb.forEach(g=>
f[g]=b[g]);Ad(Ce(f,e),!0)}}Wd.push(d);Ha&&d()},va,Ya=(a,b,c,d)=>I(`Assertion failed: ${P(a)}, at: `+[b?P(b):"unknown filename",c,d?P(d):"unknown function"]);Ya.g="vppip";var Za=(a,b)=>M.get(a)(b);Za.g="vpi";function ab(...a){return J.__lsan_ignore_object(...a)}ab.Ba=!0;function Bf(a,b,c,d){return r?O(2,1,a,b,c,d):bb(a,b,c,d)}
var bb=(a,b,c,d)=>{if(!globalThis.SharedArrayBuffer)return 6;var e=[];if(r&&0===e.length)return Bf(a,b,c,d);a={rc:c,X:a,Ea:d,tb:e};return r?(a.V="spawnThread",postMessage(a,e),0):Ud(a)};bb.g="ipppp";var Cf=18;function Df(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?FS.cwd():S(a).path;if(0==b.length){if(!c)throw new FS.h(44);return a}return a+"/"+b}
function Ef(a,b){G[a>>2]=b.Eb;G[a+4>>2]=b.mode;G[a+8>>2]=b.ac;G[a+12>>2]=b.uid;G[a+16>>2]=b.Qb;G[a+20>>2]=b.ra;H[a+24>>3]=BigInt(b.size);F[a+32>>2]=4096;F[a+36>>2]=b.Va;var c=b.$.getTime(),d=b.O.getTime(),e=b.N.getTime();H[a+40>>3]=BigInt(Math.floor(c/1E3));G[a+48>>2]=c%1E3*1E6;H[a+56>>3]=BigInt(Math.floor(d/1E3));G[a+64>>2]=d%1E3*1E6;H[a+72>>3]=BigInt(Math.floor(e/1E3));G[a+80>>2]=e%1E3*1E6;H[a+88>>3]=BigInt(b.Ub);return 0}var Ff=void 0;
function cb(a){if(r)return O(3,1,a);try{var b=S(a);return tf(b).aa}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}cb.g="ii";function db(a,b,c,d){if(r)return O(4,1,a,b,c,d);try{b=P(b);b=Df(a,b);if(c&-8)return-28;var e=FS.lookupPath(b,{follow:!0}).node;if(!e)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&mf(e,a)?-2:0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}db.g="iipii";var Gf=()=>{var a=F[+Ff>>2];Ff+=4;return a};
function eb(a,b,c){if(r)return O(5,1,a,b,c);Ff=c;try{var d=S(a);switch(b){case 0:var e=Gf();if(0>e)break;for(;FS.streams[e];)e++;return tf(d,e).aa;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Gf(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=Gf(),y[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}eb.g="iiip";
function fb(a,b){if(r)return O(6,1,a,b);try{var c=S(a),d=c.node,e=c.o.S;a=e?c:d;e??=d.m.S;rf(e,63);var f=e(a);return Ef(b,f)}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.B}}fb.g="iip";function gb(a,b){if(r)return O(7,1,a,b);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return-22;FS.ftruncate(a,b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}gb.g="iij";
function hb(a,b){if(r)return O(8,1,a,b);try{if(0===b)return-28;var c=FS.cwd(),d=Se(c)+1;if(b<d)return-68;Q(c,A,a,b);return d}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.B}}hb.g="ipp";
function ib(a,b,c){if(r)return O(9,1,a,b,c);Ff=c;try{var d=S(a);switch(b){case 21509:return d.C?0:-59;case 21505:if(!d.C)return-59;if(d.C.ea.Vb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Gf();F[e>>2]=25856;F[e+4>>2]=5;F[e+8>>2]=191;F[e+12>>2]=35387;for(var f=0;32>f;f++)x[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.C?0:-59;case 21506:case 21507:case 21508:if(!d.C)return-59;if(d.C.ea.Wb)for(e=Gf(),a=[],f=0;32>f;f++)a.push(x[e+f+17]);
return 0;case 21519:if(!d.C)return-59;e=Gf();return F[e>>2]=0;case 21520:return d.C?-28:-59;case 21537:case 21531:return e=Gf(),FS.Ja(d,b,e);case 21523:if(!d.C)return-59;d.C.ea.Xb&&(f=[24,80],e=Gf(),y[e>>1]=f[0],y[e+2>>1]=f[1]);return 0;case 21524:return d.C?0:-59;case 21515:return d.C?0:-59;default:return-28}}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.B}}ib.g="iiip";
function jb(a,b){if(r)return O(10,1,a,b);try{return a=P(a),Ef(b,FS.lstat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}jb.g="ipp";function kb(a,b,c,d){if(r)return O(11,1,a,b,c,d);try{b=P(b);var e=d&256;b=Df(a,b,d&4096);return Ef(c,e?FS.lstat(b):FS.stat(b))}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}kb.g="iippi";
function lb(a,b,c,d){if(r)return O(12,1,a,b,c,d);Ff=d;try{b=P(b);b=Df(a,b);var e=d?Gf():0;c&64&&(e&=~Cf);return FS.open(b,c,e).aa}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}lb.g="iipip";
function mb(a,b,c){if(r)return O(13,2,a,b,c);try{const u=ae;var d,e=new Promise(z=>{d=z}),f=[],g=!1;function v(z){g||(g=!0,f.forEach(B=>B()),d(z))}function C(z,B){return L=>{g||(L&=y[B+4>>1]|24,y[B+6>>1]=L,v(1))}}if(u&&0<c){var h=setTimeout(()=>{v(0)},c);f.push(()=>clearTimeout(h))}for(var k=0,l=0;l<b;l++){var m=a+8*l,q=y[m+4>>1],t=32,p=FS.cb(F[m>>2]);p&&(p.o.lb?t=u&&c?p.o.lb(p,c,C(p,m)):p.o.lb(p,-1):t=5);(t&=q|24)&&k++;y[m+6>>1]=t}return u?(!k&&c||v(k),e):k}catch(u){if("undefined"==typeof FS||"ErrnoError"!==
u.name)throw u;return-u.B}}mb.g="ipii";function nb(a){if(r)return O(14,1,a);try{return a=P(a),FS.rmdir(a),0}catch(b){if("undefined"==typeof FS||"ErrnoError"!==b.name)throw b;return-b.B}}nb.g="ip";function ob(a,b){if(r)return O(15,1,a,b);try{return a=P(a),Ef(b,FS.stat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}ob.g="ipp";
function pb(a,b,c){if(r)return O(16,1,a,b,c);try{b=P(b);b=Df(a,b);if(c)if(512===c)FS.rmdir(b);else return-28;else FS.unlink(b);return 0}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.B}}pb.g="iipi";var qb=a=>{a=new WebAssembly.Exception(yd,[a],{traceStack:!0});var b=a.getArg(yd,0);var c=wd(b);b=vd();var d=ud(4),e=ud(4);xd(c,d,e);c=G[d>>2];e=G[e>>2];d=P(c);K(c);if(e){var f=P(e);K(e)}td(b);a.message=[d,f];throw a;},rb=()=>I("");rb.g="v";
var Hf=a=>{var b=vd();a=Te(a);ed(a,0);td(b)},If=(a,b)=>{var c=P(a+36),d=F[a+4>>2];c=Ne(c);var e=!!(d&256),f=e?null:{};d={global:e,pa:!!(d&4096),I:b.I};if(b.I)return Je(c,d,f,a);try{return Je(c,d,f,a)}catch(g){return Hf(`could not load dynamic lib: ${c}\n${g}`),0}},sb=a=>If(a,{I:!1});sb.g="pp";var tb=(a,b)=>{a=re[a].exports;b=Object.keys(a)[b];b=a[b];return Be(b,b.g)};tb.g="ppi";
var ub=(a,b,c)=>{b=P(b);var d=re[a];a=Object.keys(d.exports).indexOf(b);if(-1==a||d.exports[b].Ba)return Hf(`Tried to lookup unknown symbol "${b}" in dynamic lib: ${d.name}`),0;b=d.exports[b];"function"==typeof b&&((d=we(b))?b=d:(b=Be(b,b.g),G[c>>2]=a));return b};ub.g="pppp";var Jf={},Kf=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Lf(a){return this.v(G[a>>2])}
var Mf={},Nf={},Of={},Pf=class extends Error{constructor(a){super(a);this.name="InternalError"}},U=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new Pf("Mismatched type converter count");for(var k=0;k<a.length;++k)T(a[k],h[k])}a.forEach(h=>Of[h]=b);var e=Array(b.length),f=[],g=0;for(let [h,k]of b.entries())Nf.hasOwnProperty(k)?e[h]=Nf[k]:(f.push(k),Mf.hasOwnProperty(k)||(Mf[k]=[]),Mf[k].push(()=>{e[h]=Nf[k];++g;g===f.length&&d(e)}));0===f.length&&d(e)},vb=a=>{var b=Jf[a];delete Jf[a];
var c=b.Ra,d=b.Y,e=b.bb,f=e.map(g=>g.Pb).concat(e.map(g=>g.nc));U([a],f,g=>{var h={},k,l;for([k,l]of e.entries()){const m=g[k],q=l.ma,t=l.Ob,p=g[k+e.length],u=l.mc,v=l.oc;h[l.Jb]={read:C=>m.v(q(t,C)),write:(C,z)=>{var B=[];u(v,C,p.F(B,z));Kf(B)},optional:m.optional}}return[{name:b.name,v:m=>{var q={},t;for(t in h)q[t]=h[t].read(m);d(m);return q},F:(m,q)=>{for(var t in h)if(!(t in q||h[t].optional))throw new TypeError(`Missing field: "${t}"`);var p=c();for(t in h)h[t].write(p,q[t]);null!==m&&m.push(d,
p);return p},K:Lf,H:d}]})};vb.g="vp";var V=a=>{for(var b="";;){var c=A[a++];if(!c)return b;b+=String.fromCharCode(c)}},W=class extends Error{constructor(a){super(a);this.name="BindingError"}},Qf=a=>{throw new W(a);};
function Rf(a,b,c={}){var d=b.name;if(!a)throw new W(`type "${d}" must have a positive integer typeid pointer`);if(Nf.hasOwnProperty(a)){if(c.Tb)return;throw new W(`Cannot register type '${d}' twice`);}Nf[a]=b;delete Of[a];Mf.hasOwnProperty(a)&&(b=Mf[a],delete Mf[a],b.forEach(e=>e()))}function T(a,b,c={}){return Rf(a,b,c)}
var yb=(a,b,c,d,e)=>{b=V(b);if(d)a:switch(c){case 4:d=Ka;break a;case 8:d=La;break a;default:throw new TypeError(`invalid float width (${c}): ${b}`);}else a:switch(c){case 1:d=e?x:A;break a;case 2:d=e?y:E;break a;case 4:d=e?F:G;break a;case 8:d=e?H:Ma;break a;default:throw new TypeError(`invalid integer width (${c}): ${b}`);}var f=d,g=Math.log2(c);T(a,{name:b,v:h=>{var k=h+Math.max(4,c)>>g;k=Array.from(f.subarray(k,k+G[h>>2]));K(h);return k},F:(h,k)=>{"number"==typeof k&&(k=[k]);if(!Array.isArray(k))throw new W(`Cannot pass non-array to C++ vector type ${b}`);
k=Array.prototype.concat.apply([],k);var l=k.length,m=Math.max(4,c),q=Zc(m+l*c);m=q+m>>g;G[q>>2]=l;f.set(k,m);null!==h&&h.push(K,q);return q},K:Lf,H(h){K(h)}})};yb.g="vpppii";
var Sf=(a,b,c)=>{switch(b){case 1:return c?d=>x[d]:d=>A[d];case 2:return c?d=>y[d>>1]:d=>E[d>>1];case 4:return c?d=>F[d>>2]:d=>G[d>>2];case 8:return c?d=>H[d>>3]:d=>Ma[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},zb=(a,b,c,d,e)=>{b=V(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}T(a,{name:b,v:f,F:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},K:Sf(b,c,!d),H:null})};zb.g="vpppjj";
var Ab=(a,b,c,d)=>{b=V(b);T(a,{name:b,v:function(e){return!!e},F:function(e,f){return f?c:d},K:function(e){return this.v(A[e])},H:null})};Ab.g="vppii";
var Tf=a=>{throw new W(a.l.D.s.name+" instance already deleted");},Uf=!1,Vf=!1,Wf=()=>{},Xf=a=>{if(Uf)return Xf=b=>b.deleteLater(),Xf(a);if(!globalThis.FinalizationRegistry)return Xf=b=>b,a;Vf=new FinalizationRegistry(b=>{b=b.l;--b.count.value;0===b.count.value&&(b.J?b.R.Y(b.J):b.D.s.Y(b.A))});Xf=b=>{var c=b.l;c.J&&Vf.register(b,{l:c},b);return b};Wf=b=>{Vf.unregister(b)};return Xf(a)},Yf=[],Zf=()=>{for(;Yf.length;){var a=Yf.pop();a.l.ha=!1;a["delete"]()}},$f;function ag(){}
var bg={},cg=(a,b,c)=>{if(void 0===a[b].G){var d=a[b];a[b]=function(...e){if(!a[b].G.hasOwnProperty(e.length))throw new W(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].G})!`);return a[b].G[e.length].apply(this,e)};a[b].G=[];a[b].G[d.Z]=d}},dg=(a,b,c)=>{if(n.hasOwnProperty(a)){if(void 0===c||void 0!==n[a].G&&void 0!==n[a].G[c])throw new W(`Cannot register public name '${a}' twice`);cg(n,a,a);if(n[a].G.hasOwnProperty(c))throw new W(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
n[a].G[c]=b}else n[a]=b,n[a].Z=c},eg=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function fg(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.ba=c;this.Y=d;this.M=e;this.Lb=f;this.ua=g;this.Fb=h;this.kc=[]}
var gg=(a,b,c)=>{for(;b!==c;){if(!b.ua)throw new W(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ua(a);b=b.M}return a},hg=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function ig(a,b){if(null===b){if(this.Ka)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new W(`Cannot pass "${hg(b)}" as a ${this.name}`);if(!b.l.A)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);return gg(b.l.A,b.l.D.s,this.s)}
function jg(a,b){if(null===b){if(this.Ka)throw new W(`null is not a valid ${this.name}`);if(this.za){var c=this.Ra();null!==a&&a.push(this.Y,c);return c}return 0}if(!b||!b.l)throw new W(`Cannot pass "${hg(b)}" as a ${this.name}`);if(!b.l.A)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ya&&b.l.D.ya)throw new W(`Cannot convert argument of type ${b.l.R?b.l.R.name:b.l.D.name} to parameter type ${this.name}`);c=gg(b.l.A,b.l.D.s,this.s);if(this.za){if(void 0===b.l.J)throw new W("Passing raw pointer to smart pointer is illegal");
switch(this.qc){case 0:if(b.l.R===this)c=b.l.J;else throw new W(`Cannot convert argument of type ${b.l.R?b.l.R.name:b.l.D.name} to parameter type ${this.name}`);break;case 1:c=b.l.J;break;case 2:if(b.l.R===this)c=b.l.J;else{var d=b.clone();c=this.lc(c,kg(()=>d["delete"]()));null!==a&&a.push(this.Y,c)}break;default:throw new W("Unsupported sharing policy");}}return c}
function lg(a,b){if(null===b){if(this.Ka)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new W(`Cannot pass "${hg(b)}" as a ${this.name}`);if(!b.l.A)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.l.D.ya)throw new W(`Cannot convert argument of type ${b.l.D.name} to parameter type ${this.name}`);return gg(b.l.A,b.l.D.s,this.s)}
var mg=(a,b,c)=>{if(b===c)return a;if(void 0===c.M)return null;a=mg(a,b,c.M);return null===a?null:c.Fb(a)},ng={},og=(a,b)=>{if(void 0===b)throw new W("ptr should not be undefined");for(;a.M;)b=a.ua(b),a=a.M;return ng[b]},pg=(a,b)=>{if(!b.D||!b.A)throw new Pf("makeClassHandle requires ptr and ptrType");if(!!b.R!==!!b.J)throw new Pf("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Xf(Object.create(a,{l:{value:b,writable:!0}}))};
function qg(a,b,c,d,e,f,g,h,k,l,m){this.name=a;this.s=b;this.Ka=c;this.ya=d;this.za=e;this.jc=f;this.qc=g;this.nb=h;this.Ra=k;this.lc=l;this.Y=m;e||void 0!==b.M?this.F=jg:(this.F=d?ig:lg,this.H=null)}var rg=(a,b,c)=>{if(!n.hasOwnProperty(a))throw new Pf("Replacing nonexistent public symbol");void 0!==n[a].G&&void 0!==c?n[a].G[c]=b:(n[a]=b,n[a].Z=c)},X=(a,b)=>{a=V(a);var c=M.get(b);if("function"!=typeof c)throw new W(`unknown function pointer with signature ${a}: ${b}`);return c};
class sg extends Error{}
var tg=a=>{a=bd(a);var b=V(a);K(a);return b},ug=(a,b)=>{function c(f){e[f]||Nf[f]||(Of[f]?Of[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new sg(`${a}: `+d.map(tg).join([", "]));},Bb=(a,b,c,d,e,f,g,h,k,l,m,q,t)=>{m=V(m);f=X(e,f);h&&=X(g,h);l&&=X(k,l);t=X(q,t);var p=eg(m);dg(p,function(){ug(`Cannot construct ${m} due to unbound types`,[d])});U([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var v=u.s;var C=v.ba}else C=ag.prototype;u=Ee(m,function(...D){if(Object.getPrototypeOf(this)!==z)throw new W(`Use 'new' to construct ${m}`);
if(void 0===B.ga)throw new W(`${m} has no accessible constructor`);var Ia=B.ga[D.length];if(void 0===Ia)throw new W(`Tried to invoke ctor of ${m} with invalid number of parameters (${D.length}) - expected (${Object.keys(B.ga).toString()}) parameters instead!`);return Ia.apply(this,D)});var z=Object.create(C,{constructor:{value:u}});u.prototype=z;var B=new fg(m,u,z,t,v,f,h,l);if(B.M){var L;(L=B.M).va??(L.va=[]);B.M.va.push(B)}v=new qg(m,B,!0,!1,!1);L=new qg(m+"*",B,!1,!1,!1);C=new qg(m+" const*",B,
!1,!0,!1);bg[a]={pointerType:L,Db:C};rg(p,u);return[v,L,C]})};Bb.g="vppppppppppppp";function vg(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].H)return!0;return!1}
function wg(a,b,c,d,e,f){var g=b.length;if(2>g)throw new W("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,k=vg(b);c=!b[0].gb;var l=b[0],m=b[1];d=[a,Qf,d,e,Kf,l.v.bind(l),m?.F.bind(m)];for(e=2;e<g;++e)l=b[e],d.push(l.F.bind(l));if(!k)for(e=h?1:2;e<b.length;++e)null!==b[e].H&&d.push(b[e].H);k=vg(b);e=b.length-2;m=[];l=["fn"];h&&l.push("thisWired");for(g=0;g<e;++g)m.push(`arg${g}`),l.push(`arg${g}Wired`);m=m.join(",");l=l.join(",");m=`return function (${m}) {\n`;
k&&(m+="var destructors = [];\n");var q=k?"destructors":"null",t="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(m+=`var thisWired = toClassParamWire(${q}, this);\n`);for(g=0;g<e;++g){var p=`toArg${g}Wire`;m+=`var arg${g}Wired = ${p}(${q}, arg${g});\n`;t.push(p)}m+=(c||f?"var rv = ":"")+`invoker(${l});\n`;if(k)m+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].H&&(m+=`${f}_dtor(${f});\n`,
t.push(`${f}_dtor`));c&&(m+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(t,m+"}\n"))(...d);return Ee(a,b)}
var xg=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(G[b+4*d>>2]);return c},Bg=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Cb=(a,b,c,d,e,f,g,h)=>{var k=xg(c,d);b=V(b);b=Bg(b);f=X(e,f);U([],[a],l=>{function m(){ug(`Cannot call ${q} due to unbound types`,k)}l=l[0];var q=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var t=l.s.constructor;void 0===t[b]?(m.Z=c-1,t[b]=m):(cg(t,b,q),t[b].G[c-1]=m);U([],k,p=>{p=wg(q,[p[0],null].concat(p.slice(1)),null,f,g,h);void 0===t[b].G?
(p.Z=c-1,t[b]=p):t[b].G[c-1]=p;if(l.s.va)for(const u of l.s.va)u.constructor.hasOwnProperty(b)||(u.constructor[b]=p);return[]});return[]})};Cb.g="vppippppii";
var Db=(a,b,c,d,e,f)=>{var g=xg(b,c);e=X(d,e);U([],[a],h=>{h=h[0];var k=`constructor ${h.name}`;void 0===h.s.ga&&(h.s.ga=[]);if(void 0!==h.s.ga[b-1])throw new W(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.s.ga[b-1]=()=>{ug(`Cannot construct ${h.name} due to unbound types`,g)};U([],g,l=>{l.splice(1,0,null);h.s.ga[b-1]=wg(k,l,null,e,f);return[]});
return[]})};Db.g="vpipppp";var Eb=(a,b,c,d,e,f,g,h,k)=>{var l=xg(c,d);b=V(b);b=Bg(b);f=X(e,f);U([],[a],m=>{function q(){ug(`Cannot call ${t} due to unbound types`,l)}m=m[0];var t=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&m.s.kc.push(b);var p=m.s.ba,u=p[b];void 0===u||void 0===u.G&&u.className!==m.name&&u.Z===c-2?(q.Z=c-2,q.className=m.name,p[b]=q):(cg(p,b,t),p[b].G[c-2]=q);U([],l,v=>{v=wg(t,v,m,f,g,k);void 0===p[b].G?(v.Z=c-2,p[b]=v):p[b].G[c-2]=v;return[]});return[]})};
Eb.g="vppippppiii";
var Cg=(a,b,c)=>{if(!(a instanceof Object))throw new W(`${c} with invalid "this": ${a}`);if(!(a instanceof b.s.constructor))throw new W(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.l.A)throw new W(`cannot call emscripten binding method ${c} on deleted object`);return gg(a.l.A,a.l.D.s,b.s)},Fb=(a,b,c,d,e,f,g,h,k,l)=>{b=V(b);e=X(d,e);U([],[a],m=>{m=m[0];var q=`${m.name}.${b}`,t={get(){ug(`Cannot access ${q} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};t.set=k?
()=>ug(`Cannot access ${q} due to unbound types`,[c,g]):()=>{throw new W(q+" is a read-only property");};Object.defineProperty(m.s.ba,b,t);U([],k?[c,g]:[c],p=>{var u=p[0],v={get(){var z=Cg(this,m,q+" getter");return u.v(e(f,z))},enumerable:!0};if(k){k=X(h,k);var C=p[1];v.set=function(z){var B=Cg(this,m,q+" setter"),L=[];k(l,B,C.F(L,z));Kf(L)}}Object.defineProperty(m.s.ba,b,v);return[]});return[]})};Fb.g="vpppppppppp";
var Dg=[],Eg=[0,1,,1,null,1,!0,1,!1,1],Fg=[],fc=a=>{if(9<a&&0===--Eg[a+1]){var b=Eg[a];Eg[a]=void 0;var c=Fg[a];c&&(Fg[a]=void 0,c(b));Dg.push(a)}};fc.g="vp";var Z=a=>{if(!a)throw new W(`Cannot use deleted val. handle = ${a}`);return Eg[a]},kg=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Dg.pop()||Eg.length;Eg[b]=a;Eg[b+1]=1;return b}},Gg={name:"emscripten::val",v:a=>{var b=Z(a);fc(a);return b},F:(a,b)=>kg(b),K:Lf,H:null},Gb=a=>T(a,Gg);
Gb.g="vp";
var Hg=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.v(x[d])}:function(d){return this.v(A[d])};case 2:return c?function(d){return this.v(y[d>>1])}:function(d){return this.v(E[d>>1])};case 4:return c?function(d){return this.v(F[d>>2])}:function(d){return this.v(G[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Hb=(a,b,c,d,e)=>{b=V(b);e=0===e?"object":1===e?"number":"string";switch(e){case "object":function g(){}g.values={};T(a,{name:b,constructor:g,valueType:e,
v:function(h){return this.constructor.values[h]},F:(h,k)=>k.value,K:Hg(b,c,d),H:null});dg(b,g);break;case "number":var f={};T(a,{name:b,La:f,valueType:e,v:h=>h,F:(h,k)=>k,K:Hg(b,c,d),H:null});dg(b,f);delete n[b].Z;break;case "string":f={},T(a,{name:b,ub:{},ob:{},La:f,valueType:e,v:function(h){return this.ob[h]},F:function(h,k){return this.ub[k]},K:Hg(b,c,d),H:null}),dg(b,f),delete n[b].Z}};Hb.g="vpppii";
var Ig=(a,b)=>{var c=Nf[a];if(void 0===c)throw a=`${b} has unknown type ${tg(a)}`,new W(a);return c},Ib=(a,b,c)=>{var d=Ig(a,"enum");b=V(b);switch(d.valueType){case "object":a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Ee(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d;break;case "number":d.La[b]=c;break;case "string":d.ub[b]=c,d.ob[c]=b,d.La[b]=b}};Ib.g="vppi";
var Jg=(a,b)=>{switch(b){case 4:return function(c){return this.v(Ka[c>>2])};case 8:return function(c){return this.v(La[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Jb=(a,b,c)=>{b=V(b);T(a,{name:b,v:d=>d,F:(d,e)=>e,K:Jg(b,c),H:null})};Jb.g="vppp";var Kb=(a,b,c,d,e,f,g)=>{var h=xg(b,c);a=V(a);a=Bg(a);e=X(d,e);dg(a,function(){ug(`Cannot call ${a} due to unbound types`,h)},b-1);U([],h,k=>{rg(a,wg(a,[k[0],null].concat(k.slice(1)),null,e,f,g),b-1);return[]})};Kb.g="vpippppii";
var Lb=(a,b,c,d,e)=>{b=V(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}T(a,{name:b,v:f,F:(h,k)=>k,K:Sf(b,c,0!==d),H:null})};Lb.g="vpppii";var Kg=(a,b,c)=>{const d=(e,f)=>{let g=0;return{next(){if(g>=e)return{done:!0};const h=g;g++;return{value:f(h),done:!1}},[Symbol.iterator](){return this}}};a[Symbol.iterator]||(a[Symbol.iterator]=function(){const e=this[b]();return d(e,f=>this[c](f))})},Mb=(a,b,c,d)=>{c=V(c);d=V(d);U([],[a,b],e=>{Kg(e[0].s.ba,c,d);return[]})};Mb.g="vpppp";
var Nb=(a,b,c)=>{function d(f){return new e(x.buffer,G[f+4>>2],G[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=V(c);T(a,{name:c,v:d,K:d},{Tb:!0})};Nb.g="vpip";var Lg=Object.assign({optional:!0},Gg),Ob=a=>{T(a,Lg)};Ob.g="vpp";
var Pb=(a,b)=>{b=V(b);T(a,{name:b,v(c){var d=P(c+4,G[c>>2],!0);K(c);return d},F(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new W("Cannot pass non-string to std::string");var f=e?Se(d):d.length;var g=Zc(4+f+1),h=g+4;G[g>>2]=f;e?Q(d,A,h,f+1):A.set(d,h);null!==c&&c.push(K,g);return g},K:Lf,H(c){K(c)}})};Pb.g="vpp";
var Mg=new TextDecoder("utf-16le"),Ng=(a,b,c)=>{a>>=1;return Mg.decode(E.slice(a,oe(E,a,b/2,c)))},Og=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)y[b>>1]=a.charCodeAt(e),b+=2;y[b>>1]=0;return b-d},Pg=a=>2*a.length,Qg=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=G[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Rg=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);
65535<f&&e++;F[b>>2]=f;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d},Sg=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Qb=(a,b,c)=>{c=V(c);if(2===b){var d=Ng;var e=Og;var f=Pg}else d=Qg,e=Rg,f=Sg;T(a,{name:c,v:g=>{var h=d(g+4,G[g>>2]*b,!0);K(g);return h},F:(g,h)=>{if("string"!=typeof h)throw new W(`Cannot pass non-string to C++ string type ${c}`);var k=f(h),l=Zc(4+k+b);G[l>>2]=k/b;e(h,l+4,k+b);null!==g&&g.push(K,l);return l},K:Lf,H(g){K(g)}})};Qb.g="vppp";
var Rb=(a,b,c,d,e,f)=>{Jf[a]={name:V(b),Ra:X(c,d),Y:X(e,f),bb:[]}};Rb.g="vpppppp";var Sb=(a,b,c,d,e,f,g,h,k,l)=>{Jf[a].bb.push({Jb:V(b),Pb:c,ma:X(d,e),Ob:f,nc:g,mc:X(h,k),oc:l})};Sb.g="vpppppppppp";var Tb=(a,b)=>{b=V(b);T(a,{gb:!0,name:b,v:()=>{},F:()=>{}})};Tb.g="vpp";var Ub=(a,b,c,d)=>{function e(h){var k=P(a+36);Hf(`'Could not load dynamic lib: ${k}\n${h}`);--N;$d(()=>M.get(c)(a,d))}function f(){--N;$d(()=>M.get(b)(a,d))}N+=1;var g=If(a,{I:!0});g?g.then(f,e):e()};Ub.g="vpppp";
function Tg(a){var b=Ug,c=b.P.pop()||b.fa.length;b.fa[c]=a;return c}function Vg(a){var b=Ug;b.fa[a]=void 0;b.P.push(a)}class Wg{fa=[void 0];P=[];get(a){return this.fa[a]}has(a){return void 0!==this.fa[a]}}
var Ug=new Wg,Xg=()=>{var a={};a.promise=new Promise((b,c)=>{a.reject=c;a.resolve=b});a.id=Tg(a);return a},Yg=async()=>{const a=ae,b=[];var c=Xg();b.push(c.promise);fd(c.id);for(const d of Object.keys(Gd)){const e=Number(d);e===a||Hd.has(e)||(c=Xg(),hd(e,c.id),Id[e]=c,b.push(c.promise))}await Promise.all(b);Id={}};function Vb(){if(r)return O(17,2);if(ae)return Yg();for(const a of Object.keys(Gd)){const b=Number(a);Hd.has(b)||jd(b)}}Vb.g="v";
function Wb(){var a=Zc(4*(ka.length+1)),b=a;ka.forEach(c=>{var d=G,e=b>>2,f=Se(c)+1,g=Zc(f);g&&Q(c,A,g,f);d[e]=g;b+=4});G[b>>2]=0;return a}Wb.g="p";var Xb=a=>{Aa(a,!ba,1,!aa,262144,!1);Ba()};Xb.g="vp";var Ca=a=>{Vd||(Atomics.waitAsync(F,a>>2,a).value.then(Fa),Atomics.store(F,a+120>>2,1))};Ca.g="vp";var Fa=()=>{var a=Yc();a&&$d(()=>{Ca(a);qd()})},Yb=(a,b)=>{a==b?setTimeout(Fa):r?postMessage({Da:a,V:"checkMailbox"}):(a=Gd[a])&&a.postMessage({V:"checkMailbox"})};Yb.g="vpp";
var Zg=[],Zb=(a,b,c,d,e,f,g)=>{Zg.length=0;var h=e>>3;for(d=e+d>>3;h<d;){var k;H[h++]?k=H[h++]:k=La[h++];Zg.push(k)}a=b?Ge[b]:$g[a];ae=c;c=a(...Zg);ae=0;if(f)c.then(l=>md(f,g,l));else return c};Zb.g="dippippp";var $b=()=>{be=!1;N=0};$b.g="v";var ac=a=>{r?postMessage({V:"cleanupThread",Ua:a}):Ld(a)};ac.g="vp";var bc=a=>{r?postMessage({V:"markAsFinished",Ua:a}):Nd(a)};bc.g="vp";var cc=()=>{};cc.g="vp";var dc=(a,b)=>{a=Z(a);b=Z(b);a.set(b)};dc.g="vpp";
var ah=[],bh=a=>{var b=ah.length;ah.push(a);return b},ch=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Ig(G[b+4*d>>2],`parameter ${d}`);return c},dh=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(G[b>>2]=kg(d));return a},eh={},fh=a=>{var b=eh[a];return void 0===b?V(a):b},ec=(a,b,c)=>{var [d,...e]=ch(a,b);b=d.F.bind(d);var f=e.map(k=>k.K.bind(k));a--;var g={toValue:Z};a=f.map((k,l)=>{var m=`argFromPtr${l}`;g[m]=k;return`${m}(args${l?"+"+8*l:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";
break;case 3:h="";break;case 1:g.getStringOrSymbol=fh,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${a})`;d.gb||(g.toReturnWire=b,g.emval_returnValue=dh,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n${h}\n}`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=`methodCaller<(${e.map(k=>k.name)}) => ${d.name}>`;return bh(Ee(h,c))};ec.g="pipi";var gc=a=>{if(!a)return kg(globalThis);a=fh(a);return kg(globalThis[a])};
gc.g="pp";var hc=a=>{a=fh(a);return kg(n[a])};hc.g="pp";var ic=(a,b)=>{a=Z(a);b=Z(b);return kg(a[b])};ic.g="ppp";var jc=a=>{9<a&&(Eg[a+1]+=1)};jc.g="vp";var kc=(a,b)=>{a=Z(a);b=Z(b);return a instanceof b};kc.g="ipp";var lc=(a,b,c,d,e)=>ah[a](b,c,d,e);lc.g="dppppp";var mc=a=>{a=Z(a);return"number"==typeof a};mc.g="ip";var nc=a=>{a=Z(a);return"string"==typeof a};nc.g="ip";var oc=a=>kg(fh(a));oc.g="pp";var pc=a=>{var b=Z(a);Kf(b);fc(a)};pc.g="vp";var qc=(a,b,c)=>{a=Z(a);b=Z(b);c=Z(c);a[b]=c};qc.g="vppp";
var rc=a=>{a=Z(a);return kg(typeof a)};rc.g="pp";function sc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);F[b>>2]=a.getUTCSeconds();F[b+4>>2]=a.getUTCMinutes();F[b+8>>2]=a.getUTCHours();F[b+12>>2]=a.getUTCDate();F[b+16>>2]=a.getUTCMonth();F[b+20>>2]=a.getUTCFullYear()-1900;F[b+24>>2]=a.getUTCDay();F[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0}sc.g="vjp";
var gh=[0,31,60,91,121,152,182,213,244,274,305,335],hh=[0,31,59,90,120,151,181,212,243,273,304,334];
function tc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);F[b>>2]=a.getSeconds();F[b+4>>2]=a.getMinutes();F[b+8>>2]=a.getHours();F[b+12>>2]=a.getDate();F[b+16>>2]=a.getMonth();F[b+20>>2]=a.getFullYear()-1900;F[b+24>>2]=a.getDay();var c=a.getFullYear();F[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?hh:gh)[a.getMonth()]+a.getDate()-1|0;F[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();
F[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0}tc.g="vjp";function uc(a,b,c,d,e,f,g){if(r)return O(18,1,a,b,c,d,e,f,g);e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{var h=S(d),k=FS.ja(h,a,e,b,c),l=k.A;F[f>>2]=k.fa;G[g>>2]=l;return 0}catch(m){if("undefined"==typeof FS||"ErrnoError"!==m.name)throw m;return-m.B}}uc.g="ipiiijpp";
function vc(a,b,c,d,e,f){if(r)return O(19,1,a,b,c,d,e,f);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=S(e);if(c&2){c=f;if(!FS.isFile(g.node.mode))throw new FS.h(43);d&2||FS.la(g,A.slice(a,a+b),c,b,d)}}catch(h){if("undefined"==typeof FS||"ErrnoError"!==h.name)throw h;return-h.B}}vc.g="ippiiij";
var wc=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();G[a>>2]=60*Math.max(f,e);F[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(Q(a,A,c,17),Q(b,A,d,17)):(Q(a,A,d,17),Q(b,A,c,17))};wc.g="vpppp";var Dc=()=>performance.timeOrigin+performance.now();Dc.g="d";var zc=()=>Date.now();zc.g="d";var ih=1;
function xc(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(ih)a=performance.timeOrigin+performance.now();else return 52;H[c>>3]=BigInt(Math.round(1E6*a));return 0}xc.g="iijp";var yc=()=>{};yc.g="v";var Ac=a=>w(P(a));Ac.g="vp";var Bc=()=>{N+=1;throw"unwind";};Bc.g="v";var Cc=()=>A.length;Cc.g="p";var Ec=()=>navigator.hardwareConcurrency;Ec.g="i";var Fc=a=>{Vg(a)};Fc.g="vp";
var Gc=(a,b,c)=>{a=Ug.get(a);switch(b){case 0:a.resolve(c);break;case 1:a.resolve(Ug.get(c).promise);break;case 2:a.resolve(Ug.get(c).promise);Vg(c);break;case 3:a.reject(c)}};Gc.g="vpip";var Hc=()=>!1;Hc.g="ip";
var jh={},lh=()=>{if(!kh){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in jh)void 0===jh[b]?delete a[b]:a[b]=jh[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);kh=c}return kh},kh;function Ic(a,b){if(r)return O(20,1,a,b);var c=0,d=0,e;for(e of lh()){var f=b+c;G[a+d>>2]=f;c+=Q(e,A,f,Infinity)+1;d+=4}return 0}Ic.g="ipp";
function Jc(a,b){if(r)return O(21,1,a,b);var c=lh();G[a>>2]=c.length;a=0;for(var d of c)a+=Se(d)+1;G[b>>2]=a;return 0}Jc.g="ipp";function Lc(a){if(r)return O(22,1,a);try{var b=S(a);FS.close(b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.B}}Lc.g="ii";
function Mc(a,b){if(r)return O(23,1,a,b);try{var c=S(a),d=c.C?2:FS.isDir(c.mode)?3:FS.isLink(c.mode)?7:4;x[b]=d;y[b+2>>1]=0;H[b+8>>3]=BigInt(0);H[b+16>>3]=BigInt(0);return 0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return e.B}}Mc.g="iip";
function Nc(a,b,c,d){if(r)return O(24,1,a,b,c,d);try{a:{var e=S(a);a=b;for(var f,g=b=0;g<c;g++){var h=G[a>>2],k=G[a+4>>2];a+=8;var l=FS.read(e,x,h,k,f);if(0>l){var m=-1;break a}b+=l;if(l<k)break;"undefined"!=typeof f&&(f+=l)}m=b}G[d>>2]=m;return 0}catch(q){if("undefined"==typeof FS||"ErrnoError"!==q.name)throw q;return q.B}}Nc.g="iippp";
function Oc(a,b,c,d){if(r)return O(25,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 22;var e=S(a);FS.llseek(e,b,c);H[d>>3]=BigInt(e.position);e.Ga&&0===b&&0===c&&(e.Ga=null);return 0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return f.B}}Oc.g="iijip";
function Pc(a,b,c,d){if(r)return O(26,1,a,b,c,d);try{a:{var e=S(a);a=b;for(var f,g=b=0;g<c;g++){var h=G[a>>2],k=G[a+4>>2];a+=8;var l=FS.write(e,x,h,k,f);if(0>l){var m=-1;break a}b+=l;if(l<k)break;"undefined"!=typeof f&&(f+=l)}m=b}G[d>>2]=m;return 0}catch(q){if("undefined"==typeof FS||"ErrnoError"!==q.name)throw q;return q.B}}Pc.g="iippp";function Rc(...a){return J.heif_error_success(...a)}Rc.Ba=!0;var Tc=(a,b)=>Ve(A.subarray(a,a+b));Tc.g="ipp";r||Xd();
(()=>{var a={mb:Promise.resolve(),canHandle:b=>!n.noWasmDecoding&&b.endsWith(".so"),handle:async(b,c)=>a.mb=a.mb.then(async()=>{try{var d=await Ke(b,{I:!0,pa:!0},c,{})}catch(e){throw Error(`failed to instantiate wasm: ${c}: ${e}`);}fe[c]=d;return b})};ee.push(a)})();FS.createPreloadedFile=(a,b,c,d,e,f,g,h,k,l)=>{lf(a,b,c,d,e,h,k,l).then(f).catch(g)};FS.Oc=lf;FS.da=Array(4096);FS.mount(R,{},"/");FS.mkdir("/tmp");FS.mkdir("/home");FS.mkdir("/home/web_user");
(function(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=>0,write:(d,e,f,g)=>g,llseek:()=>0});FS.mkdev("/dev/null",FS.makedev(1,3));af(FS.makedev(5,0),cf);af(FS.makedev(6,0),df);FS.mkdev("/dev/tty",FS.makedev(5,0));FS.mkdev("/dev/tty1",FS.makedev(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ve(a),b=a.byteLength);return a[--b]};FS.createDevice("/dev","random",c);FS.createDevice("/dev","urandom",c);FS.mkdir("/dev/shm");FS.mkdir("/dev/shm/tmp")})();
(function(){FS.mkdir("/proc");var a=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var b=FS.createNode(a,"fd",16895,73);b.o={llseek:R.o.llseek};b.m={ia(c,d){c=+d;var e=S(c);c={parent:null,mount:{jb:"fake"},m:{readlink:()=>e.path},id:c+1};return c.parent=c},sa(){return Array.from(FS.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();FS.Kb={MEMFS:R};
(()=>{let a=ag.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof ag&&c instanceof ag))return!1;var d=this.l.D.s,e=this.l.A;c.l=c.l;var f=c.l.D.s;for(c=c.l.A;d.M;)e=d.ua(e),d=d.M;for(;f.M;)c=f.ua(c),f=f.M;return d===f&&e===c},clone:function(){this.l.A||Tf(this);if(this.l.qa)return this.l.count.value+=1,this;var c=Xf,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.l;c=c(e.call(d,f,{l:{value:{count:g.count,ha:g.ha,qa:g.qa,A:g.A,D:g.D,J:g.J,R:g.R}}}));c.l.count.value+=1;c.l.ha=
!1;return c},["delete"](){this.l.A||Tf(this);if(this.l.ha&&!this.l.qa)throw new W("Object already scheduled for deletion");Wf(this);var c=this.l;--c.count.value;0===c.count.value&&(c.J?c.R.Y(c.J):c.D.s.Y(c.A));this.l.qa||(this.l.J=void 0,this.l.A=void 0)},isDeleted:function(){return!this.l.A},deleteLater:function(){this.l.A||Tf(this);if(this.l.ha&&!this.l.qa)throw new W("Object already scheduled for deletion");Yf.push(this);1===Yf.length&&$f&&$f(Zf);this.l.ha=!0;return this}});const b=Symbol.dispose;
b&&(a[b]=a["delete"])})();
Object.assign(qg.prototype,{Nb(a){this.nb&&(a=this.nb(a));return a},Ya(a){this.Y?.(a)},K:Lf,v:function(a){function b(){return this.za?pg(this.s.ba,{D:this.jc,A:c,R:this,J:a}):pg(this.s.ba,{D:this,A:a})}var c=this.Nb(a);if(!c)return this.Ya(a),null;var d=og(this.s,c);if(void 0!==d){if(0===d.l.count.value)return d.l.A=c,d.l.J=a,d.clone();d=d.clone();this.Ya(a);return d}d=this.s.Lb(c);d=bg[d];if(!d)return b.call(this);d=this.ya?d.Db:d.pointerType;var e=mg(c,this.s,d.s);return null===e?b.call(this):this.za?
pg(d.s.ba,{D:d,A:e,R:this,J:a}):pg(d.s.ba,{D:d,A:e})}});Md.push(()=>{jh.VIPS_DISC_THRESHOLD=1073741824;jh.VIPS_MAX_THREADS=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;jh.VIPS_CONCURRENCY=1});
Ra.push(()=>{const a=Object.getOwnPropertyDescriptor(n.SourceCustom.prototype,"onRead");Object.defineProperty(n.SourceCustom.prototype,"onRead",{set(c){return a.set.call(this,d=>kg(c(d)))}});const b=Object.getOwnPropertyDescriptor(n.TargetCustom.prototype,"onWrite");Object.defineProperty(n.TargetCustom.prototype,"onWrite",{set(c){return b.set.call(this,d=>c(Z(d)))}})});Object.assign(ag.prototype,{preventAutoDelete:function(){const a=Yf.indexOf(this);-1<a&&Yf.splice(a,1);this.l.ha=!1;return this}});
if(!r){if(n.wasmMemory)va=n.wasmMemory;else{var mh=n.INITIAL_MEMORY||1073741824;va=new WebAssembly.Memory({initial:mh/65536,maximum:mh/65536,shared:!0})}wa()}n.preloadPlugins&&(ee=n.preloadPlugins);n.noExitRuntime&&(be=n.noExitRuntime);n.print&&(ja=n.print);n.printErr&&(w=n.printErr);n.dynamicLibraries&&(ka=n.dynamicLibraries);n.wasmBinary&&(la=n.wasmBinary);n.arguments&&(ca=n.arguments);n.thisProgram&&(da=n.thisProgram);if(n.preInit)for("function"==typeof n.preInit&&(n.preInit=[n.preInit]);0<n.preInit.length;)n.preInit.shift()();
n.ENV=jh;n.addRunDependency=Rd;n.removeRunDependency=Qd;n.addFunction=Be;n.FS_preloadFile=lf;n.FS_unlink=(...a)=>FS.unlink(...a);n.FS_createPath=(...a)=>FS.createPath(...a);n.FS_createDevice=(...a)=>FS.createDevice(...a);n.FS=FS;n.FS_createDataFile=(...a)=>FS.createDataFile(...a);n.FS_createLazyFile=(...a)=>FS.createLazyFile(...a);n.setAutoDeleteLater=a=>{Uf=a};n.deletionQueue=Yf;n.setDelayFunction=a=>{$f=a;Yf.length&&$f&&$f(Zf)};
var $g=[Sc,ce,Bf,cb,db,eb,fb,gb,hb,ib,jb,kb,lb,mb,nb,ob,pb,Vb,uc,vc,Ic,Jc,Lc,Mc,Nc,Oc,Pc],Ge={};function nh(a){for(var b=E[a+6>>1];13===b&&!(16<G[a>>2]);){var c=G[a+8>>2],d=G[c>>2];if(0===d){b=0;break}else if(0===G[(c>>2)+1])a=d,b=E[d+6>>1];else break}return[a,b]}
function Qc(a,b,c,d){var e=G[(a>>2)+1],f=G[(a>>2)+6],g=G[(a>>2)+2],h=G[(a>>2)+5];a=nh(G[(a>>2)+3])[1];var k=vd(),l=k,m=[],q=!1;if(15===a)throw Error("complex ret marshalling nyi");if(0>a||15<a)throw Error("Unexpected rtype "+a);if(4===a||13===a)m.push(c),q=!0;for(var t=0;t<f;t++){var p=G[(d>>2)+t],u=nh(G[(g>>2)+t]),v=u[0];u=u[1];switch(u){case 1:case 10:case 9:m.push(G[p>>2]);break;case 2:m.push(Ka[p>>2]);break;case 3:m.push(La[p>>3]);break;case 5:m.push(A[p]);break;case 6:m.push(x[p]);break;case 7:m.push(E[p>>
1]);break;case 8:m.push(y[p>>1]);break;case 11:case 12:m.push(Ma[p>>3]);break;case 4:m.push(Ma[p>>3]);m.push(Ma[(p>>3)+1]);break;case 13:u=G[v>>2];v=E[v+4>>1];l-=u;l&=~(v-1);x.subarray(l,l+u).set(x.subarray(p,p+u));m.push(l);break;case 14:m.push(G[p>>2]);break;case 15:throw Error("complex marshalling nyi");default:throw Error("Unexpected type "+u);}}if(h&1){h=[];for(t=e-1;t>=f;t--)switch(p=G[(d>>2)+t],u=nh(G[(g>>2)+t]),v=u[0],u=u[1],u){case 5:case 6:--l;l&=-1;A[l]=A[p];break;case 7:case 8:l-=2;l&=
-2;E[l>>1]=E[p>>1];break;case 1:case 9:case 10:case 2:l-=4;l&=-4;G[l>>2]=G[p>>2];break;case 3:case 11:case 12:l-=8;l&=-8;G[l>>2]=G[p>>2];G[(l>>2)+1]=G[(p>>2)+1];break;case 4:l-=16;l&=-8;G[l>>2]=G[p>>2];G[(l>>2)+1]=G[(p>>2)+1];G[(l>>2)+2]=G[(p>>2)+2];G[(l>>2)+3]=G[(p>>2)+3];break;case 13:l-=4;l&=-4;h.push([l,p,G[v>>2],E[v+4>>1]]);break;case 14:l-=4;l&=-4;G[l>>2]=G[p>>2];break;case 15:throw Error("complex arg marshalling nyi");default:throw Error("Unexpected argtype "+u);}m.push(l);for(t=0;t<h.length;t++)e=
h[t],d=e[0],p=e[1],u=e[2],v=e[3],l-=u,l&=~(v-1),x.subarray(l,l+u).set(x.subarray(p,p+u)),G[d>>2]=l}td(l);ud(0);b=M.get(b).apply(null,m);td(k);if(!q)switch(a){case 0:break;case 1:case 9:case 10:G[c>>2]=b;break;case 2:Ka[c>>2]=b;break;case 3:La[c>>3]=b;break;case 5:case 6:A[c+0]=b;break;case 7:case 8:E[c>>1]=b;break;case 11:case 12:Ma[c>>3]=b;break;case 14:G[c>>2]=b;break;case 15:throw Error("complex ret marshalling nyi");default:throw Error("Unexpected rtype "+a);}}Qc.g="viiii";
var Yc,Zc,K,$c,ad,bd,Da,cd,dd,ed,fd,gd,hd,jd,kd,Aa,ld,Ga,md,nd,od,pd,qd,rd,Sa,sd,td,ud,vd,wd,xd,yd,zd,M,J;function oh(a=[]){var b=Fe("main").Ta;if(b){a.unshift(da);var c=a.length,d=ud(4*(c+1)),e=d,f;for(f of a)G[e>>2]=Te(f),e+=4;G[e>>2]=0;try{var g=b(c,d);Kc(g,!0)}catch(h){Ed(h)}}}
function ya(a=ca){function b(){n.calledRun=!0;if(!na&&(Oa(),pa?.(n),n.onRuntimeInitialized?.(),n.noInitialRun||oh(a),!r)){if(n.postRun)for("function"==typeof n.postRun&&(n.postRun=[n.postRun]);n.postRun.length;){var c=n.postRun.shift();me.push(c)}Pa(me)}}if(0<Od)Pd=ya;else if(r)pa?.(n),Oa();else{if(n.preRun)for("function"==typeof n.preRun&&(n.preRun=[n.preRun]);n.preRun.length;)Md.push(n.preRun.shift());Pa(Md);0<Od?Pd=ya:n.setStatus?(n.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>n.setStatus(""),
1);b()},1)):b()}}var Qa;r||(Qa=await (xa()),ya());Ha?moduleRtn=n:moduleRtn=new Promise((a,b)=>{pa=a;qa=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=Vips;module.exports.default=Vips}else if(typeof define==="function"&&define["amd"])define([],()=>Vips);var isPthread=globalThis.name=="em-pthread";isPthread&&Vips();
