async function Vips(moduleArg={}){var moduleRtn;var n=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,r=ba&&"em-pthread"==globalThis.name;n.dynamicLibraries=n.dynamicLibraries||["vips-jxl.wasm","vips-heif.wasm"];var ca=[],da="./this.program",ea=import.meta.url,fa="";function ha(a){return n.locateFile?n.locateFile(a,fa):fa+a}var ia,ja;
if(aa||ba){try{fa=(new URL(".",ea)).href}catch{}ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ia=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var ka=console.log.bind(console),w=console.error.bind(console),la=[],ma,na,oa=!1,pa,qa,ra,sa={},ta;
if(r){var va=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.V;if("load"===d){let e=[];self.onmessage=f=>e.push(f);ta=()=>{postMessage({V:"loaded"});for(let f of e)a(f);self.onmessage=a};la=c.Gb;sa=c.pc;for(const f of c.Sb)if(!n[f]||n[f].proxy)n[f]=(...g)=>{postMessage({V:"callHandler",Rb:f,Ab:g})},"print"==f&&(ka=n[f]),"printErr"==f&&(w=n[f]);wa=c.vc;xa();na=c.wc;ya();za()}else if("run"===d){Aa(c.X);Ba(c.X,0,0,1,0,0);Ca();Da(c.X);va||(Ea(),va=!0);try{Fa(c.sc,
c.Ea)}catch(e){if("unwind"!=e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?va&&Ga():d&&(w(`worker: received unknown command ${d}`),w(c)))}catch(e){throw Ia(),e;}}self.onmessage=a}var Ja=!1,Ka=!1;function xa(){var a=wa.buffer;x=new Int8Array(a);y=new Int16Array(a);A=new Uint8Array(a);E=new Uint16Array(a);F=new Int32Array(a);G=new Uint32Array(a);La=new Float32Array(a);Ma=new Float64Array(a);H=new BigInt64Array(a);Na=new BigUint64Array(a)}var Oa=[];
function Pa(){Ja=!0;r?ta():(Qa(Oa),n.noFSInit||FS.Ia||FS.init(),Ra.__wasm_call_ctors(),Qa(Sa),FS.fb=!1)}function I(a){n.onAbort?.(a);a=`Aborted(${a})`;w(a);oa=!0;a+=". Build with -sASSERTIONS for more info.";Ja&&Ta();a=new WebAssembly.RuntimeError(a);ra?.(a);throw a;}var Ua;async function Va(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==Ua&&ma)a=new Uint8Array(ma);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Wa(a,b){try{var c=await Va(a);return await WebAssembly.instantiate(c,b)}catch(d){w(`failed to asynchronously prepare wasm: ${d}`),I(d)}}async function Xa(a){var b=Ua;if(!ma)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){w(`wasm streaming compile failed: ${d}`),w("falling back to ArrayBuffer instantiation")}return Wa(b,a)}
function Ya(){J={__assert_fail:Za,__call_sighandler:ab,__lsan_ignore_object:bb,__pthread_create_js:cb,__syscall_dup:db,__syscall_faccessat:eb,__syscall_fcntl64:fb,__syscall_fstat64:gb,__syscall_ftruncate64:hb,__syscall_getcwd:ib,__syscall_ioctl:jb,__syscall_lstat64:kb,__syscall_newfstatat:lb,__syscall_openat:mb,__syscall_poll:nb,__syscall_rmdir:ob,__syscall_stat64:pb,__syscall_unlinkat:qb,__throw_exception_with_stack_trace:rb,_abort_js:sb,_dlopen_js:tb,_dlsym_catchup_js:ub,_dlsym_js:vb,_embind_finalize_value_object:yb,
_embind_register_arithmetic_vector:zb,_embind_register_bigint:Ab,_embind_register_bool:Bb,_embind_register_class:Cb,_embind_register_class_class_function:Db,_embind_register_class_constructor:Eb,_embind_register_class_function:Fb,_embind_register_class_property:Gb,_embind_register_emval:Hb,_embind_register_enum:Ib,_embind_register_enum_value:Jb,_embind_register_float:Kb,_embind_register_function:Lb,_embind_register_integer:Mb,_embind_register_iterable:Nb,_embind_register_memory_view:Ob,_embind_register_optional:Pb,
_embind_register_std_string:Qb,_embind_register_std_wstring:Rb,_embind_register_value_object:Sb,_embind_register_value_object_field:Tb,_embind_register_void:Ub,_emscripten_dlopen_js:Vb,_emscripten_dlsync_threads:Wb,_emscripten_get_dynamic_libraries_js:Xb,_emscripten_init_main_thread_js:Yb,_emscripten_notify_mailbox_postmessage:Zb,_emscripten_receive_on_main_thread_js:$b,_emscripten_runtime_keepalive_clear:ac,_emscripten_thread_cleanup:bc,_emscripten_thread_exit_joinable:cc,_emscripten_thread_mailbox_await:Da,
_emscripten_thread_set_strongref:dc,_emval_array_to_memory_view:ec,_emval_create_invoker:fc,_emval_decref:gc,_emval_get_global:hc,_emval_get_module_property:ic,_emval_get_property:jc,_emval_incref:kc,_emval_instanceof:lc,_emval_invoke:mc,_emval_is_number:nc,_emval_is_string:oc,_emval_new_cstring:pc,_emval_run_destructors:qc,_emval_set_property:rc,_emval_typeof:sc,_gmtime_js:tc,_localtime_js:uc,_mmap_js:vc,_munmap_js:wc,_tzset_js:xc,clock_time_get:yc,emscripten_check_blocking_allowed:zc,emscripten_date_now:Ac,
emscripten_err:Bc,emscripten_exit_with_live_runtime:Cc,emscripten_get_heap_max:Dc,emscripten_get_now:Ec,emscripten_num_logical_cores:Fc,emscripten_promise_destroy:Gc,emscripten_promise_resolve:Hc,emscripten_resize_heap:Ic,environ_get:Jc,environ_sizes_get:Kc,exit:Lc,fd_close:Mc,fd_fdstat_get:Nc,fd_read:Oc,fd_seek:Pc,fd_write:Qc,ffi_call_js:Rc,heif_error_success:Sc,memory:wa,proc_exit:Tc,random_get:Uc};var a=new Proxy(new Set(["__lsan_ignore_object"]),Vc);return{env:J,wasi_snapshot_preview1:J,"GOT.mem":a,
"GOT.func":a}}
async function ya(){function a(d,e){var f=Ra=d.exports;Wc(Ra);var g=Xc(e);Yc(Ra._emscripten_tls_init,d.exports,g);d=Ra;Zc=d.pthread_self;$c=d.malloc;n._main=d.main;K=d.free;ad=d.fflush;bd=d.calloc;n.__ZnamSt11align_val_t=d._ZnamSt11align_val_t;cd=d.__getTypeName;Ea=d._embind_initialize_bindings;n._emscripten_builtin_free=d.emscripten_builtin_free;dd=d.emscripten_builtin_memalign;n._emscripten_builtin_malloc=d.emscripten_builtin_malloc;ed=d.__funcs_on_exit;n.___libc_calloc=d.__libc_calloc;n.___libc_free=
d.__libc_free;n.___libc_malloc=d.__libc_malloc;fd=d.__dl_seterr;gd=d._emscripten_dlsync_self_async;hd=d._emscripten_dlsync_self;jd=d._emscripten_proxy_dlsync_async;kd=d._emscripten_proxy_dlsync;ld=d._emscripten_find_dylib;Ba=d._emscripten_thread_init;md=d.__set_thread_state;Ia=d._emscripten_thread_crashed;nd=d._emscripten_run_js_on_main_thread_done;od=d._emscripten_run_js_on_main_thread;pd=d._emscripten_thread_free_data;qd=d._emscripten_thread_exit;n._strndup=d.strndup;rd=d._emscripten_check_mailbox;
n.__ZdaPvm=d._ZdaPvm;n.___libc_realloc=d.__libc_realloc;n._emscripten_builtin_calloc=d.emscripten_builtin_calloc;n._emscripten_builtin_realloc=d.emscripten_builtin_realloc;n._malloc_size=d.malloc_size;n._malloc_usable_size=d.malloc_usable_size;n._reallocf=d.reallocf;sd=d.emscripten_get_sbrk_ptr;Ta=d.__trap;td=d.emscripten_stack_set_limits;ud=d._emscripten_stack_restore;vd=d._emscripten_stack_alloc;wd=d.emscripten_stack_get_current;xd=d.__thrown_object_from_unwind_exception;yd=d.__get_exception_message;
M=d.__indirect_function_table;zd=d.__cpp_exception;Ad=d.__heap_base.value;Bd(f);Cd("__main__",0,J);Dd();na=e;return Ra}var b=Ya();if(n.instantiateWasm)return new Promise(d=>{n.instantiateWasm(b,(e,f)=>{d(a(e,f))})});if(r){var c=new WebAssembly.Instance(na,Ya());return a(c,na)}Ua??=n.locateFile?ha("vips.wasm"):(new URL("vips.wasm",import.meta.url)).href;return function(d){return a(d.instance,d.module)}(await Xa(b))}var Fd=a=>{if(!(a instanceof Ed||"unwind"==a))throw a;};
class Ed{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var N=0,Gd=a=>{a.terminate();a.onmessage=()=>{}},Md=a=>{var b=Hd[a];Id.delete(a);a in Jd&&Jd[a].resolve();a=b.X;delete Hd[a];Kd.push(b);Ld.splice(Ld.indexOf(b),1);b.X=0;pd(a)},Qa=a=>{for(;0<a.length;)a.shift()(n)},Nd=[],Od=a=>{Id.add(a);a in Jd&&Jd[a].resolve()},Pd=0,Qd=null,Rd=()=>{Pd--;n.monitorRunDependencies?.(Pd);if(0==Pd&&Qd){var a=Qd;Qd=null;a()}},Sd=()=>{Pd++;n.monitorRunDependencies?.(Pd)},Vd=a=>{0==Kd.length&&(Td(),Ud(Kd[0]));var b=Kd.pop();if(!b)return 6;Ld.push(b);Hd[a.X]=b;b.X=a.X;b.postMessage({V:"run",
sc:a.rc,Ea:a.Ea,X:a.X},a.tb);return 0},Wd=!Atomics.waitAsync||globalThis.navigator?.userAgent&&91>Number((navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./)||[])[2]),Kd=[],Ld=[],Xd=[],Hd={};function Yd(){for(var a=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;a--;)Td();Nd.push(async()=>{var b=Zd();Sd("loading-workers");await b;Rd("loading-workers")});Jd={};Id=new Set}var $d=()=>{for(var a of Ld)Gd(a);for(a of Kd)Gd(a);Kd=[];Ld=[];Hd={}};function Ca(){Xd.forEach(a=>a())}
var Ud=a=>new Promise(b=>{a.onmessage=f=>{var g=f.data;f=g.V;if(g.Da&&g.Da!=Zc()){var h=Hd[g.Da];h?h.postMessage(g,g.tb):w(`worker sent message (${f}) to pthread (${g.Da}) that no longer exists`)}else if("checkMailbox"===f)Ga();else if("spawnThread"===f)Vd(g);else if("cleanupThread"===f)ae(()=>Md(g.Ua));else if("markAsFinished"===f)Od(g.Ua);else if("loaded"===f)a.loaded=!0,b(a);else if("setimmediate"===g.target)a.postMessage(g);else if("callHandler"===f)n[g.Rb](...g.Ab);else f&&w(`worker sent an unknown command ${f}`)};
a.onerror=f=>{w(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)n.propertyIsEnumerable(e)&&c.push(e);a.postMessage({V:"load",Sb:c,vc:wa,wc:na,Gb:la,pc:sa})});async function Zd(){if(!r)return Promise.all(Kd.map(Ud))}
function Td(){if(n.mainScriptUrlOrBlob){var a=n.mainScriptUrlOrBlob;"string"!=typeof a&&(a=URL.createObjectURL(a));a=new Worker(a,{type:"module",name:"em-pthread"})}else a=new Worker(new URL("vips-es6.js",import.meta.url),{type:"module",name:"em-pthread"});Kd.push(a)}var Id,Jd,be,O=(a,b,...c)=>{var d=16*c.length,e=wd(),f=vd(d),g=f>>3,h;for(h of c)"bigint"==typeof h?(H[g++]=1n,H[g++]=h):(H[g++]=0n,Ma[g++]=h);a=od(a,0,d,f,b);ud(e);return a};
function Tc(a){if(r)return O(0,1,a);pa=a;ce||0<N||($d(),n.onExit?.(a),oa=!0);throw new Ed(a);}Tc.g="vi";function de(a){if(r)return O(1,0,a);Lc(a)}var Lc=a=>{pa=a;if(r)throw de(a),"unwind";if(!(ce||0<N||r)){ed();FS.Ia=!1;ad(0);for(var b of FS.streams)b&&FS.close(b);$d();b=Zc();md(0,0,0,1);Wd||Atomics.notify(F,b>>2);Ka=!0}Tc(a)};Lc.g="vi";
var ae=a=>{if(!Ka&&!oa)try{a()}catch(b){Fd(b)}finally{if(!(Ka||ce||0<N))try{r?Zc()&&qd(pa):Lc(pa)}catch(b){Fd(b)}}},ee=a=>{N+=1;setTimeout(()=>{--N;ae(a)},1E4)},fe=[],ge={},he=!1;
function ie(){function a(){he=document.pointerLockElement===n.canvas}if(!je){je=!0;fe.push({canHandle:c=>!n.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c),handle:async(c,d)=>{var e=new Blob([c],{type:ke(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:ke(d)}));var f=URL.createObjectURL(e);return new Promise((g,h)=>{var k=new Image;k.onload=()=>{var l=document.createElement("canvas");l.width=k.width;l.height=k.height;l.getContext("2d").drawImage(k,0,0);URL.revokeObjectURL(f);
g(c)};k.onerror=()=>{w(`Image ${f} could not be decoded`);h()};k.src=f})}});fe.push({canHandle:c=>!n.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(c,d)=>new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,h=URL.createObjectURL(new Blob([c],{type:ke(d)})),k=new Audio;k.addEventListener("canplaythrough",()=>f(k),!1);k.onerror=()=>{if(!g){w(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);for(var l="",m=0,q=0,t=0;t<c.length;t++)for(m=m<<
8|c[t],q+=8;6<=q;){var p=m>>q-6&63;q-=6;l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[p]}2==q?(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(m&3)<<4],l+="=="):4==q&&(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(m&15)<<2],l+="=");k.src="data:audio/x-"+d.slice(-3)+";base64,"+l;f(k)}};k.src=h;ee(()=>{f(k)})})});var b=n.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),n.elementPointerLock&&b.addEventListener("click",
c=>{!he&&n.canvas.requestPointerLock&&(n.canvas.requestPointerLock(),c.preventDefault())},!1))}}function ke(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}var le={},je,me={},Vc={get(a,b){var c=me[b];c||=me[b]=new WebAssembly.Global({value:"i32",mutable:!0},-1);a.has(b)||(c.required=!0);return c}},y,F,H,x,La,Ma,E,G,Na,A,ne=[];function Aa(a){var b=G[a+48>>2];td(b,b-G[a+52>>2]);ud(b)}
var oe=new TextDecoder,pe=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},qe=(a,b=0,c)=>{c=pe(a,b,c);return oe.decode(a.buffer?a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c):new Uint8Array(a.slice(b,c)))},Xc=a=>{function b(){for(var q=0,t=1;;){var p=a[f++];q+=(p&127)*t;t*=128;if(!(p&128))break}return q}function c(){var q=b();f+=q;return qe(a,f-q,q)}function d(){for(var q=b(),t=[];q--;)t.push(c());return t}function e(q,t){if(q)throw Error(t);}var f=0,g=0;if(a instanceof
WebAssembly.Module)g=WebAssembly.Module.customSections(a,"dylink.0"),e(0===g.length,"need dylink section"),a=new Uint8Array(g[0]),g=a.length;else{g=1836278016==(new Uint32Array((new Uint8Array(a.subarray(0,24))).buffer))[0];e(!g,"need to see wasm magic number");e(0!==a[8],"need the dylink section to be first");f=9;g=b();g=f+g;var h=c();e("dylink.0"!==h)}for(h={Oa:[],sb:new Set,vb:new Set,pb:[]};f<g;){var k=a[f++],l=b();if(1===k)h.Na=b(),h.$b=b(),h.ta=b(),h.Qc=b();else if(2===k)h.Oa=d();else if(3===
k)for(k=b();k--;){l=c();var m=b();m&256&&h.sb.add(l)}else if(4===k)for(k=b();k--;)c(),l=c(),m=b(),1==(m&3)&&h.vb.add(l);else 5===k?h.pb=d():f+=l}return h},Fa=(a,b)=>{ce=N=0;hd();a=M.get(a)(b);ce||0<N?pa=a:qd(a)},Cd=(a,b,c)=>{c={Aa:Infinity,name:a,exports:c,global:!0};re[a]=c;void 0!=b&&(se[b]=c);return c},re={},se={},te=(a,b)=>Math.ceil(a/b)*b,ue=a=>{if(Ja)return bd(a,1);var b=Ad;Ad=a=b+16*Math.ceil(a/16);if(!r){var c=sd();G[c>>2]=a}return b},we=(a,b)=>{if(ve)for(var c=a;c<a+b;c++){var d=M.get(c);
d&&ve.set(d,c)}},ve,xe=a=>{ve||(ve=new WeakMap,we(0,M.length));return ve.get(a)||0},ye=[],ze=a=>{const b=a.length;return[b%128|128,b>>7,...a]},Ae={i:127,p:127,j:126,f:125,d:124,e:111},Be=a=>ze(Array.from(a,b=>Ae[b])),Ce=(a,b)=>{var c=xe(a);if(c)return c;c=ye.length?ye.pop():M.grow(1);try{M.set(c,a)}catch(d){if(!(d instanceof TypeError))throw d;b=Uint8Array.of(0,97,115,109,1,0,0,0,1,...ze([1,96,...Be(b.slice(1)),...Be("v"===b[0]?"":b[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(b);
b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f;M.set(c,b)}ve.set(a,c);return c},Bd=(a,b)=>{for(var c in a){var d=c;if(!"memory __memory_base __table_base __stack_pointer __indirect_function_table __cpp_exception __c_longjmp __wasm_apply_data_relocs __dso_handle __tls_size __tls_align __set_stack_limits _emscripten_tls_init __wasm_init_tls __wasm_call_ctors __start_em_asm __stop_em_asm __start_em_js __stop_em_js".split(" ").includes(d)&&!d.startsWith("__em_js__")){d=a[c];var e=me[c]&&-1!=me[c].value;
if(b||!e){if("function"==typeof d)d=Ce(d);else if("number"!=typeof d.value)continue;let f;me[f=c]??(me[f]=new WebAssembly.Global({value:"i32",mutable:!0}));me[c].value=d}}}},De=(a,b=0)=>{var c={},d;for(d in a){var e=d;var f=a[d];a:{if(f instanceof WebAssembly.Global)try{f.value=f.value}catch{var g=!0;break a}g=!1}f=g?new WebAssembly.Global({value:"i32"},f.value+b):f;c[e]=f}return c},Ee=a=>{a=J[a];return!a||a.Ba?!1:!0},Fe=(a,b)=>Object.defineProperty(b,"name",{value:a}),Ge=a=>{var b;Ee(a)&&(b=J[a]);
return{Ta:b,name:a}},Sa=[],P=(a,b,c)=>a?oe.decode(A.slice(a,pe(A,a,b,c))):"",Le=(a,b,c,d,e)=>{function f(){function k(C,z){function B(ua,Y){ua=[];for(var wb=0;;wb++){var $a="$"+wb;if(!Y.includes($a))break;ua.push($a)}ua=ua.join(",");He[D]=eval(`(${ua}) => { ${Y} };`)}function L(ua,Y,wb){var $a=[];Y=Y.slice(1,-1);if("void"!=Y){Y=Y.split(",");for(var zg of Y)Y=zg.split(" ").pop(),$a.push(Y.replaceAll("*",""))}p[ua]=eval(`(${$a}) => ${wb};`)}!r&&c&&(sa[c]=C);we(t,g.ta);p=De(z.exports,q);Bd(p);b.zb||
Ie();if("__start_em_asm"in p){var D=p.__start_em_asm.value;for(C=p.__stop_em_asm.value;D<C;){var Ha=P(D);B(D,Ha);D=A.indexOf(0,D)+1}}for(var xb in p)if(xb.startsWith("__em_js__")){D=p[xb].value;Ha=P(D);var [Ag,Bg]=Ha.split("<::>");L(xb.replace("__em_js__",""),Ag,Bg);delete p[xb]}Yc(p._emscripten_tls_init,z.exports,g);l&&((z=p.__wasm_apply_data_relocs)&&(Ja?z():Oa.push(z)),(z=p.__wasm_call_ctors)&&(Ja?z():Sa.push(z)));return p}var l=!e||!x[e+8];if(l){var m=Math.pow(2,g.$b),q=g.Na?te(ue(g.Na+m),m):
0,t=g.ta?M.length:0;e&&(x[e+8]=1,G[e+12>>2]=q,F[e+16>>2]=g.Na,G[e+20>>2]=t,F[e+24>>2]=g.ta)}else q=G[e+12>>2],t=G[e+20>>2];g.ta&&M.grow(g.ta);var p;m=new Proxy({},{get(C,z){switch(z){case "__memory_base":return q;case "__table_base":return t}if(z in J&&!J[z].Ba)return J[z];if(!(z in C)){var B;C[z]=(...L)=>{if(!B){var D=Ge(z).Ta;!D&&d&&(D=d[z]);D||=p[z];B=D}return B(...L)}}return C[z]}});var u=new Proxy(g.vb,Vc),v={"GOT.mem":u,"GOT.func":u,env:m,wasi_snapshot_preview1:m};if(b.I)return(async()=>{var C;
a instanceof WebAssembly.Module?C=new WebAssembly.Instance(a,v):{module:a,instance:C}=await WebAssembly.instantiate(a,v);return k(a,C)})();m=a instanceof WebAssembly.Module?a:new WebAssembly.Module(a);u=new WebAssembly.Instance(m,v);return k(m,u)}var g=Xc(a);b={...b,Sa:{ec:c,ic:g.pb}};if(b.I)return g.Oa.reduce((k,l)=>k.then(()=>{l=Je(l,b.Sa)??l;return Ke(l,b,d)}),Promise.resolve()).then(f);for(var h of g.Oa)h=Je(h,b.Sa)??h,Ke(h,b,d);return f()},Wc=a=>{var b,c;for([b,c]of Object.entries(a))Ee(b)||
(J[b]=c)},Me=async a=>{a=await ia(a);return new Uint8Array(a)},Ne=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Oe=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ne(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Pe=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";
b&&=b.slice(0,-1);return a+b},Qe=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Re=(a,b)=>Oe(a+"/"+b),Se=a=>{var b=wd();a=a();ud(b);return a},Te=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Q=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=
224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Ue=a=>{var b=Te(a)+1,c=vd(b);Q(a,A,c,b);return c},Ve=()=>a=>(a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),0),We=a=>(We=Ve())(a),Xe=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:FS.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===
c.charAt(0)}b=Ne(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ye=(a,b)=>{function c(g){for(var h=0;h<g.length&&""===g[h];h++);for(var k=g.length-1;0<=k&&""===g[k];k--);return h>k?[]:g.slice(h,k-h+1)}a=Xe(a).slice(1);b=Xe(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Ze=[],$e=a=>{var b=Array(Te(a)+1);a=Q(a,b,0,b.length);
b.length=a;return b},af=[];function bf(a,b){af[a]={input:[],output:[],ea:b};FS.registerDevice(a,cf)}
var cf={open(a){var b=af[a.node.ra];if(!b)throw new FS.h(43);a.C=b;a.seekable=!1},close(a){a.C.ea.xa(a.C)},xa(a){a.C.ea.xa(a.C)},read(a,b,c,d){if(!a.C||!a.C.ea.eb)throw new FS.h(60);for(var e=0,f=0;f<d;f++){try{var g=a.C.ea.eb(a.C)}catch(h){throw new FS.h(29);}if(void 0===g&&0===e)throw new FS.h(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.$=Date.now());return e},write(a,b,c,d){if(!a.C||!a.C.ea.Qa)throw new FS.h(60);try{for(var e=0;e<d;e++)a.C.ea.Qa(a.C,b[c+e])}catch(f){throw new FS.h(29);
}d&&(a.node.O=a.node.N=Date.now());return e}},df={eb(){a:{if(!Ze.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ze=$e(a)}a=Ze.shift()}return a},Qa(a,b){null===b||10===b?(ka(qe(a.output)),a.output=[]):0!=b&&a.output.push(b)},xa(a){0<a.output?.length&&(ka(qe(a.output)),a.output=[])},Vb(){return{Cc:25856,Ec:5,Bc:191,Dc:35387,Ac:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Wb(){return 0},Xb(){return[24,
80]}},ef={Qa(a,b){null===b||10===b?(w(qe(a.output)),a.output=[]):0!=b&&a.output.push(b)},xa(a){0<a.output?.length&&(w(qe(a.output)),a.output=[])}},ff=a=>{a=65536*Math.ceil(a/65536);var b=dd(65536,a);b&&A.fill(0,b,b+a);return b},R={W:null,mount(){return R.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=FS.isBlkdev(c))||(e=4096===(c&61440));if(e)throw new FS.h(63);R.W||(R.W={dir:{node:{S:R.m.S,U:R.m.U,ia:R.m.ia,ca:R.m.ca,rename:R.m.rename,unlink:R.m.unlink,rmdir:R.m.rmdir,sa:R.m.sa,symlink:R.m.symlink},
stream:{llseek:R.o.llseek}},file:{node:{S:R.m.S,U:R.m.U},stream:{llseek:R.o.llseek,read:R.o.read,write:R.o.write,ja:R.o.ja,la:R.o.la}},link:{node:{S:R.m.S,U:R.m.U,readlink:R.m.readlink},stream:{}},Wa:{node:{S:R.m.S,U:R.m.U},stream:FS.Cb}});c=FS.createNode(a,b,c,d);FS.isDir(c.mode)?(c.m=R.W.dir.node,c.o=R.W.dir.stream,c.u={}):FS.isFile(c.mode)?(c.m=R.W.file.node,c.o=R.W.file.stream,c.L=0,c.u=R.Hb??(R.Hb=new Uint8Array(0))):FS.isLink(c.mode)?(c.m=R.W.link.node,c.o=R.W.link.stream):FS.isChrdev(c.mode)&&
(c.m=R.W.Wa.node,c.o=R.W.Wa.stream);c.$=c.O=c.N=Date.now();a&&(a.u[b]=c,a.$=a.O=a.N=c.$);return c},m:{S(a){var b={};b.Eb=FS.isChrdev(a.mode)?a.id:1;b.Ub=a.id;b.mode=a.mode;b.ac=1;b.uid=0;b.Qb=0;b.ra=a.ra;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.L:FS.isLink(a.mode)?b.size=a.link.length:b.size=0;b.$=new Date(a.$);b.O=new Date(a.O);b.N=new Date(a.N);b.Bb=4096;b.Va=Math.ceil(b.size/b.Bb);return b},U(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&
(b=b.size,a.L!=b&&(c=a.u,a.u=new Uint8Array(b),a.u.set(c.subarray(0,Math.min(b,a.L))),a.L=b))},ia(){R.Fa||(R.Fa=new FS.h(44),R.Fa.stack="<generic error, no stack>");throw R.Fa;},ca(a,b,c,d){return R.createNode(a,b,c,d)},rename(a,b,c){try{var d=gf(b,c)}catch(f){}if(d){if(FS.isDir(a.mode))for(var e in d.u)throw new FS.h(55);hf(d)}delete a.parent.u[a.name];b.u[c]=a;a.name=c;b.N=b.O=a.parent.N=a.parent.O=Date.now()},unlink(a,b){delete a.u[b];a.N=a.O=Date.now()},rmdir(a,b){var c=gf(a,b),d;for(d in c.u)throw new FS.h(55);
delete a.u[b];a.N=a.O=Date.now()},sa(a){return[".","..",...Object.keys(a.u)]},symlink(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(!FS.isLink(a.mode))throw new FS.h(28);return a.link}},o:{read(a,b,c,d,e){if(e>=a.node.L)return 0;d=Math.min(a.node.L-e,d);b.set(a.node.u.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.O=a.N=Date.now();if(f)a.u=b.subarray(c,c+d),a.L=d;else if(0===a.L&&0===e)a.u=b.slice(c,c+d),a.L=d;else{f=e+d;var g=a.u.length;g>=f||(f=
Math.max(f,g*(1048576>g?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.u.subarray(0,a.L),a.u=new Uint8Array(f),a.u.set(g));a.u.set(b.subarray(c,c+d),e);a.L=Math.max(a.L,e+d)}return d},llseek(a,b,c){1===c?b+=a.position:2===c&&FS.isFile(a.node.mode)&&(b+=a.node.L);if(0>b)throw new FS.h(28);return b},ja(a,b,c,d,e){if(!FS.isFile(a.node.mode))throw new FS.h(43);a=a.node.u;if(e&2||a.buffer!==x.buffer){d=!0;e=ff(b);if(!e)throw new FS.h(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);x.set(a,e)}}else d=!1,e=a.byteOffset;return{A:e,fa:d}},la(a,b,c,d){R.o.write(a,b,0,d,c,!1);return 0}}},jf=a=>{"string"==typeof a&&(a=$e(a));a.subarray||(a=new Uint8Array(a));return a},kf=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},lf=async(a,b)=>{"undefined"!=typeof le&&ie();for(var c of fe)if(c.canHandle(b))return c.handle(a,b);return a},mf=async(a,b,c,d,e,f,g,h)=>{var k=b?Xe(Oe(a+"/"+b)):a,l=`cp ${k}`;Sd(l);try{var m=c;"string"==typeof c&&(m=await Me(c));m=await lf(m,k);h?.();f||FS.createDataFile(a,
b,m,d,e,g)}finally{Rd(l)}};function gf(a,b){var c=FS.isDir(a.mode)?(c=nf(a,"x"))?c:a.m.ia?0:2:54;if(c)throw new FS.h(c);for(c=FS.da[of(a.id,b)];c;c=c.ka){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return FS.ia(a,b)}function hf(a){var b=of(a.parent.id,a.name);if(FS.da[b]===a)FS.da[b]=a.ka;else for(b=FS.da[b];b;){if(b.ka===a){b.ka=a.ka;break}b=b.ka}}function of(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%FS.da.length}
function pf(a){var b=of(a.parent.id,a.name);a.ka=FS.da[b];FS.da[b]=a}function nf(a,b){return FS.fb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function qf(a,b){if(!FS.isDir(a.mode))return 54;try{return gf(a,b),20}catch(c){}return nf(a,"wx")}
function rf(a,b,c){try{var d=gf(a,b)}catch(e){return e.B}if(a=nf(a,"wx"))return a;if(c){if(!FS.isDir(d.mode))return 54;if(FS.na(d)||FS.getPath(d)===FS.cwd())return 10}else if(FS.isDir(d.mode))return 31;return 0}function sf(a,b){if(!a)throw new FS.h(b);return a}function S(a){a=FS.cb(a);if(!a)throw new FS.h(8);return a}function tf(a,b=-1){a=Object.assign(new FS.xb,a);if(-1==b)a:{for(b=0;b<=FS.yb;b++)if(!FS.streams[b])break a;throw new FS.h(33);}a.aa=b;return FS.streams[b]=a}
function uf(a,b=-1){a=tf(a,b);a.o?.Gc?.(a);return a}function vf(a,b,c){var d=a?.o.U;a=d?a:b;d??=b.m.U;sf(d,63);try{d(a,c)}catch(e){if(e instanceof RangeError)throw new FS.h(22);throw e;}}function wf(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.oa)}return b}function xf(a){var b={zc:4096,Jc:4096,Va:1E6,yc:5E5,xc:5E5,files:FS.Pa,Hc:FS.Pa-1,Kc:42,flags:2,Nc:255};a.m.rb&&Object.assign(b,a.m.rb(a.mount.cc.root));return b}
function yf(a,b,c,d){vf(a,b,{mode:c&4095|b.mode&-4096,N:Date.now(),$a:d})}function zf(a,b,c){if(FS.isDir(b.mode))throw new FS.h(31);if(!FS.isFile(b.mode))throw new FS.h(28);var d=nf(b,"w");if(d)throw new FS.h(d);vf(a,b,{size:c,timestamp:Date.now()})}function Af(a,b,c,d){a="string"==typeof a?a:FS.getPath(a);b=Oe(a+"/"+b);return FS.create(b,kf(c,d))}
function Bf(a){if(!(a.Yb||a.Zb||a.link||a.u))if(globalThis.XMLHttpRequest)I("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.u=ja(a.url)}catch(b){throw new FS.h(29);}}
var FS={root:null,oa:[],Za:{},streams:[],Pa:1,da:null,Xa:"/",Ia:!1,fb:!0,Kb:null,Ca:0,h:class{name="ErrnoError";constructor(a){this.B=a}},xb:class{P={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.P.flags}set flags(a){this.P.flags=a}get position(){return this.P.position}set position(a){this.P.position=a}},wb:class{m={};o={};T=null;constructor(a,b,c,d){a||=this;this.parent=a;this.mount=a.mount;this.id=FS.Pa++;this.name=b;this.mode=c;this.ra=d;this.$=this.O=
this.N=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Zb(){return FS.isDir(this.mode)}get Yb(){return FS.isChrdev(this.mode)}},lookupPath(a,b={}){if(!a)throw new FS.h(44);b.wa??(b.wa=!0);"/"===a.charAt(0)||(a=FS.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(h=>!!h);for(var d=FS.root,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;
if("."!==a[f])if(".."===a[f])if(e=Pe(e),FS.na(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Oe(e+"/"+a[f]);try{d=gf(d,a[f])}catch(h){if(44===h?.B&&g&&b.bc)return{path:e};throw h;}!d.T||g&&!b.wa||(d=d.T.root);if(FS.isLink(d.mode)&&(!g||b.follow)){if(!d.m.readlink)throw new FS.h(52);d=d.m.readlink(d);"/"===d.charAt(0)||(d=Pe(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new FS.h(32);},getPath(a){for(var b;;){if(FS.na(a))return a=a.mount.jb,
b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},createNode(a,b,c,d){a=new FS.wb(a,b,c,d);pf(a);return a},na(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isDir(a){return 16384===(a&61440)},isLink(a){return 40960===(a&61440)},isChrdev(a){return 8192===(a&61440)},isBlkdev(a){return 24576===(a&61440)},isSocket(a){return 49152===(a&49152)},yb:4096,cb:a=>FS.streams[a],Cb:{open(a){a.o=FS.Mb(a.node.ra).o;a.o.open?.(a)},llseek(){throw new FS.h(70);}},Ma:a=>a>>
8,Lc:a=>a&255,makedev:(a,b)=>a<<8|b,registerDevice(a,b){FS.Za[a]={o:b}},Mb:a=>FS.Za[a],syncfs(a,b){function c(h){FS.Ca--;return b(h)}function d(h){if(h){if(!d.Ib)return d.Ib=!0,c(h)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);FS.Ca++;1<FS.Ca&&w(`warning: ${FS.Ca} FS.syncfs operations in flight at once, probably just doing extra work`);var e=wf(FS.root.mount),f=0,g;for(g of e)g.type.syncfs?g.type.syncfs(g,a,d):d(null)},mount(a,b,c){var d="/"===c;if(d&&FS.root)throw new FS.h(10);if(!d&&
c){var e=FS.lookupPath(c,{wa:!1});c=e.path;e=e.node;if(e.T)throw new FS.h(10);if(!FS.isDir(e.mode))throw new FS.h(54);}b={type:a,cc:b,jb:c,oa:[]};a=a.mount(b);a.mount=b;b.root=a;d?FS.root=a:e&&(e.T=b,e.mount&&e.mount.oa.push(b));return a},unmount(a){a=FS.lookupPath(a,{wa:!1});if(!a.node.T)throw new FS.h(28);a=a.node;var b=a.T,c=wf(b);for([,e]of Object.entries(FS.da))for(;e;){var d=e.ka;c.includes(e.mount)&&hf(e);var e=d}a.T=null;a.mount.oa.splice(a.mount.oa.indexOf(b),1)},ia(a,b){return a.m.ia(a,
b)},ca(a,b,c){var d=FS.lookupPath(a,{parent:!0}).node;a=Qe(a);if(!a)throw new FS.h(28);if("."===a||".."===a)throw new FS.h(20);var e=qf(d,a);if(e)throw new FS.h(e);if(!d.m.ca)throw new FS.h(63);return d.m.ca(d,a,b,c)},rb(a){return xf(FS.lookupPath(a,{follow:!0}).node)},Pc(a){return xf(a.node)},create(a,b=438){return FS.ca(a,b&4095|32768,0)},mkdir(a,b=511){return FS.ca(a,b&1023|16384,0)},Mc(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{FS.mkdir(d,b)}catch(f){if(20!=
f.B)throw f;}}},mkdev(a,b,c){"undefined"==typeof c&&(c=b,b=438);return FS.ca(a,b|8192,c)},symlink(a,b){if(!Xe(a))throw new FS.h(44);var c=FS.lookupPath(b,{parent:!0}).node;if(!c)throw new FS.h(44);b=Qe(b);var d=qf(c,b);if(d)throw new FS.h(d);if(!c.m.symlink)throw new FS.h(63);return c.m.symlink(c,b,a)},rename(a,b){var c=Pe(a),d=Pe(b),e=Qe(a),f=Qe(b);var g=FS.lookupPath(a,{parent:!0});var h=g.node;g=FS.lookupPath(b,{parent:!0});g=g.node;if(!h||!g)throw new FS.h(44);if(h.mount!==g.mount)throw new FS.h(75);
var k=gf(h,e);a=Ye(a,d);if("."!==a.charAt(0))throw new FS.h(28);a=Ye(b,c);if("."!==a.charAt(0))throw new FS.h(55);try{var l=gf(g,f)}catch(m){}if(k!==l){b=FS.isDir(k.mode);if(e=rf(h,e,b))throw new FS.h(e);if(e=l?rf(g,f,b):qf(g,f))throw new FS.h(e);if(!h.m.rename)throw new FS.h(63);if(k.T||l&&l.T)throw new FS.h(10);if(g!==h&&(e=nf(h,"w")))throw new FS.h(e);hf(k);try{h.m.rename(k,g,f),k.parent=g}catch(m){throw m;}finally{pf(k)}}},rmdir(a){var b=FS.lookupPath(a,{parent:!0}).node;a=Qe(a);var c=gf(b,a),
d=rf(b,a,!0);if(d)throw new FS.h(d);if(!b.m.rmdir)throw new FS.h(63);if(c.T)throw new FS.h(10);b.m.rmdir(b,a);hf(c)},sa(a){a=FS.lookupPath(a,{follow:!0}).node;return sf(a.m.sa,54)(a)},unlink(a){var b=FS.lookupPath(a,{parent:!0}).node;if(!b)throw new FS.h(44);a=Qe(a);var c=gf(b,a),d=rf(b,a,!1);if(d)throw new FS.h(d);if(!b.m.unlink)throw new FS.h(63);if(c.T)throw new FS.h(10);b.m.unlink(b,a);hf(c)},readlink(a){a=FS.lookupPath(a).node;if(!a)throw new FS.h(44);if(!a.m.readlink)throw new FS.h(28);return a.m.readlink(a)},
stat(a,b){a=FS.lookupPath(a,{follow:!b}).node;return sf(a.m.S,63)(a)},lstat(a){return FS.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?FS.lookupPath(a,{follow:!c}).node:a;yf(null,a,b,c)},lchmod(a,b){FS.chmod(a,b,!0)},fchmod(a,b){a=S(a);yf(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?FS.lookupPath(a,{follow:!d}).node:a;vf(null,a,{timestamp:Date.now(),$a:d})},lchown(a,b,c){FS.chown(a,b,c,!0)},fchown(a){a=S(a);vf(a,a.node,{timestamp:Date.now(),$a:!1})},truncate(a,b){if(0>b)throw new FS.h(28);
a="string"==typeof a?FS.lookupPath(a,{follow:!0}).node:a;zf(null,a,b)},ftruncate(a,b){a=S(a);if(0>b||0===(a.flags&2097155))throw new FS.h(28);zf(a,a.node,b)},utime(a,b,c){a=FS.lookupPath(a,{follow:!0}).node;sf(a.m.U,63)(a,{$:b,O:c})},open(a,b,c=438){if(""===a)throw new FS.h(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");
var f=FS.lookupPath(a,{follow:!(b&131072),bc:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new FS.h(20);}else{if(e)throw new FS.h(31);d=FS.ca(a,c|511,0);f=!0}if(!d)throw new FS.h(44);FS.isChrdev(d.mode)&&(b&=-513);if(b&65536&&!FS.isDir(d.mode))throw new FS.h(54);if(!f){e=d;a=b;if(e)if(FS.isLink(e.mode))e=32;else{var g=["r","w","rw"][a&3];a&512&&(g+="w");e=FS.isDir(e.mode)&&("r"!==g||a&576)?31:nf(e,g)}else e=44;if(e)throw new FS.h(e);}b&512&&!f&&FS.truncate(d,0);b&=-131713;b=tf({node:d,
path:FS.getPath(d),flags:b,seekable:!0,position:0,o:d.o,uc:[],error:!1});b.o.open&&b.o.open(b);f&&FS.chmod(d,c&511);return b},close(a){if(null===a.aa)throw new FS.h(8);a.Ga&&(a.Ga=null);try{a.o.close&&a.o.close(a)}catch(b){throw b;}finally{FS.streams[a.aa]=null}a.aa=null},llseek(a,b,c){if(null===a.aa)throw new FS.h(8);if(!a.seekable||!a.o.llseek)throw new FS.h(70);if(0!=c&&1!=c&&2!=c)throw new FS.h(28);a.position=a.o.llseek(a,b,c);a.uc=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new FS.h(28);
if(null===a.aa)throw new FS.h(8);if(1===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.read)throw new FS.h(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new FS.h(28);if(null===a.aa)throw new FS.h(8);if(0===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.write)throw new FS.h(28);a.seekable&&
a.flags&1024&&FS.llseek(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.write(a,b,c,d,e,f);g||(a.position+=b);return b},ja(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new FS.h(2);if(1===(a.flags&2097155))throw new FS.h(2);if(!a.o.ja)throw new FS.h(43);if(!b)throw new FS.h(28);return a.o.ja(a,b,c,d,e)},la(a,b,c,d,e){return a.o.la?a.o.la(a,b,c,d,e):0},Ja(a,b,c){if(!a.o.Ja)throw new FS.h(59);return a.o.Ja(a,b,c)},readFile(a,b={}){b.flags=
b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&I(`Invalid encoding type "${b.encoding}"`);var c=FS.open(a,b.flags);a=FS.stat(a).size;var d=new Uint8Array(a);FS.read(c,d,0,a,0);"utf8"===b.encoding&&(d=qe(d));FS.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=FS.open(a,c.flags,c.mode);b=jf(b);FS.write(a,b,0,b.byteLength,void 0,c.Fc);FS.close(a)},cwd:()=>FS.Xa,chdir(a){a=FS.lookupPath(a,{follow:!0});if(null===a.node)throw new FS.h(44);if(!FS.isDir(a.node.mode))throw new FS.h(54);
var b=nf(a.node,"x");if(b)throw new FS.h(b);FS.Xa=a.path},init(a,b,c){FS.Ia=!0;a??=n.stdin;b??=n.stdout;c??=n.stderr;a?FS.createDevice("/dev","stdin",a):FS.symlink("/dev/tty","/dev/stdin");b?FS.createDevice("/dev","stdout",null,b):FS.symlink("/dev/tty","/dev/stdout");c?FS.createDevice("/dev","stderr",null,c):FS.symlink("/dev/tty1","/dev/stderr");FS.open("/dev/stdin",0);FS.open("/dev/stdout",1);FS.open("/dev/stderr",1)},Ic(a,b){a=FS.analyzePath(a,b);return a.ab?a.object:null},analyzePath(a,b){try{var c=
FS.lookupPath(a,{follow:!b});a=c.path}catch(e){}var d={na:!1,ab:!1,error:0,name:null,path:null,object:null,dc:!1,hc:null,fc:null};try{c=FS.lookupPath(a,{parent:!0}),d.dc=!0,d.hc=c.path,d.fc=c.node,d.name=Qe(a),c=FS.lookupPath(a,{follow:!b}),d.ab=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.na="/"===c.path}catch(e){d.error=e.B}return d},createPath(a,b){a="string"==typeof a?a:FS.getPath(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Oe(a+"/"+c);try{FS.mkdir(d)}catch(e){if(20!=
e.B)throw e;}a=d}}return d},createDataFile(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:FS.getPath(a),g=b?Oe(a+"/"+b):a);a=kf(d,e);g=FS.create(g,a);c&&(c=jf(c),FS.chmod(g,a|146),b=FS.open(g,577),FS.write(b,c,0,c.length,0,f),FS.close(b),FS.chmod(g,a))},createDevice(a,b,c,d){a=Re("string"==typeof a?a:FS.getPath(a),b);b=kf(!!c,!!d);var e;(e=FS.createDevice).Ma??(e.Ma=64);e=FS.makedev(FS.createDevice.Ma++,0);FS.registerDevice(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,h,k){for(var l=
0,m=0;m<k;m++){try{var q=c()}catch(t){throw new FS.h(29);}if(void 0===q&&0===l)throw new FS.h(6);if(null===q||void 0===q)break;l++;g[h+m]=q}l&&(f.node.$=Date.now());return l},write(f,g,h,k){for(var l=0;l<k;l++)try{d(g[h+l])}catch(m){throw new FS.h(29);}k&&(f.node.O=f.node.N=Date.now());return l}});return FS.mkdev(a,b,e)},createLazyFile(a,b,c,d,e){function f(m,q,t,p,u){m=m.node.u;if(u>=m.length)return 0;p=Math.min(m.length-u,p);if(m.slice)for(var v=0;v<p;v++)q[t+v]=m[u+v];else for(v=0;v<p;v++)q[t+
v]=m.get(u+v);return p}class g{Ha=!1;P=[];ma=void 0;ib=0;hb=0;get(m){if(!(m>this.length-1||0>m)){var q=m%this.qb;return this.ma(m/this.qb|0)[q]}}tc(m){this.ma=m}kb(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);200<=m.status&&300>m.status||304===m.status||I("Couldn't load "+c+". Status: "+m.status);var q=Number(m.getResponseHeader("Content-length")),t,p=(t=m.getResponseHeader("Accept-Ranges"))&&"bytes"===t;m=(t=m.getResponseHeader("Content-Encoding"))&&"gzip"===t;var u=1048576;p||(u=
q);var v=this;v.tc(C=>{var z=C*u,B=(C+1)*u-1;B=Math.min(B,q-1);if("undefined"==typeof v.P[C]){var L=v.P;z>B&&I("invalid range ("+z+", "+B+") or no bytes requested!");B>q-1&&I("only "+q+" bytes available! programmer error!");var D=new XMLHttpRequest;D.open("GET",c,!1);q!==u&&D.setRequestHeader("Range","bytes="+z+"-"+B);D.responseType="arraybuffer";D.overrideMimeType&&D.overrideMimeType("text/plain; charset=x-user-defined");D.send(null);200<=D.status&&300>D.status||304===D.status||I("Couldn't load "+
c+". Status: "+D.status);z=void 0!==D.response?new Uint8Array(D.response||[]):$e(D.responseText||"");L[C]=z}"undefined"==typeof v.P[C]&&I("doXHR failed!");return v.P[C]});if(m||!q)u=q=1,u=q=this.ma(0).length,ka("LazyFiles on gzip forces download of the whole file when length is accessed");this.ib=q;this.hb=u;this.Ha=!0}get length(){this.Ha||this.kb();return this.ib}get qb(){this.Ha||this.kb();return this.hb}}if(globalThis.XMLHttpRequest){ba||I("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var h=new g;var k=void 0}else k=c,h=void 0;var l=Af(a,b,d,e);h?l.u=h:k&&(l.u=null,l.url=k);Object.defineProperties(l,{L:{get:function(){return this.u.length}}});a={};for(const [m,q]of Object.entries(l.o))a[m]=(...t)=>{Bf(l);return q(...t)};a.read=(m,q,t,p,u)=>{Bf(l);return f(m,q,t,p,u)};a.ja=(m,q,t)=>{Bf(l);var p=ff(q);if(!p)throw new FS.h(48);f(m,x,p,q,t);return{A:p,fa:!0}};l.o=a;return l}},Je=(a,b)=>{if(Ja){if("/"===a.charAt(0))try{return FS.lookupPath(a),a}catch(d){return}var c=(b?.ic||[]).map(d=>
{var e=b?.ec;return d.startsWith("$ORIGIN")?d.replace("$ORIGIN",Pe(e)):d});return Se(()=>{var d=vd(512),e=Ue(c.join(":")),f=Ue(a);return(d=ld(d,e,f,512))?P(d):void 0})}};
function Ke(a,b={global:!0,pa:!0},c,d){function e(){var k=sa[a];if(k)return b.I?Promise.resolve(k):k;if(d){k=G[d+28>>2];var l=G[d+32>>2];if(k&&l)return k=x.slice(k,k+l),b.I?Promise.resolve(k):k}if(k=Je(a,b.Sa))return k=FS.readFile(k,{encoding:"binary"}),b.I?Promise.resolve(k):k;k=ha(a);if(b.I)return Me(k);if(!ja)throw Error(`${k}: file not found, and synchronous loading of external files is not available`);return ja(k)}function f(){var k=ge[a];return k?b.I?Promise.resolve(k):k:b.I?e().then(l=>Le(l,
b,a,c,d)):Le(e(),b,a,c,d)}function g(k){h.global?Wc(k):c&&Object.assign(c,k);h.exports=k}var h=re[a];if(h)return b.global?h.global||(h.global=!0,Wc(h.exports)):c&&Object.assign(c,h.exports),b.pa&&Infinity!==h.Aa&&(h.Aa=Infinity),h.Aa++,d&&(se[d]=h),b.I?Promise.resolve(!0):!0;h=Cd(a,d,"loading");h.Aa=b.pa?Infinity:1;h.global=b.global;if(b.I)return f().then(k=>{g(k);return!0});g(f());return!0}
var Ie=()=>{var a,b;for([a,b]of Object.entries(me))if(-1==b.value){var c=Ge(a).Ta;if(c||b.required)if("function"==typeof c)b.value=Ce(c,c.g);else if("number"==typeof c)b.value=c;else if("number"==typeof c.value)b.value=c;else throw Error(`bad export type for '${a}': ${typeof c} (${c})`);else b.value=0}},Dd=async()=>{if(la.length){Sd("loadDylibs");for(var a of la)await Ke(a,{I:!0,global:!0,pa:!0,zb:!0});Ie();Rd("loadDylibs")}else Ie()},ce=!1,Yc=(a,b,c)=>{function d(){var e=a();if(e){var f={};c.sb.forEach(g=>
f[g]=b[g]);Bd(De(f,e),!0)}}Xd.push(d);Ja&&d()},wa,Za=(a,b,c,d)=>I(`Assertion failed: ${P(a)}, at: `+[b?P(b):"unknown filename",c,d?P(d):"unknown function"]);Za.g="vppip";var ab=(a,b)=>M.get(a)(b);ab.g="vpi";function bb(...a){return J.__lsan_ignore_object(...a)}bb.Ba=!0;function Cf(a,b,c,d){return r?O(2,1,a,b,c,d):cb(a,b,c,d)}
var cb=(a,b,c,d)=>{if(!globalThis.SharedArrayBuffer)return 6;var e=[];if(r&&0===e.length)return Cf(a,b,c,d);a={rc:c,X:a,Ea:d,tb:e};return r?(a.V="spawnThread",postMessage(a,e),0):Vd(a)};cb.g="ipppp";var Df=18;function Ef(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?FS.cwd():S(a).path;if(0==b.length){if(!c)throw new FS.h(44);return a}return a+"/"+b}
function Ff(a,b){G[a>>2]=b.Eb;G[a+4>>2]=b.mode;G[a+8>>2]=b.ac;G[a+12>>2]=b.uid;G[a+16>>2]=b.Qb;G[a+20>>2]=b.ra;H[a+24>>3]=BigInt(b.size);F[a+32>>2]=4096;F[a+36>>2]=b.Va;var c=b.$.getTime(),d=b.O.getTime(),e=b.N.getTime();H[a+40>>3]=BigInt(Math.floor(c/1E3));G[a+48>>2]=c%1E3*1E6;H[a+56>>3]=BigInt(Math.floor(d/1E3));G[a+64>>2]=d%1E3*1E6;H[a+72>>3]=BigInt(Math.floor(e/1E3));G[a+80>>2]=e%1E3*1E6;H[a+88>>3]=BigInt(b.Ub);return 0}var Gf=void 0;
function db(a){if(r)return O(3,1,a);try{var b=S(a);return uf(b).aa}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}db.g="ii";function eb(a,b,c,d){if(r)return O(4,1,a,b,c,d);try{b=P(b);b=Ef(a,b);if(c&-8)return-28;var e=FS.lookupPath(b,{follow:!0}).node;if(!e)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&nf(e,a)?-2:0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}eb.g="iipii";var Hf=()=>{var a=F[+Gf>>2];Gf+=4;return a};
function fb(a,b,c){if(r)return O(5,1,a,b,c);Gf=c;try{var d=S(a);switch(b){case 0:var e=Hf();if(0>e)break;for(;FS.streams[e];)e++;return uf(d,e).aa;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Hf(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=Hf(),y[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}fb.g="iiip";
function gb(a,b){if(r)return O(6,1,a,b);try{var c=S(a),d=c.node,e=c.o.S;a=e?c:d;e??=d.m.S;sf(e,63);var f=e(a);return Ff(b,f)}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.B}}gb.g="iip";function hb(a,b){if(r)return O(7,1,a,b);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return-22;FS.ftruncate(a,b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}hb.g="iij";
function ib(a,b){if(r)return O(8,1,a,b);try{if(0===b)return-28;var c=FS.cwd(),d=Te(c)+1;if(b<d)return-68;Q(c,A,a,b);return d}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.B}}ib.g="ipp";
function jb(a,b,c){if(r)return O(9,1,a,b,c);Gf=c;try{var d=S(a);switch(b){case 21509:return d.C?0:-59;case 21505:if(!d.C)return-59;if(d.C.ea.Vb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Hf();F[e>>2]=25856;F[e+4>>2]=5;F[e+8>>2]=191;F[e+12>>2]=35387;for(var f=0;32>f;f++)x[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.C?0:-59;case 21506:case 21507:case 21508:if(!d.C)return-59;if(d.C.ea.Wb)for(e=Hf(),a=[],f=0;32>f;f++)a.push(x[e+f+17]);
return 0;case 21519:if(!d.C)return-59;e=Hf();return F[e>>2]=0;case 21520:return d.C?-28:-59;case 21537:case 21531:return e=Hf(),FS.Ja(d,b,e);case 21523:if(!d.C)return-59;d.C.ea.Xb&&(f=[24,80],e=Hf(),y[e>>1]=f[0],y[e+2>>1]=f[1]);return 0;case 21524:return d.C?0:-59;case 21515:return d.C?0:-59;default:return-28}}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.B}}jb.g="iiip";
function kb(a,b){if(r)return O(10,1,a,b);try{return a=P(a),Ff(b,FS.lstat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}kb.g="ipp";function lb(a,b,c,d){if(r)return O(11,1,a,b,c,d);try{b=P(b);var e=d&256;b=Ef(a,b,d&4096);return Ff(c,e?FS.lstat(b):FS.stat(b))}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}lb.g="iippi";
function mb(a,b,c,d){if(r)return O(12,1,a,b,c,d);Gf=d;try{b=P(b);b=Ef(a,b);var e=d?Hf():0;c&64&&(e&=~Df);return FS.open(b,c,e).aa}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}mb.g="iipip";
function nb(a,b,c){if(r)return O(13,2,a,b,c);try{const u=be;var d,e=new Promise(z=>{d=z}),f=[],g=!1;function v(z){g||(g=!0,f.forEach(B=>B()),d(z))}function C(z,B){return L=>{g||(L&=y[B+4>>1]|24,y[B+6>>1]=L,v(1))}}if(u&&0<c){var h=setTimeout(()=>{v(0)},c);f.push(()=>clearTimeout(h))}for(var k=0,l=0;l<b;l++){var m=a+8*l,q=y[m+4>>1],t=32,p=FS.cb(F[m>>2]);p&&(p.o.lb?t=u&&c?p.o.lb(p,c,C(p,m)):p.o.lb(p,-1):t=5);(t&=q|24)&&k++;y[m+6>>1]=t}return u?(!k&&c||v(k),e):k}catch(u){if("undefined"==typeof FS||"ErrnoError"!==
u.name)throw u;return-u.B}}nb.g="ipii";function ob(a){if(r)return O(14,1,a);try{return a=P(a),FS.rmdir(a),0}catch(b){if("undefined"==typeof FS||"ErrnoError"!==b.name)throw b;return-b.B}}ob.g="ip";function pb(a,b){if(r)return O(15,1,a,b);try{return a=P(a),Ff(b,FS.stat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}pb.g="ipp";
function qb(a,b,c){if(r)return O(16,1,a,b,c);try{b=P(b);b=Ef(a,b);if(c)if(512===c)FS.rmdir(b);else return-28;else FS.unlink(b);return 0}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.B}}qb.g="iipi";var rb=a=>{a=new WebAssembly.Exception(zd,[a],{traceStack:!0});var b=a.getArg(zd,0);var c=xd(b);b=wd();var d=vd(4),e=vd(4);yd(c,d,e);c=G[d>>2];e=G[e>>2];d=P(c);K(c);if(e){var f=P(e);K(e)}ud(b);a.message=[d,f];throw a;},sb=()=>I("");sb.g="v";
var If=a=>{var b=wd();a=Ue(a);fd(a,0);ud(b)},Jf=(a,b)=>{var c=P(a+36),d=F[a+4>>2];c=Oe(c);var e=!!(d&256),f=e?null:{};d={global:e,pa:!!(d&4096),I:b.I};if(b.I)return Ke(c,d,f,a);try{return Ke(c,d,f,a)}catch(g){return If(`could not load dynamic lib: ${c}\n${g}`),0}},tb=a=>Jf(a,{I:!1});tb.g="pp";var ub=(a,b)=>{a=se[a].exports;b=Object.keys(a)[b];b=a[b];return Ce(b,b.g)};ub.g="ppi";
var vb=(a,b,c)=>{b=P(b);var d=se[a];a=Object.keys(d.exports).indexOf(b);if(-1==a||d.exports[b].Ba)return If(`Tried to lookup unknown symbol "${b}" in dynamic lib: ${d.name}`),0;b=d.exports[b];"function"==typeof b&&((d=xe(b))?b=d:(b=Ce(b,b.g),G[c>>2]=a));return b};vb.g="pppp";var Kf={},Lf=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Mf(a){return this.v(G[a>>2])}
var Nf={},Of={},Pf={},Qf=class extends Error{constructor(a){super(a);this.name="InternalError"}},U=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new Qf("Mismatched type converter count");for(var k=0;k<a.length;++k)T(a[k],h[k])}a.forEach(h=>Pf[h]=b);var e=Array(b.length),f=[],g=0;for(let [h,k]of b.entries())Of.hasOwnProperty(k)?e[h]=Of[k]:(f.push(k),Nf.hasOwnProperty(k)||(Nf[k]=[]),Nf[k].push(()=>{e[h]=Of[k];++g;g===f.length&&d(e)}));0===f.length&&d(e)},yb=a=>{var b=Kf[a];delete Kf[a];
var c=b.Ra,d=b.Y,e=b.bb,f=e.map(g=>g.Pb).concat(e.map(g=>g.nc));U([a],f,g=>{var h={},k,l;for([k,l]of e.entries()){const m=g[k],q=l.ma,t=l.Ob,p=g[k+e.length],u=l.mc,v=l.oc;h[l.Jb]={read:C=>m.v(q(t,C)),write:(C,z)=>{var B=[];u(v,C,p.F(B,z));Lf(B)},optional:m.optional}}return[{name:b.name,v:m=>{var q={},t;for(t in h)q[t]=h[t].read(m);d(m);return q},F:(m,q)=>{for(var t in h)if(!(t in q||h[t].optional))throw new TypeError(`Missing field: "${t}"`);var p=c();for(t in h)h[t].write(p,q[t]);null!==m&&m.push(d,
p);return p},K:Mf,H:d}]})};yb.g="vp";var V=a=>{for(var b="";;){var c=A[a++];if(!c)return b;b+=String.fromCharCode(c)}},W=class extends Error{constructor(a){super(a);this.name="BindingError"}},Rf=a=>{throw new W(a);};
function Sf(a,b,c={}){var d=b.name;if(!a)throw new W(`type "${d}" must have a positive integer typeid pointer`);if(Of.hasOwnProperty(a)){if(c.Tb)return;throw new W(`Cannot register type '${d}' twice`);}Of[a]=b;delete Pf[a];Nf.hasOwnProperty(a)&&(b=Nf[a],delete Nf[a],b.forEach(e=>e()))}function T(a,b,c={}){return Sf(a,b,c)}
var zb=(a,b,c,d,e)=>{b=V(b);if(d)a:switch(c){case 4:d=La;break a;case 8:d=Ma;break a;default:throw new TypeError(`invalid float width (${c}): ${b}`);}else a:switch(c){case 1:d=e?x:A;break a;case 2:d=e?y:E;break a;case 4:d=e?F:G;break a;case 8:d=e?H:Na;break a;default:throw new TypeError(`invalid integer width (${c}): ${b}`);}var f=d,g=Math.log2(c);T(a,{name:b,v:h=>{var k=h+Math.max(4,c)>>g;k=Array.from(f.subarray(k,k+G[h>>2]));K(h);return k},F:(h,k)=>{"number"==typeof k&&(k=[k]);if(!Array.isArray(k))throw new W(`Cannot pass non-array to C++ vector type ${b}`);
k=Array.prototype.concat.apply([],k);var l=k.length,m=Math.max(4,c),q=$c(m+l*c);m=q+m>>g;G[q>>2]=l;f.set(k,m);null!==h&&h.push(K,q);return q},K:Mf,H(h){K(h)}})};zb.g="vpppii";
var Tf=(a,b,c)=>{switch(b){case 1:return c?d=>x[d]:d=>A[d];case 2:return c?d=>y[d>>1]:d=>E[d>>1];case 4:return c?d=>F[d>>2]:d=>G[d>>2];case 8:return c?d=>H[d>>3]:d=>Na[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ab=(a,b,c,d,e)=>{b=V(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}T(a,{name:b,v:f,F:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},K:Tf(b,c,!d),H:null})};Ab.g="vpppjj";
var Bb=(a,b,c,d)=>{b=V(b);T(a,{name:b,v:function(e){return!!e},F:function(e,f){return f?c:d},K:function(e){return this.v(A[e])},H:null})};Bb.g="vppii";
var Uf=a=>{throw new W(a.l.D.s.name+" instance already deleted");},Vf=!1,Wf=!1,Xf=()=>{},Yf=a=>{if(Vf)return Yf=b=>b.deleteLater(),Yf(a);if(!globalThis.FinalizationRegistry)return Yf=b=>b,a;Wf=new FinalizationRegistry(b=>{b=b.l;--b.count.value;0===b.count.value&&(b.J?b.R.Y(b.J):b.D.s.Y(b.A))});Yf=b=>{var c=b.l;c.J&&Wf.register(b,{l:c},b);return b};Xf=b=>{Wf.unregister(b)};return Yf(a)},Zf=[],$f=()=>{for(;Zf.length;){var a=Zf.pop();a.l.ha=!1;a["delete"]()}},ag;function bg(){}
var cg={},dg=(a,b,c)=>{if(void 0===a[b].G){var d=a[b];a[b]=function(...e){if(!a[b].G.hasOwnProperty(e.length))throw new W(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].G})!`);return a[b].G[e.length].apply(this,e)};a[b].G=[];a[b].G[d.Z]=d}},eg=(a,b,c)=>{if(n.hasOwnProperty(a)){if(void 0===c||void 0!==n[a].G&&void 0!==n[a].G[c])throw new W(`Cannot register public name '${a}' twice`);dg(n,a,a);if(n[a].G.hasOwnProperty(c))throw new W(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
n[a].G[c]=b}else n[a]=b,n[a].Z=c},fg=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function gg(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.ba=c;this.Y=d;this.M=e;this.Lb=f;this.ua=g;this.Fb=h;this.kc=[]}
var hg=(a,b,c)=>{for(;b!==c;){if(!b.ua)throw new W(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ua(a);b=b.M}return a},ig=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function jg(a,b){if(null===b){if(this.Ka)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new W(`Cannot pass "${ig(b)}" as a ${this.name}`);if(!b.l.A)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);return hg(b.l.A,b.l.D.s,this.s)}
function kg(a,b){if(null===b){if(this.Ka)throw new W(`null is not a valid ${this.name}`);if(this.za){var c=this.Ra();null!==a&&a.push(this.Y,c);return c}return 0}if(!b||!b.l)throw new W(`Cannot pass "${ig(b)}" as a ${this.name}`);if(!b.l.A)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ya&&b.l.D.ya)throw new W(`Cannot convert argument of type ${b.l.R?b.l.R.name:b.l.D.name} to parameter type ${this.name}`);c=hg(b.l.A,b.l.D.s,this.s);if(this.za){if(void 0===b.l.J)throw new W("Passing raw pointer to smart pointer is illegal");
switch(this.qc){case 0:if(b.l.R===this)c=b.l.J;else throw new W(`Cannot convert argument of type ${b.l.R?b.l.R.name:b.l.D.name} to parameter type ${this.name}`);break;case 1:c=b.l.J;break;case 2:if(b.l.R===this)c=b.l.J;else{var d=b.clone();c=this.lc(c,lg(()=>d["delete"]()));null!==a&&a.push(this.Y,c)}break;default:throw new W("Unsupported sharing policy");}}return c}
function mg(a,b){if(null===b){if(this.Ka)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new W(`Cannot pass "${ig(b)}" as a ${this.name}`);if(!b.l.A)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.l.D.ya)throw new W(`Cannot convert argument of type ${b.l.D.name} to parameter type ${this.name}`);return hg(b.l.A,b.l.D.s,this.s)}
var ng=(a,b,c)=>{if(b===c)return a;if(void 0===c.M)return null;a=ng(a,b,c.M);return null===a?null:c.Fb(a)},og={},pg=(a,b)=>{if(void 0===b)throw new W("ptr should not be undefined");for(;a.M;)b=a.ua(b),a=a.M;return og[b]},qg=(a,b)=>{if(!b.D||!b.A)throw new Qf("makeClassHandle requires ptr and ptrType");if(!!b.R!==!!b.J)throw new Qf("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Yf(Object.create(a,{l:{value:b,writable:!0}}))};
function rg(a,b,c,d,e,f,g,h,k,l,m){this.name=a;this.s=b;this.Ka=c;this.ya=d;this.za=e;this.jc=f;this.qc=g;this.nb=h;this.Ra=k;this.lc=l;this.Y=m;e||void 0!==b.M?this.F=kg:(this.F=d?jg:mg,this.H=null)}var sg=(a,b,c)=>{if(!n.hasOwnProperty(a))throw new Qf("Replacing nonexistent public symbol");void 0!==n[a].G&&void 0!==c?n[a].G[c]=b:(n[a]=b,n[a].Z=c)},X=(a,b)=>{a=V(a);var c=M.get(b);if("function"!=typeof c)throw new W(`unknown function pointer with signature ${a}: ${b}`);return c};
class tg extends Error{}
var ug=a=>{a=cd(a);var b=V(a);K(a);return b},vg=(a,b)=>{function c(f){e[f]||Of[f]||(Pf[f]?Pf[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new tg(`${a}: `+d.map(ug).join([", "]));},Cb=(a,b,c,d,e,f,g,h,k,l,m,q,t)=>{m=V(m);f=X(e,f);h&&=X(g,h);l&&=X(k,l);t=X(q,t);var p=fg(m);eg(p,function(){vg(`Cannot construct ${m} due to unbound types`,[d])});U([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var v=u.s;var C=v.ba}else C=bg.prototype;u=Fe(m,function(...D){if(Object.getPrototypeOf(this)!==z)throw new W(`Use 'new' to construct ${m}`);
if(void 0===B.ga)throw new W(`${m} has no accessible constructor`);var Ha=B.ga[D.length];if(void 0===Ha)throw new W(`Tried to invoke ctor of ${m} with invalid number of parameters (${D.length}) - expected (${Object.keys(B.ga).toString()}) parameters instead!`);return Ha.apply(this,D)});var z=Object.create(C,{constructor:{value:u}});u.prototype=z;var B=new gg(m,u,z,t,v,f,h,l);if(B.M){var L;(L=B.M).va??(L.va=[]);B.M.va.push(B)}v=new rg(m,B,!0,!1,!1);L=new rg(m+"*",B,!1,!1,!1);C=new rg(m+" const*",B,
!1,!0,!1);cg[a]={pointerType:L,Db:C};sg(p,u);return[v,L,C]})};Cb.g="vppppppppppppp";function wg(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].H)return!0;return!1}
function xg(a,b,c,d,e,f){var g=b.length;if(2>g)throw new W("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,k=wg(b);c=!b[0].gb;var l=b[0],m=b[1];d=[a,Rf,d,e,Lf,l.v.bind(l),m?.F.bind(m)];for(e=2;e<g;++e)l=b[e],d.push(l.F.bind(l));if(!k)for(e=h?1:2;e<b.length;++e)null!==b[e].H&&d.push(b[e].H);k=wg(b);e=b.length-2;m=[];l=["fn"];h&&l.push("thisWired");for(g=0;g<e;++g)m.push(`arg${g}`),l.push(`arg${g}Wired`);m=m.join(",");l=l.join(",");m=`return function (${m}) {\n`;
k&&(m+="var destructors = [];\n");var q=k?"destructors":"null",t="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(m+=`var thisWired = toClassParamWire(${q}, this);\n`);for(g=0;g<e;++g){var p=`toArg${g}Wire`;m+=`var arg${g}Wired = ${p}(${q}, arg${g});\n`;t.push(p)}m+=(c||f?"var rv = ":"")+`invoker(${l});\n`;if(k)m+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].H&&(m+=`${f}_dtor(${f});\n`,
t.push(`${f}_dtor`));c&&(m+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(t,m+"}\n"))(...d);return Fe(a,b)}
var yg=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(G[b+4*d>>2]);return c},Cg=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Db=(a,b,c,d,e,f,g,h)=>{var k=yg(c,d);b=V(b);b=Cg(b);f=X(e,f);U([],[a],l=>{function m(){vg(`Cannot call ${q} due to unbound types`,k)}l=l[0];var q=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var t=l.s.constructor;void 0===t[b]?(m.Z=c-1,t[b]=m):(dg(t,b,q),t[b].G[c-1]=m);U([],k,p=>{p=xg(q,[p[0],null].concat(p.slice(1)),null,f,g,h);void 0===t[b].G?
(p.Z=c-1,t[b]=p):t[b].G[c-1]=p;if(l.s.va)for(const u of l.s.va)u.constructor.hasOwnProperty(b)||(u.constructor[b]=p);return[]});return[]})};Db.g="vppippppii";
var Eb=(a,b,c,d,e,f)=>{var g=yg(b,c);e=X(d,e);U([],[a],h=>{h=h[0];var k=`constructor ${h.name}`;void 0===h.s.ga&&(h.s.ga=[]);if(void 0!==h.s.ga[b-1])throw new W(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.s.ga[b-1]=()=>{vg(`Cannot construct ${h.name} due to unbound types`,g)};U([],g,l=>{l.splice(1,0,null);h.s.ga[b-1]=xg(k,l,null,e,f);return[]});
return[]})};Eb.g="vpipppp";var Fb=(a,b,c,d,e,f,g,h,k)=>{var l=yg(c,d);b=V(b);b=Cg(b);f=X(e,f);U([],[a],m=>{function q(){vg(`Cannot call ${t} due to unbound types`,l)}m=m[0];var t=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&m.s.kc.push(b);var p=m.s.ba,u=p[b];void 0===u||void 0===u.G&&u.className!==m.name&&u.Z===c-2?(q.Z=c-2,q.className=m.name,p[b]=q):(dg(p,b,t),p[b].G[c-2]=q);U([],l,v=>{v=xg(t,v,m,f,g,k);void 0===p[b].G?(v.Z=c-2,p[b]=v):p[b].G[c-2]=v;return[]});return[]})};
Fb.g="vppippppiii";
var Dg=(a,b,c)=>{if(!(a instanceof Object))throw new W(`${c} with invalid "this": ${a}`);if(!(a instanceof b.s.constructor))throw new W(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.l.A)throw new W(`cannot call emscripten binding method ${c} on deleted object`);return hg(a.l.A,a.l.D.s,b.s)},Gb=(a,b,c,d,e,f,g,h,k,l)=>{b=V(b);e=X(d,e);U([],[a],m=>{m=m[0];var q=`${m.name}.${b}`,t={get(){vg(`Cannot access ${q} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};t.set=k?
()=>vg(`Cannot access ${q} due to unbound types`,[c,g]):()=>{throw new W(q+" is a read-only property");};Object.defineProperty(m.s.ba,b,t);U([],k?[c,g]:[c],p=>{var u=p[0],v={get(){var z=Dg(this,m,q+" getter");return u.v(e(f,z))},enumerable:!0};if(k){k=X(h,k);var C=p[1];v.set=function(z){var B=Dg(this,m,q+" setter"),L=[];k(l,B,C.F(L,z));Lf(L)}}Object.defineProperty(m.s.ba,b,v);return[]});return[]})};Gb.g="vpppppppppp";
var Eg=[],Fg=[0,1,,1,null,1,!0,1,!1,1],Gg=[],gc=a=>{if(9<a&&0===--Fg[a+1]){var b=Fg[a];Fg[a]=void 0;var c=Gg[a];c&&(Gg[a]=void 0,c(b));Eg.push(a)}};gc.g="vp";var Z=a=>{if(!a)throw new W(`Cannot use deleted val. handle = ${a}`);return Fg[a]},lg=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Eg.pop()||Fg.length;Fg[b]=a;Fg[b+1]=1;return b}},Hg={name:"emscripten::val",v:a=>{var b=Z(a);gc(a);return b},F:(a,b)=>lg(b),K:Mf,H:null},Hb=a=>T(a,Hg);
Hb.g="vp";
var Ig=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.v(x[d])}:function(d){return this.v(A[d])};case 2:return c?function(d){return this.v(y[d>>1])}:function(d){return this.v(E[d>>1])};case 4:return c?function(d){return this.v(F[d>>2])}:function(d){return this.v(G[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ib=(a,b,c,d,e)=>{b=V(b);e=0===e?"object":1===e?"number":"string";switch(e){case "object":function g(){}g.values={};T(a,{name:b,constructor:g,valueType:e,
v:function(h){return this.constructor.values[h]},F:(h,k)=>k.value,K:Ig(b,c,d),H:null});eg(b,g);break;case "number":var f={};T(a,{name:b,La:f,valueType:e,v:h=>h,F:(h,k)=>k,K:Ig(b,c,d),H:null});eg(b,f);delete n[b].Z;break;case "string":f={},T(a,{name:b,ub:{},ob:{},La:f,valueType:e,v:function(h){return this.ob[h]},F:function(h,k){return this.ub[k]},K:Ig(b,c,d),H:null}),eg(b,f),delete n[b].Z}};Ib.g="vpppii";
var Jg=(a,b)=>{var c=Of[a];if(void 0===c)throw a=`${b} has unknown type ${ug(a)}`,new W(a);return c},Jb=(a,b,c)=>{var d=Jg(a,"enum");b=V(b);switch(d.valueType){case "object":a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Fe(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d;break;case "number":d.La[b]=c;break;case "string":d.ub[b]=c,d.ob[c]=b,d.La[b]=b}};Jb.g="vppi";
var Kg=(a,b)=>{switch(b){case 4:return function(c){return this.v(La[c>>2])};case 8:return function(c){return this.v(Ma[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Kb=(a,b,c)=>{b=V(b);T(a,{name:b,v:d=>d,F:(d,e)=>e,K:Kg(b,c),H:null})};Kb.g="vppp";var Lb=(a,b,c,d,e,f,g)=>{var h=yg(b,c);a=V(a);a=Cg(a);e=X(d,e);eg(a,function(){vg(`Cannot call ${a} due to unbound types`,h)},b-1);U([],h,k=>{sg(a,xg(a,[k[0],null].concat(k.slice(1)),null,e,f,g),b-1);return[]})};Lb.g="vpippppii";
var Mb=(a,b,c,d,e)=>{b=V(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}T(a,{name:b,v:f,F:(h,k)=>k,K:Tf(b,c,0!==d),H:null})};Mb.g="vpppii";var Lg=(a,b,c)=>{const d=(e,f)=>{let g=0;return{next(){if(g>=e)return{done:!0};const h=g;g++;return{value:f(h),done:!1}},[Symbol.iterator](){return this}}};a[Symbol.iterator]||(a[Symbol.iterator]=function(){const e=this[b]();return d(e,f=>this[c](f))})},Nb=(a,b,c,d)=>{c=V(c);d=V(d);U([],[a,b],e=>{Lg(e[0].s.ba,c,d);return[]})};Nb.g="vpppp";
var Ob=(a,b,c)=>{function d(f){return new e(x.buffer,G[f+4>>2],G[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=V(c);T(a,{name:c,v:d,K:d},{Tb:!0})};Ob.g="vpip";var Mg=Object.assign({optional:!0},Hg),Pb=a=>{T(a,Mg)};Pb.g="vpp";
var Qb=(a,b)=>{b=V(b);T(a,{name:b,v(c){var d=P(c+4,G[c>>2],!0);K(c);return d},F(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new W("Cannot pass non-string to std::string");var f=e?Te(d):d.length;var g=$c(4+f+1),h=g+4;G[g>>2]=f;e?Q(d,A,h,f+1):A.set(d,h);null!==c&&c.push(K,g);return g},K:Mf,H(c){K(c)}})};Qb.g="vpp";
var Ng=new TextDecoder("utf-16le"),Og=(a,b,c)=>{a>>=1;return Ng.decode(E.slice(a,pe(E,a,b/2,c)))},Pg=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)y[b>>1]=a.charCodeAt(e),b+=2;y[b>>1]=0;return b-d},Qg=a=>2*a.length,Rg=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=G[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Sg=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);
65535<f&&e++;F[b>>2]=f;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d},Tg=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Rb=(a,b,c)=>{c=V(c);if(2===b){var d=Og;var e=Pg;var f=Qg}else d=Rg,e=Sg,f=Tg;T(a,{name:c,v:g=>{var h=d(g+4,G[g>>2]*b,!0);K(g);return h},F:(g,h)=>{if("string"!=typeof h)throw new W(`Cannot pass non-string to C++ string type ${c}`);var k=f(h),l=$c(4+k+b);G[l>>2]=k/b;e(h,l+4,k+b);null!==g&&g.push(K,l);return l},K:Mf,H(g){K(g)}})};Rb.g="vppp";
var Sb=(a,b,c,d,e,f)=>{Kf[a]={name:V(b),Ra:X(c,d),Y:X(e,f),bb:[]}};Sb.g="vpppppp";var Tb=(a,b,c,d,e,f,g,h,k,l)=>{Kf[a].bb.push({Jb:V(b),Pb:c,ma:X(d,e),Ob:f,nc:g,mc:X(h,k),oc:l})};Tb.g="vpppppppppp";var Ub=(a,b)=>{b=V(b);T(a,{gb:!0,name:b,v:()=>{},F:()=>{}})};Ub.g="vpp";var Vb=(a,b,c,d)=>{function e(h){var k=P(a+36);If(`'Could not load dynamic lib: ${k}\n${h}`);--N;ae(()=>M.get(c)(a,d))}function f(){--N;ae(()=>M.get(b)(a,d))}N+=1;var g=Jf(a,{I:!0});g?g.then(f,e):e()};Vb.g="vpppp";
function Ug(a){var b=Vg,c=b.P.pop()||b.fa.length;b.fa[c]=a;return c}function Wg(a){var b=Vg;b.fa[a]=void 0;b.P.push(a)}class Xg{fa=[void 0];P=[];get(a){return this.fa[a]}has(a){return void 0!==this.fa[a]}}
var Vg=new Xg,Yg=()=>{var a={};a.promise=new Promise((b,c)=>{a.reject=c;a.resolve=b});a.id=Ug(a);return a},Zg=async()=>{const a=be,b=[];var c=Yg();b.push(c.promise);gd(c.id);for(const d of Object.keys(Hd)){const e=Number(d);e===a||Id.has(e)||(c=Yg(),jd(e,c.id),Jd[e]=c,b.push(c.promise))}await Promise.all(b);Jd={}};function Wb(){if(r)return O(17,2);if(be)return Zg();for(const a of Object.keys(Hd)){const b=Number(a);Id.has(b)||kd(b)}}Wb.g="v";
function Xb(){var a=$c(4*(la.length+1)),b=a;la.forEach(c=>{var d=G,e=b>>2,f=Te(c)+1,g=$c(f);g&&Q(c,A,g,f);d[e]=g;b+=4});G[b>>2]=0;return a}Xb.g="p";var Yb=a=>{Ba(a,!ba,1,!aa,262144,!1);Ca()};Yb.g="vp";var Da=a=>{Wd||(Atomics.waitAsync(F,a>>2,a).value.then(Ga),Atomics.store(F,a+120>>2,1))};Da.g="vp";var Ga=()=>{var a=Zc();a&&ae(()=>{Da(a);rd()})},Zb=(a,b)=>{a==b?setTimeout(Ga):r?postMessage({Da:a,V:"checkMailbox"}):(a=Hd[a])&&a.postMessage({V:"checkMailbox"})};Zb.g="vpp";
var $g=[],$b=(a,b,c,d,e,f,g)=>{$g.length=0;var h=e>>3;for(d=e+d>>3;h<d;){var k;H[h++]?k=H[h++]:k=Ma[h++];$g.push(k)}a=b?He[b]:ah[a];be=c;c=a(...$g);be=0;if(f)c.then(l=>nd(f,g,l));else return c};$b.g="dippippp";var ac=()=>{ce=!1;N=0};ac.g="v";var bc=a=>{r?postMessage({V:"cleanupThread",Ua:a}):Md(a)};bc.g="vp";var cc=a=>{r?postMessage({V:"markAsFinished",Ua:a}):Od(a)};cc.g="vp";var dc=()=>{};dc.g="vp";var ec=(a,b)=>{a=Z(a);b=Z(b);a.set(b)};ec.g="vpp";
var bh=[],ch=a=>{var b=bh.length;bh.push(a);return b},dh=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Jg(G[b+4*d>>2],`parameter ${d}`);return c},eh=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(G[b>>2]=lg(d));return a},fh={},gh=a=>{var b=fh[a];return void 0===b?V(a):b},fc=(a,b,c)=>{var [d,...e]=dh(a,b);b=d.F.bind(d);var f=e.map(k=>k.K.bind(k));a--;var g={toValue:Z};a=f.map((k,l)=>{var m=`argFromPtr${l}`;g[m]=k;return`${m}(args${l?"+"+8*l:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";
break;case 3:h="";break;case 1:g.getStringOrSymbol=gh,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${a})`;d.gb||(g.toReturnWire=b,g.emval_returnValue=eh,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n${h}\n}`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=`methodCaller<(${e.map(k=>k.name)}) => ${d.name}>`;return ch(Fe(h,c))};fc.g="pipi";var hc=a=>{if(!a)return lg(globalThis);a=gh(a);return lg(globalThis[a])};
hc.g="pp";var ic=a=>{a=gh(a);return lg(n[a])};ic.g="pp";var jc=(a,b)=>{a=Z(a);b=Z(b);return lg(a[b])};jc.g="ppp";var kc=a=>{9<a&&(Fg[a+1]+=1)};kc.g="vp";var lc=(a,b)=>{a=Z(a);b=Z(b);return a instanceof b};lc.g="ipp";var mc=(a,b,c,d,e)=>bh[a](b,c,d,e);mc.g="dppppp";var nc=a=>{a=Z(a);return"number"==typeof a};nc.g="ip";var oc=a=>{a=Z(a);return"string"==typeof a};oc.g="ip";var pc=a=>lg(gh(a));pc.g="pp";var qc=a=>{var b=Z(a);Lf(b);gc(a)};qc.g="vp";var rc=(a,b,c)=>{a=Z(a);b=Z(b);c=Z(c);a[b]=c};rc.g="vppp";
var sc=a=>{a=Z(a);return lg(typeof a)};sc.g="pp";function tc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);F[b>>2]=a.getUTCSeconds();F[b+4>>2]=a.getUTCMinutes();F[b+8>>2]=a.getUTCHours();F[b+12>>2]=a.getUTCDate();F[b+16>>2]=a.getUTCMonth();F[b+20>>2]=a.getUTCFullYear()-1900;F[b+24>>2]=a.getUTCDay();F[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0}tc.g="vjp";
var hh=[0,31,60,91,121,152,182,213,244,274,305,335],ih=[0,31,59,90,120,151,181,212,243,273,304,334];
function uc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);F[b>>2]=a.getSeconds();F[b+4>>2]=a.getMinutes();F[b+8>>2]=a.getHours();F[b+12>>2]=a.getDate();F[b+16>>2]=a.getMonth();F[b+20>>2]=a.getFullYear()-1900;F[b+24>>2]=a.getDay();var c=a.getFullYear();F[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?ih:hh)[a.getMonth()]+a.getDate()-1|0;F[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();
F[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0}uc.g="vjp";function vc(a,b,c,d,e,f,g){if(r)return O(18,1,a,b,c,d,e,f,g);e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{var h=S(d),k=FS.ja(h,a,e,b,c),l=k.A;F[f>>2]=k.fa;G[g>>2]=l;return 0}catch(m){if("undefined"==typeof FS||"ErrnoError"!==m.name)throw m;return-m.B}}vc.g="ipiiijpp";
function wc(a,b,c,d,e,f){if(r)return O(19,1,a,b,c,d,e,f);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=S(e);if(c&2){c=f;if(!FS.isFile(g.node.mode))throw new FS.h(43);d&2||FS.la(g,A.slice(a,a+b),c,b,d)}}catch(h){if("undefined"==typeof FS||"ErrnoError"!==h.name)throw h;return-h.B}}wc.g="ippiiij";
var xc=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();G[a>>2]=60*Math.max(f,e);F[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(Q(a,A,c,17),Q(b,A,d,17)):(Q(a,A,d,17),Q(b,A,c,17))};xc.g="vpppp";var Ec=()=>performance.timeOrigin+performance.now();Ec.g="d";var Ac=()=>Date.now();Ac.g="d";var jh=1;
function yc(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(jh)a=performance.timeOrigin+performance.now();else return 52;H[c>>3]=BigInt(Math.round(1E6*a));return 0}yc.g="iijp";var zc=()=>{};zc.g="v";var Bc=a=>w(P(a));Bc.g="vp";var Cc=()=>{N+=1;throw"unwind";};Cc.g="v";var Dc=()=>A.length;Dc.g="p";var Fc=()=>navigator.hardwareConcurrency;Fc.g="i";var Gc=a=>{Wg(a)};Gc.g="vp";
var Hc=(a,b,c)=>{a=Vg.get(a);switch(b){case 0:a.resolve(c);break;case 1:a.resolve(Vg.get(c).promise);break;case 2:a.resolve(Vg.get(c).promise);Wg(c);break;case 3:a.reject(c)}};Hc.g="vpip";var Ic=()=>!1;Ic.g="ip";
var kh={},mh=()=>{if(!lh){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in kh)void 0===kh[b]?delete a[b]:a[b]=kh[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);lh=c}return lh},lh;function Jc(a,b){if(r)return O(20,1,a,b);var c=0,d=0,e;for(e of mh()){var f=b+c;G[a+d>>2]=f;c+=Q(e,A,f,Infinity)+1;d+=4}return 0}Jc.g="ipp";
function Kc(a,b){if(r)return O(21,1,a,b);var c=mh();G[a>>2]=c.length;a=0;for(var d of c)a+=Te(d)+1;G[b>>2]=a;return 0}Kc.g="ipp";function Mc(a){if(r)return O(22,1,a);try{var b=S(a);FS.close(b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.B}}Mc.g="ii";
function Nc(a,b){if(r)return O(23,1,a,b);try{var c=S(a),d=c.C?2:FS.isDir(c.mode)?3:FS.isLink(c.mode)?7:4;x[b]=d;y[b+2>>1]=0;H[b+8>>3]=BigInt(0);H[b+16>>3]=BigInt(0);return 0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return e.B}}Nc.g="iip";
function Oc(a,b,c,d){if(r)return O(24,1,a,b,c,d);try{a:{var e=S(a);a=b;for(var f,g=b=0;g<c;g++){var h=G[a>>2],k=G[a+4>>2];a+=8;var l=FS.read(e,x,h,k,f);if(0>l){var m=-1;break a}b+=l;if(l<k)break;"undefined"!=typeof f&&(f+=l)}m=b}G[d>>2]=m;return 0}catch(q){if("undefined"==typeof FS||"ErrnoError"!==q.name)throw q;return q.B}}Oc.g="iippp";
function Pc(a,b,c,d){if(r)return O(25,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 22;var e=S(a);FS.llseek(e,b,c);H[d>>3]=BigInt(e.position);e.Ga&&0===b&&0===c&&(e.Ga=null);return 0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return f.B}}Pc.g="iijip";
function Qc(a,b,c,d){if(r)return O(26,1,a,b,c,d);try{a:{var e=S(a);a=b;for(var f,g=b=0;g<c;g++){var h=G[a>>2],k=G[a+4>>2];a+=8;var l=FS.write(e,x,h,k,f);if(0>l){var m=-1;break a}b+=l;if(l<k)break;"undefined"!=typeof f&&(f+=l)}m=b}G[d>>2]=m;return 0}catch(q){if("undefined"==typeof FS||"ErrnoError"!==q.name)throw q;return q.B}}Qc.g="iippp";function Sc(...a){return J.heif_error_success(...a)}Sc.Ba=!0;var Uc=(a,b)=>We(A.subarray(a,a+b));Uc.g="ipp";r||Yd();
(()=>{var a={mb:Promise.resolve(),canHandle:b=>!n.noWasmDecoding&&b.endsWith(".so"),handle:async(b,c)=>a.mb=a.mb.then(async()=>{try{var d=await Le(b,{I:!0,pa:!0},c,{})}catch(e){throw Error(`failed to instantiate wasm: ${c}: ${e}`);}ge[c]=d;return b})};fe.push(a)})();FS.createPreloadedFile=(a,b,c,d,e,f,g,h,k,l)=>{mf(a,b,c,d,e,h,k,l).then(f).catch(g)};FS.Oc=mf;FS.da=Array(4096);FS.mount(R,{},"/");FS.mkdir("/tmp");FS.mkdir("/home");FS.mkdir("/home/web_user");
(function(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=>0,write:(d,e,f,g)=>g,llseek:()=>0});FS.mkdev("/dev/null",FS.makedev(1,3));bf(FS.makedev(5,0),df);bf(FS.makedev(6,0),ef);FS.mkdev("/dev/tty",FS.makedev(5,0));FS.mkdev("/dev/tty1",FS.makedev(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(We(a),b=a.byteLength);return a[--b]};FS.createDevice("/dev","random",c);FS.createDevice("/dev","urandom",c);FS.mkdir("/dev/shm");FS.mkdir("/dev/shm/tmp")})();
(function(){FS.mkdir("/proc");var a=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var b=FS.createNode(a,"fd",16895,73);b.o={llseek:R.o.llseek};b.m={ia(c,d){c=+d;var e=S(c);c={parent:null,mount:{jb:"fake"},m:{readlink:()=>e.path},id:c+1};return c.parent=c},sa(){return Array.from(FS.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();FS.Kb={MEMFS:R};
(()=>{let a=bg.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof bg&&c instanceof bg))return!1;var d=this.l.D.s,e=this.l.A;c.l=c.l;var f=c.l.D.s;for(c=c.l.A;d.M;)e=d.ua(e),d=d.M;for(;f.M;)c=f.ua(c),f=f.M;return d===f&&e===c},clone:function(){this.l.A||Uf(this);if(this.l.qa)return this.l.count.value+=1,this;var c=Yf,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.l;c=c(e.call(d,f,{l:{value:{count:g.count,ha:g.ha,qa:g.qa,A:g.A,D:g.D,J:g.J,R:g.R}}}));c.l.count.value+=1;c.l.ha=
!1;return c},["delete"](){this.l.A||Uf(this);if(this.l.ha&&!this.l.qa)throw new W("Object already scheduled for deletion");Xf(this);var c=this.l;--c.count.value;0===c.count.value&&(c.J?c.R.Y(c.J):c.D.s.Y(c.A));this.l.qa||(this.l.J=void 0,this.l.A=void 0)},isDeleted:function(){return!this.l.A},deleteLater:function(){this.l.A||Uf(this);if(this.l.ha&&!this.l.qa)throw new W("Object already scheduled for deletion");Zf.push(this);1===Zf.length&&ag&&ag($f);this.l.ha=!0;return this}});const b=Symbol.dispose;
b&&(a[b]=a["delete"])})();
Object.assign(rg.prototype,{Nb(a){this.nb&&(a=this.nb(a));return a},Ya(a){this.Y?.(a)},K:Mf,v:function(a){function b(){return this.za?qg(this.s.ba,{D:this.jc,A:c,R:this,J:a}):qg(this.s.ba,{D:this,A:a})}var c=this.Nb(a);if(!c)return this.Ya(a),null;var d=pg(this.s,c);if(void 0!==d){if(0===d.l.count.value)return d.l.A=c,d.l.J=a,d.clone();d=d.clone();this.Ya(a);return d}d=this.s.Lb(c);d=cg[d];if(!d)return b.call(this);d=this.ya?d.Db:d.pointerType;var e=ng(c,this.s,d.s);return null===e?b.call(this):this.za?
qg(d.s.ba,{D:d,A:e,R:this,J:a}):qg(d.s.ba,{D:d,A:e})}});Nd.push(()=>{kh.VIPS_DISC_THRESHOLD=1073741824;kh.VIPS_MAX_THREADS=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;kh.VIPS_CONCURRENCY=1});
Sa.push(()=>{const a=Object.getOwnPropertyDescriptor(n.SourceCustom.prototype,"onRead");Object.defineProperty(n.SourceCustom.prototype,"onRead",{set(c){return a.set.call(this,d=>lg(c(d)))}});const b=Object.getOwnPropertyDescriptor(n.TargetCustom.prototype,"onWrite");Object.defineProperty(n.TargetCustom.prototype,"onWrite",{set(c){return b.set.call(this,d=>c(Z(d)))}})});Object.assign(bg.prototype,{preventAutoDelete:function(){const a=Zf.indexOf(this);-1<a&&Zf.splice(a,1);this.l.ha=!1;return this}});
if(!r){if(n.wasmMemory)wa=n.wasmMemory;else{var nh=n.INITIAL_MEMORY||1073741824;wa=new WebAssembly.Memory({initial:nh/65536,maximum:nh/65536,shared:!0})}xa()}n.preloadPlugins&&(fe=n.preloadPlugins);n.noExitRuntime&&(ce=n.noExitRuntime);n.print&&(ka=n.print);n.printErr&&(w=n.printErr);n.dynamicLibraries&&(la=n.dynamicLibraries);n.wasmBinary&&(ma=n.wasmBinary);n.arguments&&(ca=n.arguments);n.thisProgram&&(da=n.thisProgram);if(n.preInit)for("function"==typeof n.preInit&&(n.preInit=[n.preInit]);0<n.preInit.length;)n.preInit.shift()();
n.ENV=kh;n.addRunDependency=Sd;n.removeRunDependency=Rd;n.addFunction=Ce;n.FS_preloadFile=mf;n.FS_unlink=(...a)=>FS.unlink(...a);n.FS_createPath=(...a)=>FS.createPath(...a);n.FS_createDevice=(...a)=>FS.createDevice(...a);n.FS=FS;n.FS_createDataFile=(...a)=>FS.createDataFile(...a);n.FS_createLazyFile=(...a)=>FS.createLazyFile(...a);n.setAutoDeleteLater=a=>{Vf=a};n.deletionQueue=Zf;n.setDelayFunction=a=>{ag=a;Zf.length&&ag&&ag($f)};
var ah=[Tc,de,Cf,db,eb,fb,gb,hb,ib,jb,kb,lb,mb,nb,ob,pb,qb,Wb,vc,wc,Jc,Kc,Mc,Nc,Oc,Pc,Qc],He={};function oh(a){for(var b=E[a+6>>1];13===b&&!(16<G[a>>2]);){var c=G[a+8>>2],d=G[c>>2];if(0===d){b=0;break}else if(0===G[(c>>2)+1])a=d,b=E[d+6>>1];else break}return[a,b]}
function Rc(a,b,c,d){var e=G[(a>>2)+1],f=G[(a>>2)+6],g=G[(a>>2)+2],h=G[(a>>2)+5];a=oh(G[(a>>2)+3])[1];var k=wd(),l=k,m=[],q=!1;if(15===a)throw Error("complex ret marshalling nyi");if(0>a||15<a)throw Error("Unexpected rtype "+a);if(4===a||13===a)m.push(c),q=!0;for(var t=0;t<f;t++){var p=G[(d>>2)+t],u=oh(G[(g>>2)+t]),v=u[0];u=u[1];switch(u){case 1:case 10:case 9:m.push(G[p>>2]);break;case 2:m.push(La[p>>2]);break;case 3:m.push(Ma[p>>3]);break;case 5:m.push(A[p]);break;case 6:m.push(x[p]);break;case 7:m.push(E[p>>
1]);break;case 8:m.push(y[p>>1]);break;case 11:case 12:m.push(Na[p>>3]);break;case 4:m.push(Na[p>>3]);m.push(Na[(p>>3)+1]);break;case 13:u=G[v>>2];v=E[v+4>>1];l-=u;l&=~(v-1);x.subarray(l,l+u).set(x.subarray(p,p+u));m.push(l);break;case 14:m.push(G[p>>2]);break;case 15:throw Error("complex marshalling nyi");default:throw Error("Unexpected type "+u);}}if(h&1){h=[];for(t=e-1;t>=f;t--)switch(p=G[(d>>2)+t],u=oh(G[(g>>2)+t]),v=u[0],u=u[1],u){case 5:case 6:--l;l&=-1;A[l]=A[p];break;case 7:case 8:l-=2;l&=
-2;E[l>>1]=E[p>>1];break;case 1:case 9:case 10:case 2:l-=4;l&=-4;G[l>>2]=G[p>>2];break;case 3:case 11:case 12:l-=8;l&=-8;G[l>>2]=G[p>>2];G[(l>>2)+1]=G[(p>>2)+1];break;case 4:l-=16;l&=-8;G[l>>2]=G[p>>2];G[(l>>2)+1]=G[(p>>2)+1];G[(l>>2)+2]=G[(p>>2)+2];G[(l>>2)+3]=G[(p>>2)+3];break;case 13:l-=4;l&=-4;h.push([l,p,G[v>>2],E[v+4>>1]]);break;case 14:l-=4;l&=-4;G[l>>2]=G[p>>2];break;case 15:throw Error("complex arg marshalling nyi");default:throw Error("Unexpected argtype "+u);}m.push(l);for(t=0;t<h.length;t++)e=
h[t],d=e[0],p=e[1],u=e[2],v=e[3],l-=u,l&=~(v-1),x.subarray(l,l+u).set(x.subarray(p,p+u)),G[d>>2]=l}ud(l);vd(0);b=M.get(b).apply(null,m);ud(k);if(!q)switch(a){case 0:break;case 1:case 9:case 10:G[c>>2]=b;break;case 2:La[c>>2]=b;break;case 3:Ma[c>>3]=b;break;case 5:case 6:A[c+0]=b;break;case 7:case 8:E[c>>1]=b;break;case 11:case 12:Na[c>>3]=b;break;case 14:G[c>>2]=b;break;case 15:throw Error("complex ret marshalling nyi");default:throw Error("Unexpected rtype "+a);}}Rc.g="viiii";
var Zc,$c,K,ad,bd,cd,Ea,dd,ed,fd,gd,hd,jd,kd,ld,Ba,md,Ia,nd,od,pd,qd,rd,sd,Ta,td,ud,vd,wd,xd,yd,zd,Ad,M,J;function ph(a=[]){var b=Ge("main").Ta;if(b){a.unshift(da);var c=a.length,d=vd(4*(c+1)),e=d,f;for(f of a)G[e>>2]=Ue(f),e+=4;G[e>>2]=0;try{var g=b(c,d);Lc(g,!0)}catch(h){Fd(h)}}}
function za(a=ca){function b(){n.calledRun=!0;if(!oa&&(Pa(),qa?.(n),n.onRuntimeInitialized?.(),n.noInitialRun||ph(a),!r)){if(n.postRun)for("function"==typeof n.postRun&&(n.postRun=[n.postRun]);n.postRun.length;){var c=n.postRun.shift();ne.push(c)}Qa(ne)}}if(0<Pd)Qd=za;else if(r)qa?.(n),Pa();else{if(n.preRun)for("function"==typeof n.preRun&&(n.preRun=[n.preRun]);n.preRun.length;)Nd.push(n.preRun.shift());Qa(Nd);0<Pd?Qd=za:n.setStatus?(n.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>n.setStatus(""),
1);b()},1)):b()}}var Ra;r||(Ra=await (ya()),za());Ja?moduleRtn=n:moduleRtn=new Promise((a,b)=>{qa=a;ra=b});
;return moduleRtn}export default Vips;var isPthread=globalThis.name=="em-pthread";isPthread&&Vips();
