async function Vips(moduleArg={}){var moduleRtn;var h=moduleArg,aa=!!globalThis.window,ca=!!globalThis.WorkerGlobalScope,p=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,r=ca&&"em-pthread"==globalThis.name;if(p){const {createRequire:a}=await import("node:module");var require=a(import.meta.url),worker_threads=require("node:worker_threads");globalThis.Worker=worker_threads.Worker;r=(ca=!worker_threads.isMainThread)&&"em-pthread"==worker_threads.workerData}
h.dynamicLibraries=h.dynamicLibraries||["vips-jxl.wasm","vips-heif.wasm"];var da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=import.meta.url,ia="";function ja(a){return h.locateFile?h.locateFile(a,ia):ia+a}var ka,la;
if(p){var fs=require("node:fs");ha.startsWith("file:")&&(ia=require("node:path").dirname(require("node:url").fileURLToPath(ha))+"/");la=a=>{a=ma(a)?new URL(a):a;return fs.readFileSync(a)};ka=async a=>{a=ma(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ca){try{ia=(new URL(".",ha)).href}catch{}p||(ca&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType=
"arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);})}var na=console.log.bind(console),oa=console.error.bind(console);if(p){var pa=require("node:util"),qa=a=>"object"==typeof a?pa.inspect(a):a;na=(...a)=>fs.writeSync(1,a.map(qa).join(" ")+"\n");oa=(...a)=>fs.writeSync(2,a.map(qa).join(" ")+"\n")}var ra=na,w=oa,sa=[],ta,ua,va=!1,wa,ma=a=>a.startsWith("file://");
function y(){xa.buffer!=z.buffer&&ya()}var za,Aa;if(p&&r){globalThis.self=globalThis;var Ca=worker_threads.parentPort;globalThis.postMessage||(Ca.on("message",a=>globalThis.onmessage?.({data:a})),globalThis.postMessage=a=>Ca.postMessage(a));process.on("uncaughtException",a=>{postMessage({R:"uncaughtException",error:a});process.exit(1)})}var Da={},Ea;
if(r){var Fa=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.R;if("load"===d){let e=[];self.onmessage=f=>e.push(f);Ea=()=>{postMessage({R:"loaded"});for(let f of e)a(f);self.onmessage=a};sa=c.Bb;Da=c.lc;for(const f of c.Pb)if(!h[f]||h[f].proxy)h[f]=(...g)=>{postMessage({R:"callHandler",Ob:f,args:g})},"print"==f&&(ra=h[f]),"printErr"==f&&(w=h[f]);xa=c.sc;ya();ua=c.tc;Ga();Ha()}else if("run"===d){Ia(c.W);Ja(c.W,0,0,1,0,0);Ka();La(c.W);Fa||(Na(),Fa=!0);try{Oa(c.oc,
c.Ba)}catch(e){if("unwind"!=e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?Fa&&Pa():d&&(w(`worker: received unknown command ${d}`),w(c)))}catch(e){throw Qa(),e;}}self.onmessage=a}var Ra=!1,Sa=!1;function ya(){var a=xa.buffer;z=new Int8Array(a);A=new Int16Array(a);F=new Uint8Array(a);G=new Uint16Array(a);H=new Int32Array(a);I=new Uint32Array(a);Ta=new Float32Array(a);Ua=new Float64Array(a);J=new BigInt64Array(a);Va=new BigUint64Array(a)}var Wa=[];
function Xa(){Ra=!0;r?Ea():(Ya(Wa),h.noFSInit||FS.Ga||FS.init(),Za.__wasm_call_ctors(),Ya($a),FS.eb=!1)}function K(a){h.onAbort?.(a);a=`Aborted(${a})`;w(a);va=!0;a+=". Build with -sASSERTIONS for more info.";Ra&&bb();a=new WebAssembly.RuntimeError(a);Aa?.(a);throw a;}var cb;async function db(a){if(!ta)try{var b=await ka(a);return new Uint8Array(b)}catch{}if(a==cb&&ta)a=new Uint8Array(ta);else if(la)a=la(a);else throw"both async and sync fetching of the wasm failed";return a}
async function eb(a,b){try{var c=await db(a);return await WebAssembly.instantiate(c,b)}catch(d){w(`failed to asynchronously prepare wasm: ${d}`),K(d)}}async function fb(a){var b=cb;if(!ta&&!p)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){w(`wasm streaming compile failed: ${d}`),w("falling back to ArrayBuffer instantiation")}return eb(b,a)}
function gb(){hb={__assert_fail:ib,__call_sighandler:jb,__lsan_ignore_object:kb,__pthread_create_js:lb,__syscall_dup:mb,__syscall_faccessat:nb,__syscall_fcntl64:ob,__syscall_fstat64:pb,__syscall_ftruncate64:qb,__syscall_getcwd:rb,__syscall_ioctl:sb,__syscall_lstat64:tb,__syscall_newfstatat:ub,__syscall_openat:vb,__syscall_rmdir:wb,__syscall_stat64:xb,__syscall_unlinkat:yb,__throw_exception_with_stack_trace:zb,_abort_js:Ab,_dlopen_js:Bb,_dlsym_catchup_js:Eb,_dlsym_js:Fb,_embind_finalize_value_object:Gb,
_embind_register_arithmetic_vector:Hb,_embind_register_bigint:Ib,_embind_register_bool:Jb,_embind_register_class:Kb,_embind_register_class_class_function:Lb,_embind_register_class_constructor:Mb,_embind_register_class_function:Nb,_embind_register_class_property:Ob,_embind_register_emval:Pb,_embind_register_enum:Qb,_embind_register_enum_value:Rb,_embind_register_float:Sb,_embind_register_function:Tb,_embind_register_integer:Ub,_embind_register_iterable:Vb,_embind_register_memory_view:Wb,_embind_register_optional:Xb,
_embind_register_std_string:Yb,_embind_register_std_wstring:Zb,_embind_register_value_object:$b,_embind_register_value_object_field:ac,_embind_register_void:bc,_emscripten_dlopen_js:cc,_emscripten_dlsync_threads:dc,_emscripten_get_dynamic_libraries_js:ec,_emscripten_init_main_thread_js:fc,_emscripten_notify_mailbox_postmessage:gc,_emscripten_receive_on_main_thread_js:hc,_emscripten_runtime_keepalive_clear:ic,_emscripten_thread_cleanup:jc,_emscripten_thread_exit_joinable:kc,_emscripten_thread_mailbox_await:La,
_emscripten_thread_set_strongref:lc,_emval_array_to_memory_view:mc,_emval_create_invoker:nc,_emval_decref:oc,_emval_get_global:pc,_emval_get_module_property:qc,_emval_get_property:rc,_emval_incref:sc,_emval_instanceof:tc,_emval_invoke:uc,_emval_is_number:vc,_emval_is_string:wc,_emval_new_cstring:xc,_emval_run_destructors:yc,_emval_set_property:zc,_emval_typeof:Ac,_gmtime_js:Bc,_localtime_js:Cc,_mmap_js:Dc,_munmap_js:Ec,_tzset_js:Fc,clock_time_get:Gc,emscripten_check_blocking_allowed:Hc,emscripten_date_now:Ic,
emscripten_err:Jc,emscripten_exit_with_live_runtime:Kc,emscripten_get_heap_max:Lc,emscripten_get_now:Mc,emscripten_num_logical_cores:Nc,emscripten_promise_destroy:Oc,emscripten_promise_resolve:Pc,emscripten_resize_heap:Qc,environ_get:Rc,environ_sizes_get:Sc,exit:Tc,fd_close:Uc,fd_fdstat_get:Vc,fd_read:Wc,fd_seek:Xc,fd_write:Yc,ffi_call_js:Zc,memory:xa,proc_exit:$c,random_get:ad};var a=new Proxy(new Set(["__lsan_ignore_object"]),bd);return{env:hb,wasi_snapshot_preview1:hb,"GOT.mem":a,"GOT.func":a}}
async function Ga(){function a(d,e){var f=Za=d.exports;cd(Za);var g=dd(e);ed(Za._emscripten_tls_init,d.exports,g);d=Za;fd=d.pthread_self;gd=d.malloc;h._main=d.main;L=d.free;hd=d.fflush;jd=d.calloc;h.__ZnamSt11align_val_t=d._ZnamSt11align_val_t;kd=d.__getTypeName;Na=d._embind_initialize_bindings;h._emscripten_builtin_free=d.emscripten_builtin_free;ld=d.emscripten_builtin_memalign;h._emscripten_builtin_malloc=d.emscripten_builtin_malloc;md=d.__funcs_on_exit;h.___libc_calloc=d.__libc_calloc;h.___libc_free=
d.__libc_free;h.___libc_malloc=d.__libc_malloc;nd=d.__dl_seterr;od=d._emscripten_dlsync_self_async;pd=d._emscripten_dlsync_self;qd=d._emscripten_proxy_dlsync_async;rd=d._emscripten_proxy_dlsync;sd=d._emscripten_find_dylib;Ja=d._emscripten_thread_init;td=d.__set_thread_state;Qa=d._emscripten_thread_crashed;ud=d._emscripten_run_js_on_main_thread_done;vd=d._emscripten_run_js_on_main_thread;wd=d._emscripten_thread_free_data;xd=d._emscripten_thread_exit;h._strndup=d.strndup;yd=d._emscripten_check_mailbox;
h.__ZdaPvm=d._ZdaPvm;h.___libc_realloc=d.__libc_realloc;h._emscripten_builtin_calloc=d.emscripten_builtin_calloc;h._emscripten_builtin_realloc=d.emscripten_builtin_realloc;h._malloc_size=d.malloc_size;h._malloc_usable_size=d.malloc_usable_size;h._reallocf=d.reallocf;zd=d.emscripten_get_sbrk_ptr;bb=d.__trap;Ad=d.emscripten_stack_set_limits;Bd=d._emscripten_stack_restore;Cd=d._emscripten_stack_alloc;Dd=d.emscripten_stack_get_current;Ed=d.__thrown_object_from_unwind_exception;Fd=d.__get_exception_message;
M=d.__indirect_function_table;Gd=d.__heap_base.value;Hd=d.__cpp_exception;Id(f);Jd("__main__",0,hb);Kd();ua=e;return Za}var b=gb();if(h.instantiateWasm)return new Promise(d=>{h.instantiateWasm(b,(e,f)=>{d(a(e,f))})});if(r){var c=new WebAssembly.Instance(ua,gb());return a(c,ua)}cb??=h.locateFile?ja("vips.wasm"):(new URL("vips.wasm",import.meta.url)).href;return function(d){return a(d.instance,d.module)}(await fb(b))}
class Ld{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Md={},bd={get(a,b){var c=Md[b];c||=Md[b]=new WebAssembly.Global({value:"i32",mutable:!0},-1);a.has(b)||(c.required=!0);return c}},A,H,J,z,Ta,Ua,G,I,Va,F,Nd=a=>{a.terminate();a.onmessage=()=>{}},Td=a=>{var b=Od[a];Pd.delete(a);a in Qd&&Qd[a].resolve();a=b.W;delete Od[a];Rd.push(b);Sd.splice(Sd.indexOf(b),1);b.W=0;wd(a)},Ya=a=>{for(;0<a.length;)a.shift()(h)},Ud=[],Vd=a=>{Pd.add(a);a in Qd&&Qd[a].resolve()},Xd=a=>{if(0==Rd.length){if(h.mainScriptUrlOrBlob){var b=h.mainScriptUrlOrBlob;"string"!=typeof b&&
(b=URL.createObjectURL(b));b=new Worker(b,{type:"module",workerData:"em-pthread",name:"em-pthread"})}else b=new Worker(new URL("vips-node.mjs",import.meta.url),{type:"module",workerData:"em-pthread",name:"em-pthread"});Rd.push(b);Wd()}b=Rd.pop();if(!b)return 6;Sd.push(b);Od[a.W]=b;b.W=a.W;var c={R:"run",oc:a.nc,Ba:a.Ba,W:a.W};p&&b.unref();b.postMessage(c,a.pb);return 0},Yd=0,N=(a,b,...c)=>{var d=16*c.length,e=Dd(),f=Cd(d),g=f>>3,k;for(k of c)"bigint"==typeof k?((y(),J)[g++]=1n,(y(),
J)[g++]=k):((y(),J)[g++]=0n,(y(),Ua)[g++]=k);a=vd(a,0,d,f,b);Bd(e);return a};function $c(a){if(r)return N(0,1,a);wa=a;Zd||0<Yd||($d(),h.onExit?.(a),va=!0);fa(a,new Ld(a))}$c.h="vi";function ae(a){if(r)return N(1,0,a);Tc(a)}var Tc=a=>{wa=a;if(r)throw ae(a),"unwind";if(!(Zd||0<Yd||r)){md();FS.Ga=!1;hd(0);for(var b of FS.streams)b&&FS.close(b);$d();b=fd();td(0,0,0,1);be||Atomics.notify((y(),H),b>>2);Sa=!0}$c(a)};Tc.h="vi";
var be=!Atomics.waitAsync||globalThis.navigator?.userAgent&&91>Number((navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./)||[])[2]),Rd=[],Sd=[],ce=[],Od={},$d=()=>{for(var a of Sd)Nd(a);for(a of Rd)Nd(a);Rd=[];Sd=[];Od={}};function Ka(){ce.forEach(a=>a())}
var Wd=()=>{var a=Rd[0];new Promise(b=>{a.onmessage=f=>{var g=f.data;f=g.R;if(g.Aa&&g.Aa!=fd()){var k=Od[g.Aa];k?k.postMessage(g,g.pb):w(`worker sent message (${f}) to pthread (${g.Aa}) that no longer exists`)}else if("checkMailbox"===f)Pa();else if("spawnThread"===f)Xd(g);else if("cleanupThread"===f)de(()=>Td(g.Va));else if("markAsFinished"===f)Vd(g.Va);else if("loaded"===f)a.loaded=!0,b(a);else if("setimmediate"===g.target)a.postMessage(g);else if("uncaughtException"===f)a.onerror(g.error);else if("callHandler"===
f)h[g.Ob](...g.args);else f&&w(`worker sent an unknown command ${f}`)};a.onerror=f=>{w(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};p&&(a.on("message",f=>a.onmessage({data:f})),a.on("error",f=>a.onerror(f)));var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)h.propertyIsEnumerable(e)&&c.push(e);a.postMessage({R:"load",Pb:c,sc:xa,tc:ua,Bb:sa,lc:Da})})},Pd,Qd,ee,fe=[];function Ia(a){var b=(y(),I)[a+48>>2];a=(y(),I)[a+52>>2];Ad(b,b-a);Bd(b)}
var ge=new TextDecoder,he=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},ie=(a,b=0,c)=>{c=he(a,b,c);return ge.decode(a.buffer?a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c):new Uint8Array(a.slice(b,c)))},dd=a=>{function b(){for(var t=0,u=1;;){var q=a[f++];t+=(q&127)*u;u*=128;if(!(q&128))break}return t}function c(){var t=b();f+=t;return ie(a,f-t,t)}function d(){for(var t=b(),u=[];t--;)u.push(c());return u}function e(t,u){if(t)throw Error(u);}var f=0,g=0;if(a instanceof
WebAssembly.Module)g=WebAssembly.Module.customSections(a,"dylink.0"),e(0===g.length,"need dylink section"),a=new Uint8Array(g[0]),g=a.length;else{g=1836278016==(new Uint32Array((new Uint8Array(a.subarray(0,24))).buffer))[0];e(!g,"need to see wasm magic number");e(0!==a[8],"need the dylink section to be first");f=9;g=b();g=f+g;var k=c();e("dylink.0"!==k)}for(k={La:[],ob:new Set,rb:new Set,nb:[]};f<g;){var l=a[f++],m=b();if(1===l)k.Ka=b(),k.Wb=b(),k.sa=b(),k.Ic=b();else if(2===l)k.La=d();else if(3===
l)for(l=b();l--;){m=c();var n=b();n&256&&k.ob.add(m)}else if(4===l)for(l=b();l--;)c(),m=c(),n=b(),1==(n&3)&&k.rb.add(m);else 5===l?k.nb=d():f+=m}return k},Oa=(a,b)=>{Zd=Yd=0;pd();a=M.get(a)(b);Zd||0<Yd?wa=a:xd(a)},Jd=(a,b,c)=>{c={ka:Infinity,name:a,exports:c,global:!0};je[a]=c;void 0!=b&&(ke[b]=c);return c},je={},ke={},le=(a,b)=>Math.ceil(a/b)*b,me=a=>{if(Ra)return jd(a,1);var b=Gd;Gd=a=b+16*Math.ceil(a/16);if(!r){var c=zd();(y(),I)[c>>2]=a}return b},oe=(a,b)=>{if(ne)for(var c=a;c<a+b;c++){var d=
M.get(c);d&&ne.set(d,c)}},ne,pe=a=>{ne||(ne=new WeakMap,oe(0,M.length));return ne.get(a)||0},qe=[],re=a=>{const b=a.length;return[b%128|128,b>>7,...a]},se={i:127,p:127,j:126,f:125,d:124,e:111},te=a=>re(Array.from(a,b=>se[b])),ue=(a,b)=>{var c=pe(a);if(c)return c;c=qe.length?qe.pop():M.grow(1);try{M.set(c,a)}catch(d){if(!(d instanceof TypeError))throw d;b=Uint8Array.of(0,97,115,109,1,0,0,0,1,...re([1,96,...te(b.slice(1)),...te("v"===b[0]?"":b[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(b);
b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f;M.set(c,b)}ne.set(a,c);return c},Id=(a,b)=>{for(var c in a){var d=c;if(!"memory __memory_base __table_base __stack_pointer __indirect_function_table __cpp_exception __c_longjmp __wasm_apply_data_relocs __dso_handle __tls_size __tls_align __set_stack_limits _emscripten_tls_init __wasm_init_tls __wasm_call_ctors __start_em_asm __stop_em_asm __start_em_js __stop_em_js".split(" ").includes(d)&&!d.startsWith("__em_js__")){d=a[c];var e=Md[c]&&-1!=Md[c].value;
if(b||!e){if("function"==typeof d)d=ue(d);else if("number"!=typeof d.value)continue;let f;Md[f=c]??(Md[f]=new WebAssembly.Global({value:"i32",mutable:!0}));Md[c].value=d}}}},ve=(a,b=0)=>{var c={},d;for(d in a){var e=d;var f=a[d];a:{if(f instanceof WebAssembly.Global)try{f.value=f.value}catch{var g=!0;break a}g=!1}f=g?new WebAssembly.Global({value:"i32"},f.value+b):f;c[e]=f}return c},we=a=>{a=hb[a];return!a||a.Ta?!1:!0},xe=(a,b)=>Object.defineProperty(b,"name",{value:a}),ye=a=>{var b;we(a)&&(b=hb[a]);
return{Ua:b,name:a}},$a=[],O=(a,b,c)=>{if(!a)return"";b=he((y(),F),a,b,c);return ge.decode((y(),F).slice(a,b))},De=(a,b,c,d,e)=>{function f(){function l(D,B){function E(Ba,ba){Ba=[];for(var Cb=0;;Cb++){var ab="$"+Cb;if(!ba.includes(ab))break;Ba.push(ab)}Ba=Ba.join(",");ze[C]=eval(`(${Ba}) => { ${ba} };`)}function T(Ba,ba,Cb){var ab=[];ba=ba.slice(1,-1);if("void"!=ba){ba=ba.split(",");for(var Fg of ba)ba=Fg.split(" ").pop(),ab.push(ba.replaceAll("*",""))}q[Ba]=eval(`(${ab}) => ${Cb};`)}!r&&c&&(Da[c]=
D);oe(u,g.sa);q=ve(B.exports,t);Id(q);b.vb||Ae();if("__start_em_asm"in q){var C=q.__start_em_asm.value;for(D=q.__stop_em_asm.value;C<D;){var Ma=O(C);E(C,Ma);C=(y(),F).indexOf(0,C)+1}}for(var Db in q)if(Db.startsWith("__em_js__")){C=q[Db].value;Ma=O(C);var [Gg,Hg]=Ma.split("<::>");T(Db.replace("__em_js__",""),Gg,Hg);delete q[Db]}ed(q._emscripten_tls_init,B.exports,g);m&&((B=q.__wasm_apply_data_relocs)&&(Ra?B():Wa.push(B)),(B=q.__wasm_call_ctors)&&(Ra?B():$a.push(B)));return q}var m=!e||!(y(),z)[e+
8];if(m){var n=Math.pow(2,g.Wb),t=g.Ka?le(me(g.Ka+n),n):0,u=g.sa?M.length:0;e&&((y(),z)[e+8]=1,(y(),I)[e+12>>2]=t,(y(),H)[e+16>>2]=g.Ka,(y(),I)[e+20>>2]=u,(y(),H)[e+24>>2]=g.sa)}else t=(y(),I)[e+12>>2],u=(y(),I)[e+20>>2];g.sa&&M.grow(g.sa);var q;n=new Proxy({},{get(D,B){switch(B){case "__memory_base":return t;case "__table_base":return u}if(B in hb&&!hb[B].Ta)return hb[B];if(!(B in D)){var E;D[B]=(...T)=>{if(!E){var C=ye(B).Ua;!C&&d&&(C=d[B]);C||=q[B];E=C}return E(...T)}}return D[B]}});var v=new Proxy(g.rb,
bd),x={"GOT.mem":v,"GOT.func":v,env:n,wasi_snapshot_preview1:n};if(b.J)return(async()=>{var D;a instanceof WebAssembly.Module?D=new WebAssembly.Instance(a,x):{module:a,instance:D}=await WebAssembly.instantiate(a,x);return l(a,D)})();n=a instanceof WebAssembly.Module?a:new WebAssembly.Module(a);v=new WebAssembly.Instance(n,x);return l(n,v)}var g=dd(a);b={...b,Ra:{$b:c,cc:g.nb}};if(b.J)return g.La.reduce((l,m)=>l.then(()=>{m=Be(m,b.Ra)??m;return Ce(m,b,d)}),Promise.resolve()).then(f);for(var k of g.La)k=
Be(k,b.Ra)??k,Ce(k,b,d);return f()},cd=a=>{var b,c;for([b,c]of Object.entries(a))we(b)||(hb[b]=c)},Ee=async a=>{a=await ka(a);return new Uint8Array(a)},Fe=[],Ge={},He=require("node:path"),Ie=He.isAbsolute,Je=He.normalize,Ke=He.dirname,Le=He.basename,Me=He.join,Ne=He.join,Oe=a=>{var b=Dd();a=a();Bd(b);return a},Pe=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Qe=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=
0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Re=(a,b,c)=>Qe(a,(y(),F),b,c),Se=a=>{var b=Pe(a)+1,c=Cd(b);Re(a,c,b);return c},Te=()=>{if(p){var a=require("node:crypto");return b=>a.randomFillSync(b)}return b=>
(b.set(crypto.getRandomValues(new Uint8Array(b.byteLength))),0)},Ue=a=>(Ue=Te())(a),Ve=(...a)=>{a.unshift(FS.cwd());return He.posix.resolve(...a)},We=(a,b)=>He.posix.relative(a||FS.cwd(),b||FS.cwd()),Xe=[],Ye=a=>{var b=Array(Pe(a)+1);a=Qe(a,b,0,b.length);b.length=a;return b},Ze=[];function $e(a,b){Ze[a]={input:[],output:[],da:b};FS.registerDevice(a,af)}
var af={open(a){var b=Ze[a.node.rdev];if(!b)throw new FS.g(43);a.tty=b;a.seekable=!1},close(a){a.tty.da.fsync(a.tty)},fsync(a){a.tty.da.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.da.cb)throw new FS.g(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.da.cb(a.tty)}catch(k){throw new FS.g(29);}if(void 0===g&&0===e)throw new FS.g(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.da.Oa)throw new FS.g(60);try{for(var e=0;e<d;e++)a.tty.da.Oa(a.tty,
b[c+e])}catch(f){throw new FS.g(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},bf={cb(){a:{if(!Xe.length){var a=null;if(p){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}if(!a){a=null;break a}Xe=Ye(a)}a=Xe.shift()}return a},Oa(a,b){null===b||10===b?(ra(ie(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ra(ie(a.output)),a.output=[])},
Rb(){return{zc:25856,Bc:5,yc:191,Ac:35387,xc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Sb(){return 0},Tb(){return[24,80]}},cf={Oa(a,b){null===b||10===b?(w(ie(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(w(ie(a.output)),a.output=[])}},df=a=>{a=65536*Math.ceil(a/65536);var b=ld(65536,a);b&&(y(),F).fill(0,b,b+a);return b},P={V:null,mount(){return P.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(FS.isBlkdev(c)||FS.isFIFO(c))throw new FS.g(63);
P.V||(P.V={dir:{node:{I:P.m.I,K:P.m.K,lookup:P.m.lookup,S:P.m.S,rename:P.m.rename,unlink:P.m.unlink,rmdir:P.m.rmdir,readdir:P.m.readdir,symlink:P.m.symlink},stream:{llseek:P.o.llseek}},file:{node:{I:P.m.I,K:P.m.K},stream:{llseek:P.o.llseek,read:P.o.read,write:P.o.write,aa:P.o.aa,ea:P.o.ea}},link:{node:{I:P.m.I,K:P.m.K,readlink:P.m.readlink},stream:{}},Wa:{node:{I:P.m.I,K:P.m.K},stream:FS.xb}});c=FS.createNode(a,b,c,d);FS.isDir(c.mode)?(c.m=P.V.dir.node,c.o=P.V.dir.stream,c.v={}):FS.isFile(c.mode)?
(c.m=P.V.file.node,c.o=P.V.file.stream,c.N=0,c.v=P.Cb??(P.Cb=new Uint8Array(0))):FS.isLink(c.mode)?(c.m=P.V.link.node,c.o=P.V.link.stream):FS.isChrdev(c.mode)&&(c.m=P.V.Wa.node,c.o=P.V.Wa.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.v[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},m:{I(a){var b={};b.dev=FS.isChrdev(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.N:FS.isLink(a.mode)?b.size=a.link.length:b.size=
0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},K(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.N!=b&&(c=a.v,a.v=new Uint8Array(b),a.v.set(c.subarray(0,Math.min(b,a.N))),a.N=b))},lookup(){P.Ca||(P.Ca=new FS.g(44),P.Ca.stack="<generic error, no stack>");throw P.Ca;},S(a,b,c,d){return P.createNode(a,b,c,d)},rename(a,b,c){try{var d=ef(b,c)}catch(f){}if(d){if(FS.isDir(a.mode))for(var e in d.v)throw new FS.g(55);
ff(d)}delete a.parent.v[a.name];b.v[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.v[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=ef(a,b),d;for(d in c.v)throw new FS.g(55);delete a.v[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.v)]},symlink(a,b,c){a=P.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(!FS.isLink(a.mode))throw new FS.g(28);return a.link}},o:{read(a,b,c,d,e){if(e>=a.node.N)return 0;d=Math.min(a.node.N-
e,d);b.set(a.node.v.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===(y(),z).buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(f)a.v=b.subarray(c,c+d),a.N=d;else if(0===a.N&&0===e)a.v=b.slice(c,c+d),a.N=d;else{f=e+d;var g=a.v.length;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.v.subarray(0,a.N),a.v=new Uint8Array(f),a.v.set(g));a.v.set(b.subarray(c,c+d),e);a.N=Math.max(a.N,e+d)}return d},llseek(a,b,c){1===c?b+=a.position:2===c&&FS.isFile(a.node.mode)&&
(b+=a.node.N);if(0>b)throw new FS.g(28);return b},aa(a,b,c,d,e){if(!FS.isFile(a.node.mode))throw new FS.g(43);a=a.node.v;if(e&2||a.buffer!==(y(),z).buffer){d=!0;e=df(b);if(!e)throw new FS.g(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);(y(),z).set(a,e)}}else d=!1,e=a.byteOffset;return{u:e,U:d}},ea(a,b,c,d){P.o.write(a,b,0,d,c,!1);return 0}}},gf=a=>{if("string"!=typeof a)return a;var b={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[a];if("undefined"==
typeof b)throw Error(`Unknown file open mode: ${a}`);return b},hf=a=>{"string"==typeof a&&(a=Ye(a));a.subarray||(a=new Uint8Array(a));return a},jf=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},kf={EPERM:63,ENOENT:44,ESRCH:71,EINTR:27,EIO:29,ENXIO:60,E2BIG:1,ENOEXEC:45,EBADF:8,ECHILD:12,EAGAIN:6,EWOULDBLOCK:6,ENOMEM:48,EACCES:2,EFAULT:21,ENOTBLK:105,EBUSY:10,EEXIST:20,EXDEV:75,ENODEV:43,ENOTDIR:54,EISDIR:31,EINVAL:28,ENFILE:41,EMFILE:33,ENOTTY:59,ETXTBSY:74,EFBIG:22,ENOSPC:51,ESPIPE:70,EROFS:69,
EMLINK:34,EPIPE:64,EDOM:18,ERANGE:68,ENOMSG:49,EIDRM:24,ECHRNG:106,EL2NSYNC:156,EL3HLT:107,EL3RST:108,ELNRNG:109,EUNATCH:110,ENOCSI:111,EL2HLT:112,EDEADLK:16,ENOLCK:46,EBADE:113,EBADR:114,EXFULL:115,ENOANO:104,EBADRQC:103,EBADSLT:102,EDEADLOCK:16,EBFONT:101,ENOSTR:100,ENODATA:116,ETIME:117,ENOSR:118,ENONET:119,ENOPKG:120,EREMOTE:121,ENOLINK:47,EADV:122,ESRMNT:123,ECOMM:124,EPROTO:65,EMULTIHOP:36,EDOTDOT:125,EBADMSG:9,ENOTUNIQ:126,EBADFD:127,EREMCHG:128,ELIBACC:129,ELIBBAD:130,ELIBSCN:131,ELIBMAX:132,
ELIBEXEC:133,ENOSYS:52,ENOTEMPTY:55,ENAMETOOLONG:37,ELOOP:32,EOPNOTSUPP:138,EPFNOSUPPORT:139,ECONNRESET:15,ENOBUFS:42,EAFNOSUPPORT:5,EPROTOTYPE:67,ENOTSOCK:57,ENOPROTOOPT:50,ESHUTDOWN:140,ECONNREFUSED:14,EADDRINUSE:3,ECONNABORTED:13,ENETUNREACH:40,ENETDOWN:38,ETIMEDOUT:73,EHOSTDOWN:142,EHOSTUNREACH:23,EINPROGRESS:26,EALREADY:7,EDESTADDRREQ:17,EMSGSIZE:35,EPROTONOSUPPORT:66,ESOCKTNOSUPPORT:137,EADDRNOTAVAIL:4,ENETRESET:39,EISCONN:30,ENOTCONN:53,ETOOMANYREFS:141,EUSERS:136,EDQUOT:19,ESTALE:72,ENOTSUP:138,
ENOMEDIUM:148,EILSEQ:25,EOVERFLOW:61,ECANCELED:11,ENOTRECOVERABLE:56,EOWNERDEAD:62,ESTRPIPE:135};function Q(a){try{return a()}catch(b){if(!b.code)throw b;if("UNKNOWN"===b.code)throw new FS.g(28);throw new FS.g(kf[b.code]);}}function lf(a){return Q(()=>{var b=fs.lstatSync(a).mode;NODEFS.la&&(b|=(b&292)>>2);return b})}function R(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.mount.Na.root);b.reverse();return Me(...b)}
function mf(a){a&=-2721793;var b=0,c;for(c in NODEFS.bb)a&c&&(b|=NODEFS.bb[c],a^=c);if(a)throw new FS.g(28);return b}
var NODEFS={la:!1,Sa(){NODEFS.la=!!process.platform.match(/^win/);var a=process.binding("constants").fs;NODEFS.bb={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,256:a.O_NOCTTY,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY,131072:a.O_NOFOLLOW}},mount(a){return NODEFS.createNode(null,"/",lf(a.Na.root),0)},createNode(a,b,c){if(!FS.isDir(c)&&!FS.isFile(c)&&!FS.isLink(c))throw new FS.g(28);a=FS.createNode(a,b,c);a.m=NODEFS.m;a.o=NODEFS.o;return a},I(a,b){a=Q(a);NODEFS.la&&(a.blksize||(a.blksize=
4096),a.blocks||(a.blocks=(a.size+a.blksize-1)/a.blksize|0),a.mode|=(a.mode&292)>>2);return{dev:a.dev,ino:b.id,mode:a.mode,nlink:a.nlink,uid:a.uid,gid:a.gid,rdev:a.rdev,size:a.size,atime:a.atime,mtime:a.mtime,ctime:a.ctime,blksize:a.blksize,blocks:a.blocks}},K(a,b,c,d,e,f,g){Q(()=>{if(void 0!==c.mode){var k=c.mode;NODEFS.la&&(k&=384);d(a,k);b.mode=c.mode}if("number"===typeof(c.atime??c.mtime)){k=new Date(c.atime??g(a).atime);var l=new Date(c.mtime??g(a).mtime);e(a,k,l)}void 0!==c.size&&f(a,c.size)})},
m:{I(a){var b=R(a);return NODEFS.I(()=>fs.lstatSync(b),a)},K(a,b){var c=R(a);if(null!=b.mode&&b.Da)throw new FS.g(52);NODEFS.K(c,a,b,fs.chmodSync,fs.utimesSync,fs.truncateSync,fs.lstatSync)},lookup(a,b){var c=Ne(R(a),b);c=lf(c);return NODEFS.createNode(a,b,c)},S(a,b,c,d){var e=NODEFS.createNode(a,b,c,d),f=R(e);Q(()=>{FS.isDir(e.mode)?fs.mkdirSync(f,e.mode):fs.writeFileSync(f,"",{mode:e.mode})});return e},rename(a,b,c){var d=R(a),e=Ne(R(b),c);try{FS.unlink(e)}catch(f){}Q(()=>fs.renameSync(d,e));a.name=
c},unlink(a,b){var c=Ne(R(a),b);Q(()=>fs.unlinkSync(c))},rmdir(a,b){var c=Ne(R(a),b);Q(()=>fs.rmdirSync(c))},readdir(a){var b=R(a);return Q(()=>fs.readdirSync(b))},symlink(a,b,c){var d=Ne(R(a),b);Q(()=>fs.symlinkSync(c,d))},readlink(a){var b=R(a);return Q(()=>fs.readlinkSync(b))},ra(a){var b=Q(()=>fs.qc(a));b.Gb=b.wb;return b}},o:{I(a){return NODEFS.I(()=>fs.fstatSync(a.C),a.node)},K(a,b){NODEFS.K(a.C,a.node,b,fs.fchmodSync,fs.futimesSync,fs.ftruncateSync,fs.fstatSync)},open(a){var b=R(a.node);Q(()=>
{a.Y.ka=1;a.C=fs.openSync(b,mf(a.flags))})},close(a){Q(()=>{a.C&&0===--a.Y.ka&&fs.closeSync(a.C)})},Ab(a){a.Y.ka++},read(a,b,c,d,e){return Q(()=>fs.readSync(a.C,b,c,d,e))},write(a,b,c,d,e){return Q(()=>fs.writeSync(a.C,b,c,d,e))},llseek(a,b,c){var d=b;1===c?d+=a.position:2===c&&FS.isFile(a.node.mode)&&Q(()=>{d+=fs.fstatSync(a.C).size});if(0>d)throw new FS.g(28);return d},aa(a,b,c){if(!FS.isFile(a.node.mode))throw new FS.g(43);var d=df(b);NODEFS.o.read(a,(y(),z),d,b,c);return{u:d,U:!0}},ea(a,b,c,d){NODEFS.o.write(a,
b,0,d,c,!1);return 0}}},nf={close(a){FS.streams[a.fd]=null;0>=--a.Y.Qa&&2<a.C&&fs.closeSync(a.C)},llseek(a,b,c){if(1===c)b+=a.position;else if(2===c)b+=fs.fstatSync(a.C).size;else if(0!==c)throw new FS.g(28);if(0>b)throw new FS.g(28);return a.position=b},read(a,b,c,d,e){var f="undefined"!=typeof e;!f&&a.seekable&&(e=a.position);b=fs.readSync(a.C,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e){a.flags&1024&&FS.llseek(a,0,2);var f="undefined"!=typeof e;!f&&a.seekable&&(e=a.position);b=fs.writeSync(a.C,
b,c,d,e);f||(a.position+=b);return b},aa(a,b,c){if(!b)throw new FS.g(28);var d=df(b);FS.read(a,(y(),z),d,b,c);return{u:d,U:!0}},ea(a,b,c,d){FS.write(a,b,0,d,c);return 0},wa(){throw new FS.g(59);}},of={lookup(a,b){return FS.lookupPath(`${a.path}/${b}`).node},lookupPath(a,b={}){b.parent&&(a=Ke(a));b=fs.lstatSync(a);var c=lf(a);return{path:a,node:{id:b.ino,mode:c,m:of,path:a}}},Xa(){FS.ga({C:0,position:0,path:"/dev/stdin",flags:0,seekable:!1},0);for(var a=[,"/dev/stdout","/dev/stderr"],b=1;3>b;b++)FS.ga({C:b,
position:0,path:a[b],flags:577,seekable:!1},b)},cwd(){return process.cwd()},chdir(...a){process.chdir(...a)},S(a,b){FS.isDir(a)?fs.mkdirSync(a,b):fs.writeFileSync(a,"",{mode:b})},mkdir(...a){fs.mkdirSync(...a)},symlink(...a){fs.symlinkSync(...a)},rename(...a){fs.renameSync(...a)},rmdir(...a){fs.rmdirSync(...a)},readdir(...a){return[".",".."].concat(fs.readdirSync(...a))},unlink(...a){fs.unlinkSync(...a)},readlink(...a){return fs.readlinkSync(...a)},stat(a,b){a=b?fs.lstatSync(a):fs.statSync(a);NODEFS.la&&
(a.mode|=(a.mode&292)>>2);return a},fstat(a){a=S(a);return fs.fstatSync(a.C)},ra(a){return Object.assign({Hb:42,flags:2,Xb:255},fs.qc(a))},pc(a){return FS.ra(a.path)},chmod(a,b,c){b&=4095;NODEFS.la&&(b&=384);if(c&&fs.lstatSync(a).isSymbolicLink())throw new FS.g(138);fs.chmodSync(a,b)},fchmod(a,b){a=S(a);fs.fchmodSync(a.C,b)},chown(...a){fs.chownSync(...a)},fchown(a,b,c){a=S(a);fs.fchownSync(a.C,b,c)},truncate(a,b){if(0>b)throw new FS.g(28);return fs.truncateSync(a,b)},ftruncate(a,b){if(0>b)throw new FS.g(28);
a=S(a);fs.ftruncateSync(a.C,b)},utime(){},open(a,b,c){b=gf(b);var d=a.split("/").map(f=>f.slice(0,255)).join("/");c=fs.openSync(d,mf(b),c);var e=fs.fstatSync(c);if(b&65536&&!e.isDirectory())throw fs.closeSync(c),new FS.g(kf.uc);d=lf(d);return FS.ga({C:c,position:0,path:a,flags:b,node:{id:e.ino,mode:d,m:of,path:a},seekable:!0})},ga(a,b){b=pf.ga(a,b);if(!a.o){let c;(c=b.Y).Qa??(c.Qa=0);b.Y.Qa++;b.tty=qf.isatty(b.C)}return b}},rf=0,sf=null,tf=()=>{rf--;h.monitorRunDependencies?.(rf);if(0==rf&&sf){var a=
sf;sf=null;a()}},uf=()=>{rf++;h.monitorRunDependencies?.(rf)},vf=async(a,b)=>{"undefined"!=typeof Browser&&Browser.init();for(var c of Fe)if(c.canHandle(b))return c.handle(a,b);return a},wf=async(a,b,c,d,e,f,g,k)=>{var l=b?Ve(Ne(a,b)):a,m=`cp ${l}`;uf(m);try{var n=c;"string"==typeof c&&(n=await Ee(c));n=await vf(n,l);k?.();f||FS.createDataFile(a,b,n,d,e,g)}finally{tf(m)}};
function ef(a,b){var c=FS.isDir(a.mode)?(c=xf(a,"x"))?c:a.m.lookup?0:2:54;if(c)throw new FS.g(c);for(c=FS.ba[yf(a.id,b)];c;c=c.ja){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return FS.lookup(a,b)}function ff(a){var b=yf(a.parent.id,a.name);if(FS.ba[b]===a)FS.ba[b]=a.ja;else for(b=FS.ba[b];b;){if(b.ja===a){b.ja=a.ja;break}b=b.ja}}function S(a){a=FS.Lb(a);if(!a)throw new FS.g(8);return a}
function yf(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%FS.ba.length}function zf(a){var b=yf(a.parent.id,a.name);a.ja=FS.ba[b];FS.ba[b]=a}function xf(a,b){return FS.eb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function Af(a,b){if(!FS.isDir(a.mode))return 54;try{return ef(a,b),20}catch(c){}return xf(a,"wx")}
function Bf(a,b,c){try{var d=ef(a,b)}catch(e){return e.B}if(a=xf(a,"wx"))return a;if(c){if(!FS.isDir(d.mode))return 54;if(FS.na(d)||FS.getPath(d)===FS.cwd())return 10}else if(FS.isDir(d.mode))return 31;return 0}function Cf(a,b){if(!a)throw new FS.g(b);return a}function Df(a,b=-1){a=FS.ga(a,b);a.o?.Ab?.(a);return a}function Ef(a,b,c){var d=a?.o.K;a=d?a:b;d??=b.m.K;Cf(d,63);try{d(a,c)}catch(e){if(e instanceof RangeError)throw new FS.g(22);throw e;}}
function Ff(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.oa)}return b}function Gf(a){var b={wb:4096,Gb:4096,blocks:1E6,wc:5E5,vc:5E5,files:FS.Ma,Dc:FS.Ma-1,Hb:42,flags:2,Xb:255};a.m.ra&&Object.assign(b,a.m.ra(a.mount.Na.root));return b}function Hf(a,b,c,d){Ef(a,b,{mode:c&4095|b.mode&-4096,ctime:Date.now(),Da:d})}
function If(a,b,c){if(FS.isDir(b.mode))throw new FS.g(31);if(!FS.isFile(b.mode))throw new FS.g(28);var d=xf(b,"w");if(d)throw new FS.g(d);Ef(a,b,{size:c,timestamp:Date.now()})}
function Jf(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=>0,write:(d,e,f,g)=>g,llseek:()=>0});FS.mkdev("/dev/null",FS.makedev(1,3));$e(FS.makedev(5,0),bf);$e(FS.makedev(6,0),cf);FS.mkdev("/dev/tty",FS.makedev(5,0));FS.mkdev("/dev/tty1",FS.makedev(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ue(a),b=a.byteLength);return a[--b]};FS.createDevice("/dev","random",c);FS.createDevice("/dev","urandom",c);FS.mkdir("/dev/shm");FS.mkdir("/dev/shm/tmp")}
function Kf(){FS.mkdir("/proc");var a=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var b=FS.createNode(a,"fd",16895,73);b.o={llseek:P.o.llseek};b.m={lookup(c,d){c=+d;var e=S(c);c={parent:null,mount:{ib:"fake"},m:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(FS.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")}
function Lf(a,b,c,d){a=Ne("string"==typeof a?a:FS.getPath(a),b);return FS.create(a,jf(c,d))}function Mf(a){if(!(a.Ub||a.Vb||a.link||a.v))if(globalThis.XMLHttpRequest)K("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.v=la(a.url)}catch(b){throw new FS.g(29);}}
var FS={root:null,oa:[],$a:{},streams:[],Ma:1,ba:null,Ya:"/",Ga:!1,eb:!0,Fb:null,za:0,g:class{name="ErrnoError";constructor(a){this.B=a}},tb:class{Y={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.Y.flags}set flags(a){this.Y.flags=a}get position(){return this.Y.position}set position(a){this.Y.position=a}},sb:class{m={};o={};T=null;constructor(a,b,c,d){a||=this;this.parent=a;this.mount=a.mount;this.id=FS.Ma++;this.name=b;this.mode=c;this.rdev=d;this.atime=
this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Vb(){return FS.isDir(this.mode)}get Ub(){return FS.isChrdev(this.mode)}},lookupPath(a,b={}){if(!a)throw new FS.g(44);b.va??(b.va=!0);Ie(a)||(a=FS.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=FS.root,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;
if("."!==a[f])if(".."===a[f])if(e=Ke(e),FS.na(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Ne(e,a[f]);try{d=ef(d,a[f])}catch(k){if(44===k?.B&&g&&b.Yb)return{path:e};throw k;}!d.T||g&&!b.va||(d=d.T.root);if(FS.isLink(d.mode)&&(!g||b.follow)){if(!d.m.readlink)throw new FS.g(52);d=d.m.readlink(d);Ie(d)||(d=Ke(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new FS.g(32);},getPath(a){for(var b;;){if(FS.na(a))return a=a.mount.ib,b?"/"!==a[a.length-
1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},createNode(a,b,c,d){a=new FS.sb(a,b,c,d);zf(a);return a},na(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isDir(a){return 16384===(a&61440)},isLink(a){return 40960===(a&61440)},isChrdev(a){return 8192===(a&61440)},isBlkdev(a){return 24576===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},ub:4096,Lb:a=>FS.streams[a],ga(a,b=-1){a=Object.assign(new FS.tb,a);if(-1==b)a:{for(b=0;b<=FS.ub;b++)if(!FS.streams[b])break a;
throw new FS.g(33);}a.fd=b;return FS.streams[b]=a},xb:{open(a){a.o=FS.Jb(a.node.rdev).o;a.o.open?.(a)},llseek(){throw new FS.g(70);}},Ja:a=>a>>8,Fc:a=>a&255,makedev:(a,b)=>a<<8|b,registerDevice(a,b){FS.$a[a]={o:b}},Jb:a=>FS.$a[a],syncfs(a,b){function c(k){FS.za--;return b(k)}function d(k){if(k){if(!d.Db)return d.Db=!0,c(k)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);FS.za++;1<FS.za&&w(`warning: ${FS.za} FS.syncfs operations in flight at once, probably just doing extra work`);var e=
Ff(FS.root.mount),f=0,g;for(g of e)g.type.syncfs?g.type.syncfs(g,a,d):d(null)},mount(a,b,c){var d="/"===c;if(d&&FS.root)throw new FS.g(10);if(!d&&c){var e=FS.lookupPath(c,{va:!1});c=e.path;e=e.node;if(e.T)throw new FS.g(10);if(!FS.isDir(e.mode))throw new FS.g(54);}b={type:a,Na:b,ib:c,oa:[]};a=a.mount(b);a.mount=b;b.root=a;d?FS.root=a:e&&(e.T=b,e.mount&&e.mount.oa.push(b));return a},unmount(a){a=FS.lookupPath(a,{va:!1});if(!a.node.T)throw new FS.g(28);a=a.node;var b=a.T,c=Ff(b);for([,e]of Object.entries(FS.ba))for(;e;){var d=
e.ja;c.includes(e.mount)&&ff(e);var e=d}a.T=null;a.mount.oa.splice(a.mount.oa.indexOf(b),1)},lookup(a,b){return a.m.lookup(a,b)},S(a,b,c){var d=FS.lookupPath(a,{parent:!0}).node;a=Le(a);if(!a)throw new FS.g(28);if("."===a||".."===a)throw new FS.g(20);var e=Af(d,a);if(e)throw new FS.g(e);if(!d.m.S)throw new FS.g(63);return d.m.S(d,a,b,c)},ra(a){return Gf(FS.lookupPath(a,{follow:!0}).node)},pc(a){return Gf(a.node)},create(a,b=438){return FS.S(a,b&4095|32768,0)},mkdir(a,b=511){return FS.S(a,b&1023|16384,
0)},Gc(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||Ie(a))d+="/";d+=e;try{FS.mkdir(d,b)}catch(f){if(20!=f.B)throw f;}}},mkdev(a,b,c){"undefined"==typeof c&&(c=b,b=438);return FS.S(a,b|8192,c)},symlink(a,b){if(!Ve(a))throw new FS.g(44);var c=FS.lookupPath(b,{parent:!0}).node;if(!c)throw new FS.g(44);b=Le(b);var d=Af(c,b);if(d)throw new FS.g(d);if(!c.m.symlink)throw new FS.g(63);return c.m.symlink(c,b,a)},rename(a,b){var c=Ke(a),d=Ke(b),e=Le(a),f=Le(b);var g=FS.lookupPath(a,{parent:!0});var k=
g.node;g=FS.lookupPath(b,{parent:!0});g=g.node;if(!k||!g)throw new FS.g(44);if(k.mount!==g.mount)throw new FS.g(75);var l=ef(k,e);a=We(a,d);if("."!==a.charAt(0))throw new FS.g(28);a=We(b,c);if("."!==a.charAt(0))throw new FS.g(55);try{var m=ef(g,f)}catch(n){}if(l!==m){b=FS.isDir(l.mode);if(e=Bf(k,e,b))throw new FS.g(e);if(e=m?Bf(g,f,b):Af(g,f))throw new FS.g(e);if(!k.m.rename)throw new FS.g(63);if(l.T||m&&m.T)throw new FS.g(10);if(g!==k&&(e=xf(k,"w")))throw new FS.g(e);ff(l);try{k.m.rename(l,g,f),
l.parent=g}catch(n){throw n;}finally{zf(l)}}},rmdir(a){var b=FS.lookupPath(a,{parent:!0}).node;a=Le(a);var c=ef(b,a),d=Bf(b,a,!0);if(d)throw new FS.g(d);if(!b.m.rmdir)throw new FS.g(63);if(c.T)throw new FS.g(10);b.m.rmdir(b,a);ff(c)},readdir(a){a=FS.lookupPath(a,{follow:!0}).node;return Cf(a.m.readdir,54)(a)},unlink(a){var b=FS.lookupPath(a,{parent:!0}).node;if(!b)throw new FS.g(44);a=Le(a);var c=ef(b,a),d=Bf(b,a,!1);if(d)throw new FS.g(d);if(!b.m.unlink)throw new FS.g(63);if(c.T)throw new FS.g(10);
b.m.unlink(b,a);ff(c)},readlink(a){a=FS.lookupPath(a).node;if(!a)throw new FS.g(44);if(!a.m.readlink)throw new FS.g(28);return a.m.readlink(a)},stat(a,b){a=FS.lookupPath(a,{follow:!b}).node;return Cf(a.m.I,63)(a)},fstat(a){var b=S(a);a=b.node;var c=b.o.I;b=c?b:a;c??=a.m.I;Cf(c,63);return c(b)},lstat(a){return FS.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?FS.lookupPath(a,{follow:!c}).node:a;Hf(null,a,b,c)},lchmod(a,b){FS.chmod(a,b,!0)},fchmod(a,b){a=S(a);Hf(a,a.node,b,!1)},chown(a,b,c,d){a="string"==
typeof a?FS.lookupPath(a,{follow:!d}).node:a;Ef(null,a,{timestamp:Date.now(),Da:d})},lchown(a,b,c){FS.chown(a,b,c,!0)},fchown(a){a=S(a);Ef(a,a.node,{timestamp:Date.now(),Da:!1})},truncate(a,b){if(0>b)throw new FS.g(28);a="string"==typeof a?FS.lookupPath(a,{follow:!0}).node:a;If(null,a,b)},ftruncate(a,b){a=S(a);if(0>b||0===(a.flags&2097155))throw new FS.g(28);If(a,a.node,b)},utime(a,b,c){a=FS.lookupPath(a,{follow:!0}).node;Cf(a.m.K,63)(a,{atime:b,mtime:c})},open(a,b,c=438){if(""===a)throw new FS.g(44);
b=gf(b);c=b&64?c&4095|32768:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");var f=FS.lookupPath(a,{follow:!(b&131072),Yb:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new FS.g(20);}else{if(e)throw new FS.g(31);d=FS.S(a,c|511,0);f=!0}if(!d)throw new FS.g(44);FS.isChrdev(d.mode)&&(b&=-513);if(b&65536&&!FS.isDir(d.mode))throw new FS.g(54);if(!f){e=d;a=b;if(e)if(FS.isLink(e.mode))e=32;else{var g=["r","w","rw"][a&3];a&512&&(g+="w");e=FS.isDir(e.mode)&&("r"!==g||a&576)?31:xf(e,g)}else e=
44;if(e)throw new FS.g(e);}b&512&&!f&&FS.truncate(d,0);b&=-131713;b=FS.ga({node:d,path:FS.getPath(d),flags:b,seekable:!0,position:0,o:d.o,rc:[],error:!1});b.o.open&&b.o.open(b);f&&FS.chmod(d,c&511);return b},close(a){if(null===a.fd)throw new FS.g(8);a.Ea&&(a.Ea=null);try{a.o.close&&a.o.close(a)}catch(b){throw b;}finally{FS.streams[a.fd]=null}a.fd=null},llseek(a,b,c){if(null===a.fd)throw new FS.g(8);if(!a.seekable||!a.o.llseek)throw new FS.g(70);if(0!=c&&1!=c&&2!=c)throw new FS.g(28);a.position=a.o.llseek(a,
b,c);a.rc=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new FS.g(28);if(null===a.fd)throw new FS.g(8);if(1===(a.flags&2097155))throw new FS.g(8);if(FS.isDir(a.node.mode))throw new FS.g(31);if(!a.o.read)throw new FS.g(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new FS.g(70);b=a.o.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new FS.g(28);if(null===a.fd)throw new FS.g(8);if(0===(a.flags&2097155))throw new FS.g(8);if(FS.isDir(a.node.mode))throw new FS.g(31);
if(!a.o.write)throw new FS.g(28);a.seekable&&a.flags&1024&&FS.llseek(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new FS.g(70);b=a.o.write(a,b,c,d,e,f);g||(a.position+=b);return b},aa(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new FS.g(2);if(1===(a.flags&2097155))throw new FS.g(2);if(!a.o.aa)throw new FS.g(43);if(!b)throw new FS.g(28);return a.o.aa(a,b,c,d,e)},ea(a,b,c,d,e){return a.o.ea?a.o.ea(a,b,c,d,e):0},wa(a,b,c){if(!a.o.wa)throw new FS.g(59);
return a.o.wa(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&K(`Invalid encoding type "${b.encoding}"`);var c=FS.open(a,b.flags);a=FS.stat(a).size;var d=new Uint8Array(a);FS.read(c,d,0,a,0);"utf8"===b.encoding&&(d=ie(d));FS.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=FS.open(a,c.flags,c.mode);b=hf(b);FS.write(a,b,0,b.byteLength,void 0,c.Cc);FS.close(a)},cwd:()=>FS.Ya,chdir(a){a=FS.lookupPath(a,{follow:!0});
if(null===a.node)throw new FS.g(44);if(!FS.isDir(a.node.mode))throw new FS.g(54);var b=xf(a.node,"x");if(b)throw new FS.g(b);FS.Ya=a.path},Xa(a,b,c){a?FS.createDevice("/dev","stdin",a):FS.symlink("/dev/tty","/dev/stdin");b?FS.createDevice("/dev","stdout",null,b):FS.symlink("/dev/tty","/dev/stdout");c?FS.createDevice("/dev","stderr",null,c):FS.symlink("/dev/tty1","/dev/stderr");FS.open("/dev/stdin",0);FS.open("/dev/stdout",1);FS.open("/dev/stderr",1)},Sa(){FS.ba=Array(4096);FS.mount(P,{},"/");FS.mkdir("/tmp");
FS.mkdir("/home");FS.mkdir("/home/web_user");Jf();Kf();FS.Fb={MEMFS:P,NODEFS}},init(a,b,c){FS.Ga=!0;a??=h.stdin;b??=h.stdout;c??=h.stderr;FS.Xa(a,b,c)},Ec(a,b){a=FS.analyzePath(a,b);return a.exists?a.object:null},analyzePath(a,b){try{var c=FS.lookupPath(a,{follow:!b});a=c.path}catch(e){}var d={na:!1,exists:!1,error:0,name:null,path:null,object:null,Zb:!1,bc:null,ac:null};try{c=FS.lookupPath(a,{parent:!0}),d.Zb=!0,d.bc=c.path,d.ac=c.node,d.name=Le(a),c=FS.lookupPath(a,{follow:!b}),d.exists=!0,d.path=
c.path,d.object=c.node,d.name=c.node.name,d.na="/"===c.path}catch(e){d.error=e.B}return d},createPath(a,b){a="string"==typeof a?a:FS.getPath(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ne(a,c);try{FS.mkdir(d)}catch(e){if(20!=e.B)throw e;}a=d}}return d},createDataFile(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:FS.getPath(a),g=b?Ne(a,b):a);a=jf(d,e);g=FS.create(g,a);c&&(c=hf(c),FS.chmod(g,a|146),b=FS.open(g,577),FS.write(b,c,0,c.length,0,f),FS.close(b),FS.chmod(g,a))},
createDevice(a,b,c,d){a=Ne("string"==typeof a?a:FS.getPath(a),b);b=jf(!!c,!!d);var e;(e=FS.createDevice).Ja??(e.Ja=64);e=FS.makedev(FS.createDevice.Ja++,0);FS.registerDevice(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,k,l){for(var m=0,n=0;n<l;n++){try{var t=c()}catch(u){throw new FS.g(29);}if(void 0===t&&0===m)throw new FS.g(6);if(null===t||void 0===t)break;m++;g[k+n]=t}m&&(f.node.atime=Date.now());return m},write(f,g,k,l){for(var m=0;m<l;m++)try{d(g[k+m])}catch(n){throw new FS.g(29);
}l&&(f.node.mtime=f.node.ctime=Date.now());return m}});return FS.mkdev(a,b,e)},createLazyFile(a,b,c,d,e){function f(n,t,u,q,v){n=n.node.v;if(v>=n.length)return 0;q=Math.min(n.length-v,q);if(n.slice)for(var x=0;x<q;x++)t[u+x]=n[v+x];else for(x=0;x<q;x++)t[u+x]=n.get(v+x);return q}class g{Fa=!1;ia=[];ma=void 0;hb=0;gb=0;get(n){if(!(n>this.length-1||0>n)){var t=n%this.chunkSize;return this.ma(n/this.chunkSize|0)[t]}}hc(n){this.ma=n}jb(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);200<=
n.status&&300>n.status||304===n.status||K("Couldn't load "+c+". Status: "+n.status);var t=Number(n.getResponseHeader("Content-length")),u,q=(u=n.getResponseHeader("Accept-Ranges"))&&"bytes"===u;n=(u=n.getResponseHeader("Content-Encoding"))&&"gzip"===u;var v=1048576;q||(v=t);var x=this;x.hc(D=>{var B=D*v,E=(D+1)*v-1;E=Math.min(E,t-1);if("undefined"==typeof x.ia[D]){var T=x.ia;B>E&&K("invalid range ("+B+", "+E+") or no bytes requested!");E>t-1&&K("only "+t+" bytes available! programmer error!");var C=
new XMLHttpRequest;C.open("GET",c,!1);t!==v&&C.setRequestHeader("Range","bytes="+B+"-"+E);C.responseType="arraybuffer";C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");C.send(null);200<=C.status&&300>C.status||304===C.status||K("Couldn't load "+c+". Status: "+C.status);B=void 0!==C.response?new Uint8Array(C.response||[]):Ye(C.responseText||"");T[D]=B}"undefined"==typeof x.ia[D]&&K("doXHR failed!");return x.ia[D]});if(n||!t)v=t=1,v=t=this.ma(0).length,ra("LazyFiles on gzip forces download of the whole file when length is accessed");
this.hb=t;this.gb=v;this.Fa=!0}get length(){this.Fa||this.jb();return this.hb}get chunkSize(){this.Fa||this.jb();return this.gb}}if(globalThis.XMLHttpRequest){ca||K("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var k=new g;var l=void 0}else l=c,k=void 0;var m=Lf(a,b,d,e);k?m.v=k:l&&(m.v=null,m.url=l);Object.defineProperties(m,{N:{get:function(){return this.v.length}}});a={};for(const [n,t]of Object.entries(m.o))a[n]=(...u)=>
{Mf(m);return t(...u)};a.read=(n,t,u,q,v)=>{Mf(m);return f(n,t,u,q,v)};a.aa=(n,t,u)=>{Mf(m);var q=df(t);if(!q)throw new FS.g(48);f(n,(y(),z),q,t,u);return{u:q,U:!0}};m.o=a;return m}},Be=(a,b)=>{if(Ra){if(Ie(a))try{return FS.lookupPath(a),a}catch(d){return}var c=(b?.cc||[]).map(d=>{var e=b?.$b;d.startsWith("$ORIGIN")&&(e=Ke(e),d=d.replace("$ORIGIN",e));return d});return Oe(()=>{var d=Cd(512),e=Se(c.join(":")),f=Se(a);return(d=sd(d,e,f,512))?O(d):void 0})}};
function Ce(a,b={global:!0,pa:!0},c,d){function e(){var l=Da[a];if(l)return b.J?Promise.resolve(l):l;if(d){l=(y(),I)[d+28>>2];var m=(y(),I)[d+32>>2];if(l&&m)return l=(y(),z).slice(l,l+m),b.J?Promise.resolve(l):l}if(l=Be(a,b.Ra))return l=FS.readFile(l,{encoding:"binary"}),b.J?Promise.resolve(l):l;l=ja(a);if(b.J)return Ee(l);if(!la)throw Error(`${l}: file not found, and synchronous loading of external files is not available`);return la(l)}function f(){var l=Ge[a];return l?b.J?Promise.resolve(l):l:b.J?
e().then(m=>De(m,b,a,c,d)):De(e(),b,a,c,d)}function g(l){k.global?cd(l):c&&Object.assign(c,l);k.exports=l}var k=je[a];if(k)return b.global?k.global||(k.global=!0,cd(k.exports)):c&&Object.assign(c,k.exports),b.pa&&Infinity!==k.ka&&(k.ka=Infinity),k.ka++,d&&(ke[d]=k),b.J?Promise.resolve(!0):!0;k=Jd(a,d,"loading");k.ka=b.pa?Infinity:1;k.global=b.global;if(b.J)return f().then(l=>{g(l);return!0});g(f());return!0}
var Ae=()=>{var a,b;for([a,b]of Object.entries(Md))if(-1==b.value){var c=ye(a).Ua;if(c||b.required)if("function"==typeof c)b.value=ue(c,c.h);else if("number"==typeof c)b.value=c;else if("number"==typeof c.value)b.value=c;else throw Error(`bad export type for '${a}': ${typeof c} (${c})`);else b.value=0}},Kd=async()=>{if(sa.length){uf("loadDylibs");for(var a of sa)await Ce(a,{J:!0,global:!0,pa:!0,vb:!0});Ae();tf("loadDylibs")}else Ae()},Zd=!1,ed=(a,b,c)=>{function d(){var e=a();if(e){var f={};c.ob.forEach(g=>
f[g]=b[g]);Id(ve(f,e),!0)}}ce.push(d);Ra&&d()},xa,ib=(a,b,c,d)=>K(`Assertion failed: ${O(a)}, at: `+[b?O(b):"unknown filename",c,d?O(d):"unknown function"]);ib.h="vppip";var jb=(a,b)=>M.get(a)(b);jb.h="vpi";function kb(...a){return hb.__lsan_ignore_object(...a)}kb.Ta=!0;function Nf(a,b,c,d){return r?N(2,1,a,b,c,d):lb(a,b,c,d)}
var lb=(a,b,c,d)=>{if(!globalThis.SharedArrayBuffer)return 6;var e=[];if(r&&0===e.length)return Nf(a,b,c,d);a={nc:c,W:a,Ba:d,pb:e};return r?(a.R="spawnThread",postMessage(a,e),0):Xd(a)};lb.h="ipppp";var Of=18;function Pf(a,b,c){if(Ie(b))return b;a=-100===a?FS.cwd():S(a).path;if(0==b.length){if(!c)throw new FS.g(44);return a}return a+"/"+b}
function Qf(a,b){(y(),I)[a>>2]=b.dev;(y(),I)[a+4>>2]=b.mode;(y(),I)[a+8>>2]=b.nlink;(y(),I)[a+12>>2]=b.uid;(y(),I)[a+16>>2]=b.gid;(y(),I)[a+20>>2]=b.rdev;(y(),J)[a+24>>3]=BigInt(b.size);(y(),H)[a+32>>2]=4096;(y(),H)[a+36>>2]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),e=b.ctime.getTime();(y(),J)[a+40>>3]=BigInt(Math.floor(c/1E3));(y(),I)[a+48>>2]=c%1E3*1E6;(y(),J)[a+56>>3]=BigInt(Math.floor(d/1E3));(y(),I)[a+64>>2]=d%1E3*1E6;(y(),J)[a+72>>3]=BigInt(Math.floor(e/1E3));(y(),I)[a+80>>2]=e%1E3*
1E6;(y(),J)[a+88>>3]=BigInt(b.ino);return 0}var Rf=void 0;function mb(a){if(r)return N(3,1,a);try{var b=S(a);return Df(b).fd}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}mb.h="ii";
function nb(a,b,c,d){if(r)return N(4,1,a,b,c,d);try{b=O(b);b=Pf(a,b);if(c&-8)return-28;var e=FS.lookupPath(b,{follow:!0}).node;if(!e)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&xf(e,a)?-2:0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}nb.h="iipii";var Sf=()=>{var a=(y(),H)[+Rf>>2];Rf+=4;return a};
function ob(a,b,c){if(r)return N(5,1,a,b,c);Rf=c;try{var d=S(a);switch(b){case 0:var e=Sf();if(0>e)break;for(;FS.streams[e];)e++;return Df(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Sf(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=Sf(),(y(),A)[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}ob.h="iiip";
function pb(a,b){if(r)return N(6,1,a,b);try{return Qf(b,FS.fstat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}pb.h="iip";function qb(a,b){if(r)return N(7,1,a,b);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return-22;FS.ftruncate(a,b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}qb.h="iij";
function rb(a,b){if(r)return N(8,1,a,b);try{if(0===b)return-28;var c=FS.cwd(),d=Pe(c)+1;if(b<d)return-68;Re(c,a,b);return d}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.B}}rb.h="ipp";
function sb(a,b,c){if(r)return N(9,1,a,b,c);Rf=c;try{var d=S(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.da.Rb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Sf();(y(),H)[e>>2]=25856;(y(),H)[e+4>>2]=5;(y(),H)[e+8>>2]=191;(y(),H)[e+12>>2]=35387;for(var f=0;32>f;f++)(y(),z)[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.da.Sb)for(e=
Sf(),y(),y(),y(),y(),a=[],f=0;32>f;f++)a.push((y(),z)[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=Sf();return(y(),H)[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:return e=Sf(),FS.wa(d,b,e);case 21523:if(!d.tty)return-59;d.tty.da.Tb&&(f=[24,80],e=Sf(),(y(),A)[e>>1]=f[0],(y(),A)[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.B}}sb.h="iiip";
function tb(a,b){if(r)return N(10,1,a,b);try{return a=O(a),Qf(b,FS.lstat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}tb.h="ipp";function ub(a,b,c,d){if(r)return N(11,1,a,b,c,d);try{b=O(b);var e=d&256;b=Pf(a,b,d&4096);return Qf(c,e?FS.lstat(b):FS.stat(b))}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}ub.h="iippi";
function vb(a,b,c,d){if(r)return N(12,1,a,b,c,d);Rf=d;try{b=O(b);b=Pf(a,b);var e=d?Sf():0;c&64&&(e&=~Of);return FS.open(b,c,e).fd}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}vb.h="iipip";function wb(a){if(r)return N(13,1,a);try{return a=O(a),FS.rmdir(a),0}catch(b){if("undefined"==typeof FS||"ErrnoError"!==b.name)throw b;return-b.B}}wb.h="ip";
function xb(a,b){if(r)return N(14,1,a,b);try{return a=O(a),Qf(b,FS.stat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}xb.h="ipp";function yb(a,b,c){if(r)return N(15,1,a,b,c);try{b=O(b);b=Pf(a,b);if(c)if(512===c)FS.rmdir(b);else return-28;else FS.unlink(b);return 0}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.B}}yb.h="iipi";
var zb=a=>{a=new WebAssembly.Exception(Hd,[a],{traceStack:!0});var b=a.getArg(Hd,0);var c=Ed(b);b=Dd();var d=Cd(4),e=Cd(4);Fd(c,d,e);c=(y(),I)[d>>2];e=(y(),I)[e>>2];d=O(c);L(c);if(e){var f=O(e);L(e)}Bd(b);a.message=[d,f];throw a;},Ab=()=>K("");Ab.h="v";
var Tf=a=>{var b=Dd();a=Se(a);nd(a,0);Bd(b)},Uf=(a,b)=>{var c=O(a+36),d=(y(),H)[a+4>>2];c=Je(c);var e=!!(d&256),f=e?null:{};d={global:e,pa:!!(d&4096),J:b.J};if(b.J)return Ce(c,d,f,a);try{return Ce(c,d,f,a)}catch(g){return Tf(`could not load dynamic lib: ${c}\n${g}`),0}},Bb=a=>Uf(a,{J:!1});Bb.h="pp";var Eb=(a,b)=>{a=ke[a].exports;b=Object.keys(a)[b];b=a[b];return ue(b,b.h)};Eb.h="ppi";
var Fb=(a,b,c)=>{b=O(b);var d=ke[a];a=Object.keys(d.exports).indexOf(b);if(-1==a||d.exports[b].Ta)return Tf(`Tried to lookup unknown symbol "${b}" in dynamic lib: ${d.name}`),0;b=d.exports[b];"function"==typeof b&&((d=pe(b))?b=d:(b=ue(b,b.h),(y(),I)[c>>2]=a));return b};Fb.h="pppp";var Vf={},Wf=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Xf(a){return this.A((y(),I)[a>>2])}
var Yf={},Zf={},$f={},ag=class extends Error{constructor(a){super(a);this.name="InternalError"}},V=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new ag("Mismatched type converter count");for(var l=0;l<a.length;++l)U(a[l],k[l])}a.forEach(k=>$f[k]=b);var e=Array(b.length),f=[],g=0;for(let [k,l]of b.entries())Zf.hasOwnProperty(l)?e[k]=Zf[l]:(f.push(l),Yf.hasOwnProperty(l)||(Yf[l]=[]),Yf[l].push(()=>{e[k]=Zf[l];++g;g===f.length&&d(e)}));0===f.length&&d(e)},Gb=a=>{var b=Vf[a];delete Vf[a];
var c=b.Pa,d=b.X,e=b.ab,f=e.map(g=>g.Nb).concat(e.map(g=>g.jc));V([a],f,g=>{var k={},l,m;for([l,m]of e.entries()){const n=g[l],t=m.ma,u=m.Mb,q=g[l+e.length],v=m.ic,x=m.kc;k[m.Eb]={read:D=>n.A(t(u,D)),write:(D,B)=>{var E=[];v(x,D,q.F(E,B));Wf(E)},optional:n.optional}}return[{name:b.name,A:n=>{var t={},u;for(u in k)t[u]=k[u].read(n);d(n);return t},F:(n,t)=>{for(var u in k)if(!(u in t||k[u].optional))throw new TypeError(`Missing field: "${u}"`);var q=c();for(u in k)k[u].write(q,t[u]);null!==n&&n.push(d,
q);return q},M:Xf,H:d}]})};Gb.h="vp";var W=a=>{for(var b="";;){var c=(y(),F)[a++];if(!c)return b;b+=String.fromCharCode(c)}},X=class extends Error{constructor(a){super(a);this.name="BindingError"}},bg=a=>{throw new X(a);};
function cg(a,b,c={}){var d=b.name;if(!a)throw new X(`type "${d}" must have a positive integer typeid pointer`);if(Zf.hasOwnProperty(a)){if(c.Qb)return;throw new X(`Cannot register type '${d}' twice`);}Zf[a]=b;delete $f[a];Yf.hasOwnProperty(a)&&(b=Yf[a],delete Yf[a],b.forEach(e=>e()))}function U(a,b,c={}){return cg(a,b,c)}
var dg=(a,b)=>{switch(b){case 4:return y(),Ta;case 8:return y(),Ua;default:throw new TypeError(`invalid float width (${b}): ${a}`);}},eg=(a,b,c)=>{switch(b){case 1:return c?(y(),z):(y(),F);case 2:return c?(y(),A):(y(),G);case 4:return c?(y(),H):(y(),I);case 8:return c?(y(),J):(y(),Va);default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Hb=(a,b,c,d,e)=>{b=W(b);var f=d?dg(b,c):eg(b,c,e),g=Math.log2(c);U(a,{name:b,A:k=>{var l=(y(),I)[k>>2],m=k+Math.max(4,c)>>g;l=Array.from(f.subarray(m,
m+l));L(k);return l},F:(k,l)=>{"number"==typeof l&&(l=[l]);if(!Array.isArray(l))throw new X(`Cannot pass non-array to C++ vector type ${b}`);l=Array.prototype.concat.apply([],l);var m=l.length,n=Math.max(4,c),t=gd(n+m*c);n=t+n>>g;(y(),I)[t>>2]=m;f.set(l,n);null!==k&&k.push(L,t);return t},M:Xf,H(k){L(k)}})};Hb.h="vpppii";
var fg=(a,b,c)=>{switch(b){case 1:return c?d=>(y(),z)[d]:d=>(y(),F)[d];case 2:return c?d=>(y(),A)[d>>1]:d=>(y(),G)[d>>1];case 4:return c?d=>(y(),H)[d>>2]:d=>(y(),I)[d>>2];case 8:return c?d=>(y(),J)[d>>3]:d=>(y(),Va)[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ib=(a,b,c,d,e)=>{b=W(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=k=>BigInt.asUintN(g,k);e=f(e)}U(a,{name:b,A:f,F:(g,k)=>{"number"==typeof k&&(k=BigInt(k));return k},M:fg(b,c,!d),H:null})};Ib.h="vpppjj";
var Jb=(a,b,c,d)=>{b=W(b);U(a,{name:b,A:function(e){return!!e},F:function(e,f){return f?c:d},M:function(e){return this.A((y(),F)[e])},H:null})};Jb.h="vppii";
var gg=a=>{throw new X(a.l.D.s.name+" instance already deleted");},hg=!1,ig=!1,jg=()=>{},kg=a=>{if(hg)return kg=b=>b.deleteLater(),kg(a);if(!globalThis.FinalizationRegistry)return kg=b=>b,a;ig=new FinalizationRegistry(b=>{b=b.l;--b.count.value;0===b.count.value&&(b.L?b.P.X(b.L):b.D.s.X(b.u))});kg=b=>{var c=b.l;c.L&&ig.register(b,{l:c},b);return b};jg=b=>{ig.unregister(b)};return kg(a)},lg=[],mg=()=>{for(;lg.length;){var a=lg.pop();a.l.ha=!1;a["delete"]()}},ng;function og(){}
var pg={},qg=(a,b,c)=>{if(void 0===a[b].G){var d=a[b];a[b]=function(...e){if(!a[b].G.hasOwnProperty(e.length))throw new X(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].G})!`);return a[b].G[e.length].apply(this,e)};a[b].G=[];a[b].G[d.Z]=d}},rg=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].G&&void 0!==h[a].G[c])throw new X(`Cannot register public name '${a}' twice`);qg(h,a,a);if(h[a].G.hasOwnProperty(c))throw new X(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].G[c]=b}else h[a]=b,h[a].Z=c},sg=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function tg(a,b,c,d,e,f,g,k){this.name=a;this.constructor=b;this.$=c;this.X=d;this.O=e;this.Ib=f;this.ta=g;this.zb=k;this.ec=[]}
var ug=(a,b,c)=>{for(;b!==c;){if(!b.ta)throw new X(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ta(a);b=b.O}return a},vg=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function wg(a,b){if(null===b){if(this.Ha)throw new X(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new X(`Cannot pass "${vg(b)}" as a ${this.name}`);if(!b.l.u)throw new X(`Cannot pass deleted object as a pointer of type ${this.name}`);return ug(b.l.u,b.l.D.s,this.s)}
function xg(a,b){if(null===b){if(this.Ha)throw new X(`null is not a valid ${this.name}`);if(this.ya){var c=this.Pa();null!==a&&a.push(this.X,c);return c}return 0}if(!b||!b.l)throw new X(`Cannot pass "${vg(b)}" as a ${this.name}`);if(!b.l.u)throw new X(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.xa&&b.l.D.xa)throw new X(`Cannot convert argument of type ${b.l.P?b.l.P.name:b.l.D.name} to parameter type ${this.name}`);c=ug(b.l.u,b.l.D.s,this.s);if(this.ya){if(void 0===b.l.L)throw new X("Passing raw pointer to smart pointer is illegal");
switch(this.mc){case 0:if(b.l.P===this)c=b.l.L;else throw new X(`Cannot convert argument of type ${b.l.P?b.l.P.name:b.l.D.name} to parameter type ${this.name}`);break;case 1:c=b.l.L;break;case 2:if(b.l.P===this)c=b.l.L;else{var d=b.clone();c=this.fc(c,yg(()=>d["delete"]()));null!==a&&a.push(this.X,c)}break;default:throw new X("Unsupported sharing policy");}}return c}
function zg(a,b){if(null===b){if(this.Ha)throw new X(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new X(`Cannot pass "${vg(b)}" as a ${this.name}`);if(!b.l.u)throw new X(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.l.D.xa)throw new X(`Cannot convert argument of type ${b.l.D.name} to parameter type ${this.name}`);return ug(b.l.u,b.l.D.s,this.s)}
var Ag=(a,b,c)=>{if(b===c)return a;if(void 0===c.O)return null;a=Ag(a,b,c.O);return null===a?null:c.zb(a)},Bg={},Cg=(a,b)=>{if(void 0===b)throw new X("ptr should not be undefined");for(;a.O;)b=a.ta(b),a=a.O;return Bg[b]},Dg=(a,b)=>{if(!b.D||!b.u)throw new ag("makeClassHandle requires ptr and ptrType");if(!!b.P!==!!b.L)throw new ag("Both smartPtrType and smartPtr must be specified");b.count={value:1};return kg(Object.create(a,{l:{value:b,writable:!0}}))};
function Eg(a,b,c,d,e,f,g,k,l,m,n){this.name=a;this.s=b;this.Ha=c;this.xa=d;this.ya=e;this.dc=f;this.mc=g;this.lb=k;this.Pa=l;this.fc=m;this.X=n;e||void 0!==b.O?this.F=xg:(this.F=d?wg:zg,this.H=null)}var Ig=(a,b,c)=>{if(!h.hasOwnProperty(a))throw new ag("Replacing nonexistent public symbol");void 0!==h[a].G&&void 0!==c?h[a].G[c]=b:(h[a]=b,h[a].Z=c)},Y=(a,b)=>{a=W(a);var c=M.get(b);if("function"!=typeof c)throw new X(`unknown function pointer with signature ${a}: ${b}`);return c};
class Jg extends Error{}
var Kg=a=>{a=kd(a);var b=W(a);L(a);return b},Lg=(a,b)=>{function c(f){e[f]||Zf[f]||($f[f]?$f[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Jg(`${a}: `+d.map(Kg).join([", "]));},Kb=(a,b,c,d,e,f,g,k,l,m,n,t,u)=>{n=W(n);f=Y(e,f);k&&=Y(g,k);m&&=Y(l,m);u=Y(t,u);var q=sg(n);rg(q,function(){Lg(`Cannot construct ${n} due to unbound types`,[d])});V([a,b,c],d?[d]:[],v=>{v=v[0];if(d){var x=v.s;var D=x.$}else D=og.prototype;v=xe(n,function(...C){if(Object.getPrototypeOf(this)!==B)throw new X(`Use 'new' to construct ${n}`);
if(void 0===E.fa)throw new X(`${n} has no accessible constructor`);var Ma=E.fa[C.length];if(void 0===Ma)throw new X(`Tried to invoke ctor of ${n} with invalid number of parameters (${C.length}) - expected (${Object.keys(E.fa).toString()}) parameters instead!`);return Ma.apply(this,C)});var B=Object.create(D,{constructor:{value:v}});v.prototype=B;var E=new tg(n,v,B,u,x,f,k,m);if(E.O){var T;(T=E.O).ua??(T.ua=[]);E.O.ua.push(E)}x=new Eg(n,E,!0,!1,!1);T=new Eg(n+"*",E,!1,!1,!1);D=new Eg(n+" const*",E,
!1,!0,!1);pg[a]={pointerType:T,yb:D};Ig(q,v);return[x,T,D]})};Kb.h="vppppppppppppp";function Mg(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].H)return!0;return!1}
function Ng(a,b,c,d,e,f){var g=b.length;if(2>g)throw new X("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,l=Mg(b);c=!b[0].fb;var m=b[0],n=b[1];d=[a,bg,d,e,Wf,m.A.bind(m),n?.F.bind(n)];for(e=2;e<g;++e)m=b[e],d.push(m.F.bind(m));if(!l)for(e=k?1:2;e<b.length;++e)null!==b[e].H&&d.push(b[e].H);l=Mg(b);e=b.length-2;n=[];m=["fn"];k&&m.push("thisWired");for(g=0;g<e;++g)n.push(`arg${g}`),m.push(`arg${g}Wired`);n=n.join(",");m=m.join(",");n=`return function (${n}) {\n`;
l&&(n+="var destructors = [];\n");var t=l?"destructors":"null",u="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");k&&(n+=`var thisWired = toClassParamWire(${t}, this);\n`);for(g=0;g<e;++g){var q=`toArg${g}Wire`;n+=`var arg${g}Wired = ${q}(${t}, arg${g});\n`;u.push(q)}n+=(c||f?"var rv = ":"")+`invoker(${m});\n`;if(l)n+="runDestructors(destructors);\n";else for(g=k?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].H&&(n+=`${f}_dtor(${f});\n`,
u.push(`${f}_dtor`));c&&(n+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(u,n+"}\n"))(...d);return xe(a,b)}
var Og=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push((y(),I)[b+4*d>>2]);return c},Pg=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Lb=(a,b,c,d,e,f,g,k)=>{var l=Og(c,d);b=W(b);b=Pg(b);f=Y(e,f);V([],[a],m=>{function n(){Lg(`Cannot call ${t} due to unbound types`,l)}m=m[0];var t=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var u=m.s.constructor;void 0===u[b]?(n.Z=c-1,u[b]=n):(qg(u,b,t),u[b].G[c-1]=n);V([],l,q=>{q=[q[0],null].concat(q.slice(1));q=Ng(t,q,null,f,g,k);void 0===
u[b].G?(q.Z=c-1,u[b]=q):u[b].G[c-1]=q;if(m.s.ua)for(const v of m.s.ua)v.constructor.hasOwnProperty(b)||(v.constructor[b]=q);return[]});return[]})};Lb.h="vppippppii";
var Mb=(a,b,c,d,e,f)=>{var g=Og(b,c);e=Y(d,e);V([],[a],k=>{k=k[0];var l=`constructor ${k.name}`;void 0===k.s.fa&&(k.s.fa=[]);if(void 0!==k.s.fa[b-1])throw new X(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);k.s.fa[b-1]=()=>{Lg(`Cannot construct ${k.name} due to unbound types`,g)};V([],g,m=>{m.splice(1,0,null);k.s.fa[b-1]=Ng(l,m,null,e,f);return[]});
return[]})};Mb.h="vpipppp";var Nb=(a,b,c,d,e,f,g,k,l)=>{var m=Og(c,d);b=W(b);b=Pg(b);f=Y(e,f);V([],[a],n=>{function t(){Lg(`Cannot call ${u} due to unbound types`,m)}n=n[0];var u=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&n.s.ec.push(b);var q=n.s.$,v=q[b];void 0===v||void 0===v.G&&v.className!==n.name&&v.Z===c-2?(t.Z=c-2,t.className=n.name,q[b]=t):(qg(q,b,u),q[b].G[c-2]=t);V([],m,x=>{x=Ng(u,x,n,f,g,l);void 0===q[b].G?(x.Z=c-2,q[b]=x):q[b].G[c-2]=x;return[]});return[]})};
Nb.h="vppippppiii";
var Qg=(a,b,c)=>{if(!(a instanceof Object))throw new X(`${c} with invalid "this": ${a}`);if(!(a instanceof b.s.constructor))throw new X(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.l.u)throw new X(`cannot call emscripten binding method ${c} on deleted object`);return ug(a.l.u,a.l.D.s,b.s)},Ob=(a,b,c,d,e,f,g,k,l,m)=>{b=W(b);e=Y(d,e);V([],[a],n=>{n=n[0];var t=`${n.name}.${b}`,u={get(){Lg(`Cannot access ${t} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};u.set=l?
()=>Lg(`Cannot access ${t} due to unbound types`,[c,g]):()=>{throw new X(t+" is a read-only property");};Object.defineProperty(n.s.$,b,u);V([],l?[c,g]:[c],q=>{var v=q[0],x={get(){var B=Qg(this,n,t+" getter");return v.A(e(f,B))},enumerable:!0};if(l){l=Y(k,l);var D=q[1];x.set=function(B){var E=Qg(this,n,t+" setter"),T=[];l(m,E,D.F(T,B));Wf(T)}}Object.defineProperty(n.s.$,b,x);return[]});return[]})};Ob.h="vpppppppppp";
var Rg=[],Sg=[0,1,,1,null,1,!0,1,!1,1],Tg=[],oc=a=>{if(9<a&&0===--Sg[a+1]){var b=Sg[a];Sg[a]=void 0;var c=Tg[a];c&&(Tg[a]=void 0,c(b));Rg.push(a)}};oc.h="vp";var Z=a=>{if(!a)throw new X(`Cannot use deleted val. handle = ${a}`);return Sg[a]},yg=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Rg.pop()||Sg.length;Sg[b]=a;Sg[b+1]=1;return b}},Ug={name:"emscripten::val",A:a=>{var b=Z(a);oc(a);return b},F:(a,b)=>yg(b),M:Xf,H:null},Pb=a=>U(a,Ug);
Pb.h="vp";
var Vg=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.A((y(),z)[d])}:function(d){return this.A((y(),F)[d])};case 2:return c?function(d){return this.A((y(),A)[d>>1])}:function(d){return this.A((y(),G)[d>>1])};case 4:return c?function(d){return this.A((y(),H)[d>>2])}:function(d){return this.A((y(),I)[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Qb=(a,b,c,d,e)=>{b=W(b);e=0===e?"object":1===e?"number":"string";switch(e){case "object":function g(){}g.values={};
U(a,{name:b,constructor:g,valueType:e,A:function(k){return this.constructor.values[k]},F:(k,l)=>l.value,M:Vg(b,c,d),H:null});rg(b,g);break;case "number":var f={};U(a,{name:b,Ia:f,valueType:e,A:k=>k,F:(k,l)=>l,M:Vg(b,c,d),H:null});rg(b,f);delete h[b].Z;break;case "string":f={},U(a,{name:b,qb:{},mb:{},Ia:f,valueType:e,A:function(k){return this.mb[k]},F:function(k,l){return this.qb[l]},M:Vg(b,c,d),H:null}),rg(b,f),delete h[b].Z}};Qb.h="vpppii";
var Wg=(a,b)=>{var c=Zf[a];if(void 0===c)throw a=`${b} has unknown type ${Kg(a)}`,new X(a);return c},Rb=(a,b,c)=>{var d=Wg(a,"enum");b=W(b);switch(d.valueType){case "object":a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:xe(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d;break;case "number":d.Ia[b]=c;break;case "string":d.qb[b]=c,d.mb[c]=b,d.Ia[b]=b}};Rb.h="vppi";
var Xg=(a,b)=>{switch(b){case 4:return function(c){return this.A((y(),Ta)[c>>2])};case 8:return function(c){return this.A((y(),Ua)[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Sb=(a,b,c)=>{b=W(b);U(a,{name:b,A:d=>d,F:(d,e)=>e,M:Xg(b,c),H:null})};Sb.h="vppp";var Tb=(a,b,c,d,e,f,g)=>{var k=Og(b,c);a=W(a);a=Pg(a);e=Y(d,e);rg(a,function(){Lg(`Cannot call ${a} due to unbound types`,k)},b-1);V([],k,l=>{l=[l[0],null].concat(l.slice(1));Ig(a,Ng(a,l,null,e,f,g),b-1);return[]})};
Tb.h="vpippppii";var Ub=(a,b,c,d,e)=>{b=W(b);let f=k=>k;if(0===d){var g=32-8*c;f=k=>k<<g>>>g;e=f(e)}U(a,{name:b,A:f,F:(k,l)=>l,M:fg(b,c,0!==d),H:null})};Ub.h="vpppii";var Yg=(a,b,c)=>{const d=(e,f)=>{let g=0;return{next(){if(g>=e)return{done:!0};const k=g;g++;return{value:f(k),done:!1}},[Symbol.iterator](){return this}}};a[Symbol.iterator]||(a[Symbol.iterator]=function(){const e=this[b]();return d(e,f=>this[c](f))})},Vb=(a,b,c,d)=>{c=W(c);d=W(d);V([],[a,b],e=>{Yg(e[0].s.$,c,d);return[]})};Vb.h="vpppp";
var Wb=(a,b,c)=>{function d(f){var g=(y(),I)[f>>2];f=(y(),I)[f+4>>2];return new e((y(),z).buffer,f,g)}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=W(c);U(a,{name:c,A:d,M:d},{Qb:!0})};Wb.h="vpip";var Zg=Object.assign({optional:!0},Ug),Xb=a=>{U(a,Zg)};Xb.h="vpp";
var Yb=(a,b)=>{b=W(b);U(a,{name:b,A(c){var d=(y(),I)[c>>2];d=O(c+4,d,!0);L(c);return d},F(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new X("Cannot pass non-string to std::string");var f=e?Pe(d):d.length;var g=gd(4+f+1),k=g+4;(y(),I)[g>>2]=f;e?Re(d,k,f+1):(y(),F).set(d,k);null!==c&&c.push(L,g);return g},M:Xf,H(c){L(c)}})};Yb.h="vpp";
var $g=new TextDecoder("utf-16le"),ah=(a,b,c)=>{a>>=1;b=he((y(),G),a,b/2,c);return $g.decode((y(),G).slice(a,b))},bh=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);(y(),A)[b>>1]=f;b+=2}(y(),A)[b>>1]=0;return b-d},ch=a=>2*a.length,dh=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=(y(),I)[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},eh=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=
0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;(y(),H)[b>>2]=f;b+=4;if(b+4>c)break}(y(),H)[b>>2]=0;return b-d},fh=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Zb=(a,b,c)=>{c=W(c);if(2===b){var d=ah;var e=bh;var f=ch}else d=dh,e=eh,f=fh;U(a,{name:c,A:g=>{var k=(y(),I)[g>>2];k=d(g+4,k*b,!0);L(g);return k},F:(g,k)=>{if("string"!=typeof k)throw new X(`Cannot pass non-string to C++ string type ${c}`);var l=f(k),m=gd(4+l+b);(y(),I)[m>>2]=l/b;e(k,m+4,l+b);null!==g&&
g.push(L,m);return m},M:Xf,H(g){L(g)}})};Zb.h="vppp";var $b=(a,b,c,d,e,f)=>{Vf[a]={name:W(b),Pa:Y(c,d),X:Y(e,f),ab:[]}};$b.h="vpppppp";var ac=(a,b,c,d,e,f,g,k,l,m)=>{Vf[a].ab.push({Eb:W(b),Nb:c,ma:Y(d,e),Mb:f,jc:g,ic:Y(k,l),kc:m})};ac.h="vpppppppppp";var bc=(a,b)=>{b=W(b);U(a,{fb:!0,name:b,A:()=>{},F:()=>{}})};bc.h="vpp";
var gh=a=>{a instanceof Ld||"unwind"==a||fa(1,a)},de=a=>{if(!Sa&&!va)try{a()}catch(b){gh(b)}finally{if(!(Sa||Zd||0<Yd))try{r?fd()&&xd(wa):Tc(wa)}catch(b){gh(b)}}},cc=(a,b,c,d)=>{function e(k){var l=O(a+36);Tf(`'Could not load dynamic lib: ${l}\n${k}`);--Yd;de(()=>M.get(c)(a,d))}function f(){--Yd;de(()=>M.get(b)(a,d))}Yd+=1;var g=Uf(a,{J:!0});g?g.then(f,e):e()};cc.h="vpppp";function hh(a){var b=ih,c=b.ia.pop()||b.U.length;b.U[c]=a;return c}function jh(a){var b=ih;b.U[a]=void 0;b.ia.push(a)}
class kh{U=[void 0];ia=[];get(a){return this.U[a]}has(a){return void 0!==this.U[a]}}var ih=new kh,lh=()=>{var a={};a.promise=new Promise((b,c)=>{a.reject=c;a.resolve=b});a.id=hh(a);return a},mh=async()=>{const a=ee,b=[];var c=lh();b.push(c.promise);od(c.id);for(const d of Object.keys(Od)){const e=Number(d);e===a||Pd.has(e)||(c=lh(),qd(e,c.id),Qd[e]=c,b.push(c.promise))}await Promise.all(b);Qd={}};
function dc(){if(r)return N(16,2);if(ee)return mh();for(const a of Object.keys(Od)){const b=Number(a);Pd.has(b)||rd(b)}}dc.h="v";function ec(){var a=gd(4*(sa.length+1)),b=a;sa.forEach(c=>{var d=(y(),I),e=b>>2,f=Pe(c)+1,g=gd(f);g&&Re(c,g,f);d[e]=g;b+=4});(y(),I)[b>>2]=0;return a}ec.h="p";var fc=a=>{Ja(a,!ca,1,!aa,262144,!1);Ka()};fc.h="vp";var La=a=>{be||(Atomics.waitAsync((y(),H),a>>2,a).value.then(Pa),a+=120,Atomics.store((y(),H),a>>2,1))};La.h="vp";
var Pa=()=>{var a=fd();a&&de(()=>{La(a);yd()})},gc=(a,b)=>{a==b?setTimeout(Pa):r?postMessage({Aa:a,R:"checkMailbox"}):(a=Od[a])&&a.postMessage({R:"checkMailbox"})};gc.h="vpp";var nh=[],hc=(a,b,c,d,e,f,g)=>{nh.length=0;var k=e>>3;for(d=e+d>>3;k<d;){var l;(y(),J)[k++]?l=(y(),J)[k++]:l=(y(),Ua)[k++];nh.push(l)}a=b?ze[b]:oh[a];ee=c;c=a(...nh);ee=0;if(f)c.then(m=>ud(f,g,m));else return c};hc.h="dippippp";var ic=()=>{Zd=!1;Yd=0};ic.h="v";var jc=a=>{r?postMessage({R:"cleanupThread",Va:a}):Td(a)};jc.h="vp";
var kc=a=>{r?postMessage({R:"markAsFinished",Va:a}):Vd(a)};kc.h="vp";var lc=a=>{p&&Od[a].ref()};lc.h="vp";var mc=(a,b)=>{a=Z(a);b=Z(b);a.set(b)};mc.h="vpp";
var ph=[],qh=a=>{var b=ph.length;ph.push(a);return b},rh=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Wg((y(),I)[b+4*d>>2],`parameter ${d}`);return c},sh=(a,b,c)=>{var d=[];a=a(d,c);d.length&&((y(),I)[b>>2]=yg(d));return a},th={},uh=a=>{var b=th[a];return void 0===b?W(a):b},nc=(a,b,c)=>{var [d,...e]=rh(a,b);b=d.F.bind(d);var f=e.map(l=>l.M.bind(l));a--;var g={toValue:Z};a=f.map((l,m)=>{var n=`argFromPtr${m}`;g[n]=l;return`${n}(args${m?"+"+8*m:""})`});switch(c){case 0:var k="toValue(handle)";break;
case 2:k="new (toValue(handle))";break;case 3:k="";break;case 1:g.getStringOrSymbol=uh,k="toValue(handle)[getStringOrSymbol(methodName)]"}k+=`(${a})`;d.fb||(g.toReturnWire=b,g.emval_returnValue=sh,k=`return emval_returnValue(toReturnWire, destructorsRef, ${k})`);k=`return function (handle, methodName, destructorsRef, args) {\n${k}\n}`;c=(new Function(Object.keys(g),k))(...Object.values(g));k=`methodCaller<(${e.map(l=>l.name)}) => ${d.name}>`;return qh(xe(k,c))};nc.h="pipi";
var pc=a=>{if(!a)return yg(globalThis);a=uh(a);return yg(globalThis[a])};pc.h="pp";var qc=a=>{a=uh(a);return yg(h[a])};qc.h="pp";var rc=(a,b)=>{a=Z(a);b=Z(b);return yg(a[b])};rc.h="ppp";var sc=a=>{9<a&&(Sg[a+1]+=1)};sc.h="vp";var tc=(a,b)=>{a=Z(a);b=Z(b);return a instanceof b};tc.h="ipp";var uc=(a,b,c,d,e)=>ph[a](b,c,d,e);uc.h="dppppp";var vc=a=>{a=Z(a);return"number"==typeof a};vc.h="ip";var wc=a=>{a=Z(a);return"string"==typeof a};wc.h="ip";var xc=a=>yg(uh(a));xc.h="pp";
var yc=a=>{var b=Z(a);Wf(b);oc(a)};yc.h="vp";var zc=(a,b,c)=>{a=Z(a);b=Z(b);c=Z(c);a[b]=c};zc.h="vppp";var Ac=a=>{a=Z(a);return yg(typeof a)};Ac.h="pp";
function Bc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);(y(),H)[b>>2]=a.getUTCSeconds();(y(),H)[b+4>>2]=a.getUTCMinutes();(y(),H)[b+8>>2]=a.getUTCHours();(y(),H)[b+12>>2]=a.getUTCDate();(y(),H)[b+16>>2]=a.getUTCMonth();(y(),H)[b+20>>2]=a.getUTCFullYear()-1900;(y(),H)[b+24>>2]=a.getUTCDay();a=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;(y(),H)[b+28>>2]=a}Bc.h="vjp";
var vh=[0,31,60,91,121,152,182,213,244,274,305,335],wh=[0,31,59,90,120,151,181,212,243,273,304,334];
function Cc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);(y(),H)[b>>2]=a.getSeconds();(y(),H)[b+4>>2]=a.getMinutes();(y(),H)[b+8>>2]=a.getHours();(y(),H)[b+12>>2]=a.getDate();(y(),H)[b+16>>2]=a.getMonth();(y(),H)[b+20>>2]=a.getFullYear()-1900;(y(),H)[b+24>>2]=a.getDay();var c=a.getFullYear();c=(0!==c%4||0===c%100&&0!==c%400?wh:vh)[a.getMonth()]+a.getDate()-1|0;(y(),H)[b+28>>2]=c;(y(),H)[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();
var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();a=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0;(y(),H)[b+32>>2]=a}Cc.h="vjp";function Dc(a,b,c,d,e,f,g){if(r)return N(17,1,a,b,c,d,e,f,g);e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{var k=S(d),l=FS.aa(k,a,e,b,c),m=l.u;(y(),H)[f>>2]=l.U;(y(),I)[g>>2]=m;return 0}catch(n){if("undefined"==typeof FS||"ErrnoError"!==n.name)throw n;return-n.B}}Dc.h="ipiiijpp";
function Ec(a,b,c,d,e,f){if(r)return N(18,1,a,b,c,d,e,f);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=S(e);if(c&2){c=f;if(!FS.isFile(g.node.mode))throw new FS.g(43);if(!(d&2)){var k=(y(),F).slice(a,a+b);FS.ea(g,k,c,b,d)}}}catch(l){if("undefined"==typeof FS||"ErrnoError"!==l.name)throw l;return-l.B}}Ec.h="ippiiij";
var Fc=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var g=Math.max(f,e);(y(),I)[a>>2]=60*g;(y(),H)[b>>2]=Number(f!=e);b=k=>{var l=Math.abs(k);return`UTC${0<=k?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(Re(a,c,17),Re(b,d,17)):(Re(a,d,17),Re(b,c,17))};Fc.h="vpppp";var Mc=()=>performance.timeOrigin+performance.now();Mc.h="d";var Ic=()=>Date.now();Ic.h="d";
var xh=1;function Gc(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(xh)a=performance.timeOrigin+performance.now();else return 52;a=Math.round(1E6*a);(y(),J)[c>>3]=BigInt(a);return 0}Gc.h="iijp";var Hc=()=>{};Hc.h="v";var Jc=a=>w(O(a));Jc.h="vp";var Kc=()=>{Yd+=1;throw"unwind";};Kc.h="v";var Lc=()=>2147483648;Lc.h="p";var Nc=()=>p?require("node:os").cpus().length:navigator.hardwareConcurrency;Nc.h="i";var Oc=a=>{jh(a)};Oc.h="vp";
var Pc=(a,b,c)=>{a=ih.get(a);switch(b){case 0:a.resolve(c);break;case 1:a.resolve(ih.get(c).promise);break;case 2:a.resolve(ih.get(c).promise);jh(c);break;case 3:a.reject(c)}};Pc.h="vpip";var Qc=a=>{var b=(y(),F).length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-xa.buffer.byteLength+65535)/65536|0;try{xa.grow(d);ya();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1};
Qc.h="ip";var yh={},Ah=()=>{if(!zh){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"};p&&(a=process.env);for(var b in yh)void 0===yh[b]?delete a[b]:a[b]=yh[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);zh=c}return zh},zh;function Rc(a,b){if(r)return N(19,1,a,b);var c=0,d=0,e;for(e of Ah()){var f=b+c;(y(),I)[a+d>>2]=f;c+=Re(e,f,Infinity)+1;d+=4}return 0}Rc.h="ipp";
function Sc(a,b){if(r)return N(20,1,a,b);var c=Ah();(y(),I)[a>>2]=c.length;a=0;for(var d of c)a+=Pe(d)+1;(y(),I)[b>>2]=a;return 0}Sc.h="ipp";function Uc(a){if(r)return N(21,1,a);try{var b=S(a);FS.close(b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.B}}Uc.h="ii";
function Vc(a,b){if(r)return N(22,1,a,b);try{var c=S(a),d=c.tty?2:FS.isDir(c.mode)?3:FS.isLink(c.mode)?7:4;(y(),z)[b]=d;(y(),A)[b+2>>1]=0;(y(),J)[b+8>>3]=BigInt(0);(y(),J)[b+16>>3]=BigInt(0);return 0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return e.B}}Vc.h="iip";
function Wc(a,b,c,d){if(r)return N(23,1,a,b,c,d);try{a:{var e=S(a);a=b;for(var f,g=b=0;g<c;g++){var k=(y(),I)[a>>2],l=(y(),I)[a+4>>2];a+=8;var m=FS.read(e,(y(),z),k,l,f);if(0>m){var n=-1;break a}b+=m;if(m<l)break;"undefined"!=typeof f&&(f+=m)}n=b}(y(),I)[d>>2]=n;return 0}catch(t){if("undefined"==typeof FS||"ErrnoError"!==t.name)throw t;return t.B}}Wc.h="iippp";
function Xc(a,b,c,d){if(r)return N(24,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 22;var e=S(a);FS.llseek(e,b,c);(y(),J)[d>>3]=BigInt(e.position);e.Ea&&0===b&&0===c&&(e.Ea=null);return 0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return f.B}}Xc.h="iijip";
function Yc(a,b,c,d){if(r)return N(25,1,a,b,c,d);try{a:{var e=S(a);a=b;for(var f,g=b=0;g<c;g++){var k=(y(),I)[a>>2],l=(y(),I)[a+4>>2];a+=8;var m=FS.write(e,(y(),z),k,l,f);if(0>m){var n=-1;break a}b+=m;if(m<l)break;"undefined"!=typeof f&&(f+=m)}n=b}(y(),I)[d>>2]=n;return 0}catch(t){if("undefined"==typeof FS||"ErrnoError"!==t.name)throw t;return t.B}}Yc.h="iippp";var ad=(a,b)=>Ue((y(),F).subarray(a,a+b));ad.h="ipp";r||(Qd={},Pd=new Set);
(()=>{var a={kb:Promise.resolve(),canHandle:b=>!h.noWasmDecoding&&b.endsWith(".so"),handle:async(b,c)=>a.kb=a.kb.then(async()=>{try{var d=await De(b,{J:!0,pa:!0},c,{})}catch(e){throw Error(`failed to instantiate wasm: ${c}: ${e}`);}Ge[c]=d;return b})};Fe.push(a)})();FS.createPreloadedFile=(a,b,c,d,e,f,g,k,l,m)=>{wf(a,b,c,d,e,k,l,m).then(f).catch(g)};FS.Hc=wf;FS.Sa();p&&NODEFS.Sa();if(!p)throw Error("NODERAWFS is currently only supported on Node.js environment.");var qf=require("node:tty");
function Bh(a){return(...b)=>{try{return a(...b)}catch(c){"BadResource"==c.name&&(c.code="EBADF");if(c.code)throw new FS.g(kf[c.code]);throw c;}}}function Ch(a,b){return Bh((c,...d)=>c.o?b(c,...d):a(c,...d))}var pf={...FS};for(const [a,b]of Object.entries(of))FS[a]=Bh(b);for(const [a,b]of Object.entries(nf))FS[a]=Ch(b,FS[a]);
(()=>{let a=og.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof og&&c instanceof og))return!1;var d=this.l.D.s,e=this.l.u;c.l=c.l;var f=c.l.D.s;for(c=c.l.u;d.O;)e=d.ta(e),d=d.O;for(;f.O;)c=f.ta(c),f=f.O;return d===f&&e===c},clone:function(){this.l.u||gg(this);if(this.l.qa)return this.l.count.value+=1,this;var c=kg,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.l;c=c(e.call(d,f,{l:{value:{count:g.count,ha:g.ha,qa:g.qa,u:g.u,D:g.D,L:g.L,P:g.P}}}));c.l.count.value+=1;c.l.ha=
!1;return c},["delete"](){this.l.u||gg(this);if(this.l.ha&&!this.l.qa)throw new X("Object already scheduled for deletion");jg(this);var c=this.l;--c.count.value;0===c.count.value&&(c.L?c.P.X(c.L):c.D.s.X(c.u));this.l.qa||(this.l.L=void 0,this.l.u=void 0)},isDeleted:function(){return!this.l.u},deleteLater:function(){this.l.u||gg(this);if(this.l.ha&&!this.l.qa)throw new X("Object already scheduled for deletion");lg.push(this);1===lg.length&&ng&&ng(mg);this.l.ha=!0;return this}});const b=Symbol.dispose;
b&&(a[b]=a["delete"])})();
Object.assign(Eg.prototype,{Kb(a){this.lb&&(a=this.lb(a));return a},Za(a){this.X?.(a)},M:Xf,A:function(a){function b(){return this.ya?Dg(this.s.$,{D:this.dc,u:c,P:this,L:a}):Dg(this.s.$,{D:this,u:a})}var c=this.Kb(a);if(!c)return this.Za(a),null;var d=Cg(this.s,c);if(void 0!==d){if(0===d.l.count.value)return d.l.u=c,d.l.L=a,d.clone();d=d.clone();this.Za(a);return d}d=this.s.Ib(c);d=pg[d];if(!d)return b.call(this);d=this.xa?d.yb:d.pointerType;var e=Ag(c,this.s,d.s);return null===e?b.call(this):this.ya?
Dg(d.s.$,{D:d,u:e,P:this,L:a}):Dg(d.s.$,{D:d,u:e})}});Ud.push(()=>{yh.TMPDIR=require("node:os").tmpdir()});$a.push(()=>{const a=Object.getOwnPropertyDescriptor(h.SourceCustom.prototype,"onRead");Object.defineProperty(h.SourceCustom.prototype,"onRead",{set(c){return a.set.call(this,d=>yg(c(d)))}});const b=Object.getOwnPropertyDescriptor(h.TargetCustom.prototype,"onWrite");Object.defineProperty(h.TargetCustom.prototype,"onWrite",{set(c){return b.set.call(this,d=>c(Z(d)))}})});
Object.assign(og.prototype,{preventAutoDelete:function(){const a=lg.indexOf(this);-1<a&&lg.splice(a,1);this.l.ha=!1;return this}});r||(h.wasmMemory?xa=h.wasmMemory:xa=new WebAssembly.Memory({initial:(h.INITIAL_MEMORY||268435456)/65536,maximum:32768,shared:!0}),ya());h.preloadPlugins&&(Fe=h.preloadPlugins);h.noExitRuntime&&(Zd=h.noExitRuntime);h.print&&(ra=h.print);h.printErr&&(w=h.printErr);h.dynamicLibraries&&(sa=h.dynamicLibraries);h.wasmBinary&&(ta=h.wasmBinary);h.arguments&&(da=h.arguments);
h.thisProgram&&(ea=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.ENV=yh;h.addRunDependency=uf;h.removeRunDependency=tf;h.addFunction=ue;h.FS_preloadFile=wf;h.FS_unlink=(...a)=>FS.unlink(...a);h.FS_createPath=(...a)=>FS.createPath(...a);h.FS_createDevice=(...a)=>FS.createDevice(...a);h.FS=FS;h.FS_createDataFile=(...a)=>FS.createDataFile(...a);h.FS_createLazyFile=(...a)=>FS.createLazyFile(...a);
h.setAutoDeleteLater=a=>{hg=a};h.deletionQueue=lg;h.setDelayFunction=a=>{ng=a;lg.length&&ng&&ng(mg)};var oh=[$c,ae,Nf,mb,nb,ob,pb,qb,rb,sb,tb,ub,vb,wb,xb,yb,dc,Dc,Ec,Rc,Sc,Uc,Vc,Wc,Xc,Yc],ze={};function Dh(a){for(var b=(y(),G)[a+6>>1];13===b&&!(16<(y(),I)[a>>2]);){var c=(y(),I)[a+8>>2],d=(y(),I)[c>>2];if(0===d){b=0;break}else if(0===(y(),I)[(c>>2)+1])a=d,b=(y(),G)[d+6>>1];else break}return[a,b]}
function Zc(a,b,c,d){y();var e=(y(),I)[(a>>2)+1],f=(y(),I)[(a>>2)+6],g=(y(),I)[(a>>2)+2],k=(y(),I)[(a>>2)+5];a=Dh((y(),I)[(a>>2)+3])[1];var l=Dd(),m=l,n=[],t=!1;if(15===a)throw Error("complex ret marshalling nyi");if(0>a||15<a)throw Error("Unexpected rtype "+a);if(4===a||13===a)n.push(c),t=!0;for(var u=0;u<f;u++){var q=(y(),I)[(d>>2)+u],v=Dh((y(),I)[(g>>2)+u]),x=v[0];v=v[1];switch(v){case 1:case 10:case 9:n.push((y(),I)[q>>2]);break;case 2:n.push((y(),Ta)[q>>2]);break;case 3:n.push((y(),Ua)[q>>3]);
break;case 5:n.push((y(),F)[q]);break;case 6:n.push((y(),z)[q]);break;case 7:n.push((y(),G)[q>>1]);break;case 8:n.push((y(),A)[q>>1]);break;case 11:case 12:n.push((y(),Va)[q>>3]);break;case 4:n.push((y(),Va)[q>>3]);n.push((y(),Va)[(q>>3)+1]);break;case 13:v=(y(),I)[x>>2];x=(y(),G)[x+4>>1];m-=v;m&=~(x-1);(y(),z).subarray(m,m+v).set((y(),z).subarray(q,q+v));n.push(m);break;case 14:n.push((y(),I)[q>>2]);break;case 15:throw Error("complex marshalling nyi");default:throw Error("Unexpected type "+v);}}if(k&
1){k=[];for(u=e-1;u>=f;u--)switch(q=(y(),I)[(d>>2)+u],v=Dh((y(),I)[(g>>2)+u]),x=v[0],v=v[1],v){case 5:case 6:--m;m&=-1;(y(),F)[m]=(y(),F)[q];break;case 7:case 8:m-=2;m&=-2;(y(),G)[m>>1]=(y(),G)[q>>1];break;case 1:case 9:case 10:case 2:m-=4;m&=-4;(y(),I)[m>>2]=(y(),I)[q>>2];break;case 3:case 11:case 12:m-=8;m&=-8;(y(),I)[m>>2]=(y(),I)[q>>2];(y(),I)[(m>>2)+1]=(y(),I)[(q>>2)+1];break;case 4:m-=16;m&=-8;(y(),I)[m>>2]=(y(),I)[q>>2];(y(),I)[(m>>2)+1]=(y(),I)[(q>>2)+1];(y(),I)[(m>>2)+2]=(y(),I)[(q>>2)+2];
(y(),I)[(m>>2)+3]=(y(),I)[(q>>2)+3];break;case 13:m-=4;m&=-4;k.push([m,q,(y(),I)[x>>2],(y(),G)[x+4>>1]]);break;case 14:m-=4;m&=-4;(y(),I)[m>>2]=(y(),I)[q>>2];break;case 15:throw Error("complex arg marshalling nyi");default:throw Error("Unexpected argtype "+v);}n.push(m);for(u=0;u<k.length;u++)e=k[u],d=e[0],q=e[1],v=e[2],x=e[3],m-=v,m&=~(x-1),(y(),z).subarray(m,m+v).set((y(),z).subarray(q,q+v)),(y(),I)[d>>2]=m}Bd(m);Cd(0);b=M.get(b).apply(null,n);Bd(l);if(!t)switch(a){case 0:break;case 1:case 9:case 10:(y(),
I)[c>>2]=b;break;case 2:(y(),Ta)[c>>2]=b;break;case 3:(y(),Ua)[c>>3]=b;break;case 5:case 6:(y(),F)[c+0]=b;break;case 7:case 8:(y(),G)[c>>1]=b;break;case 11:case 12:(y(),Va)[c>>3]=b;break;case 14:(y(),I)[c>>2]=b;break;case 15:throw Error("complex ret marshalling nyi");default:throw Error("Unexpected rtype "+a);}}Zc.h="viiii";var fd,gd,L,hd,jd,kd,Na,ld,md,nd,od,pd,qd,rd,sd,Ja,td,Qa,ud,vd,wd,xd,yd,zd,bb,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,M,hb;
function Eh(a=[]){var b=ye("main").Ua;if(b){a.unshift(ea);var c=a.length,d=Cd(4*(c+1)),e=d,f;for(f of a)(y(),I)[e>>2]=Se(f),e+=4;(y(),I)[e>>2]=0;try{var g=b(c,d);Tc(g,!0)}catch(k){gh(k)}}}
function Ha(a=da){function b(){h.calledRun=!0;if(!va&&(Xa(),za?.(h),h.onRuntimeInitialized?.(),h.noInitialRun||Eh(a),!r)){if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();fe.push(c)}Ya(fe)}}if(0<rf)sf=Ha;else if(r)za?.(h),Xa();else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ud.push(h.preRun.shift());Ya(Ud);0<rf?sf=Ha:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),
1);b()},1)):b()}}var Za;r||(Za=await (Ga()),Ha());Ra?moduleRtn=h:moduleRtn=new Promise((a,b)=>{za=a;Aa=b});
;return moduleRtn}export default Vips;var isPthread=globalThis.name=="em-pthread";var isNode=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer";if(isNode)isPthread=(await import("node:worker_threads")).workerData==="em-pthread";isPthread&&Vips();
