async function Vips(moduleArg={}){var moduleRtn;var n=moduleArg,ba=!!globalThis.window,ca=!!globalThis.WorkerGlobalScope,q=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,w=ca&&"em-pthread"==globalThis.name;if(q){var worker_threads=require("node:worker_threads");globalThis.Worker=worker_threads.Worker;w=(ca=!worker_threads.isMainThread)&&"em-pthread"==worker_threads.workerData}n.dynamicLibraries=n.dynamicLibraries||["vips-jxl.wasm","vips-heif.wasm"];var da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha;
"undefined"!=typeof __filename?ha=__filename:ca&&(ha=self.location.href);var ia="";function ja(a){return n.locateFile?n.locateFile(a,ia):ia+a}var ka,la;
if(q){var fs=require("node:fs");ia=__dirname+"/";la=a=>{a=ma(a)?new URL(a):a;return fs.readFileSync(a)};ka=async a=>{a=ma(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(ba||ca){try{ia=(new URL(".",ha)).href}catch{}q||(ca&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=async a=>
{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);})}var na=console.log.bind(console),oa=console.error.bind(console);if(q){var pa=require("node:util"),qa=a=>"object"==typeof a?pa.inspect(a):a;na=(...a)=>fs.writeSync(1,a.map(qa).join(" ")+"\n");oa=(...a)=>fs.writeSync(2,a.map(qa).join(" ")+"\n")}var ra=na,x=oa,sa=[],ta,ua,va=!1,wa,ma=a=>a.startsWith("file://"),xa,ya;
if(q&&w){globalThis.self=globalThis;var za=worker_threads.parentPort;globalThis.postMessage||(za.on("message",a=>globalThis.onmessage?.({data:a})),globalThis.postMessage=a=>za.postMessage(a));process.on("uncaughtException",a=>{postMessage({R:"uncaughtException",error:a});process.exit(1)})}var Ba={},Ca;
if(w){var Da=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.R;if("load"===d){let e=[];self.onmessage=f=>e.push(f);Ca=()=>{postMessage({R:"loaded"});for(let f of e)a(f);self.onmessage=a};sa=c.Db;Ba=c.mc;for(const f of c.Qb)if(!n[f]||n[f].proxy)n[f]=(...g)=>{postMessage({R:"callHandler",Pb:f,args:g})},"print"==f&&(ra=n[f]),"printErr"==f&&(x=n[f]);Ea=c.tc;Fa();ua=c.uc;Ga();Ha()}else if("run"===d){Ia(c.W);Ja(c.W,0,0,1,0,0);Ka();Ma(c.W);Da||(Na(),Da=!0);try{Oa(c.pc,
c.Ca)}catch(e){if("unwind"!=e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?Da&&Pa():d&&(x(`worker: received unknown command ${d}`),x(c)))}catch(e){throw Qa(),e;}}self.onmessage=a}var Ra=!1,Sa=!1;function Fa(){var a=Ea.buffer;y=new Int8Array(a);A=new Int16Array(a);E=new Uint8Array(a);F=new Uint16Array(a);G=new Int32Array(a);H=new Uint32Array(a);Ta=new Float32Array(a);Ua=new Float64Array(a);I=new BigInt64Array(a);Va=new BigUint64Array(a)}var Wa=[];
function Xa(){Ra=!0;w?Ca():(Ya(Wa),n.noFSInit||FS.Ha||FS.init(),Za.__wasm_call_ctors(),Ya($a),FS.fb=!1)}function J(a){n.onAbort?.(a);a=`Aborted(${a})`;x(a);va=!0;a+=". Build with -sASSERTIONS for more info.";Ra&&bb();a=new WebAssembly.RuntimeError(a);ya?.(a);throw a;}var cb;async function db(a){if(!ta)try{var b=await ka(a);return new Uint8Array(b)}catch{}if(a==cb&&ta)a=new Uint8Array(ta);else if(la)a=la(a);else throw"both async and sync fetching of the wasm failed";return a}
async function eb(a,b){try{var c=await db(a);return await WebAssembly.instantiate(c,b)}catch(d){x(`failed to asynchronously prepare wasm: ${d}`),J(d)}}async function fb(a){var b=cb;if(!ta&&!q)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){x(`wasm streaming compile failed: ${d}`),x("falling back to ArrayBuffer instantiation")}return eb(b,a)}
function gb(){K={__assert_fail:hb,__call_sighandler:ib,__lsan_ignore_object:jb,__pthread_create_js:kb,__syscall_dup:lb,__syscall_faccessat:mb,__syscall_fcntl64:nb,__syscall_fstat64:ob,__syscall_ftruncate64:pb,__syscall_getcwd:qb,__syscall_ioctl:rb,__syscall_lstat64:sb,__syscall_newfstatat:tb,__syscall_openat:ub,__syscall_poll:vb,__syscall_rmdir:wb,__syscall_stat64:xb,__syscall_unlinkat:yb,__throw_exception_with_stack_trace:zb,_abort_js:Ab,_dlopen_js:Db,_dlsym_catchup_js:Eb,_dlsym_js:Fb,_embind_finalize_value_object:Gb,
_embind_register_arithmetic_vector:Hb,_embind_register_bigint:Ib,_embind_register_bool:Jb,_embind_register_class:Kb,_embind_register_class_class_function:Lb,_embind_register_class_constructor:Mb,_embind_register_class_function:Nb,_embind_register_class_property:Ob,_embind_register_emval:Pb,_embind_register_enum:Qb,_embind_register_enum_value:Rb,_embind_register_float:Sb,_embind_register_function:Tb,_embind_register_integer:Ub,_embind_register_iterable:Vb,_embind_register_memory_view:Wb,_embind_register_optional:Xb,
_embind_register_std_string:Yb,_embind_register_std_wstring:Zb,_embind_register_value_object:$b,_embind_register_value_object_field:ac,_embind_register_void:bc,_emscripten_dlopen_js:cc,_emscripten_dlsync_threads:dc,_emscripten_get_dynamic_libraries_js:ec,_emscripten_init_main_thread_js:fc,_emscripten_notify_mailbox_postmessage:gc,_emscripten_receive_on_main_thread_js:hc,_emscripten_runtime_keepalive_clear:ic,_emscripten_thread_cleanup:jc,_emscripten_thread_exit_joinable:kc,_emscripten_thread_mailbox_await:Ma,
_emscripten_thread_set_strongref:lc,_emval_array_to_memory_view:mc,_emval_create_invoker:nc,_emval_decref:oc,_emval_get_global:pc,_emval_get_module_property:qc,_emval_get_property:rc,_emval_incref:sc,_emval_instanceof:tc,_emval_invoke:uc,_emval_is_number:vc,_emval_is_string:wc,_emval_new_cstring:xc,_emval_run_destructors:yc,_emval_set_property:zc,_emval_typeof:Ac,_gmtime_js:Bc,_localtime_js:Cc,_mmap_js:Dc,_munmap_js:Ec,_tzset_js:Fc,clock_time_get:Gc,emscripten_check_blocking_allowed:Hc,emscripten_date_now:Ic,
emscripten_err:Jc,emscripten_exit_with_live_runtime:Kc,emscripten_get_heap_max:Lc,emscripten_get_now:Mc,emscripten_num_logical_cores:Nc,emscripten_promise_destroy:Oc,emscripten_promise_resolve:Pc,emscripten_resize_heap:Qc,environ_get:Rc,environ_sizes_get:Sc,exit:Tc,fd_close:Uc,fd_fdstat_get:Vc,fd_read:Wc,fd_seek:Xc,fd_write:Yc,ffi_call_js:Zc,heif_error_success:$c,memory:Ea,proc_exit:ad,random_get:bd};var a=new Proxy(new Set(["__lsan_ignore_object"]),cd);return{env:K,wasi_snapshot_preview1:K,"GOT.mem":a,
"GOT.func":a}}
async function Ga(){function a(d,e){var f=Za=d.exports;dd(Za);var g=ed(e);fd(Za._emscripten_tls_init,d.exports,g);d=Za;gd=d.pthread_self;hd=d.malloc;n._main=d.main;M=d.free;jd=d.fflush;kd=d.calloc;n.__ZnamSt11align_val_t=d._ZnamSt11align_val_t;ld=d.__getTypeName;Na=d._embind_initialize_bindings;n._emscripten_builtin_free=d.emscripten_builtin_free;md=d.emscripten_builtin_memalign;n._emscripten_builtin_malloc=d.emscripten_builtin_malloc;nd=d.__funcs_on_exit;n.___libc_calloc=d.__libc_calloc;n.___libc_free=
d.__libc_free;n.___libc_malloc=d.__libc_malloc;od=d.__dl_seterr;pd=d._emscripten_dlsync_self_async;qd=d._emscripten_dlsync_self;rd=d._emscripten_proxy_dlsync_async;sd=d._emscripten_proxy_dlsync;td=d._emscripten_find_dylib;Ja=d._emscripten_thread_init;ud=d.__set_thread_state;Qa=d._emscripten_thread_crashed;vd=d._emscripten_run_js_on_main_thread_done;wd=d._emscripten_run_js_on_main_thread;xd=d._emscripten_thread_free_data;yd=d._emscripten_thread_exit;n._strndup=d.strndup;zd=d._emscripten_check_mailbox;
n.__ZdaPvm=d._ZdaPvm;n.___libc_realloc=d.__libc_realloc;n._emscripten_builtin_calloc=d.emscripten_builtin_calloc;n._emscripten_builtin_realloc=d.emscripten_builtin_realloc;n._malloc_size=d.malloc_size;n._malloc_usable_size=d.malloc_usable_size;n._reallocf=d.reallocf;Ad=d.emscripten_get_sbrk_ptr;bb=d.__trap;Bd=d.emscripten_stack_set_limits;Cd=d._emscripten_stack_restore;Dd=d._emscripten_stack_alloc;Ed=d.emscripten_stack_get_current;Fd=d.__thrown_object_from_unwind_exception;Gd=d.__get_exception_message;
N=d.__indirect_function_table;Hd=d.__cpp_exception;Id=d.__heap_base.value;Jd(f);Kd("__main__",0,K);Ld();ua=e;return Za}var b=gb();if(n.instantiateWasm)return new Promise(d=>{n.instantiateWasm(b,(e,f)=>{d(a(e,f))})});if(w){var c=new WebAssembly.Instance(ua,gb());return a(c,ua)}cb??=ja("vips.wasm");return function(d){return a(d.instance,d.module)}(await fb(b))}class Md{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Nd={},cd={get(a,b){var c=Nd[b];c||=Nd[b]=new WebAssembly.Global({value:"i32",mutable:!0},-1);a.has(b)||(c.required=!0);return c}},A,G,I,y,Ta,Ua,F,H,Va,E,Od=a=>{a.terminate();a.onmessage=()=>{}},Ud=a=>{var b=Pd[a];Qd.delete(a);a in Rd&&Rd[a].resolve();a=b.W;delete Pd[a];Sd.push(b);Td.splice(Td.indexOf(b),1);b.W=0;xd(a)},Ya=a=>{for(;0<a.length;)a.shift()(n)},Vd=[],Wd=a=>{Qd.add(a);a in Rd&&Rd[a].resolve()},Yd=a=>{if(0==Sd.length){var b=ha;n.mainScriptUrlOrBlob&&(b=n.mainScriptUrlOrBlob,"string"!=
typeof b&&(b=URL.createObjectURL(b)));b=new Worker(b,{workerData:"em-pthread",name:"em-pthread"});Sd.push(b);Xd()}b=Sd.pop();if(!b)return 6;Td.push(b);Pd[a.W]=b;b.W=a.W;var c={R:"run",pc:a.oc,Ca:a.Ca,W:a.W};q&&b.unref();b.postMessage(c,a.rb);return 0},Zd=0,O=(a,b,...c)=>{var d=16*c.length,e=Ed(),f=Dd(d),g=f>>3,h;for(h of c)"bigint"==typeof h?(I[g++]=1n,I[g++]=h):(I[g++]=0n,Ua[g++]=h);a=wd(a,0,d,f,b);Cd(e);return a};
function ad(a){if(w)return O(0,1,a);wa=a;$d||0<Zd||(ae(),n.onExit?.(a),va=!0);fa(a,new Md(a))}ad.h="vi";function be(a){if(w)return O(1,0,a);Tc(a)}var Tc=a=>{wa=a;if(w)throw be(a),"unwind";if(!($d||0<Zd||w)){nd();FS.Ha=!1;jd(0);for(var b of FS.streams)b&&FS.close(b);ae();b=gd();ud(0,0,0,1);ce||Atomics.notify(G,b>>2);Sa=!0}ad(a)};Tc.h="vi";
var ce=!Atomics.waitAsync||globalThis.navigator?.userAgent&&91>Number((navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./)||[])[2]),Sd=[],Td=[],de=[],Pd={},ae=()=>{for(var a of Td)Od(a);for(a of Sd)Od(a);Sd=[];Td=[];Pd={}};function Ka(){de.forEach(a=>a())}
var Xd=()=>{var a=Sd[0];new Promise(b=>{a.onmessage=f=>{var g=f.data;f=g.R;if(g.Ba&&g.Ba!=gd()){var h=Pd[g.Ba];h?h.postMessage(g,g.rb):x(`worker sent message (${f}) to pthread (${g.Ba}) that no longer exists`)}else if("checkMailbox"===f)Pa();else if("spawnThread"===f)Yd(g);else if("cleanupThread"===f)ee(()=>Ud(g.Va));else if("markAsFinished"===f)Wd(g.Va);else if("loaded"===f)a.loaded=!0,b(a);else if("setimmediate"===g.target)a.postMessage(g);else if("uncaughtException"===f)a.onerror(g.error);else if("callHandler"===
f)n[g.Pb](...g.args);else f&&x(`worker sent an unknown command ${f}`)};a.onerror=f=>{x(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};q&&(a.on("message",f=>a.onmessage({data:f})),a.on("error",f=>a.onerror(f)));var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)n.propertyIsEnumerable(e)&&c.push(e);a.postMessage({R:"load",Qb:c,tc:Ea,uc:ua,Db:sa,mc:Ba})})},Qd,Rd,fe,ge=[];function Ia(a){var b=H[a+48>>2];Bd(b,b-H[a+52>>2]);Cd(b)}
var he=new TextDecoder,ie=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},je=(a,b=0,c)=>{c=ie(a,b,c);return he.decode(a.buffer?a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c):new Uint8Array(a.slice(b,c)))},ed=a=>{function b(){for(var r=0,t=1;;){var p=a[f++];r+=(p&127)*t;t*=128;if(!(p&128))break}return r}function c(){var r=b();f+=r;return je(a,f-r,r)}function d(){for(var r=b(),t=[];r--;)t.push(c());return t}function e(r,t){if(r)throw Error(t);}var f=0,g=0;if(a instanceof
WebAssembly.Module)g=WebAssembly.Module.customSections(a,"dylink.0"),e(0===g.length,"need dylink section"),a=new Uint8Array(g[0]),g=a.length;else{g=1836278016==(new Uint32Array((new Uint8Array(a.subarray(0,24))).buffer))[0];e(!g,"need to see wasm magic number");e(0!==a[8],"need the dylink section to be first");f=9;g=b();g=f+g;var h=c();e("dylink.0"!==h)}for(h={Ma:[],qb:new Set,tb:new Set,pb:[]};f<g;){var k=a[f++],l=b();if(1===k)h.La=b(),h.Xb=b(),h.sa=b(),h.Jc=b();else if(2===k)h.Ma=d();else if(3===
k)for(k=b();k--;){l=c();var m=b();m&256&&h.qb.add(l)}else if(4===k)for(k=b();k--;)c(),l=c(),m=b(),1==(m&3)&&h.tb.add(l);else 5===k?h.pb=d():f+=l}return h},Oa=(a,b)=>{$d=Zd=0;qd();a=N.get(a)(b);$d||0<Zd?wa=a:yd(a)},Kd=(a,b,c)=>{c={ka:Infinity,name:a,exports:c,global:!0};ke[a]=c;void 0!=b&&(le[b]=c);return c},ke={},le={},me=(a,b)=>Math.ceil(a/b)*b,ne=a=>{if(Ra)return kd(a,1);var b=Id;Id=a=b+16*Math.ceil(a/16);if(!w){var c=Ad();H[c>>2]=a}return b},pe=(a,b)=>{if(oe)for(var c=a;c<a+b;c++){var d=N.get(c);
d&&oe.set(d,c)}},oe,qe=a=>{oe||(oe=new WeakMap,pe(0,N.length));return oe.get(a)||0},re=[],se=a=>{const b=a.length;return[b%128|128,b>>7,...a]},te={i:127,p:127,j:126,f:125,d:124,e:111},ue=a=>se(Array.from(a,b=>te[b])),ve=(a,b)=>{var c=qe(a);if(c)return c;c=re.length?re.pop():N.grow(1);try{N.set(c,a)}catch(d){if(!(d instanceof TypeError))throw d;b=Uint8Array.of(0,97,115,109,1,0,0,0,1,...se([1,96,...ue(b.slice(1)),...ue("v"===b[0]?"":b[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(b);
b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f;N.set(c,b)}oe.set(a,c);return c},Jd=(a,b)=>{for(var c in a){var d=c;if(!"memory __memory_base __table_base __stack_pointer __indirect_function_table __cpp_exception __c_longjmp __wasm_apply_data_relocs __dso_handle __tls_size __tls_align __set_stack_limits _emscripten_tls_init __wasm_init_tls __wasm_call_ctors __start_em_asm __stop_em_asm __start_em_js __stop_em_js".split(" ").includes(d)&&!d.startsWith("__em_js__")){d=a[c];var e=Nd[c]&&-1!=Nd[c].value;
if(b||!e){if("function"==typeof d)d=ve(d);else if("number"!=typeof d.value)continue;let f;Nd[f=c]??(Nd[f]=new WebAssembly.Global({value:"i32",mutable:!0}));Nd[c].value=d}}}},we=(a,b=0)=>{var c={},d;for(d in a){var e=d;var f=a[d];a:{if(f instanceof WebAssembly.Global)try{f.value=f.value}catch{var g=!0;break a}g=!1}f=g?new WebAssembly.Global({value:"i32"},f.value+b):f;c[e]=f}return c},xe=a=>{a=K[a];return!a||a.za?!1:!0},ye=(a,b)=>Object.defineProperty(b,"name",{value:a}),ze=a=>{var b;xe(a)&&(b=K[a]);
return{Ua:b,name:a}},$a=[],P=(a,b,c)=>a?he.decode(E.slice(a,ie(E,a,b,c))):"",Ee=(a,b,c,d,e)=>{function f(){function k(C,z){function B(Aa,aa){Aa=[];for(var Bb=0;;Bb++){var ab="$"+Bb;if(!aa.includes(ab))break;Aa.push(ab)}Aa=Aa.join(",");Ae[D]=eval(`(${Aa}) => { ${aa} };`)}function L(Aa,aa,Bb){var ab=[];aa=aa.slice(1,-1);if("void"!=aa){aa=aa.split(",");for(var Gg of aa)aa=Gg.split(" ").pop(),ab.push(aa.replaceAll("*",""))}p[Aa]=eval(`(${ab}) => ${Bb};`)}!w&&c&&(Ba[c]=C);pe(t,g.sa);p=we(z.exports,r);
Jd(p);b.xb||Be();if("__start_em_asm"in p){var D=p.__start_em_asm.value;for(C=p.__stop_em_asm.value;D<C;){var La=P(D);B(D,La);D=E.indexOf(0,D)+1}}for(var Cb in p)if(Cb.startsWith("__em_js__")){D=p[Cb].value;La=P(D);var [Hg,Ig]=La.split("<::>");L(Cb.replace("__em_js__",""),Hg,Ig);delete p[Cb]}fd(p._emscripten_tls_init,z.exports,g);l&&((z=p.__wasm_apply_data_relocs)&&(Ra?z():Wa.push(z)),(z=p.__wasm_call_ctors)&&(Ra?z():$a.push(z)));return p}var l=!e||!y[e+8];if(l){var m=Math.pow(2,g.Xb),r=g.La?me(ne(g.La+
m),m):0,t=g.sa?N.length:0;e&&(y[e+8]=1,H[e+12>>2]=r,G[e+16>>2]=g.La,H[e+20>>2]=t,G[e+24>>2]=g.sa)}else r=H[e+12>>2],t=H[e+20>>2];g.sa&&N.grow(g.sa);var p;m=new Proxy({},{get(C,z){switch(z){case "__memory_base":return r;case "__table_base":return t}if(z in K&&!K[z].za)return K[z];if(!(z in C)){var B;C[z]=(...L)=>{if(!B){var D=ze(z).Ua;!D&&d&&(D=d[z]);D||=p[z];B=D}return B(...L)}}return C[z]}});var u=new Proxy(g.tb,cd),v={"GOT.mem":u,"GOT.func":u,env:m,wasi_snapshot_preview1:m};if(b.J)return(async()=>
{var C;a instanceof WebAssembly.Module?C=new WebAssembly.Instance(a,v):{module:a,instance:C}=await WebAssembly.instantiate(a,v);return k(a,C)})();m=a instanceof WebAssembly.Module?a:new WebAssembly.Module(a);u=new WebAssembly.Instance(m,v);return k(m,u)}var g=ed(a);b={...b,Sa:{ac:c,dc:g.pb}};if(b.J)return g.Ma.reduce((k,l)=>k.then(()=>{l=Ce(l,b.Sa)??l;return De(l,b,d)}),Promise.resolve()).then(f);for(var h of g.Ma)h=Ce(h,b.Sa)??h,De(h,b,d);return f()},dd=a=>{var b,c;for([b,c]of Object.entries(a))xe(b)||
(K[b]=c)},Fe=async a=>{a=await ka(a);return new Uint8Array(a)},Ge=[],He={},Ie=require("node:path"),Je=Ie.isAbsolute,Ke=Ie.normalize,Le=Ie.dirname,Me=Ie.basename,Ne=Ie.join,Oe=Ie.join,Pe=a=>{var b=Ed();a=a();Cd(b);return a},Qe=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Re=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=
g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Se=a=>{var b=Qe(a)+1,c=Dd(b);Re(a,E,c,b);return c},Te=()=>{if(q){var a=require("node:crypto");return b=>a.randomFillSync(b)}return b=>(b.set(crypto.getRandomValues(new Uint8Array(b.byteLength))),0)},Ue=a=>(Ue=Te())(a),Ve=(...a)=>{a.unshift(FS.cwd());
return Ie.posix.resolve(...a)},We=(a,b)=>Ie.posix.relative(a||FS.cwd(),b||FS.cwd()),Xe=[],Ye=a=>{var b=Array(Qe(a)+1);a=Re(a,b,0,b.length);b.length=a;return b},Ze=[];function $e(a,b){Ze[a]={input:[],output:[],da:b};FS.registerDevice(a,af)}
var af={open(a){var b=Ze[a.node.rdev];if(!b)throw new FS.g(43);a.tty=b;a.seekable=!1},close(a){a.tty.da.fsync(a.tty)},fsync(a){a.tty.da.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.da.eb)throw new FS.g(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.da.eb(a.tty)}catch(h){throw new FS.g(29);}if(void 0===g&&0===e)throw new FS.g(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.da.Pa)throw new FS.g(60);try{for(var e=0;e<d;e++)a.tty.da.Pa(a.tty,
b[c+e])}catch(f){throw new FS.g(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},bf={eb(){a:{if(!Xe.length){var a=null;if(q){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}if(!a){a=null;break a}Xe=Ye(a)}a=Xe.shift()}return a},Pa(a,b){null===b||10===b?(ra(je(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ra(je(a.output)),a.output=[])},
Sb(){return{Ac:25856,Cc:5,zc:191,Bc:35387,yc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Tb(){return 0},Ub(){return[24,80]}},cf={Pa(a,b){null===b||10===b?(x(je(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(x(je(a.output)),a.output=[])}},df=a=>{a=65536*Math.ceil(a/65536);var b=md(65536,a);b&&E.fill(0,b,b+a);return b},Q={V:null,mount(){return Q.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(FS.isBlkdev(c)||FS.isFIFO(c))throw new FS.g(63);
Q.V||(Q.V={dir:{node:{I:Q.m.I,K:Q.m.K,lookup:Q.m.lookup,S:Q.m.S,rename:Q.m.rename,unlink:Q.m.unlink,rmdir:Q.m.rmdir,readdir:Q.m.readdir,symlink:Q.m.symlink},stream:{llseek:Q.o.llseek}},file:{node:{I:Q.m.I,K:Q.m.K},stream:{llseek:Q.o.llseek,read:Q.o.read,write:Q.o.write,aa:Q.o.aa,ea:Q.o.ea}},link:{node:{I:Q.m.I,K:Q.m.K,readlink:Q.m.readlink},stream:{}},Wa:{node:{I:Q.m.I,K:Q.m.K},stream:FS.zb}});c=FS.createNode(a,b,c,d);FS.isDir(c.mode)?(c.m=Q.V.dir.node,c.o=Q.V.dir.stream,c.v={}):FS.isFile(c.mode)?
(c.m=Q.V.file.node,c.o=Q.V.file.stream,c.N=0,c.v=Q.Eb??(Q.Eb=new Uint8Array(0))):FS.isLink(c.mode)?(c.m=Q.V.link.node,c.o=Q.V.link.stream):FS.isChrdev(c.mode)&&(c.m=Q.V.Wa.node,c.o=Q.V.Wa.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.v[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},m:{I(a){var b={};b.dev=FS.isChrdev(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.N:FS.isLink(a.mode)?b.size=a.link.length:b.size=
0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},K(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.N!=b&&(c=a.v,a.v=new Uint8Array(b),a.v.set(c.subarray(0,Math.min(b,a.N))),a.N=b))},lookup(){Q.Da||(Q.Da=new FS.g(44),Q.Da.stack="<generic error, no stack>");throw Q.Da;},S(a,b,c,d){return Q.createNode(a,b,c,d)},rename(a,b,c){try{var d=ef(b,c)}catch(f){}if(d){if(FS.isDir(a.mode))for(var e in d.v)throw new FS.g(55);
ff(d)}delete a.parent.v[a.name];b.v[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.v[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=ef(a,b),d;for(d in c.v)throw new FS.g(55);delete a.v[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.v)]},symlink(a,b,c){a=Q.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(!FS.isLink(a.mode))throw new FS.g(28);return a.link}},o:{read(a,b,c,d,e){if(e>=a.node.N)return 0;d=Math.min(a.node.N-
e,d);b.set(a.node.v.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(f)a.v=b.subarray(c,c+d),a.N=d;else if(0===a.N&&0===e)a.v=b.slice(c,c+d),a.N=d;else{f=e+d;var g=a.v.length;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.v.subarray(0,a.N),a.v=new Uint8Array(f),a.v.set(g));a.v.set(b.subarray(c,c+d),e);a.N=Math.max(a.N,e+d)}return d},llseek(a,b,c){1===c?b+=a.position:2===c&&FS.isFile(a.node.mode)&&(b+=a.node.N);if(0>b)throw new FS.g(28);
return b},aa(a,b,c,d,e){if(!FS.isFile(a.node.mode))throw new FS.g(43);a=a.node.v;if(e&2||a.buffer!==y.buffer){d=!0;e=df(b);if(!e)throw new FS.g(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);y.set(a,e)}}else d=!1,e=a.byteOffset;return{u:e,U:d}},ea(a,b,c,d){Q.o.write(a,b,0,d,c,!1);return 0}}},gf=a=>{if("string"!=typeof a)return a;var b={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[a];if("undefined"==typeof b)throw Error(`Unknown file open mode: ${a}`);
return b},hf=a=>{"string"==typeof a&&(a=Ye(a));a.subarray||(a=new Uint8Array(a));return a},jf=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},kf={EPERM:63,ENOENT:44,ESRCH:71,EINTR:27,EIO:29,ENXIO:60,E2BIG:1,ENOEXEC:45,EBADF:8,ECHILD:12,EAGAIN:6,EWOULDBLOCK:6,ENOMEM:48,EACCES:2,EFAULT:21,ENOTBLK:105,EBUSY:10,EEXIST:20,EXDEV:75,ENODEV:43,ENOTDIR:54,EISDIR:31,EINVAL:28,ENFILE:41,EMFILE:33,ENOTTY:59,ETXTBSY:74,EFBIG:22,ENOSPC:51,ESPIPE:70,EROFS:69,EMLINK:34,EPIPE:64,EDOM:18,ERANGE:68,ENOMSG:49,EIDRM:24,
ECHRNG:106,EL2NSYNC:156,EL3HLT:107,EL3RST:108,ELNRNG:109,EUNATCH:110,ENOCSI:111,EL2HLT:112,EDEADLK:16,ENOLCK:46,EBADE:113,EBADR:114,EXFULL:115,ENOANO:104,EBADRQC:103,EBADSLT:102,EDEADLOCK:16,EBFONT:101,ENOSTR:100,ENODATA:116,ETIME:117,ENOSR:118,ENONET:119,ENOPKG:120,EREMOTE:121,ENOLINK:47,EADV:122,ESRMNT:123,ECOMM:124,EPROTO:65,EMULTIHOP:36,EDOTDOT:125,EBADMSG:9,ENOTUNIQ:126,EBADFD:127,EREMCHG:128,ELIBACC:129,ELIBBAD:130,ELIBSCN:131,ELIBMAX:132,ELIBEXEC:133,ENOSYS:52,ENOTEMPTY:55,ENAMETOOLONG:37,
ELOOP:32,EOPNOTSUPP:138,EPFNOSUPPORT:139,ECONNRESET:15,ENOBUFS:42,EAFNOSUPPORT:5,EPROTOTYPE:67,ENOTSOCK:57,ENOPROTOOPT:50,ESHUTDOWN:140,ECONNREFUSED:14,EADDRINUSE:3,ECONNABORTED:13,ENETUNREACH:40,ENETDOWN:38,ETIMEDOUT:73,EHOSTDOWN:142,EHOSTUNREACH:23,EINPROGRESS:26,EALREADY:7,EDESTADDRREQ:17,EMSGSIZE:35,EPROTONOSUPPORT:66,ESOCKTNOSUPPORT:137,EADDRNOTAVAIL:4,ENETRESET:39,EISCONN:30,ENOTCONN:53,ETOOMANYREFS:141,EUSERS:136,EDQUOT:19,ESTALE:72,ENOTSUP:138,ENOMEDIUM:148,EILSEQ:25,EOVERFLOW:61,ECANCELED:11,
ENOTRECOVERABLE:56,EOWNERDEAD:62,ESTRPIPE:135};function R(a){try{return a()}catch(b){if(!b.code)throw b;if("UNKNOWN"===b.code)throw new FS.g(28);throw new FS.g(kf[b.code]);}}function lf(a){return R(()=>{var b=fs.lstatSync(a).mode;NODEFS.la&&(b|=(b&292)>>2);return b})}function S(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.mount.Oa.root);b.reverse();return Ne(...b)}
function mf(a){a&=-2721793;var b=0,c;for(c in NODEFS.bb)a&c&&(b|=NODEFS.bb[c],a^=c);if(a)throw new FS.g(28);return b}
var NODEFS={la:!1,Ta(){NODEFS.la=!!process.platform.match(/^win/);var a=process.binding("constants").fs;NODEFS.bb={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,256:a.O_NOCTTY,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY,131072:a.O_NOFOLLOW}},mount(a){return NODEFS.createNode(null,"/",lf(a.Oa.root),0)},createNode(a,b,c){if(!FS.isDir(c)&&!FS.isFile(c)&&!FS.isLink(c))throw new FS.g(28);a=FS.createNode(a,b,c);a.m=NODEFS.m;a.o=NODEFS.o;return a},I(a,b){a=R(a);NODEFS.la&&(a.blksize||(a.blksize=
4096),a.blocks||(a.blocks=(a.size+a.blksize-1)/a.blksize|0),a.mode|=(a.mode&292)>>2);return{dev:a.dev,ino:b.id,mode:a.mode,nlink:a.nlink,uid:a.uid,gid:a.gid,rdev:a.rdev,size:a.size,atime:a.atime,mtime:a.mtime,ctime:a.ctime,blksize:a.blksize,blocks:a.blocks}},K(a,b,c,d,e,f,g){R(()=>{if(void 0!==c.mode){var h=c.mode;NODEFS.la&&(h&=384);d(a,h);b.mode=c.mode}if("number"===typeof(c.atime??c.mtime)){h=new Date(c.atime??g(a).atime);var k=new Date(c.mtime??g(a).mtime);e(a,h,k)}void 0!==c.size&&f(a,c.size)})},
m:{I(a){var b=S(a);return NODEFS.I(()=>fs.lstatSync(b),a)},K(a,b){var c=S(a);if(null!=b.mode&&b.Ea)throw new FS.g(52);NODEFS.K(c,a,b,fs.chmodSync,fs.utimesSync,fs.truncateSync,fs.lstatSync)},lookup(a,b){var c=Oe(S(a),b);c=lf(c);return NODEFS.createNode(a,b,c)},S(a,b,c,d){var e=NODEFS.createNode(a,b,c,d),f=S(e);R(()=>{FS.isDir(e.mode)?fs.mkdirSync(f,e.mode):fs.writeFileSync(f,"",{mode:e.mode})});return e},rename(a,b,c){var d=S(a),e=Oe(S(b),c);try{FS.unlink(e)}catch(f){}R(()=>fs.renameSync(d,e));a.name=
c},unlink(a,b){var c=Oe(S(a),b);R(()=>fs.unlinkSync(c))},rmdir(a,b){var c=Oe(S(a),b);R(()=>fs.rmdirSync(c))},readdir(a){var b=S(a);return R(()=>fs.readdirSync(b))},symlink(a,b,c){var d=Oe(S(a),b);R(()=>fs.symlinkSync(c,d))},readlink(a){var b=S(a);return R(()=>fs.readlinkSync(b))},ra(a){var b=R(()=>fs.rc(a));b.Ib=b.yb;return b}},o:{I(a){return NODEFS.I(()=>fs.fstatSync(a.C),a.node)},K(a,b){NODEFS.K(a.C,a.node,b,fs.fchmodSync,fs.futimesSync,fs.ftruncateSync,fs.fstatSync)},open(a){var b=S(a.node);R(()=>
{a.Y.ka=1;a.C=fs.openSync(b,mf(a.flags))})},close(a){R(()=>{a.C&&0===--a.Y.ka&&fs.closeSync(a.C)})},Cb(a){a.Y.ka++},read(a,b,c,d,e){return R(()=>fs.readSync(a.C,b,c,d,e))},write(a,b,c,d,e){return R(()=>fs.writeSync(a.C,b,c,d,e))},llseek(a,b,c){var d=b;1===c?d+=a.position:2===c&&FS.isFile(a.node.mode)&&R(()=>{d+=fs.fstatSync(a.C).size});if(0>d)throw new FS.g(28);return d},aa(a,b,c){if(!FS.isFile(a.node.mode))throw new FS.g(43);var d=df(b);NODEFS.o.read(a,y,d,b,c);return{u:d,U:!0}},ea(a,b,c,d){NODEFS.o.write(a,
b,0,d,c,!1);return 0}}},nf={close(a){FS.streams[a.fd]=null;0>=--a.Y.Ra&&2<a.C&&fs.closeSync(a.C)},llseek(a,b,c){if(1===c)b+=a.position;else if(2===c)b+=fs.fstatSync(a.C).size;else if(0!==c)throw new FS.g(28);if(0>b)throw new FS.g(28);return a.position=b},read(a,b,c,d,e){var f="undefined"!=typeof e;!f&&a.seekable&&(e=a.position);b=fs.readSync(a.C,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e){a.flags&1024&&FS.llseek(a,0,2);var f="undefined"!=typeof e;!f&&a.seekable&&(e=a.position);b=fs.writeSync(a.C,
b,c,d,e);f||(a.position+=b);return b},aa(a,b,c){if(!b)throw new FS.g(28);var d=df(b);FS.read(a,y,d,b,c);return{u:d,U:!0}},ea(a,b,c,d){FS.write(a,b,0,d,c);return 0},wa(){throw new FS.g(59);}},of={lookup(a,b){return FS.lookupPath(`${a.path}/${b}`).node},lookupPath(a,b={}){b.parent&&(a=Le(a));b=fs.lstatSync(a);var c=lf(a);return{path:a,node:{id:b.ino,mode:c,m:of,path:a}}},Xa(){FS.ga({C:0,position:0,path:"/dev/stdin",flags:0,seekable:!1},0);for(var a=[,"/dev/stdout","/dev/stderr"],b=1;3>b;b++)FS.ga({C:b,
position:0,path:a[b],flags:577,seekable:!1},b)},cwd(){return process.cwd()},chdir(...a){process.chdir(...a)},S(a,b){FS.isDir(a)?fs.mkdirSync(a,b):fs.writeFileSync(a,"",{mode:b})},mkdir(...a){fs.mkdirSync(...a)},symlink(...a){fs.symlinkSync(...a)},rename(...a){fs.renameSync(...a)},rmdir(...a){fs.rmdirSync(...a)},readdir(...a){return[".",".."].concat(fs.readdirSync(...a))},unlink(...a){fs.unlinkSync(...a)},readlink(...a){return fs.readlinkSync(...a)},stat(a,b){a=b?fs.lstatSync(a):fs.statSync(a);NODEFS.la&&
(a.mode|=(a.mode&292)>>2);return a},fstat(a){a=T(a);return fs.fstatSync(a.C)},ra(a){return Object.assign({Jb:42,flags:2,Yb:255},fs.rc(a))},qc(a){return FS.ra(a.path)},chmod(a,b,c){b&=4095;NODEFS.la&&(b&=384);if(c&&fs.lstatSync(a).isSymbolicLink())throw new FS.g(138);fs.chmodSync(a,b)},fchmod(a,b){a=T(a);fs.fchmodSync(a.C,b)},chown(...a){fs.chownSync(...a)},fchown(a,b,c){a=T(a);fs.fchownSync(a.C,b,c)},truncate(a,b){if(0>b)throw new FS.g(28);return fs.truncateSync(a,b)},ftruncate(a,b){if(0>b)throw new FS.g(28);
a=T(a);fs.ftruncateSync(a.C,b)},utime(){},open(a,b,c){b=gf(b);var d=a.split("/").map(f=>f.slice(0,255)).join("/");c=fs.openSync(d,mf(b),c);var e=fs.fstatSync(c);if(b&65536&&!e.isDirectory())throw fs.closeSync(c),new FS.g(kf.vc);d=lf(d);return FS.ga({C:c,position:0,path:a,flags:b,node:{id:e.ino,mode:d,m:of,path:a},seekable:!0})},ga(a,b){b=pf.ga(a,b);if(!a.o){let c;(c=b.Y).Ra??(c.Ra=0);b.Y.Ra++;b.tty=qf.isatty(b.C)}return b}},rf=0,sf=null,tf=()=>{rf--;n.monitorRunDependencies?.(rf);if(0==rf&&sf){var a=
sf;sf=null;a()}},uf=()=>{rf++;n.monitorRunDependencies?.(rf)},vf=async(a,b)=>{"undefined"!=typeof Browser&&Browser.init();for(var c of Ge)if(c.canHandle(b))return c.handle(a,b);return a},wf=async(a,b,c,d,e,f,g,h)=>{var k=b?Ve(Oe(a,b)):a,l=`cp ${k}`;uf(l);try{var m=c;"string"==typeof c&&(m=await Fe(c));m=await vf(m,k);h?.();f||FS.createDataFile(a,b,m,d,e,g)}finally{tf(l)}};
function ef(a,b){var c=FS.isDir(a.mode)?(c=xf(a,"x"))?c:a.m.lookup?0:2:54;if(c)throw new FS.g(c);for(c=FS.ba[yf(a.id,b)];c;c=c.ja){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return FS.lookup(a,b)}function ff(a){var b=yf(a.parent.id,a.name);if(FS.ba[b]===a)FS.ba[b]=a.ja;else for(b=FS.ba[b];b;){if(b.ja===a){b.ja=a.ja;break}b=b.ja}}function T(a){a=FS.cb(a);if(!a)throw new FS.g(8);return a}
function yf(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%FS.ba.length}function zf(a){var b=yf(a.parent.id,a.name);a.ja=FS.ba[b];FS.ba[b]=a}function xf(a,b){return FS.fb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function Af(a,b){if(!FS.isDir(a.mode))return 54;try{return ef(a,b),20}catch(c){}return xf(a,"wx")}
function Bf(a,b,c){try{var d=ef(a,b)}catch(e){return e.B}if(a=xf(a,"wx"))return a;if(c){if(!FS.isDir(d.mode))return 54;if(FS.na(d)||FS.getPath(d)===FS.cwd())return 10}else if(FS.isDir(d.mode))return 31;return 0}function Cf(a,b){if(!a)throw new FS.g(b);return a}function Df(a,b=-1){a=FS.ga(a,b);a.o?.Cb?.(a);return a}function Ef(a,b,c){var d=a?.o.K;a=d?a:b;d??=b.m.K;Cf(d,63);try{d(a,c)}catch(e){if(e instanceof RangeError)throw new FS.g(22);throw e;}}
function Ff(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.oa)}return b}function Gf(a){var b={yb:4096,Ib:4096,blocks:1E6,xc:5E5,wc:5E5,files:FS.Na,Ec:FS.Na-1,Jb:42,flags:2,Yb:255};a.m.ra&&Object.assign(b,a.m.ra(a.mount.Oa.root));return b}function Hf(a,b,c,d){Ef(a,b,{mode:c&4095|b.mode&-4096,ctime:Date.now(),Ea:d})}
function If(a,b,c){if(FS.isDir(b.mode))throw new FS.g(31);if(!FS.isFile(b.mode))throw new FS.g(28);var d=xf(b,"w");if(d)throw new FS.g(d);Ef(a,b,{size:c,timestamp:Date.now()})}
function Jf(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=>0,write:(d,e,f,g)=>g,llseek:()=>0});FS.mkdev("/dev/null",FS.makedev(1,3));$e(FS.makedev(5,0),bf);$e(FS.makedev(6,0),cf);FS.mkdev("/dev/tty",FS.makedev(5,0));FS.mkdev("/dev/tty1",FS.makedev(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ue(a),b=a.byteLength);return a[--b]};FS.createDevice("/dev","random",c);FS.createDevice("/dev","urandom",c);FS.mkdir("/dev/shm");FS.mkdir("/dev/shm/tmp")}
function Kf(){FS.mkdir("/proc");var a=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var b=FS.createNode(a,"fd",16895,73);b.o={llseek:Q.o.llseek};b.m={lookup(c,d){c=+d;var e=T(c);c={parent:null,mount:{jb:"fake"},m:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(FS.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")}
function Lf(a,b,c,d){a=Oe("string"==typeof a?a:FS.getPath(a),b);return FS.create(a,jf(c,d))}function Mf(a){if(!(a.Vb||a.Wb||a.link||a.v))if(globalThis.XMLHttpRequest)J("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.v=la(a.url)}catch(b){throw new FS.g(29);}}
var FS={root:null,oa:[],$a:{},streams:[],Na:1,ba:null,Ya:"/",Ha:!1,fb:!0,Hb:null,Aa:0,g:class{name="ErrnoError";constructor(a){this.B=a}},vb:class{Y={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.Y.flags}set flags(a){this.Y.flags=a}get position(){return this.Y.position}set position(a){this.Y.position=a}},ub:class{m={};o={};T=null;constructor(a,b,c,d){a||=this;this.parent=a;this.mount=a.mount;this.id=FS.Na++;this.name=b;this.mode=c;this.rdev=d;this.atime=
this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Wb(){return FS.isDir(this.mode)}get Vb(){return FS.isChrdev(this.mode)}},lookupPath(a,b={}){if(!a)throw new FS.g(44);b.va??(b.va=!0);Je(a)||(a=FS.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(h=>!!h);for(var d=FS.root,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;
if("."!==a[f])if(".."===a[f])if(e=Le(e),FS.na(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Oe(e,a[f]);try{d=ef(d,a[f])}catch(h){if(44===h?.B&&g&&b.Zb)return{path:e};throw h;}!d.T||g&&!b.va||(d=d.T.root);if(FS.isLink(d.mode)&&(!g||b.follow)){if(!d.m.readlink)throw new FS.g(52);d=d.m.readlink(d);Je(d)||(d=Le(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new FS.g(32);},getPath(a){for(var b;;){if(FS.na(a))return a=a.mount.jb,b?"/"!==a[a.length-
1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},createNode(a,b,c,d){a=new FS.ub(a,b,c,d);zf(a);return a},na(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isDir(a){return 16384===(a&61440)},isLink(a){return 40960===(a&61440)},isChrdev(a){return 8192===(a&61440)},isBlkdev(a){return 24576===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},wb:4096,cb:a=>FS.streams[a],ga(a,b=-1){a=Object.assign(new FS.vb,a);if(-1==b)a:{for(b=0;b<=FS.wb;b++)if(!FS.streams[b])break a;
throw new FS.g(33);}a.fd=b;return FS.streams[b]=a},zb:{open(a){a.o=FS.Lb(a.node.rdev).o;a.o.open?.(a)},llseek(){throw new FS.g(70);}},Ka:a=>a>>8,Gc:a=>a&255,makedev:(a,b)=>a<<8|b,registerDevice(a,b){FS.$a[a]={o:b}},Lb:a=>FS.$a[a],syncfs(a,b){function c(h){FS.Aa--;return b(h)}function d(h){if(h){if(!d.Fb)return d.Fb=!0,c(h)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);FS.Aa++;1<FS.Aa&&x(`warning: ${FS.Aa} FS.syncfs operations in flight at once, probably just doing extra work`);var e=
Ff(FS.root.mount),f=0,g;for(g of e)g.type.syncfs?g.type.syncfs(g,a,d):d(null)},mount(a,b,c){var d="/"===c;if(d&&FS.root)throw new FS.g(10);if(!d&&c){var e=FS.lookupPath(c,{va:!1});c=e.path;e=e.node;if(e.T)throw new FS.g(10);if(!FS.isDir(e.mode))throw new FS.g(54);}b={type:a,Oa:b,jb:c,oa:[]};a=a.mount(b);a.mount=b;b.root=a;d?FS.root=a:e&&(e.T=b,e.mount&&e.mount.oa.push(b));return a},unmount(a){a=FS.lookupPath(a,{va:!1});if(!a.node.T)throw new FS.g(28);a=a.node;var b=a.T,c=Ff(b);for([,e]of Object.entries(FS.ba))for(;e;){var d=
e.ja;c.includes(e.mount)&&ff(e);var e=d}a.T=null;a.mount.oa.splice(a.mount.oa.indexOf(b),1)},lookup(a,b){return a.m.lookup(a,b)},S(a,b,c){var d=FS.lookupPath(a,{parent:!0}).node;a=Me(a);if(!a)throw new FS.g(28);if("."===a||".."===a)throw new FS.g(20);var e=Af(d,a);if(e)throw new FS.g(e);if(!d.m.S)throw new FS.g(63);return d.m.S(d,a,b,c)},ra(a){return Gf(FS.lookupPath(a,{follow:!0}).node)},qc(a){return Gf(a.node)},create(a,b=438){return FS.S(a,b&4095|32768,0)},mkdir(a,b=511){return FS.S(a,b&1023|16384,
0)},Hc(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||Je(a))d+="/";d+=e;try{FS.mkdir(d,b)}catch(f){if(20!=f.B)throw f;}}},mkdev(a,b,c){"undefined"==typeof c&&(c=b,b=438);return FS.S(a,b|8192,c)},symlink(a,b){if(!Ve(a))throw new FS.g(44);var c=FS.lookupPath(b,{parent:!0}).node;if(!c)throw new FS.g(44);b=Me(b);var d=Af(c,b);if(d)throw new FS.g(d);if(!c.m.symlink)throw new FS.g(63);return c.m.symlink(c,b,a)},rename(a,b){var c=Le(a),d=Le(b),e=Me(a),f=Me(b);var g=FS.lookupPath(a,{parent:!0});var h=
g.node;g=FS.lookupPath(b,{parent:!0});g=g.node;if(!h||!g)throw new FS.g(44);if(h.mount!==g.mount)throw new FS.g(75);var k=ef(h,e);a=We(a,d);if("."!==a.charAt(0))throw new FS.g(28);a=We(b,c);if("."!==a.charAt(0))throw new FS.g(55);try{var l=ef(g,f)}catch(m){}if(k!==l){b=FS.isDir(k.mode);if(e=Bf(h,e,b))throw new FS.g(e);if(e=l?Bf(g,f,b):Af(g,f))throw new FS.g(e);if(!h.m.rename)throw new FS.g(63);if(k.T||l&&l.T)throw new FS.g(10);if(g!==h&&(e=xf(h,"w")))throw new FS.g(e);ff(k);try{h.m.rename(k,g,f),
k.parent=g}catch(m){throw m;}finally{zf(k)}}},rmdir(a){var b=FS.lookupPath(a,{parent:!0}).node;a=Me(a);var c=ef(b,a),d=Bf(b,a,!0);if(d)throw new FS.g(d);if(!b.m.rmdir)throw new FS.g(63);if(c.T)throw new FS.g(10);b.m.rmdir(b,a);ff(c)},readdir(a){a=FS.lookupPath(a,{follow:!0}).node;return Cf(a.m.readdir,54)(a)},unlink(a){var b=FS.lookupPath(a,{parent:!0}).node;if(!b)throw new FS.g(44);a=Me(a);var c=ef(b,a),d=Bf(b,a,!1);if(d)throw new FS.g(d);if(!b.m.unlink)throw new FS.g(63);if(c.T)throw new FS.g(10);
b.m.unlink(b,a);ff(c)},readlink(a){a=FS.lookupPath(a).node;if(!a)throw new FS.g(44);if(!a.m.readlink)throw new FS.g(28);return a.m.readlink(a)},stat(a,b){a=FS.lookupPath(a,{follow:!b}).node;return Cf(a.m.I,63)(a)},fstat(a){var b=T(a);a=b.node;var c=b.o.I;b=c?b:a;c??=a.m.I;Cf(c,63);return c(b)},lstat(a){return FS.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?FS.lookupPath(a,{follow:!c}).node:a;Hf(null,a,b,c)},lchmod(a,b){FS.chmod(a,b,!0)},fchmod(a,b){a=T(a);Hf(a,a.node,b,!1)},chown(a,b,c,d){a="string"==
typeof a?FS.lookupPath(a,{follow:!d}).node:a;Ef(null,a,{timestamp:Date.now(),Ea:d})},lchown(a,b,c){FS.chown(a,b,c,!0)},fchown(a){a=T(a);Ef(a,a.node,{timestamp:Date.now(),Ea:!1})},truncate(a,b){if(0>b)throw new FS.g(28);a="string"==typeof a?FS.lookupPath(a,{follow:!0}).node:a;If(null,a,b)},ftruncate(a,b){a=T(a);if(0>b||0===(a.flags&2097155))throw new FS.g(28);If(a,a.node,b)},utime(a,b,c){a=FS.lookupPath(a,{follow:!0}).node;Cf(a.m.K,63)(a,{atime:b,mtime:c})},open(a,b,c=438){if(""===a)throw new FS.g(44);
b=gf(b);c=b&64?c&4095|32768:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");var f=FS.lookupPath(a,{follow:!(b&131072),Zb:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new FS.g(20);}else{if(e)throw new FS.g(31);d=FS.S(a,c|511,0);f=!0}if(!d)throw new FS.g(44);FS.isChrdev(d.mode)&&(b&=-513);if(b&65536&&!FS.isDir(d.mode))throw new FS.g(54);if(!f){e=d;a=b;if(e)if(FS.isLink(e.mode))e=32;else{var g=["r","w","rw"][a&3];a&512&&(g+="w");e=FS.isDir(e.mode)&&("r"!==g||a&576)?31:xf(e,g)}else e=
44;if(e)throw new FS.g(e);}b&512&&!f&&FS.truncate(d,0);b&=-131713;b=FS.ga({node:d,path:FS.getPath(d),flags:b,seekable:!0,position:0,o:d.o,sc:[],error:!1});b.o.open&&b.o.open(b);f&&FS.chmod(d,c&511);return b},close(a){if(null===a.fd)throw new FS.g(8);a.Fa&&(a.Fa=null);try{a.o.close&&a.o.close(a)}catch(b){throw b;}finally{FS.streams[a.fd]=null}a.fd=null},llseek(a,b,c){if(null===a.fd)throw new FS.g(8);if(!a.seekable||!a.o.llseek)throw new FS.g(70);if(0!=c&&1!=c&&2!=c)throw new FS.g(28);a.position=a.o.llseek(a,
b,c);a.sc=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new FS.g(28);if(null===a.fd)throw new FS.g(8);if(1===(a.flags&2097155))throw new FS.g(8);if(FS.isDir(a.node.mode))throw new FS.g(31);if(!a.o.read)throw new FS.g(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new FS.g(70);b=a.o.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new FS.g(28);if(null===a.fd)throw new FS.g(8);if(0===(a.flags&2097155))throw new FS.g(8);if(FS.isDir(a.node.mode))throw new FS.g(31);
if(!a.o.write)throw new FS.g(28);a.seekable&&a.flags&1024&&FS.llseek(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new FS.g(70);b=a.o.write(a,b,c,d,e,f);g||(a.position+=b);return b},aa(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new FS.g(2);if(1===(a.flags&2097155))throw new FS.g(2);if(!a.o.aa)throw new FS.g(43);if(!b)throw new FS.g(28);return a.o.aa(a,b,c,d,e)},ea(a,b,c,d,e){return a.o.ea?a.o.ea(a,b,c,d,e):0},wa(a,b,c){if(!a.o.wa)throw new FS.g(59);
return a.o.wa(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&J(`Invalid encoding type "${b.encoding}"`);var c=FS.open(a,b.flags);a=FS.stat(a).size;var d=new Uint8Array(a);FS.read(c,d,0,a,0);"utf8"===b.encoding&&(d=je(d));FS.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=FS.open(a,c.flags,c.mode);b=hf(b);FS.write(a,b,0,b.byteLength,void 0,c.Dc);FS.close(a)},cwd:()=>FS.Ya,chdir(a){a=FS.lookupPath(a,{follow:!0});
if(null===a.node)throw new FS.g(44);if(!FS.isDir(a.node.mode))throw new FS.g(54);var b=xf(a.node,"x");if(b)throw new FS.g(b);FS.Ya=a.path},Xa(a,b,c){a?FS.createDevice("/dev","stdin",a):FS.symlink("/dev/tty","/dev/stdin");b?FS.createDevice("/dev","stdout",null,b):FS.symlink("/dev/tty","/dev/stdout");c?FS.createDevice("/dev","stderr",null,c):FS.symlink("/dev/tty1","/dev/stderr");FS.open("/dev/stdin",0);FS.open("/dev/stdout",1);FS.open("/dev/stderr",1)},Ta(){FS.ba=Array(4096);FS.mount(Q,{},"/");FS.mkdir("/tmp");
FS.mkdir("/home");FS.mkdir("/home/web_user");Jf();Kf();FS.Hb={MEMFS:Q,NODEFS}},init(a,b,c){FS.Ha=!0;a??=n.stdin;b??=n.stdout;c??=n.stderr;FS.Xa(a,b,c)},Fc(a,b){a=FS.analyzePath(a,b);return a.exists?a.object:null},analyzePath(a,b){try{var c=FS.lookupPath(a,{follow:!b});a=c.path}catch(e){}var d={na:!1,exists:!1,error:0,name:null,path:null,object:null,$b:!1,cc:null,bc:null};try{c=FS.lookupPath(a,{parent:!0}),d.$b=!0,d.cc=c.path,d.bc=c.node,d.name=Me(a),c=FS.lookupPath(a,{follow:!b}),d.exists=!0,d.path=
c.path,d.object=c.node,d.name=c.node.name,d.na="/"===c.path}catch(e){d.error=e.B}return d},createPath(a,b){a="string"==typeof a?a:FS.getPath(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Oe(a,c);try{FS.mkdir(d)}catch(e){if(20!=e.B)throw e;}a=d}}return d},createDataFile(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:FS.getPath(a),g=b?Oe(a,b):a);a=jf(d,e);g=FS.create(g,a);c&&(c=hf(c),FS.chmod(g,a|146),b=FS.open(g,577),FS.write(b,c,0,c.length,0,f),FS.close(b),FS.chmod(g,a))},
createDevice(a,b,c,d){a=Oe("string"==typeof a?a:FS.getPath(a),b);b=jf(!!c,!!d);var e;(e=FS.createDevice).Ka??(e.Ka=64);e=FS.makedev(FS.createDevice.Ka++,0);FS.registerDevice(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,h,k){for(var l=0,m=0;m<k;m++){try{var r=c()}catch(t){throw new FS.g(29);}if(void 0===r&&0===l)throw new FS.g(6);if(null===r||void 0===r)break;l++;g[h+m]=r}l&&(f.node.atime=Date.now());return l},write(f,g,h,k){for(var l=0;l<k;l++)try{d(g[h+l])}catch(m){throw new FS.g(29);
}k&&(f.node.mtime=f.node.ctime=Date.now());return l}});return FS.mkdev(a,b,e)},createLazyFile(a,b,c,d,e){function f(m,r,t,p,u){m=m.node.v;if(u>=m.length)return 0;p=Math.min(m.length-u,p);if(m.slice)for(var v=0;v<p;v++)r[t+v]=m[u+v];else for(v=0;v<p;v++)r[t+v]=m.get(u+v);return p}class g{Ga=!1;ia=[];ma=void 0;ib=0;hb=0;get(m){if(!(m>this.length-1||0>m)){var r=m%this.chunkSize;return this.ma(m/this.chunkSize|0)[r]}}ic(m){this.ma=m}kb(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);200<=
m.status&&300>m.status||304===m.status||J("Couldn't load "+c+". Status: "+m.status);var r=Number(m.getResponseHeader("Content-length")),t,p=(t=m.getResponseHeader("Accept-Ranges"))&&"bytes"===t;m=(t=m.getResponseHeader("Content-Encoding"))&&"gzip"===t;var u=1048576;p||(u=r);var v=this;v.ic(C=>{var z=C*u,B=(C+1)*u-1;B=Math.min(B,r-1);if("undefined"==typeof v.ia[C]){var L=v.ia;z>B&&J("invalid range ("+z+", "+B+") or no bytes requested!");B>r-1&&J("only "+r+" bytes available! programmer error!");var D=
new XMLHttpRequest;D.open("GET",c,!1);r!==u&&D.setRequestHeader("Range","bytes="+z+"-"+B);D.responseType="arraybuffer";D.overrideMimeType&&D.overrideMimeType("text/plain; charset=x-user-defined");D.send(null);200<=D.status&&300>D.status||304===D.status||J("Couldn't load "+c+". Status: "+D.status);z=void 0!==D.response?new Uint8Array(D.response||[]):Ye(D.responseText||"");L[C]=z}"undefined"==typeof v.ia[C]&&J("doXHR failed!");return v.ia[C]});if(m||!r)u=r=1,u=r=this.ma(0).length,ra("LazyFiles on gzip forces download of the whole file when length is accessed");
this.ib=r;this.hb=u;this.Ga=!0}get length(){this.Ga||this.kb();return this.ib}get chunkSize(){this.Ga||this.kb();return this.hb}}if(globalThis.XMLHttpRequest){ca||J("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var h=new g;var k=void 0}else k=c,h=void 0;var l=Lf(a,b,d,e);h?l.v=h:k&&(l.v=null,l.url=k);Object.defineProperties(l,{N:{get:function(){return this.v.length}}});a={};for(const [m,r]of Object.entries(l.o))a[m]=(...t)=>
{Mf(l);return r(...t)};a.read=(m,r,t,p,u)=>{Mf(l);return f(m,r,t,p,u)};a.aa=(m,r,t)=>{Mf(l);var p=df(r);if(!p)throw new FS.g(48);f(m,y,p,r,t);return{u:p,U:!0}};l.o=a;return l}},Ce=(a,b)=>{if(Ra){if(Je(a))try{return FS.lookupPath(a),a}catch(d){return}var c=(b?.dc||[]).map(d=>{var e=b?.ac;d.startsWith("$ORIGIN")&&(e=Le(e),d=d.replace("$ORIGIN",e));return d});return Pe(()=>{var d=Dd(512),e=Se(c.join(":")),f=Se(a);return(d=td(d,e,f,512))?P(d):void 0})}};
function De(a,b={global:!0,pa:!0},c,d){function e(){var k=Ba[a];if(k)return b.J?Promise.resolve(k):k;if(d){k=H[d+28>>2];var l=H[d+32>>2];if(k&&l)return k=y.slice(k,k+l),b.J?Promise.resolve(k):k}if(k=Ce(a,b.Sa))return k=FS.readFile(k,{encoding:"binary"}),b.J?Promise.resolve(k):k;k=ja(a);if(b.J)return Fe(k);if(!la)throw Error(`${k}: file not found, and synchronous loading of external files is not available`);return la(k)}function f(){var k=He[a];return k?b.J?Promise.resolve(k):k:b.J?e().then(l=>Ee(l,
b,a,c,d)):Ee(e(),b,a,c,d)}function g(k){h.global?dd(k):c&&Object.assign(c,k);h.exports=k}var h=ke[a];if(h)return b.global?h.global||(h.global=!0,dd(h.exports)):c&&Object.assign(c,h.exports),b.pa&&Infinity!==h.ka&&(h.ka=Infinity),h.ka++,d&&(le[d]=h),b.J?Promise.resolve(!0):!0;h=Kd(a,d,"loading");h.ka=b.pa?Infinity:1;h.global=b.global;if(b.J)return f().then(k=>{g(k);return!0});g(f());return!0}
var Be=()=>{var a,b;for([a,b]of Object.entries(Nd))if(-1==b.value){var c=ze(a).Ua;if(c||b.required)if("function"==typeof c)b.value=ve(c,c.h);else if("number"==typeof c)b.value=c;else if("number"==typeof c.value)b.value=c;else throw Error(`bad export type for '${a}': ${typeof c} (${c})`);else b.value=0}},Ld=async()=>{if(sa.length){uf("loadDylibs");for(var a of sa)await De(a,{J:!0,global:!0,pa:!0,xb:!0});Be();tf("loadDylibs")}else Be()},$d=!1,fd=(a,b,c)=>{function d(){var e=a();if(e){var f={};c.qb.forEach(g=>
f[g]=b[g]);Jd(we(f,e),!0)}}de.push(d);Ra&&d()},Ea,hb=(a,b,c,d)=>J(`Assertion failed: ${P(a)}, at: `+[b?P(b):"unknown filename",c,d?P(d):"unknown function"]);hb.h="vppip";var ib=(a,b)=>N.get(a)(b);ib.h="vpi";function jb(...a){return K.__lsan_ignore_object(...a)}jb.za=!0;function Nf(a,b,c,d){return w?O(2,1,a,b,c,d):kb(a,b,c,d)}
var kb=(a,b,c,d)=>{if(!globalThis.SharedArrayBuffer)return 6;var e=[];if(w&&0===e.length)return Nf(a,b,c,d);a={oc:c,W:a,Ca:d,rb:e};return w?(a.R="spawnThread",postMessage(a,e),0):Yd(a)};kb.h="ipppp";var Of=18;function Pf(a,b,c){if(Je(b))return b;a=-100===a?FS.cwd():T(a).path;if(0==b.length){if(!c)throw new FS.g(44);return a}return a+"/"+b}
function Qf(a,b){H[a>>2]=b.dev;H[a+4>>2]=b.mode;H[a+8>>2]=b.nlink;H[a+12>>2]=b.uid;H[a+16>>2]=b.gid;H[a+20>>2]=b.rdev;I[a+24>>3]=BigInt(b.size);G[a+32>>2]=4096;G[a+36>>2]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),e=b.ctime.getTime();I[a+40>>3]=BigInt(Math.floor(c/1E3));H[a+48>>2]=c%1E3*1E6;I[a+56>>3]=BigInt(Math.floor(d/1E3));H[a+64>>2]=d%1E3*1E6;I[a+72>>3]=BigInt(Math.floor(e/1E3));H[a+80>>2]=e%1E3*1E6;I[a+88>>3]=BigInt(b.ino);return 0}var Rf=void 0;
function lb(a){if(w)return O(3,1,a);try{var b=T(a);return Df(b).fd}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}lb.h="ii";function mb(a,b,c,d){if(w)return O(4,1,a,b,c,d);try{b=P(b);b=Pf(a,b);if(c&-8)return-28;var e=FS.lookupPath(b,{follow:!0}).node;if(!e)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&xf(e,a)?-2:0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}mb.h="iipii";var Sf=()=>{var a=G[+Rf>>2];Rf+=4;return a};
function nb(a,b,c){if(w)return O(5,1,a,b,c);Rf=c;try{var d=T(a);switch(b){case 0:var e=Sf();if(0>e)break;for(;FS.streams[e];)e++;return Df(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Sf(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=Sf(),A[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}nb.h="iiip";
function ob(a,b){if(w)return O(6,1,a,b);try{return Qf(b,FS.fstat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}ob.h="iip";function pb(a,b){if(w)return O(7,1,a,b);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return-22;FS.ftruncate(a,b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}pb.h="iij";
function qb(a,b){if(w)return O(8,1,a,b);try{if(0===b)return-28;var c=FS.cwd(),d=Qe(c)+1;if(b<d)return-68;Re(c,E,a,b);return d}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.B}}qb.h="ipp";
function rb(a,b,c){if(w)return O(9,1,a,b,c);Rf=c;try{var d=T(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.da.Sb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Sf();G[e>>2]=25856;G[e+4>>2]=5;G[e+8>>2]=191;G[e+12>>2]=35387;for(var f=0;32>f;f++)y[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.da.Tb)for(e=Sf(),a=[],f=0;32>f;f++)a.push(y[e+
f+17]);return 0;case 21519:if(!d.tty)return-59;e=Sf();return G[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:return e=Sf(),FS.wa(d,b,e);case 21523:if(!d.tty)return-59;d.tty.da.Ub&&(f=[24,80],e=Sf(),A[e>>1]=f[0],A[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.B}}rb.h="iiip";
function sb(a,b){if(w)return O(10,1,a,b);try{return a=P(a),Qf(b,FS.lstat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}sb.h="ipp";function tb(a,b,c,d){if(w)return O(11,1,a,b,c,d);try{b=P(b);var e=d&256;b=Pf(a,b,d&4096);return Qf(c,e?FS.lstat(b):FS.stat(b))}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}tb.h="iippi";
function ub(a,b,c,d){if(w)return O(12,1,a,b,c,d);Rf=d;try{b=P(b);b=Pf(a,b);var e=d?Sf():0;c&64&&(e&=~Of);return FS.open(b,c,e).fd}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}ub.h="iipip";
function vb(a,b,c){if(w)return O(13,2,a,b,c);try{const u=fe;var d,e=new Promise(z=>{d=z}),f=[],g=!1;function v(z){g||(g=!0,f.forEach(B=>B()),d(z))}function C(z,B){return L=>{g||(L&=A[B+4>>1]|24,A[B+6>>1]=L,v(1))}}if(u&&0<c){var h=setTimeout(()=>{v(0)},c);f.push(()=>clearTimeout(h))}for(var k=0,l=0;l<b;l++){var m=a+8*l,r=A[m+4>>1],t=32,p=FS.cb(G[m>>2]);p&&(p.o.lb?t=u&&c?p.o.lb(p,c,C(p,m)):p.o.lb(p,-1):t=5);(t&=r|24)&&k++;A[m+6>>1]=t}return u?(!k&&c||v(k),e):k}catch(u){if("undefined"==typeof FS||"ErrnoError"!==
u.name)throw u;return-u.B}}vb.h="ipii";function wb(a){if(w)return O(14,1,a);try{return a=P(a),FS.rmdir(a),0}catch(b){if("undefined"==typeof FS||"ErrnoError"!==b.name)throw b;return-b.B}}wb.h="ip";function xb(a,b){if(w)return O(15,1,a,b);try{return a=P(a),Qf(b,FS.stat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}xb.h="ipp";
function yb(a,b,c){if(w)return O(16,1,a,b,c);try{b=P(b);b=Pf(a,b);if(c)if(512===c)FS.rmdir(b);else return-28;else FS.unlink(b);return 0}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.B}}yb.h="iipi";var zb=a=>{a=new WebAssembly.Exception(Hd,[a],{traceStack:!0});var b=a.getArg(Hd,0);var c=Fd(b);b=Ed();var d=Dd(4),e=Dd(4);Gd(c,d,e);c=H[d>>2];e=H[e>>2];d=P(c);M(c);if(e){var f=P(e);M(e)}Cd(b);a.message=[d,f];throw a;},Ab=()=>J("");Ab.h="v";
var Tf=a=>{var b=Ed();a=Se(a);od(a,0);Cd(b)},Uf=(a,b)=>{var c=P(a+36),d=G[a+4>>2];c=Ke(c);var e=!!(d&256),f=e?null:{};d={global:e,pa:!!(d&4096),J:b.J};if(b.J)return De(c,d,f,a);try{return De(c,d,f,a)}catch(g){return Tf(`could not load dynamic lib: ${c}\n${g}`),0}},Db=a=>Uf(a,{J:!1});Db.h="pp";var Eb=(a,b)=>{a=le[a].exports;b=Object.keys(a)[b];b=a[b];return ve(b,b.h)};Eb.h="ppi";
var Fb=(a,b,c)=>{b=P(b);var d=le[a];a=Object.keys(d.exports).indexOf(b);if(-1==a||d.exports[b].za)return Tf(`Tried to lookup unknown symbol "${b}" in dynamic lib: ${d.name}`),0;b=d.exports[b];"function"==typeof b&&((d=qe(b))?b=d:(b=ve(b,b.h),H[c>>2]=a));return b};Fb.h="pppp";var Vf={},Wf=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Xf(a){return this.A(H[a>>2])}
var Yf={},Zf={},$f={},ag=class extends Error{constructor(a){super(a);this.name="InternalError"}},V=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new ag("Mismatched type converter count");for(var k=0;k<a.length;++k)U(a[k],h[k])}a.forEach(h=>$f[h]=b);var e=Array(b.length),f=[],g=0;for(let [h,k]of b.entries())Zf.hasOwnProperty(k)?e[h]=Zf[k]:(f.push(k),Yf.hasOwnProperty(k)||(Yf[k]=[]),Yf[k].push(()=>{e[h]=Zf[k];++g;g===f.length&&d(e)}));0===f.length&&d(e)},Gb=a=>{var b=Vf[a];delete Vf[a];
var c=b.Qa,d=b.X,e=b.ab,f=e.map(g=>g.Ob).concat(e.map(g=>g.kc));V([a],f,g=>{var h={},k,l;for([k,l]of e.entries()){const m=g[k],r=l.ma,t=l.Nb,p=g[k+e.length],u=l.jc,v=l.lc;h[l.Gb]={read:C=>m.A(r(t,C)),write:(C,z)=>{var B=[];u(v,C,p.F(B,z));Wf(B)},optional:m.optional}}return[{name:b.name,A:m=>{var r={},t;for(t in h)r[t]=h[t].read(m);d(m);return r},F:(m,r)=>{for(var t in h)if(!(t in r||h[t].optional))throw new TypeError(`Missing field: "${t}"`);var p=c();for(t in h)h[t].write(p,r[t]);null!==m&&m.push(d,
p);return p},M:Xf,H:d}]})};Gb.h="vp";var W=a=>{for(var b="";;){var c=E[a++];if(!c)return b;b+=String.fromCharCode(c)}},X=class extends Error{constructor(a){super(a);this.name="BindingError"}},bg=a=>{throw new X(a);};
function cg(a,b,c={}){var d=b.name;if(!a)throw new X(`type "${d}" must have a positive integer typeid pointer`);if(Zf.hasOwnProperty(a)){if(c.Rb)return;throw new X(`Cannot register type '${d}' twice`);}Zf[a]=b;delete $f[a];Yf.hasOwnProperty(a)&&(b=Yf[a],delete Yf[a],b.forEach(e=>e()))}function U(a,b,c={}){return cg(a,b,c)}
var Hb=(a,b,c,d,e)=>{b=W(b);if(d)a:switch(c){case 4:d=Ta;break a;case 8:d=Ua;break a;default:throw new TypeError(`invalid float width (${c}): ${b}`);}else a:switch(c){case 1:d=e?y:E;break a;case 2:d=e?A:F;break a;case 4:d=e?G:H;break a;case 8:d=e?I:Va;break a;default:throw new TypeError(`invalid integer width (${c}): ${b}`);}var f=d,g=Math.log2(c);U(a,{name:b,A:h=>{var k=h+Math.max(4,c)>>g;k=Array.from(f.subarray(k,k+H[h>>2]));M(h);return k},F:(h,k)=>{"number"==typeof k&&(k=[k]);if(!Array.isArray(k))throw new X(`Cannot pass non-array to C++ vector type ${b}`);
k=Array.prototype.concat.apply([],k);var l=k.length,m=Math.max(4,c),r=hd(m+l*c);m=r+m>>g;H[r>>2]=l;f.set(k,m);null!==h&&h.push(M,r);return r},M:Xf,H(h){M(h)}})};Hb.h="vpppii";
var dg=(a,b,c)=>{switch(b){case 1:return c?d=>y[d]:d=>E[d];case 2:return c?d=>A[d>>1]:d=>F[d>>1];case 4:return c?d=>G[d>>2]:d=>H[d>>2];case 8:return c?d=>I[d>>3]:d=>Va[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ib=(a,b,c,d,e)=>{b=W(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}U(a,{name:b,A:f,F:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},M:dg(b,c,!d),H:null})};Ib.h="vpppjj";
var Jb=(a,b,c,d)=>{b=W(b);U(a,{name:b,A:function(e){return!!e},F:function(e,f){return f?c:d},M:function(e){return this.A(E[e])},H:null})};Jb.h="vppii";
var eg=a=>{throw new X(a.l.D.s.name+" instance already deleted");},fg=!1,gg=!1,hg=()=>{},ig=a=>{if(fg)return ig=b=>b.deleteLater(),ig(a);if(!globalThis.FinalizationRegistry)return ig=b=>b,a;gg=new FinalizationRegistry(b=>{b=b.l;--b.count.value;0===b.count.value&&(b.L?b.P.X(b.L):b.D.s.X(b.u))});ig=b=>{var c=b.l;c.L&&gg.register(b,{l:c},b);return b};hg=b=>{gg.unregister(b)};return ig(a)},jg=[],kg=()=>{for(;jg.length;){var a=jg.pop();a.l.ha=!1;a["delete"]()}},lg;function mg(){}
var ng={},og=(a,b,c)=>{if(void 0===a[b].G){var d=a[b];a[b]=function(...e){if(!a[b].G.hasOwnProperty(e.length))throw new X(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].G})!`);return a[b].G[e.length].apply(this,e)};a[b].G=[];a[b].G[d.Z]=d}},pg=(a,b,c)=>{if(n.hasOwnProperty(a)){if(void 0===c||void 0!==n[a].G&&void 0!==n[a].G[c])throw new X(`Cannot register public name '${a}' twice`);og(n,a,a);if(n[a].G.hasOwnProperty(c))throw new X(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
n[a].G[c]=b}else n[a]=b,n[a].Z=c},qg=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function rg(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.$=c;this.X=d;this.O=e;this.Kb=f;this.ta=g;this.Bb=h;this.fc=[]}
var sg=(a,b,c)=>{for(;b!==c;){if(!b.ta)throw new X(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ta(a);b=b.O}return a},tg=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function ug(a,b){if(null===b){if(this.Ia)throw new X(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new X(`Cannot pass "${tg(b)}" as a ${this.name}`);if(!b.l.u)throw new X(`Cannot pass deleted object as a pointer of type ${this.name}`);return sg(b.l.u,b.l.D.s,this.s)}
function vg(a,b){if(null===b){if(this.Ia)throw new X(`null is not a valid ${this.name}`);if(this.ya){var c=this.Qa();null!==a&&a.push(this.X,c);return c}return 0}if(!b||!b.l)throw new X(`Cannot pass "${tg(b)}" as a ${this.name}`);if(!b.l.u)throw new X(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.xa&&b.l.D.xa)throw new X(`Cannot convert argument of type ${b.l.P?b.l.P.name:b.l.D.name} to parameter type ${this.name}`);c=sg(b.l.u,b.l.D.s,this.s);if(this.ya){if(void 0===b.l.L)throw new X("Passing raw pointer to smart pointer is illegal");
switch(this.nc){case 0:if(b.l.P===this)c=b.l.L;else throw new X(`Cannot convert argument of type ${b.l.P?b.l.P.name:b.l.D.name} to parameter type ${this.name}`);break;case 1:c=b.l.L;break;case 2:if(b.l.P===this)c=b.l.L;else{var d=b.clone();c=this.hc(c,wg(()=>d["delete"]()));null!==a&&a.push(this.X,c)}break;default:throw new X("Unsupported sharing policy");}}return c}
function xg(a,b){if(null===b){if(this.Ia)throw new X(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new X(`Cannot pass "${tg(b)}" as a ${this.name}`);if(!b.l.u)throw new X(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.l.D.xa)throw new X(`Cannot convert argument of type ${b.l.D.name} to parameter type ${this.name}`);return sg(b.l.u,b.l.D.s,this.s)}
var yg=(a,b,c)=>{if(b===c)return a;if(void 0===c.O)return null;a=yg(a,b,c.O);return null===a?null:c.Bb(a)},zg={},Ag=(a,b)=>{if(void 0===b)throw new X("ptr should not be undefined");for(;a.O;)b=a.ta(b),a=a.O;return zg[b]},Bg=(a,b)=>{if(!b.D||!b.u)throw new ag("makeClassHandle requires ptr and ptrType");if(!!b.P!==!!b.L)throw new ag("Both smartPtrType and smartPtr must be specified");b.count={value:1};return ig(Object.create(a,{l:{value:b,writable:!0}}))};
function Cg(a,b,c,d,e,f,g,h,k,l,m){this.name=a;this.s=b;this.Ia=c;this.xa=d;this.ya=e;this.ec=f;this.nc=g;this.nb=h;this.Qa=k;this.hc=l;this.X=m;e||void 0!==b.O?this.F=vg:(this.F=d?ug:xg,this.H=null)}var Dg=(a,b,c)=>{if(!n.hasOwnProperty(a))throw new ag("Replacing nonexistent public symbol");void 0!==n[a].G&&void 0!==c?n[a].G[c]=b:(n[a]=b,n[a].Z=c)},Y=(a,b)=>{a=W(a);var c=N.get(b);if("function"!=typeof c)throw new X(`unknown function pointer with signature ${a}: ${b}`);return c};
class Eg extends Error{}
var Fg=a=>{a=ld(a);var b=W(a);M(a);return b},Jg=(a,b)=>{function c(f){e[f]||Zf[f]||($f[f]?$f[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Eg(`${a}: `+d.map(Fg).join([", "]));},Kb=(a,b,c,d,e,f,g,h,k,l,m,r,t)=>{m=W(m);f=Y(e,f);h&&=Y(g,h);l&&=Y(k,l);t=Y(r,t);var p=qg(m);pg(p,function(){Jg(`Cannot construct ${m} due to unbound types`,[d])});V([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var v=u.s;var C=v.$}else C=mg.prototype;u=ye(m,function(...D){if(Object.getPrototypeOf(this)!==z)throw new X(`Use 'new' to construct ${m}`);
if(void 0===B.fa)throw new X(`${m} has no accessible constructor`);var La=B.fa[D.length];if(void 0===La)throw new X(`Tried to invoke ctor of ${m} with invalid number of parameters (${D.length}) - expected (${Object.keys(B.fa).toString()}) parameters instead!`);return La.apply(this,D)});var z=Object.create(C,{constructor:{value:u}});u.prototype=z;var B=new rg(m,u,z,t,v,f,h,l);if(B.O){var L;(L=B.O).ua??(L.ua=[]);B.O.ua.push(B)}v=new Cg(m,B,!0,!1,!1);L=new Cg(m+"*",B,!1,!1,!1);C=new Cg(m+" const*",B,
!1,!0,!1);ng[a]={pointerType:L,Ab:C};Dg(p,u);return[v,L,C]})};Kb.h="vppppppppppppp";function Kg(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].H)return!0;return!1}
function Lg(a,b,c,d,e,f){var g=b.length;if(2>g)throw new X("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,k=Kg(b);c=!b[0].gb;var l=b[0],m=b[1];d=[a,bg,d,e,Wf,l.A.bind(l),m?.F.bind(m)];for(e=2;e<g;++e)l=b[e],d.push(l.F.bind(l));if(!k)for(e=h?1:2;e<b.length;++e)null!==b[e].H&&d.push(b[e].H);k=Kg(b);e=b.length-2;m=[];l=["fn"];h&&l.push("thisWired");for(g=0;g<e;++g)m.push(`arg${g}`),l.push(`arg${g}Wired`);m=m.join(",");l=l.join(",");m=`return function (${m}) {\n`;
k&&(m+="var destructors = [];\n");var r=k?"destructors":"null",t="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(m+=`var thisWired = toClassParamWire(${r}, this);\n`);for(g=0;g<e;++g){var p=`toArg${g}Wire`;m+=`var arg${g}Wired = ${p}(${r}, arg${g});\n`;t.push(p)}m+=(c||f?"var rv = ":"")+`invoker(${l});\n`;if(k)m+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].H&&(m+=`${f}_dtor(${f});\n`,
t.push(`${f}_dtor`));c&&(m+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(t,m+"}\n"))(...d);return ye(a,b)}
var Mg=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(H[b+4*d>>2]);return c},Ng=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Lb=(a,b,c,d,e,f,g,h)=>{var k=Mg(c,d);b=W(b);b=Ng(b);f=Y(e,f);V([],[a],l=>{function m(){Jg(`Cannot call ${r} due to unbound types`,k)}l=l[0];var r=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var t=l.s.constructor;void 0===t[b]?(m.Z=c-1,t[b]=m):(og(t,b,r),t[b].G[c-1]=m);V([],k,p=>{p=[p[0],null].concat(p.slice(1));p=Lg(r,p,null,f,g,h);void 0===
t[b].G?(p.Z=c-1,t[b]=p):t[b].G[c-1]=p;if(l.s.ua)for(const u of l.s.ua)u.constructor.hasOwnProperty(b)||(u.constructor[b]=p);return[]});return[]})};Lb.h="vppippppii";
var Mb=(a,b,c,d,e,f)=>{var g=Mg(b,c);e=Y(d,e);V([],[a],h=>{h=h[0];var k=`constructor ${h.name}`;void 0===h.s.fa&&(h.s.fa=[]);if(void 0!==h.s.fa[b-1])throw new X(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.s.fa[b-1]=()=>{Jg(`Cannot construct ${h.name} due to unbound types`,g)};V([],g,l=>{l.splice(1,0,null);h.s.fa[b-1]=Lg(k,l,null,e,f);return[]});
return[]})};Mb.h="vpipppp";var Nb=(a,b,c,d,e,f,g,h,k)=>{var l=Mg(c,d);b=W(b);b=Ng(b);f=Y(e,f);V([],[a],m=>{function r(){Jg(`Cannot call ${t} due to unbound types`,l)}m=m[0];var t=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&m.s.fc.push(b);var p=m.s.$,u=p[b];void 0===u||void 0===u.G&&u.className!==m.name&&u.Z===c-2?(r.Z=c-2,r.className=m.name,p[b]=r):(og(p,b,t),p[b].G[c-2]=r);V([],l,v=>{v=Lg(t,v,m,f,g,k);void 0===p[b].G?(v.Z=c-2,p[b]=v):p[b].G[c-2]=v;return[]});return[]})};
Nb.h="vppippppiii";
var Og=(a,b,c)=>{if(!(a instanceof Object))throw new X(`${c} with invalid "this": ${a}`);if(!(a instanceof b.s.constructor))throw new X(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.l.u)throw new X(`cannot call emscripten binding method ${c} on deleted object`);return sg(a.l.u,a.l.D.s,b.s)},Ob=(a,b,c,d,e,f,g,h,k,l)=>{b=W(b);e=Y(d,e);V([],[a],m=>{m=m[0];var r=`${m.name}.${b}`,t={get(){Jg(`Cannot access ${r} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};t.set=k?
()=>Jg(`Cannot access ${r} due to unbound types`,[c,g]):()=>{throw new X(r+" is a read-only property");};Object.defineProperty(m.s.$,b,t);V([],k?[c,g]:[c],p=>{var u=p[0],v={get(){var z=Og(this,m,r+" getter");return u.A(e(f,z))},enumerable:!0};if(k){k=Y(h,k);var C=p[1];v.set=function(z){var B=Og(this,m,r+" setter"),L=[];k(l,B,C.F(L,z));Wf(L)}}Object.defineProperty(m.s.$,b,v);return[]});return[]})};Ob.h="vpppppppppp";
var Pg=[],Qg=[0,1,,1,null,1,!0,1,!1,1],Rg=[],oc=a=>{if(9<a&&0===--Qg[a+1]){var b=Qg[a];Qg[a]=void 0;var c=Rg[a];c&&(Rg[a]=void 0,c(b));Pg.push(a)}};oc.h="vp";var Z=a=>{if(!a)throw new X(`Cannot use deleted val. handle = ${a}`);return Qg[a]},wg=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Pg.pop()||Qg.length;Qg[b]=a;Qg[b+1]=1;return b}},Sg={name:"emscripten::val",A:a=>{var b=Z(a);oc(a);return b},F:(a,b)=>wg(b),M:Xf,H:null},Pb=a=>U(a,Sg);
Pb.h="vp";
var Tg=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.A(y[d])}:function(d){return this.A(E[d])};case 2:return c?function(d){return this.A(A[d>>1])}:function(d){return this.A(F[d>>1])};case 4:return c?function(d){return this.A(G[d>>2])}:function(d){return this.A(H[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Qb=(a,b,c,d,e)=>{b=W(b);e=0===e?"object":1===e?"number":"string";switch(e){case "object":function g(){}g.values={};U(a,{name:b,constructor:g,valueType:e,
A:function(h){return this.constructor.values[h]},F:(h,k)=>k.value,M:Tg(b,c,d),H:null});pg(b,g);break;case "number":var f={};U(a,{name:b,Ja:f,valueType:e,A:h=>h,F:(h,k)=>k,M:Tg(b,c,d),H:null});pg(b,f);delete n[b].Z;break;case "string":f={},U(a,{name:b,sb:{},ob:{},Ja:f,valueType:e,A:function(h){return this.ob[h]},F:function(h,k){return this.sb[k]},M:Tg(b,c,d),H:null}),pg(b,f),delete n[b].Z}};Qb.h="vpppii";
var Ug=(a,b)=>{var c=Zf[a];if(void 0===c)throw a=`${b} has unknown type ${Fg(a)}`,new X(a);return c},Rb=(a,b,c)=>{var d=Ug(a,"enum");b=W(b);switch(d.valueType){case "object":a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:ye(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d;break;case "number":d.Ja[b]=c;break;case "string":d.sb[b]=c,d.ob[c]=b,d.Ja[b]=b}};Rb.h="vppi";
var Vg=(a,b)=>{switch(b){case 4:return function(c){return this.A(Ta[c>>2])};case 8:return function(c){return this.A(Ua[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Sb=(a,b,c)=>{b=W(b);U(a,{name:b,A:d=>d,F:(d,e)=>e,M:Vg(b,c),H:null})};Sb.h="vppp";var Tb=(a,b,c,d,e,f,g)=>{var h=Mg(b,c);a=W(a);a=Ng(a);e=Y(d,e);pg(a,function(){Jg(`Cannot call ${a} due to unbound types`,h)},b-1);V([],h,k=>{k=[k[0],null].concat(k.slice(1));Dg(a,Lg(a,k,null,e,f,g),b-1);return[]})};Tb.h="vpippppii";
var Ub=(a,b,c,d,e)=>{b=W(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}U(a,{name:b,A:f,F:(h,k)=>k,M:dg(b,c,0!==d),H:null})};Ub.h="vpppii";var Wg=(a,b,c)=>{const d=(e,f)=>{let g=0;return{next(){if(g>=e)return{done:!0};const h=g;g++;return{value:f(h),done:!1}},[Symbol.iterator](){return this}}};a[Symbol.iterator]||(a[Symbol.iterator]=function(){const e=this[b]();return d(e,f=>this[c](f))})},Vb=(a,b,c,d)=>{c=W(c);d=W(d);V([],[a,b],e=>{Wg(e[0].s.$,c,d);return[]})};Vb.h="vpppp";
var Wb=(a,b,c)=>{function d(f){return new e(y.buffer,H[f+4>>2],H[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=W(c);U(a,{name:c,A:d,M:d},{Rb:!0})};Wb.h="vpip";var Xg=Object.assign({optional:!0},Sg),Xb=a=>{U(a,Xg)};Xb.h="vpp";
var Yb=(a,b)=>{b=W(b);U(a,{name:b,A(c){var d=P(c+4,H[c>>2],!0);M(c);return d},F(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new X("Cannot pass non-string to std::string");var f=e?Qe(d):d.length;var g=hd(4+f+1),h=g+4;H[g>>2]=f;e?Re(d,E,h,f+1):E.set(d,h);null!==c&&c.push(M,g);return g},M:Xf,H(c){M(c)}})};Yb.h="vpp";
var Yg=new TextDecoder("utf-16le"),Zg=(a,b,c)=>{a>>=1;return Yg.decode(F.slice(a,ie(F,a,b/2,c)))},$g=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)A[b>>1]=a.charCodeAt(e),b+=2;A[b>>1]=0;return b-d},ah=a=>2*a.length,bh=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=H[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},ch=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);
65535<f&&e++;G[b>>2]=f;b+=4;if(b+4>c)break}G[b>>2]=0;return b-d},dh=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Zb=(a,b,c)=>{c=W(c);if(2===b){var d=Zg;var e=$g;var f=ah}else d=bh,e=ch,f=dh;U(a,{name:c,A:g=>{var h=d(g+4,H[g>>2]*b,!0);M(g);return h},F:(g,h)=>{if("string"!=typeof h)throw new X(`Cannot pass non-string to C++ string type ${c}`);var k=f(h),l=hd(4+k+b);H[l>>2]=k/b;e(h,l+4,k+b);null!==g&&g.push(M,l);return l},M:Xf,H(g){M(g)}})};Zb.h="vppp";
var $b=(a,b,c,d,e,f)=>{Vf[a]={name:W(b),Qa:Y(c,d),X:Y(e,f),ab:[]}};$b.h="vpppppp";var ac=(a,b,c,d,e,f,g,h,k,l)=>{Vf[a].ab.push({Gb:W(b),Ob:c,ma:Y(d,e),Nb:f,kc:g,jc:Y(h,k),lc:l})};ac.h="vpppppppppp";var bc=(a,b)=>{b=W(b);U(a,{gb:!0,name:b,A:()=>{},F:()=>{}})};bc.h="vpp";
var eh=a=>{a instanceof Md||"unwind"==a||fa(1,a)},ee=a=>{if(!Sa&&!va)try{a()}catch(b){eh(b)}finally{if(!(Sa||$d||0<Zd))try{w?gd()&&yd(wa):Tc(wa)}catch(b){eh(b)}}},cc=(a,b,c,d)=>{function e(h){var k=P(a+36);Tf(`'Could not load dynamic lib: ${k}\n${h}`);--Zd;ee(()=>N.get(c)(a,d))}function f(){--Zd;ee(()=>N.get(b)(a,d))}Zd+=1;var g=Uf(a,{J:!0});g?g.then(f,e):e()};cc.h="vpppp";function fh(a){var b=gh,c=b.ia.pop()||b.U.length;b.U[c]=a;return c}function hh(a){var b=gh;b.U[a]=void 0;b.ia.push(a)}
class ih{U=[void 0];ia=[];get(a){return this.U[a]}has(a){return void 0!==this.U[a]}}var gh=new ih,jh=()=>{var a={};a.promise=new Promise((b,c)=>{a.reject=c;a.resolve=b});a.id=fh(a);return a},kh=async()=>{const a=fe,b=[];var c=jh();b.push(c.promise);pd(c.id);for(const d of Object.keys(Pd)){const e=Number(d);e===a||Qd.has(e)||(c=jh(),rd(e,c.id),Rd[e]=c,b.push(c.promise))}await Promise.all(b);Rd={}};
function dc(){if(w)return O(17,2);if(fe)return kh();for(const a of Object.keys(Pd)){const b=Number(a);Qd.has(b)||sd(b)}}dc.h="v";function ec(){var a=hd(4*(sa.length+1)),b=a;sa.forEach(c=>{var d=H,e=b>>2,f=Qe(c)+1,g=hd(f);g&&Re(c,E,g,f);d[e]=g;b+=4});H[b>>2]=0;return a}ec.h="p";var fc=a=>{Ja(a,!ca,1,!ba,262144,!1);Ka()};fc.h="vp";var Ma=a=>{ce||(Atomics.waitAsync(G,a>>2,a).value.then(Pa),Atomics.store(G,a+120>>2,1))};Ma.h="vp";
var Pa=()=>{var a=gd();a&&ee(()=>{Ma(a);zd()})},gc=(a,b)=>{a==b?setTimeout(Pa):w?postMessage({Ba:a,R:"checkMailbox"}):(a=Pd[a])&&a.postMessage({R:"checkMailbox"})};gc.h="vpp";var lh=[],hc=(a,b,c,d,e,f,g)=>{lh.length=0;var h=e>>3;for(d=e+d>>3;h<d;){var k;I[h++]?k=I[h++]:k=Ua[h++];lh.push(k)}a=b?Ae[b]:mh[a];fe=c;c=a(...lh);fe=0;if(f)c.then(l=>vd(f,g,l));else return c};hc.h="dippippp";var ic=()=>{$d=!1;Zd=0};ic.h="v";var jc=a=>{w?postMessage({R:"cleanupThread",Va:a}):Ud(a)};jc.h="vp";
var kc=a=>{w?postMessage({R:"markAsFinished",Va:a}):Wd(a)};kc.h="vp";var lc=a=>{q&&Pd[a].ref()};lc.h="vp";var mc=(a,b)=>{a=Z(a);b=Z(b);a.set(b)};mc.h="vpp";
var nh=[],oh=a=>{var b=nh.length;nh.push(a);return b},ph=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Ug(H[b+4*d>>2],`parameter ${d}`);return c},qh=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(H[b>>2]=wg(d));return a},rh={},sh=a=>{var b=rh[a];return void 0===b?W(a):b},nc=(a,b,c)=>{var [d,...e]=ph(a,b);b=d.F.bind(d);var f=e.map(k=>k.M.bind(k));a--;var g={toValue:Z};a=f.map((k,l)=>{var m=`argFromPtr${l}`;g[m]=k;return`${m}(args${l?"+"+8*l:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";
break;case 3:h="";break;case 1:g.getStringOrSymbol=sh,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${a})`;d.gb||(g.toReturnWire=b,g.emval_returnValue=qh,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n${h}\n}`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=`methodCaller<(${e.map(k=>k.name)}) => ${d.name}>`;return oh(ye(h,c))};nc.h="pipi";var pc=a=>{if(!a)return wg(globalThis);a=sh(a);return wg(globalThis[a])};
pc.h="pp";var qc=a=>{a=sh(a);return wg(n[a])};qc.h="pp";var rc=(a,b)=>{a=Z(a);b=Z(b);return wg(a[b])};rc.h="ppp";var sc=a=>{9<a&&(Qg[a+1]+=1)};sc.h="vp";var tc=(a,b)=>{a=Z(a);b=Z(b);return a instanceof b};tc.h="ipp";var uc=(a,b,c,d,e)=>nh[a](b,c,d,e);uc.h="dppppp";var vc=a=>{a=Z(a);return"number"==typeof a};vc.h="ip";var wc=a=>{a=Z(a);return"string"==typeof a};wc.h="ip";var xc=a=>wg(sh(a));xc.h="pp";var yc=a=>{var b=Z(a);Wf(b);oc(a)};yc.h="vp";var zc=(a,b,c)=>{a=Z(a);b=Z(b);c=Z(c);a[b]=c};zc.h="vppp";
var Ac=a=>{a=Z(a);return wg(typeof a)};Ac.h="pp";function Bc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);G[b>>2]=a.getUTCSeconds();G[b+4>>2]=a.getUTCMinutes();G[b+8>>2]=a.getUTCHours();G[b+12>>2]=a.getUTCDate();G[b+16>>2]=a.getUTCMonth();G[b+20>>2]=a.getUTCFullYear()-1900;G[b+24>>2]=a.getUTCDay();G[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0}Bc.h="vjp";
var th=[0,31,60,91,121,152,182,213,244,274,305,335],uh=[0,31,59,90,120,151,181,212,243,273,304,334];
function Cc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);G[b>>2]=a.getSeconds();G[b+4>>2]=a.getMinutes();G[b+8>>2]=a.getHours();G[b+12>>2]=a.getDate();G[b+16>>2]=a.getMonth();G[b+20>>2]=a.getFullYear()-1900;G[b+24>>2]=a.getDay();var c=a.getFullYear();G[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?uh:th)[a.getMonth()]+a.getDate()-1|0;G[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();
G[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0}Cc.h="vjp";function Dc(a,b,c,d,e,f,g){if(w)return O(18,1,a,b,c,d,e,f,g);e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{var h=T(d),k=FS.aa(h,a,e,b,c),l=k.u;G[f>>2]=k.U;H[g>>2]=l;return 0}catch(m){if("undefined"==typeof FS||"ErrnoError"!==m.name)throw m;return-m.B}}Dc.h="ipiiijpp";
function Ec(a,b,c,d,e,f){if(w)return O(19,1,a,b,c,d,e,f);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=T(e);if(c&2){c=f;if(!FS.isFile(g.node.mode))throw new FS.g(43);if(!(d&2)){var h=E.slice(a,a+b);FS.ea(g,h,c,b,d)}}}catch(k){if("undefined"==typeof FS||"ErrnoError"!==k.name)throw k;return-k.B}}Ec.h="ippiiij";
var Fc=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();H[a>>2]=60*Math.max(f,e);G[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(Re(a,E,c,17),Re(b,E,d,17)):(Re(a,E,d,17),Re(b,E,c,17))};Fc.h="vpppp";var Mc=()=>performance.timeOrigin+performance.now();Mc.h="d";var Ic=()=>Date.now();Ic.h="d";var vh=1;
function Gc(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(vh)a=performance.timeOrigin+performance.now();else return 52;I[c>>3]=BigInt(Math.round(1E6*a));return 0}Gc.h="iijp";var Hc=()=>{};Hc.h="v";var Jc=a=>x(P(a));Jc.h="vp";var Kc=()=>{Zd+=1;throw"unwind";};Kc.h="v";var Lc=()=>E.length;Lc.h="p";var Nc=()=>q?require("node:os").cpus().length:navigator.hardwareConcurrency;Nc.h="i";var Oc=a=>{hh(a)};Oc.h="vp";
var Pc=(a,b,c)=>{a=gh.get(a);switch(b){case 0:a.resolve(c);break;case 1:a.resolve(gh.get(c).promise);break;case 2:a.resolve(gh.get(c).promise);hh(c);break;case 3:a.reject(c)}};Pc.h="vpip";var Qc=()=>!1;Qc.h="ip";
var wh={},yh=()=>{if(!xh){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"};q&&(a=process.env);for(var b in wh)void 0===wh[b]?delete a[b]:a[b]=wh[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);xh=c}return xh},xh;function Rc(a,b){if(w)return O(20,1,a,b);var c=0,d=0,e;for(e of yh()){var f=b+c;H[a+d>>2]=f;c+=Re(e,E,f,Infinity)+1;d+=4}return 0}Rc.h="ipp";
function Sc(a,b){if(w)return O(21,1,a,b);var c=yh();H[a>>2]=c.length;a=0;for(var d of c)a+=Qe(d)+1;H[b>>2]=a;return 0}Sc.h="ipp";function Uc(a){if(w)return O(22,1,a);try{var b=T(a);FS.close(b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.B}}Uc.h="ii";
function Vc(a,b){if(w)return O(23,1,a,b);try{var c=T(a),d=c.tty?2:FS.isDir(c.mode)?3:FS.isLink(c.mode)?7:4;y[b]=d;A[b+2>>1]=0;I[b+8>>3]=BigInt(0);I[b+16>>3]=BigInt(0);return 0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return e.B}}Vc.h="iip";
function Wc(a,b,c,d){if(w)return O(24,1,a,b,c,d);try{a:{var e=T(a);a=b;for(var f,g=b=0;g<c;g++){var h=H[a>>2],k=H[a+4>>2];a+=8;var l=FS.read(e,y,h,k,f);if(0>l){var m=-1;break a}b+=l;if(l<k)break;"undefined"!=typeof f&&(f+=l)}m=b}H[d>>2]=m;return 0}catch(r){if("undefined"==typeof FS||"ErrnoError"!==r.name)throw r;return r.B}}Wc.h="iippp";
function Xc(a,b,c,d){if(w)return O(25,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 22;var e=T(a);FS.llseek(e,b,c);I[d>>3]=BigInt(e.position);e.Fa&&0===b&&0===c&&(e.Fa=null);return 0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return f.B}}Xc.h="iijip";
function Yc(a,b,c,d){if(w)return O(26,1,a,b,c,d);try{a:{var e=T(a);a=b;for(var f,g=b=0;g<c;g++){var h=H[a>>2],k=H[a+4>>2];a+=8;var l=FS.write(e,y,h,k,f);if(0>l){var m=-1;break a}b+=l;if(l<k)break;"undefined"!=typeof f&&(f+=l)}m=b}H[d>>2]=m;return 0}catch(r){if("undefined"==typeof FS||"ErrnoError"!==r.name)throw r;return r.B}}Yc.h="iippp";function $c(...a){return K.heif_error_success(...a)}$c.za=!0;var bd=(a,b)=>Ue(E.subarray(a,a+b));bd.h="ipp";w||(Rd={},Qd=new Set);
(()=>{var a={mb:Promise.resolve(),canHandle:b=>!n.noWasmDecoding&&b.endsWith(".so"),handle:async(b,c)=>a.mb=a.mb.then(async()=>{try{var d=await Ee(b,{J:!0,pa:!0},c,{})}catch(e){throw Error(`failed to instantiate wasm: ${c}: ${e}`);}He[c]=d;return b})};Ge.push(a)})();FS.createPreloadedFile=(a,b,c,d,e,f,g,h,k,l)=>{wf(a,b,c,d,e,h,k,l).then(f).catch(g)};FS.Ic=wf;FS.Ta();q&&NODEFS.Ta();if(!q)throw Error("NODERAWFS is currently only supported on Node.js environment.");var qf=require("node:tty");
function zh(a){return(...b)=>{try{return a(...b)}catch(c){"BadResource"==c.name&&(c.code="EBADF");if(c.code)throw new FS.g(kf[c.code]);throw c;}}}function Ah(a,b){return zh((c,...d)=>c.o?b(c,...d):a(c,...d))}var pf={...FS};for(const [a,b]of Object.entries(of))FS[a]=zh(b);for(const [a,b]of Object.entries(nf))FS[a]=Ah(b,FS[a]);
(()=>{let a=mg.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof mg&&c instanceof mg))return!1;var d=this.l.D.s,e=this.l.u;c.l=c.l;var f=c.l.D.s;for(c=c.l.u;d.O;)e=d.ta(e),d=d.O;for(;f.O;)c=f.ta(c),f=f.O;return d===f&&e===c},clone:function(){this.l.u||eg(this);if(this.l.qa)return this.l.count.value+=1,this;var c=ig,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.l;c=c(e.call(d,f,{l:{value:{count:g.count,ha:g.ha,qa:g.qa,u:g.u,D:g.D,L:g.L,P:g.P}}}));c.l.count.value+=1;c.l.ha=
!1;return c},["delete"](){this.l.u||eg(this);if(this.l.ha&&!this.l.qa)throw new X("Object already scheduled for deletion");hg(this);var c=this.l;--c.count.value;0===c.count.value&&(c.L?c.P.X(c.L):c.D.s.X(c.u));this.l.qa||(this.l.L=void 0,this.l.u=void 0)},isDeleted:function(){return!this.l.u},deleteLater:function(){this.l.u||eg(this);if(this.l.ha&&!this.l.qa)throw new X("Object already scheduled for deletion");jg.push(this);1===jg.length&&lg&&lg(kg);this.l.ha=!0;return this}});const b=Symbol.dispose;
b&&(a[b]=a["delete"])})();
Object.assign(Cg.prototype,{Mb(a){this.nb&&(a=this.nb(a));return a},Za(a){this.X?.(a)},M:Xf,A:function(a){function b(){return this.ya?Bg(this.s.$,{D:this.ec,u:c,P:this,L:a}):Bg(this.s.$,{D:this,u:a})}var c=this.Mb(a);if(!c)return this.Za(a),null;var d=Ag(this.s,c);if(void 0!==d){if(0===d.l.count.value)return d.l.u=c,d.l.L=a,d.clone();d=d.clone();this.Za(a);return d}d=this.s.Kb(c);d=ng[d];if(!d)return b.call(this);d=this.xa?d.Ab:d.pointerType;var e=yg(c,this.s,d.s);return null===e?b.call(this):this.ya?
Bg(d.s.$,{D:d,u:e,P:this,L:a}):Bg(d.s.$,{D:d,u:e})}});Vd.push(()=>{wh.TMPDIR=require("node:os").tmpdir()});$a.push(()=>{const a=Object.getOwnPropertyDescriptor(n.SourceCustom.prototype,"onRead");Object.defineProperty(n.SourceCustom.prototype,"onRead",{set(c){return a.set.call(this,d=>wg(c(d)))}});const b=Object.getOwnPropertyDescriptor(n.TargetCustom.prototype,"onWrite");Object.defineProperty(n.TargetCustom.prototype,"onWrite",{set(c){return b.set.call(this,d=>c(Z(d)))}})});
Object.assign(mg.prototype,{preventAutoDelete:function(){const a=jg.indexOf(this);-1<a&&jg.splice(a,1);this.l.ha=!1;return this}});if(!w){if(n.wasmMemory)Ea=n.wasmMemory;else{var Bh=n.INITIAL_MEMORY||1073741824;Ea=new WebAssembly.Memory({initial:Bh/65536,maximum:Bh/65536,shared:!0})}Fa()}n.preloadPlugins&&(Ge=n.preloadPlugins);n.noExitRuntime&&($d=n.noExitRuntime);n.print&&(ra=n.print);n.printErr&&(x=n.printErr);n.dynamicLibraries&&(sa=n.dynamicLibraries);n.wasmBinary&&(ta=n.wasmBinary);
n.arguments&&(da=n.arguments);n.thisProgram&&(ea=n.thisProgram);if(n.preInit)for("function"==typeof n.preInit&&(n.preInit=[n.preInit]);0<n.preInit.length;)n.preInit.shift()();n.ENV=wh;n.addRunDependency=uf;n.removeRunDependency=tf;n.addFunction=ve;n.FS_preloadFile=wf;n.FS_unlink=(...a)=>FS.unlink(...a);n.FS_createPath=(...a)=>FS.createPath(...a);n.FS_createDevice=(...a)=>FS.createDevice(...a);n.FS=FS;n.FS_createDataFile=(...a)=>FS.createDataFile(...a);n.FS_createLazyFile=(...a)=>FS.createLazyFile(...a);
n.setAutoDeleteLater=a=>{fg=a};n.deletionQueue=jg;n.setDelayFunction=a=>{lg=a;jg.length&&lg&&lg(kg)};var mh=[ad,be,Nf,lb,mb,nb,ob,pb,qb,rb,sb,tb,ub,vb,wb,xb,yb,dc,Dc,Ec,Rc,Sc,Uc,Vc,Wc,Xc,Yc],Ae={};function Ch(a){for(var b=F[a+6>>1];13===b&&!(16<H[a>>2]);){var c=H[a+8>>2],d=H[c>>2];if(0===d){b=0;break}else if(0===H[(c>>2)+1])a=d,b=F[d+6>>1];else break}return[a,b]}
function Zc(a,b,c,d){var e=H[(a>>2)+1],f=H[(a>>2)+6],g=H[(a>>2)+2],h=H[(a>>2)+5];a=Ch(H[(a>>2)+3])[1];var k=Ed(),l=k,m=[],r=!1;if(15===a)throw Error("complex ret marshalling nyi");if(0>a||15<a)throw Error("Unexpected rtype "+a);if(4===a||13===a)m.push(c),r=!0;for(var t=0;t<f;t++){var p=H[(d>>2)+t],u=Ch(H[(g>>2)+t]),v=u[0];u=u[1];switch(u){case 1:case 10:case 9:m.push(H[p>>2]);break;case 2:m.push(Ta[p>>2]);break;case 3:m.push(Ua[p>>3]);break;case 5:m.push(E[p]);break;case 6:m.push(y[p]);break;case 7:m.push(F[p>>
1]);break;case 8:m.push(A[p>>1]);break;case 11:case 12:m.push(Va[p>>3]);break;case 4:m.push(Va[p>>3]);m.push(Va[(p>>3)+1]);break;case 13:u=H[v>>2];v=F[v+4>>1];l-=u;l&=~(v-1);y.subarray(l,l+u).set(y.subarray(p,p+u));m.push(l);break;case 14:m.push(H[p>>2]);break;case 15:throw Error("complex marshalling nyi");default:throw Error("Unexpected type "+u);}}if(h&1){h=[];for(t=e-1;t>=f;t--)switch(p=H[(d>>2)+t],u=Ch(H[(g>>2)+t]),v=u[0],u=u[1],u){case 5:case 6:--l;l&=-1;E[l]=E[p];break;case 7:case 8:l-=2;l&=
-2;F[l>>1]=F[p>>1];break;case 1:case 9:case 10:case 2:l-=4;l&=-4;H[l>>2]=H[p>>2];break;case 3:case 11:case 12:l-=8;l&=-8;H[l>>2]=H[p>>2];H[(l>>2)+1]=H[(p>>2)+1];break;case 4:l-=16;l&=-8;H[l>>2]=H[p>>2];H[(l>>2)+1]=H[(p>>2)+1];H[(l>>2)+2]=H[(p>>2)+2];H[(l>>2)+3]=H[(p>>2)+3];break;case 13:l-=4;l&=-4;h.push([l,p,H[v>>2],F[v+4>>1]]);break;case 14:l-=4;l&=-4;H[l>>2]=H[p>>2];break;case 15:throw Error("complex arg marshalling nyi");default:throw Error("Unexpected argtype "+u);}m.push(l);for(t=0;t<h.length;t++)e=
h[t],d=e[0],p=e[1],u=e[2],v=e[3],l-=u,l&=~(v-1),y.subarray(l,l+u).set(y.subarray(p,p+u)),H[d>>2]=l}Cd(l);Dd(0);b=N.get(b).apply(null,m);Cd(k);if(!r)switch(a){case 0:break;case 1:case 9:case 10:H[c>>2]=b;break;case 2:Ta[c>>2]=b;break;case 3:Ua[c>>3]=b;break;case 5:case 6:E[c+0]=b;break;case 7:case 8:F[c>>1]=b;break;case 11:case 12:Va[c>>3]=b;break;case 14:H[c>>2]=b;break;case 15:throw Error("complex ret marshalling nyi");default:throw Error("Unexpected rtype "+a);}}Zc.h="viiii";
var gd,hd,M,jd,kd,ld,Na,md,nd,od,pd,qd,rd,sd,td,Ja,ud,Qa,vd,wd,xd,yd,zd,Ad,bb,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,N,K;function Dh(a=[]){var b=ze("main").Ua;if(b){a.unshift(ea);var c=a.length,d=Dd(4*(c+1)),e=d,f;for(f of a)H[e>>2]=Se(f),e+=4;H[e>>2]=0;try{var g=b(c,d);Tc(g,!0)}catch(h){eh(h)}}}
function Ha(a=da){function b(){n.calledRun=!0;if(!va&&(Xa(),xa?.(n),n.onRuntimeInitialized?.(),n.noInitialRun||Dh(a),!w)){if(n.postRun)for("function"==typeof n.postRun&&(n.postRun=[n.postRun]);n.postRun.length;){var c=n.postRun.shift();ge.push(c)}Ya(ge)}}if(0<rf)sf=Ha;else if(w)xa?.(n),Xa();else{if(n.preRun)for("function"==typeof n.preRun&&(n.preRun=[n.preRun]);n.preRun.length;)Vd.push(n.preRun.shift());Ya(Vd);0<rf?sf=Ha:n.setStatus?(n.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>n.setStatus(""),
1);b()},1)):b()}}var Za;w||(Za=await (Ga()),Ha());Ra?moduleRtn=n:moduleRtn=new Promise((a,b)=>{xa=a;ya=b});
;return moduleRtn}if(typeof exports==="object"&&typeof module==="object"){module.exports=Vips;module.exports.default=Vips}else if(typeof define==="function"&&define["amd"])define([],()=>Vips);var isPthread=globalThis.name=="em-pthread";var isNode=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer";if(isNode)isPthread=require("node:worker_threads").workerData==="em-pthread";isPthread&&Vips();
